### ISSUE TITLE
Use fonts

### ISSUE THREAD

**Issue by tomfischerNL** [barryvdh/laravel-dompdf#1]
Dear Barry,

Is it possible to use fonts in this module?

If I load a view (PDF/invoice), it does not recognise my fonts, even not inline.

<code>
$pdf = PDF::loadView('PDF/invoice', array('user' => $user));
</code>

Edit:
Solved.. Just in the head, worked 

body {  
    font-family: 'Helvetica'  
}

**Comment by career-builders-ltd** [comment]
Load font using load_font.php then copy "dompdf_font_family_cache.php" within the 'vendor/dompdf/lib/' to 'storage/fonts'. Works fine.
