### ISSUE TITLE
dompdf set_base_path

### ISSUE THREAD

**Issue by stechnique** [barryvdh/laravel-dompdf#10]
Hi,
Thanks for you package and use and love it. I've run into problems especially now that we are using Queues and building PDFs and mailing them from the artisan CLI, with relative PATHs. The fix was to use dompdf's ->set_base_path() method but I couldn't figure out where I could do that with your package so in PDF.php in your package, inside the init() function I added this call:
        $this->dompdf = new \DOMPDF();
        $this->dompdf->set_base_path(realpath(public_path())); //Mod by LP

If you think this makes sense for others you can add it, and this way mine doesn't break when I composer update to the next version ;)

**Comment by Harrrrry** [comment]
Hyy i found that it have some external css path, image path and footer tag issue after removing that it work fine. 
How can i use these css file and footer tag ?
