### ISSUE TITLE
/app/models/Style.php - No such file or directory

### ISSUE THREAD

**Issue by techfoobar** [barryvdh/laravel-dompdf#100]
For some reason, laravel-dompdf is looking for a file named Style.php (i do not have such a model) from my models directory /app/models/

I've included the service provider correctly in app.php and my attempt at writing the PDF goes like (exactly as in the example):

    $pdf = App::make('dompdf');
    $pdf->loadHTML('<h1>Test</h1>');
    return $pdf->stream();

If it helps: from the stacktrace, I could figure out that the line responsible for this incorrect autoload attempt is:

/vendor/dompdf/dompdf/include/stylesheet.cls.php - line 1289

    $style = new Style($this);

The above causes composer's classloader to incorrectly resolve to my models directory - which results in the following:

> include(/xxx/xxx/xxx/app/models/Style.php): failed to open stream: No such file or directory

**Comment by barryvdh** [comment]
it should load this class: https://github.com/dompdf/dompdf/blob/master/include/style.cls.php

Not sure why your autoloader would try to include it from your models, if it doesn't exist. Did you modify the autoloader?

**Comment by techfoobar** [comment]
Yes, that what I thought too (that it should resolve to style.cls.php). Instead it is resolving to a non existent Style.php in /app/models. 

No i haven't touched the autoloader.

BTW, I'm using the 0.4 branch, since I'm on Laravel 4.2.*

**Comment by techfoobar** [comment]
Oops! Sorry. False alarm.

I previously had a model name Style in /app/models and the autoloader was still resolving to that instead of the one in dompdf (which I installed today).

I refreshed it with "composer dumpautoload" and viola, everything is perfect.
