### ISSUE TITLE
Not rendering CSS file

### ISSUE THREAD

**Issue by francoisdusautoir** [barryvdh/laravel-dompdf#101]
Hi  :)

When I load view and stream pdf, css files require in this file are not read. Is there something to do ?

**Comment by Svanmark** [comment]
I have the same problem.

**Comment by barryvdh** [comment]
Have you tried using the full url?

**Comment by lucidlemon** [comment]
Some info within the Readme about CSS Support and how much CSS is supported (CSS3? Flexbox?) would be great. I had to come to the issues panel to find out if it supports any css at all.
