### ISSUE TITLE
domPDF cropping records on multipage pdf file

### ISSUE THREAD

**Issue by Waqas-Sharif** [barryvdh/laravel-dompdf#1013]
Hi there, facing issue when I scroll the page the pdf viewer start cropping from top and bottom. I'm sharing images too for reference.
![image](https://github.com/barryvdh/laravel-dompdf/assets/60465802/9fbd6064-d449-4c9d-a8ca-afa16f00b494)

**Comment by parallels999** [comment]
https://github.com/barryvdh/laravel-dompdf/blob/424a223ce80e7afc8bfb6e84449679efe272fbb5/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L10-L12
>**This is just a Dompdf wrapper!**
I understand that this package is just a Laravel wrapper for https://github.com/dompdf/dompdf
Any issues with PDF rendering, CSS that is not applied correctly, aligning/fonts/characters/images/html etc that are not directly related to this package, should be reported there. When having doubts, please try to reproduce the issue with just dompdf. If it's also present there, do not open an issue here please.
