### ISSUE TITLE
When I updated composer, it gave me these vulnerability issues

### ISSUE THREAD

**Issue by B-Carcamo** [barryvdh/laravel-dompdf#1019]
Do you know if the vulnerability has been fixed?

![Captura de pantalla de 2023-12-14 21-24-36](https://github.com/barryvdh/laravel-dompdf/assets/18128720/322ebbf5-9d27-4d11-b3fc-2abf9e2a94db)

**Comment by parallels999** [comment]
Those vulnerabilities do not come from this package, and yes, they have already been corrected, you just have to update

**Comment by alberto-ripoll** [comment]
> Those vulnerabilities do not come from this package, and yes, they have already been corrected, you just have to update `composer update -W`

not with the uppercase.
Execute the following command to fix it:
`composer update barryvdh/laravel-dompdf -w`

**Comment by B-Carcamo** [comment]
That's fine thanks.

**Comment by B-Carcamo** [comment]
That's fine thanks.
