### ISSUE TITLE
Dompdf 2.0.4 fixes Possible DoS caused by infinite recursion when validating SVG images

### ISSUE THREAD

**Issue by jamessmeda** [barryvdh/laravel-dompdf#1021]
Are you able to wrap the latest version?

**Comment by parallels999** [comment]
`composer update barryvdh/laravel-dompdf -w`

**Comment by jamessmeda** [comment]
> `composer update barryvdh/laravel-dompdf -w`

Thanks for the manual fix but should the wraparound not install the latest?

**Comment by parallels999** [comment]
I don't see the point of adding a new release every time a dependency makes a release when you can simply update what you need without problems

**Comment by jamessmeda** [comment]
Thanks no worries, appreciate the reply.
