### ISSUE TITLE
Error 503. Service Unavailable

### ISSUE THREAD

**Issue by jleira** [barryvdh/laravel-dompdf#1022]
When attempting to create a PDF from an HTML source, an error 503 is encountered. The following is my code:

$pdf = PDF::loadHtml($html);
$pdf->setPaper('A4', 'landscape');
return $pdf->download('offer-gss-' . $id . '.pdf');

**Expected behavior**
"I used to receive a PDF file, which I downloaded on the front end.

**Screenshots**
<img width="1015" alt="Captura de pantalla 2023-12-22 a la(s) 11 59 22 a  m" src="https://github.com/barryvdh/laravel-dompdf/assets/33931471/76675337-cc6a-444a-a9d5-43d8166a0267">

**Comment by sajjad-mascot** [comment]
I also facing the same issue, before 2 days ago, it works fine before that for the last 2 years, after troubleshooting the problem, found that the render(); did not work


` $html = ob_get_clean();
// instantiate and use the dompdf class
    $dompdf = new Dompdf();
    define("DOMPDF_ENABLE_REMOTE", false);
    $dompdf->set_paper(array(0,0,136.6,800));

    $GLOBALS['bodyHeight'] = 0;

    $dompdf->setCallbacks(
        array(
            'myCallbacks' => array(
                'event' => 'end_frame', 'f' => function ($infos) {
                    $frame = $infos["frame"];
                    if (strtolower($frame->get_node()->nodeName) === "body") {
                        $padding_box = $frame->get_padding_box();
                        $GLOBALS['bodyHeight'] += $padding_box['h'];
                    }
                }
            )
        )
    );

    $dompdf->loadHtml($html);
    $dompdf->render();
    unset($dompdf);

    $dompdf = new Dompdf();
    $dompdf->set_paper(array(0,0,136.6,$GLOBALS['bodyHeight']+10));
    $dompdf->loadHtml($html);
    $dompdf->render();
    $output = $dompdf->output();
    $im = new imagick();
    $im->setResolution(300, 300);
    $im->readImageBlob($output);
    $im->setImageFormat('jpg');
    $im->setImageCompression(Imagick::COMPRESSION_JPEG);
    $im->setCompressionQuality(100);
    header("Content-type: image/jpeg");
    header("Cache-Control: no-store, no-cache");
    header('Content-Disposition: attachment; filename="'.$filename.'.jpg"');`

![image](https://github.com/barryvdh/laravel-dompdf/assets/98080623/093b40da-3cd0-48f4-bb03-0e2a1f724ef9)

**Comment by losbit** [comment]
> When attempting to create a PDF from an HTML source, an error 503 is encountered. The following is my code:
> 
> $pdf = PDF::loadHtml($html); $pdf->setPaper('A4', 'landscape'); return $pdf->download('offer-gss-' . $id . '.pdf');
> 
> **Expected behavior** "I used to receive a PDF file, which I downloaded on the front end.
> 
> **Screenshots** <img alt="Captura de pantalla 2023-12-22 a la(s) 11 59 22 a  m" width="1015" src="https://private-user-images.githubusercontent.com/33931471/292546861-76675337-cc6a-444a-a9d5-43d8166a0267.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzcxNTYsIm5iZiI6MTcwNDQzNjg1NiwicGF0aCI6Ii8zMzkzMTQ3MS8yOTI1NDY4NjEtNzY2NzUzMzctY2M2YS00NDRhLWE5ZDUtNDNkODE2NmEwMjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA2NDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViMDRjOWY0Yzk4Y2E2NGM1N2M0OGVlNDJlOTYzMDBmM2I2OGRjY2ZmZTQ4NDZiZjk3MzdkMDJhZTE4ZTQwNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WS-1axib2vrDTOj1Y1gG-KyzqLIyv5CwVgtbNCm9gOg">

How did you solve the issue?

**Comment by losbit** [comment]
I have the same problem, but do not know how to solve it, why did you close it?

**Comment by sajjad-mascot** [comment]
The issue was automatically resolved after a few days. I believe it was related to a **server resources** problem in my case; the disk space on my server was full. Consequently, I resolved the issue by cleaning up the disk space and deleting unnecessary files. It is now functioning properly.
