### ISSUE TITLE
loadView setOrientation('landscape') always produces portrait

### ISSUE THREAD

**Issue by NikolaiM** [barryvdh/laravel-dompdf#103]
I cannot get the PDF to be output in landscape format.
Portrait PDFs are working fine, and we have some PDF's which we require to stay portrait, so we cannot change the global configuration file to landscape.

Here is the sample code:
$file   = PDF::loadView('emails.invoice.pdf', [] )->setPaper('a4')->setOrientation('landscape')->setWarnings(false)->output();

This is taken from the documentation on the GitHub page, I've also tried having setOrientation before and after loadView, which makes no difference.

**Comment by NikolaiM** [comment]
I omitted the options which are passed to the view for simplicity's sake.

**Comment by NikolaiM** [comment]
I also published the config using the suggested command for Laravel4, changed the oritenation to landscape, and portrait is STILL being output.

**Comment by GertjanRoke** [comment]
I don't know if you worked this out or not.. but this is a way that works for me.

$file = PDF::loadView('emails.invoice.pdf', [] )->setPaper('a4', 'landscape'')->setWarnings(false)->output();
