### ISSUE TITLE
UTF8 STILL NOT WORKING ON LARAVEL 4 0.4

### ISSUE THREAD

**Issue by bartoss77** [barryvdh/laravel-dompdf#104]
CAN YOU UPDATE FOR 0.6 DOMPDF... VERSION FOR LARAVEL 4??

**Comment by barryvdh** [comment]
What do I need to update?

**Comment by bartoss77** [comment]
nvm :P i think you require 0.4 (of dompdf its 0.6 its all ok) my mistake
one important thing: <styles>*{font-family:'dejavu sans'}</styles> is required for my languge chars utf8 (polish)

Regards
