### ISSUE TITLE
Return Corrupted PDF 

### ISSUE THREAD

**Issue by Penderis** [barryvdh/laravel-dompdf#105]
Hi, I am currently able to return a pdf created with Dompdf via Response::download but not via PDF::download() or stream() , well they do return a pdf with the following contents

%PDF-1.3 1 0 obj > endobj 2 0 obj > endobj 3 0 obj > /XObject > >> /MediaBox [0.000 0.000 595.280
841.890] >> endobj 4 0 obj [/PDF /Text /ImageC ] endobj 5 0 obj > endobj 6 0 obj > endobj 7 0 obj > stream
xV[sF~WN=c*TbOqjDC~}#afss-mQiE

Where as Response::download is a perfectly formatted invoice with attached image, I will not that when I created the pdf with dompdf and then return stream or download it works fine.

I user a route to get the files from storage and I pass a single fully formatted url to the 
```
$file = PDF::loadFile('/my/url/here/invoice.pdf')
return $file->download();
```
Any Ideas?

**Comment by barryvdh** [comment]
You can't load PDF files. You have to load a html file, that get's turned in to a PDF. When you already have the PDF, just use `Response::download()` directly.
