### ISSUE TITLE
Pdf to Pdf write possible?

### ISSUE THREAD

**Issue by gvanto** [barryvdh/laravel-dompdf#106]
Is this possible with dompdf? (Or any other way using PHP perhaps?)

What about writing image to pdf using dompdf?

many thanks for help

Gert

**Comment by barryvdh** [comment]
Not that I know of. What are you trying to do, Gill some blank spaces?

**Comment by gvanto** [comment]
Trying to append a PDF to another one.

Thinking that a (slightly ugly but probably possible) workaround is to convert the PDF to be appended to an image first, then include this in the HTML (which will be used to produce the final PDF).
