### ISSUE TITLE
Browser not rendering PDF correctly in Laravel

### ISSUE THREAD

**Issue by kalehege** [barryvdh/laravel-dompdf#1060]
![Screenshot 2024-07-17 205620](https://github.com/user-attachments/assets/9293fb83-afa5-45f7-b054-f1f537072ce4)
how i fix that

        $pdf = PDF::loadView('pdf.cv', ['candidates_data' => $candidate])->setPaper('A3', 'portrait');

        return $pdf->stream('cv-'.$request->em_id.'pdf');

**Comment by parallels999** [comment]
https://github.com/dompdf/dompdf/issues/3375#issuecomment-1889980894

**Comment by kalehege** [comment]
> [dompdf/dompdf#3375 (comment)](https://github.com/dompdf/dompdf/issues/3375#issuecomment-1889980894)

same results man

**Comment by parallels999** [comment]
It works for me, make a demo showing the problem, surely you have something wrong

**Comment by kalehege** [comment]
public function generateCV(Request $request)
    {

        $candidate = Candidate::with(
            'job',
            'education_infos',
            'professional_qus',
            'language_skills',
            'employment_histories',
            'other_emplies',
            'vaccinations',
            'professional_qus',
            'professional_refers'
        )
            ->find($request->candidate_id);

//        dd($candidate);

        $pdf = PDF::loadView('pdf.cv', ['candidates_data' => $candidate])->setPaper('A3', 'portrait');

        return $pdf->download('cv-'.$request->em_id.'pdf');
    }
    
    my code like this

**Comment by parallels999** [comment]
it works 👍

**Comment by kalehege** [comment]
> it works 👍

same bro
![image](https://github.com/user-attachments/assets/016f15eb-6e6e-446c-9fab-c3203a3afaf8)

**Comment by parallels999** [comment]
>make a demo showing the problem, surely you have something wrong somewhere else in your application

**Comment by kalehege** [comment]
> > it works 👍
> 
> same bro ![image](https://private-user-images.githubusercontent.com/82233855/351498451-016f15eb-6e6e-446c-9fab-c3203a3afaf8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NzA1MzUsIm5iZiI6MTcyMTc3MDIzNSwicGF0aCI6Ii84MjIzMzg1NS8zNTE0OTg0NTEtMDE2ZjE1ZWItNmU2ZS00NDZjLTlmYWItYzMyMDNhM2FmYWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDIxMzAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MDI5ODFlMmYyNDMxMTA3MzUxMDNiY2RkMGQ5NmJjYTEzNTZiN2UyNGIyNmZlZWQxNjM3OTQ2ZDU5Y2FlMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tRgdNVi3U0WVqvaU7QkIHrd_OuWBrKGGaR0IVx3kH0s)

It works with IDM Download Manager, but it doesn't work with browser downloads.

**Comment by parallels999** [comment]
Maybe the browser,
Your screenshots don't give much information, you could be showing me an iframe and I don't even know
