### ISSUE TITLE
v3 Release

### ISSUE THREAD

**Issue by JamesFreeman** [barryvdh/laravel-dompdf#1063]
Hi, i've noticed that [v3.0.0-beta](https://github.com/barryvdh/laravel-dompdf/releases/tag/v3.0.0-beta2) has been around since May this year. 

Is there anything outstanding that is required to get this stable? Is there a rough roadmap for the release?

Thanks,
James.

**Comment by barryvdh** [comment]
Done! https://github.com/barryvdh/laravel-dompdf/releases/tag/v3.0.0
