### ISSUE TITLE
PAGE_NUM and PAGE_COUNT

### ISSUE THREAD

**Issue by marioene** [barryvdh/laravel-dompdf#107]
Hi,
Is it possible to add PAGE_NUM and PAGE_COUNT parameters (like in CodeIgniter) to this package for Laravel 5?
Thanks!

**Comment by prabhakaran8737** [comment]
Have you found any solution for this @marioene

**Comment by marioene** [comment]
No solution!

**Comment by bebnev** [comment]
Hi.
You can achieve it with doing such steps:
1) Enable PHP in your dompdf by changing `DOMPDF_ENABLE_PHP` to `true` in `dompdf.php` config.
2) Add lines to your pdf view:
```html
<script type="text/php">
    if ( isset($pdf) ) {
        $text = 'Page: {PAGE_NUM} from {PAGE_COUNT}';
        $font = Font_Metrics::get_font("helvetica", "bold");

        $pdf->page_text(36, 18, $text, $font, 14);
    }
</script>
```
That script will add page_num and page_count to the every page.

**Comment by marioene** [comment]
@bebnev Thank You! Great solution! It's working!

**Comment by marioene** [comment]
@bebnev Thank You! Great solution! It's working!
