### ISSUE TITLE
errors in PDF constructor

### ISSUE THREAD

**Issue by danve** [barryvdh/laravel-dompdf#108]
I am injecting in my controller'construct the PDF $pdf_exporter (by the book).
with
use Barryvdh\DomPDF\PDF;

in my method I have
$pdf = $this->pdf_exporter->loadView('testpdf');

problems are these:
Unresolvable dependency resolving [Parameter #2 [ <required> $view ]] in class Barryvdh\DomPDF\PDF

and PDF construtor looks like:
public function __construct(ConfigRepository $config, Filesystem $files, /\* Illuminate\View\Factory */ $view, $publicPath)

where $view and $publicPath seems not defined.

can I have some help? Thanks

**Comment by barryvdh** [comment]
Probably use the IoC instance or facade, not the class directly.

**Comment by barryvdh** [comment]
But I could change the typehints to match the contracts for L5

**Comment by danve** [comment]
thanks for update

**Comment by ferrites** [comment]
PHP Fatal error:  Class 'Barryvdh\DomPDF\ServiceProvider' not found
