### ISSUE TITLE
Non latin symbols support

### ISSUE THREAD

**Issue by ravaboard** [barryvdh/laravel-dompdf#110]
Checked all the issues, but there was one only asking about arabic support and that guy converted to alternative.

This package works fine, just I need to support these letters ąčęęėėįįėęšįššųūųūūž.

Even after applying utf8 charset to the view does not help. What would be the best solution to get around this as now these symbols are not displayed correctly.

Thanks!

**Comment by adriandmitroca** [comment]
You have to set font with latin-extended support in your CSS (default font hasn't latin-ext characters).

Fortunately, one of built-in fonts support latin characters - just define `font-family: 'DejaVu Sans', sans-serif;` in your `body` tag in CSS file.

**Comment by NazarAli** [comment]
not work

**Comment by nikola-absolute** [comment]
After setting `font-family: 'DejaVu Sans', sans-serif;` text is white and it's ignoring css rules.
Any suggestions?

**Comment by kejsu** [comment]
this works for me, thanks

**Comment by rahul7yadav** [comment]
It's not working for á and ó (I got square box after normal a and o)
