### ISSUE TITLE
loadView dont working

### ISSUE THREAD

**Issue by bendo01** [barryvdh/laravel-dompdf#113]
using laravel 5
when testing in my controller
```php
     $pdf = PDF::loadHTML('<p>Hello World!!</p>');
     return $pdf->stream();
```
it works
then i try example
```php
     $pdf = PDF::loadView('pdf.invoice');
     return $pdf->download('invoice.pdf');
```
it show me this error
InvalidArgumentException in FileViewFinder.php line 140: View [pdf.invoice] not found.

**Comment by barryvdh** [comment]
And `return View::make('pdf.invoice');` does work?

**Comment by bendo01** [comment]
it seem i do some newbie mistake, instead put the view file in the resources/views folder i put it in /resource folder, i'm sorry for this silly mistake

**Comment by arturcesarmelo** [comment]
### Tree

![image](https://user-images.githubusercontent.com/18191910/43970533-4df45c18-9ca4-11e8-9efc-8d40cea6d8f0.png)

### Calling

![image](https://user-images.githubusercontent.com/18191910/43970573-6aa99314-9ca4-11e8-914e-f693d8c6851d.png)

### error

![image](https://user-images.githubusercontent.com/18191910/43970590-7418549e-9ca4-11e8-86d7-e85fc79d61d5.png)

What i'm doing wrong?
