### ISSUE TITLE
Problem loading image

### ISSUE THREAD

**Issue by ArmandoMendoza** [barryvdh/laravel-dompdf#114]
When use the helper asset() in the view, takes a long time to generate the file and don’t render the image. I'm using the 0.4.\* version.

**Comment by barryvdh** [comment]
Using the php cli server, or a real server?

**Comment by ArmandoMendoza** [comment]
php cli server.

**Comment by vadimwe** [comment]
works fine for me.

**Comment by eezhal92** [comment]
Is this related to image size? My image is about 5MB. When the pdf downloaded, i can't find the image there. I use asset() helper too

**Comment by giolvani** [comment]
This issue happens to me as well.

Web images loads perfectly, but images from localhost, does not load no way.

Should this issue is cause I'm using php-cli? Actually I'm running with artisan.

**Comment by miftahafina** [comment]
Use public_path() instead of asset()
