### ISSUE TITLE
PHP Fatal error:  Class 'App\\Http\\Controllers\\PDF' not found

### ISSUE THREAD

**Issue by edward-buskus** [barryvdh/laravel-dompdf#117]
My Controller function : 
public function getinvoice()
    {
       $data = 'test';
        $pdf = PDF::loadView('pdf.invoice', $data);
        return $pdf->download('invoice.pdf');
    }
And get error 500 .

**Comment by barryvdh** [comment]
'\PDF' or 'use Pdf;'
Just a namespace problem ;)

**Comment by etmind** [comment]
Thanks,
but   $pdf = Pdf::loadView('pdf.invoice', $data);
i get same error.

**Comment by barryvdh** [comment]
`$pdf = \PDF::loadView('pdf.invoice', $data);`

**Comment by etmind** [comment]
Thank you ! 
There was other problem, i run composer with root, and this causes problems with permissions.

**Comment by lmoralejo** [comment]
Add the line: 
use Barryvdh\DomPDF\Facade as PDF;

**Comment by tanjilbhuiyan** [comment]
table width is not working  for download, 

    function downloadreport($id = null) {
        $id = str_replace('.pdf', '', $id);
        $data = array(
            'pageTitle' => 'View Report',
            'stgplan' => Stgplan::find($id)
        );
        $pdf = App::make('dompdf.wrapper');
        $pdf->loadView('pdf/from', $data);
        return $pdf->stream($id . ".pdf");

        
    }
applying normal css but width is not working, everything else working.
style:

<style type="text/css">
        
            body{

                font-family: "Open Sans", sans-serif;
                font-size: 18px;

            }

            table{
                

                text-align:left;
                width: 100%;
            }
            

            table, td, th {

                border: 1px solid #e6e6e6;

                
            }

            

            
</style>

**Comment by JSetup** [comment]
This is a way to instantiate a class with \ App :: make () ... and this inherits the DOMPDF methods
`
public function downloadReport(){
        $pdf = \App::make('dompdf.wrapper');
        $pdf->loadHTML('<h2>Mostrar htlm directo</h2>');
        return $pdf->stream();
}
`

Another way is instantiating the Facade

`
use Barryvdh\DomPDF\Facade as PDF;

public function downloadReport(){
        //loadView loads the view of: resources / views / reports / products.blade.php
        $pdf = PDF::loadView('reportes.products');

        //If you specify a string in the stream method it will have the default name of the download if you click on the google tool
        return $pdf->stream('myreport_users.pdf');

        //if you want to make the direct download with a name by default
        //return $pdf->download('cenas_navideñas.pdf');
}
 `
I hope you help, greetings
