### ISSUE TITLE
Composer: dompdf/dompdf 0.6.* -> no matching package found

### ISSUE THREAD

**Issue by hiddeco** [barryvdh/laravel-dompdf#119]
```bash
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for barryvdh/laravel-dompdf 0.5.* -> satisfiable by barryvdh/laravel-dompdf[v0.5.0].
    - barryvdh/laravel-dompdf v0.5.0 requires dompdf/dompdf 0.6.* -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by GrahamCampbell** [comment]
You need to set the minimum stability correctly.

**Comment by hiddeco** [comment]
@GrahamCampbell: tried every minimum stability option, didn't work. Added ```"dompdf/dompdf": "0.6.1"``` to my own composer.json and everything works fine now.

**Comment by GrahamCampbell** [comment]
> Added "dompdf/dompdf": "0.6.1" to my own composer.json and everything works fine now.

That's not a correct solution.

**Comment by hiddeco** [comment]
@GrahamCampbell: 
```
"minimum-stability": "dev",
"prefer-stable": true
```

```bash
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - barryvdh/laravel-dompdf v0.5.0 requires dompdf/dompdf 0.6.* -> no matching package found.
    - barryvdh/laravel-dompdf v0.5.0 requires dompdf/dompdf 0.6.* -> no matching package found.
    - Installation request for barryvdh/laravel-dompdf 0.5.* -> satisfiable by barryvdh/laravel-dompdf[v0.5.0].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by GrahamCampbell** [comment]
Trying running `composer self-update`, `composer clear-cache`, `rm -rf vendor`, `rm composer.lock`, `composer install`.

**Comment by GrahamCampbell** [comment]
`composer update` sometimes doesn't behave correctly because correctly installed stuff influences it.

**Comment by hiddeco** [comment]
Didn't do the trick, same message again.

**Comment by GrahamCampbell** [comment]
Can you provide your whole composer.json file and I'll try to replicate.

**Comment by hiddeco** [comment]
Tried again and it works smoothly now, thanks.

**Comment by shanmca** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package dompdf/dompdf (locked at v0.6.2, required as dev-master) is satisfiable by dompdf/dompdf[v0.6.2] but these conflict with your requirements or minimum-stability.
  Problem 2
    - Installation request for dompdf/dompdf dev-master -> satisfiable by dompdf/dompdf[dev-master].
    - dompdf/dompdf dev-master requires ext-gd * -> the requested PHP extension gd is missing from your system.
  Problem 3
    - yajra/laravel-datatables-oracle v6.17.0 requires dompdf/dompdf ^0.6.1 -> satisfiable by dompdf/dompdf[v0.6.1, v0.6.2] but these conflict with your requirements or minimum-stability.
    - yajra/laravel-datatables-oracle v6.17.0 requires dompdf/dompdf ^0.6.1 -> satisfiable by dompdf/dompdf[v0.6.1, v0.6.2] but these conflict with your requirements or minimum-stability.
    - yajra/laravel-datatables-oracle v6.17.0 requires dompdf/dompdf ^0.6.1 -> satisfiable by dompdf/dompdf[v0.6.1, v0.6.2] but these conflict with your requirements or minimum-stability.
    - Installation request for yajra/laravel-datatables-oracle (locked at v6.17.0, required as ~6.0) -> satisfiable by yajra/laravel-datatables-oracle[v6.17.0].

how to solve this one'

**Comment by MPJHorner** [comment]
@GrahamCampbell best answer without needing to allow @dev.

**Comment by A7medHub** [comment]
@GrahamCampbell  thanks
