### ISSUE TITLE
Laravel Forge wont deploy code if I include your AWESOME plugin

### ISSUE THREAD

**Issue by HeadShotBoom** [barryvdh/laravel-dompdf#120]
I am using laravel-dompdf on a project im working on. It works awesome in the development environment, but when I try to use Laravel Forge to push my code to digital ocean, I get the following error.

Error Output: PHP Fatal error:  Class 'Barryvdh\DomPDF\ServiceProvider' not found in /home/forge/default/vendor/compiled.php on line 6561  
  PHP Stack trace:  
  PHP   1. {main}() /home/forge/default/artisan:0  
  PHP   2. Illuminate\Foundation\Console\Kernel->handle() /home/forge/default/artisan:36  
  PHP   3. Illuminate\Foundation\Console\Kernel->bootstrap() /home/forge/default/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:92  
  PHP   4. Illuminate\Foundation\Application->bootstrapWith() /home/forge/default/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:195  
  PHP   5. Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap() /home/forge/default/vendor/compiled.php:1314  
  PHP   6. Illuminate\Foundation\Application->registerConfiguredProviders() /home/forge/default/vendor/compiled.php:1827  
  PHP   7. Illuminate\Foundation\ProviderRepository->load() /home/forge/default/vendor/compiled.php:1429  
  PHP   8. Illuminate\Foundation\ProviderRepository->compileManifest() /home/forge/default/vendor/compiled.php:6523  
  PHP   9. Illuminate\Foundation\ProviderRepository->createProvider() /home/forge/default/vendor/compiled.php:6547

**Comment by barryvdh** [comment]
Dus you require it correctly? Not accidentally in require-dev perhaps?

**Comment by HeadShotBoom** [comment]
You sir are correct. I did exactly as you suggested. After correcting it, works like a champ!!
