### ISSUE TITLE
How can I add external css to generate PDF using view file

### ISSUE THREAD

**Issue by avptechnocrats** [barryvdh/laravel-dompdf#121]
How can I add external css to generate PDF using view file? Can you please help me in this?

**Comment by hiddeco** [comment]
Add the following line to the `head` part of your blade file to include the external CSS. 

```
<link rel="stylesheet" href="{{ asset('/path/to/your/pdf.css') }}" media="all" />
```

**Comment by raffe90** [comment]
This is not working for me. No CSS styles are being loaded

**Comment by tejasrsuthar** [comment]
Same here :(

**Comment by davidjuntak** [comment]
I solve this problem by using external CSS's full path. This one worked on my linux ubuntu server :
`<link rel="stylesheet" href="/var/www/mysite/public/css/main.css" media="all" />`

You also can solve not loaded image problem by using this solution.

**Comment by barryvdh** [comment]
Are you using actual servers? Or CLI or something?
I think absolute urls should work for apache/nginx

**Comment by davidjuntak** [comment]
I am using actual production server and it works.

**Comment by venkateshcontus** [comment]
I have tried the below code
            $pdf = app()->make('dompdf.wrapper');
            $pdf->loadHTML('<h1>Test</h1>');
            return $pdf->stream();
   Blank pdf is generated . But it's work in my local system.

**Comment by hekmatinasser** [comment]
I solve this problem by using external CSS's full path. This one worked on my linux ubuntu server :
`<link href="{{ public_path('css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />`
and work on image.

**Comment by AbdullahValley** [comment]
any solution for windows user ??
<link rel="stylesheet" href="{{ asset('/path/to/your/pdf.css') }}" media="all" />

its not woking - loading and loading

**Comment by himalayaahuja** [comment]
I am using external css with full url paths , but i am getting an error , while generating pdf i think it is not able to parse / read css classes or selectors.. here's the error i am getting : 
![laravel_dompdf_issue](https://user-images.githubusercontent.com/17468499/39172903-d6479a96-47c0-11e8-9498-8470b9ad31ab.png)

**Comment by heidilux** [comment]
@himalayaahuja You're just missing the `/fonts` directory that you need to create in your `storage` directory

**Comment by StrikeAgainst** [comment]
Will there be a way to load this in via Laravel helper functions any time soon? Working with fixed URLs is highly unreliable...

**Comment by vince83110** [comment]
It works for me on Windows : 

`<link rel="stylesheet" href="{{ ltrim(public_path('css/pdf.css'), '/') }}" />`

**Comment by adysxp** [comment]
fix permission +750 all folder css,  work fine:
<link rel="stylesheet" href="{{ URL::asset('css/site.css') }}" type="text/css" />
<link rel="stylesheet" href="{{ URL::asset('bootstrap/css/bootstrap.min.css') }}" type="text/css" />

**Comment by dbvgonezoren** [comment]
> It works for me on Windows :
> 
> `<link rel="stylesheet" href="{{ ltrim(public_path('css/pdf.css'), '/') }}" />`

Im using windows and it works. Thanks!

**Comment by dxm99** [comment]
I was in hurry so i used Occam's razor. I created another blade template, pdf-css, with only one tag: 

> <style>...</style>
and in my tempates i added

> 	@include('pdf-css')
It's prolly not the best solution but it is a solution that works without hussle

**Comment by stipsuarez** [comment]
dompdf have some probles with some styles, for example display:flex. I have to creete a view.blade.php : 
<tbody>
                <tr>
                    <td>
                        <img class="responsive center-img" src="{{asset('images/logoEmp.png')}}" width="150px !important" height="auto" alt="Fabri Hogar">
                    </td>
                    <td>
                        <div class="center">
                            <h4>Órden de Pedido</h4>
                            <p id="sellerorder_id">{{$sellerorder->id}}</p>

                        </div>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" class="center">
                        <div>
                            <h4>
                                <span>NIT:
                                    <a href="/home"> {{$company->nit}}</a></span>
                            </h4>

                        </div>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <div class="col-md-12 col-sm-3  text-center">
                            <h4 class="text-center bg-primary rounded-pill">Dirección: {{$company->address}} PISO 3 Tel: {{explode(',',$company->telephone)[0]}} {{$company->city->name}}. D.C -
                                Colombia </h4>
                        </div>
                    </td>

                </tr>
                <tr>
                    <td>
                        <div class="col-md-8 col-sm-3  text-left">
                            <h4 class="rounded-pill text-center bg-secondary text-light">
                                Cliente:{{$sellerorder->customer->name_customer}}</h4>
                            <h4 class="rounded-pill text-center bg-secondary text-light" id="ccCustomer">CC/Nit: {{$sellerorder->customer->cc}} </h4>
                            <h4 class="rounded-pill text-center bg-secondary text-light" id="addressCustomer">Dirección: {{$sellerorder->customer->address}}, {{$sellerorder->customer->city->name}}, {{$sellerorder->customer->department->name}} </h4>
                            <h4 class="rounded-pill text-center bg-secondary text-light" id="telephoneCustomer">Teléfono: {{$sellerorder->customer->telephone}}</h4>

                        </div>
                    </td>
                    <td>
                        <div class="col-md-4 col-sm-3  text-center">
                            <h4 class=" rounded-pill bg-secondary text-light">Fecha de creada:
                                {{date('d-m-Y', strtotime(str_replace('-', '/', $sellerorder->created_date)))}}
                            </h4>
                            <h4 class=" rounded-pill bg-secondary text-light">Vendedor: {{$sellerorder->seller->user->name}}

                            </h4>
                            <h4 class=" rounded-pill bg-secondary text-light">
                                Condición de Pago: {{$sellerorder->payment_type}}
                            </h4>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="center">
                            <h4 class=" rounded-pill bg-primary text-light">Número de Seguimiento: {{$sellerorder->tracking_number}} </h4>

                        </div>
                    </td>
                    <td>
                        <div class="center">
                            <h4 class=" rounded-pill bg-primary text-light">Fecha de envío:
                                @if($sellerorder->shipping_date)
                                {{date('Y-m-d', strtotime(str_replace('-', '/', $sellerorder->shipping_date)))}}
                                @endif
                            </h4>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>

and add some styles:
.left {

            text-align: left;
            margin: 30px;
        }

        .rigtht {
            text-align: right;
            margin: 30px;

        }

        .center {
            text-align: center;
            align-items: center;
            align-content: center;
            width: 100%;
        }

        .center-img {
            text-align: center;
            align-items: center;
            align-content: center;
        }

        html {
            margin: 10px;
        }

        body {
            font-family: "Times New Roman", serif;
            margin: 45mm 8mm 2mm 8mm;
        }

        .rounded-pill {
            border: solid 1px #86895D;
            border-radius: 10px;
            background-color: #86895D;
            color: #fff !important;
            margin: 5px;
        }
    </style>
