### ISSUE TITLE
View [invoice.pdf] not found.

### ISSUE THREAD

**Issue by xfaraway** [barryvdh/laravel-dompdf#125]
Hi,
I already follow the instruction but when i use PDF::loadView, it shows up with an error "View [invoice.pdf] not found."
My function:
public function pdf(){
        $data = 'test';
        $pdf = PDF::loadView('pdf.invoice', $data);
        return $pdf->download('invoice.pdf');
}
I don't know what i missed with the code above.
I also try to use it like this and it worked to shows up with a pdf. 
My other try:
public function pdf(){
$pdf1 = PDF::loadHTML('< h1 >Test 1< / h1 >');
        return $pdf1->stream();
}

**Comment by adriandmitroca** [comment]
Well, error `View [invoice.pdf] not found.` means that your view file does not exist in `resources/views/pdf/invoice.php` or `resources/views/pdf/invoice.blade.php`

**Comment by madhuribrictech** [comment]
Same issue.
View [pdf.invoice] not found.

**Comment by arturcesarmelo** [comment]
Same issue.
view [pdf.meeting] not found.
