### ISSUE TITLE
v0.5.1 - Call to undefined method DOMPDF::loadHtml()

### ISSUE THREAD

**Issue by marchampson** [barryvdh/laravel-dompdf#129]
I've just run composer update and it picked up v0.5.1 - since then I'm getting the following error:

Call to undefined method DOMPDF::loadHtml()

Any ideas?
Thanks

**Comment by barryvdh** [comment]
Did you register the facade? Are you referencing it exactly as you defined the facade (with casing also)

**Comment by marchampson** [comment]
Hi, yes, it was all working fine until I ran the update. Will check again
though. Thanks

On Tuesday, June 9, 2015, Barry vd. Heuvel <notifications@github.com> wrote:

> Did you register the facade? Are you referencing it exactly as you defined
> the facade (with casing also)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/barryvdh/laravel-dompdf/issues/129#issuecomment-110435024>
> .
>


-- 
M Hampson
Head of Development



wk360 Limited | Applescan House | Latimer Road | Luton | LU1 3XE

01582 487580
07872 516946
www.wk360.com


CLICK THE LINK to send your files to wk360 http://wk360.wetransfer.com




This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. E-mail transmission cannot be
guaranteed to be secure or error-free as information could be intercepted,
corrupted, lost, destroyed, arrive late or incomplete, or contain viruses.
The sender therefore does not accept liability for any errors or omissions
in the contents of this message, which arise as a result of e-mail
transmission. If verification is required please request a hard-copy
version.

**Comment by marchampson** [comment]
Hi,

I'm not sure what is going on here - I've gone back to previous version and all fine. There were a number of updates from composer so I'm sure it's my setup. Closing the issue.

Thanks
