### ISSUE TITLE
Problem in arabic

### ISSUE THREAD

**Issue by NazarAli** [barryvdh/laravel-dompdf#131]
i have problem in arabic language how can supported it in dompdf
the Arabic appear ???? ???

**Comment by NazarAli** [comment]
Helllllp pleas

**Comment by djoudi** [comment]
me two same problem

**Comment by gjinesh90** [comment]
to resolve "???"  text issue in pdf you have to set css with following
font-family: 'dejavu sans', sans-serif;
direction:rtl;
text-alignment:right;

**Comment by MyatHtut** [comment]
not ok @gjinesh90

**Comment by hbsoftco** [comment]
Persian and arabic does not support

**Comment by BBEDERRAR** [comment]
i have the same problem

**Comment by erfansahaf** [comment]
Follow Chaiwei instructions in:
https://github.com/barryvdh/laravel-dompdf/issues/79
Now you don't see the question mark instead characters but still, there is a problem with both Arabic and Persian text. The letters of words, show apart.

**Comment by obiefy** [comment]
you can use [mPDF](https://github.com/mpdf/mpdf)
this here the [arabic](https://mpdf.github.io/fonts-languages/arabic-rtl-text-v5-x.html) language support

**Comment by hannanstd** [comment]
use below package:
https://github.com/mccarlosen/laravel-mpdf

i tested and works with persian well.
