### ISSUE TITLE
Lumen 5.1 Install

### ISSUE THREAD

**Issue by joffroi** [barryvdh/laravel-dompdf#133]
Hello,

I have installed Dompdf on Lumen 5.1, based on Laravel 5.1 throw composer.

Now, I’m trying to configure Lumen to use Dompdf.
I add : $app->register('barryvdh\laravel-dompdf\src\ServiceProvider’); in app.php, whitch give me "error NetworkError: 500"
And : class_alias('barryvdh\laravel-dompdf\src\ServiceProvider', 'PDF’); in Application.php, witch give me the error « Class dompdf.wrapper does not exist » when I’m using the library ($pdf = App::make('dompdf.wrapper');

I also tried, as shown for Laravel 5 the link "Barryvdh\DomPDF\ServiceProvider » without success.

Is there something special to do with Lumen ?

Thank you in advance,

**Comment by bebnev** [comment]
Please, require `"barryvdh/laravel-dompdf": "dev-master"` in your composer to check lumen support.
