### ISSUE TITLE
Call to undefined method DOMText::getAttribute()

### ISSUE THREAD

**Issue by vjandrea** [barryvdh/laravel-dompdf#136]
After upgrading to Laravel 5.1 i get this error both using `->stream()` or `->download()`: 
`FatalErrorException in cellmap.cls.php line 437: Call to undefined method DOMText::getAttribute()`
The full trace is here: http://laravel.io/bin/PXmmk

**Comment by vjandrea** [comment]
After looking at this issue: https://github.com/dompdf/dompdf/issues/449 i found out that i had an error in my html markup (colspan not matching total column number).

**Comment by AgungPambudi** [comment]
Change this code 

// Determine where this cell is going
    $colspan = $node->getAttribute("colspan");
    $rowspan = $node->getAttribute("rowspan");

    if ( !$colspan ) {
      $colspan = 1;
      $node->setAttribute("colspan",1);
    }

    if ( !$rowspan ) {
      $rowspan = 1;
      $node->setAttribute("rowspan",1);
    }

to 

$colspan = 1;
$rowspan = 1;

**Comment by raxhet91** [comment]
agungPambudi  how you have resolved that? if I put $colspan = 1; $rowspan = 1; in that file, the style of table was gone, because you set all colspan and rowspan 1, and if in the table I have colspan 4 it will be setted to one? how can I resolv this problem? please help me!

**Comment by aravintha** [comment]
Any solution for this. 
If we set 
```
$colspan = 1;
$rowspan = 1;
```
then the HTML style is collapsed.

**Comment by bosz** [comment]
I get similar error. 
But mine, when i try to generate pdf from about < 20 columns, it works well, 

But when i have over 100 columns to generate pdf from, it gives me that error. 
`Call to undefined method Dompdf\FrameDecorator\TableRowGroup::get_cellmap()`

**Comment by bosz** [comment]
Ahh, i saw my error. I had some unclosed tags thats why it was getting the error. 
So, if you got similar issues, pls check your tags well.
