### ISSUE TITLE
Simple Table looks kilter

### ISSUE THREAD

**Issue by DanLuevano** [barryvdh/laravel-dompdf#138]
I'm using this add-on on Laravel 5. this is my code:
view.blade.php
@extends('pdf')
@section('content')
	<div class="container">	
		<table class="table">
			<tr>
				<th>Nombre</th>
				<th>Departamento</th>
				<th>Unidad de Medida</th>
				<th>Medida</th>
				<th>Proveedor</th>
				<th>Codigo de Barras</th>
				<th>Estado</th>
				<th>Cantidad</th>
			</tr>
			<tr>
				<td>Plumas</td>
				<td>Papeleria</td>
				<td>Unidad</td>
				<td>Grande</td>
				<td>La Palma</td>
				<td>2342423424234</td>
				<td>Bueno</td>
				<td>9</td>
			</tr>
		</table>

	</div>
@endsection
And this is how it looks when generated the PDF
![image](https://cloud.githubusercontent.com/assets/13123120/8438349/e17c1b88-1f2a-11e5-9ee9-155b59366149.png)

As you can see the table data don't match with the table headers.

**Comment by DanLuevano** [comment]
It was a css issue, sorry.

**Comment by djoks** [comment]
Hello, I have the same issue, can you please tell me how you fixed it?
