### ISSUE TITLE
Have you a simple HTML Blade example with Twitter Bootstrap ?

### ISSUE THREAD

**Issue by paguemaou** [barryvdh/laravel-dompdf#140]
I'm looking for a simple Twitter Bootstrap HTML example (even an HTML Blade without variables) witch is well converted by laravel-dompdf.

All of the tests I've made ignore all the Bootstrap CSS format.

Thanks for you help (and also for debugbar and ide_helper !)

Paguemaou

**Comment by barryvdh** [comment]
Nope Bootstrap is pretty complex.
Try my snappy pdf package for that.

**Comment by paguemaou** [comment]
OK, thanks.

Does Snappy's requirements could be installed in Forge ?
