### ISSUE TITLE
using blade view that has a @include for a partial

### ISSUE THREAD

**Issue by asivaneswaran** [barryvdh/laravel-dompdf#141]
Hi guys,

I got a quick question, I am trying to create a pdf from a view and in the view I use the @include tag to include partials. But for some reason, I get a white page as return. If I remove the partials, everything works fine.... I have no error, I even checked my log.

Anyone knows what to do?

Thanks, Ara

**Comment by bebnev** [comment]
@asivaneswaran hello. Problem is still actual, can you provide the code, because I've just tested `@include` statement and it works fine.
