### ISSUE TITLE
How to get multi-record data for use Laravel 5 Blade template

### ISSUE THREAD

**Issue by sunnyjayjay** [barryvdh/laravel-dompdf#142]
I have this code to try to generate a report on all records in a table:

```
$items = Line::all();
$data = $items->toArray();
$pdf = PDF::loadView('pdf.catalogue', $data);
return $pdf->stream();
```

How do I access the array in my Blade template? I have tried 
    @foreach ($data as $item) 
but that does not work.

**Comment by sunnyjayjay** [comment]
OK, I now see that $data['items']=$items->toArray() will work. But then I lose all the Eloquent relationships. Is there now way in the Blade template for the report of referring to $items->owner()->surname (where owner is a related table)?

**Comment by denndk** [comment]
@sunnyjayjay 

Just send your Eloquent models. 

```php
$items = Line::all();
$data['items'] = $items;
$pdf = PDF::loadView('pdf.catelogue', $data);
return $pdf->stream();
```

**Comment by vigneshbc** [comment]
When i use dis code i get error 
![screencapture-localhost-laravel5-public-pdf-1443533188019](https://cloud.githubusercontent.com/assets/14816300/10165262/e9e86526-66db-11e5-84ea-61ff542d0601.png)

**Comment by raffe90** [comment]
That error is just the app telling it can't find the font. Make sure the fonts are stored in coherence with the configuration you have set. In this case it is looking for your fonts in the storage_path('fonts/')

**Comment by dorinhila** [comment]
Try this.
$items = Line::all();
$data['items] = $items
$pdf = PDF::loadView('pdf.catalogue', $data);
return $pdf->stream();

//In blade.
foreach($items as $item) {
//...
}
