### ISSUE TITLE
In Lumen 5.0

### ISSUE THREAD

**Issue by rogepage** [barryvdh/laravel-dompdf#143]
Fatal error: Call to undefined function Barryvdh\DomPDF\config_path() in /home/vagrant/Code/hospedagem/vendor/barryvdh/laravel-dompdf/src/ServiceProvider.php on line 43

**Comment by bebnev** [comment]
Please, require `"barryvdh/laravel-dompdf": "dev-master"` in your composer to check lumen support.

**Comment by rogepage** [comment]
Perfact! Thanks.
