### ISSUE TITLE
DejaVu Sans font - text not visible

### ISSUE THREAD

**Issue by nikola-absolute** [barryvdh/laravel-dompdf#145]
Hi,
I need extended support for latin fonts, so I wanted to use `font-family: "dejavu sans", serif;` but the text is completely white and it is ignoring css rules.
When I copy text from pdf I see correct output.
Any ideas?

**Comment by barryvdh** [comment]
Does it work in plain html?

**Comment by nikola-absolute** [comment]
I resolved a problem, it took me some time to figure out.

Page numbering was making fonts invisible.
```php
  $pdf = PDF::loadView("project.accounting.pdf_offer", $data);
        $pdf->output();
        $dom_pdf = $pdf->getDomPDF();
        $canvas = $dom_pdf->get_canvas();
        $canvas->page_text(35, 818, sprintf("%s {PAGE_NUM} %s {PAGE_COUNT}", Lang::get("default.page"), Lang::get("default.from")), null, 7, array(0, 0, 0));
        
        return $pdf->stream();
```
So I just removed that part and insert it inline as script/php and it was working fine
```php
$pdf = PDF::loadView("project.accounting.pdf_offer", $data);
return $pdf->stream();
```
