### ISSUE TITLE
Calling without facades

### ISSUE THREAD

**Issue by jonathantjh** [barryvdh/laravel-dompdf#146]
How do i call it without facades on laravel 5

PDF::loadHTML($html)->setPaper('a4')->setOrientation('landscape')->setWarnings(false)->save('myfile.pdf')

return PDF::loadFile(public_path().'/myfile.html')->save('/path-to/my_stored_file.pdf')->stream('download.pdf');

**Comment by barryvdh** [comment]
Did you read the readme? It's literally there..

```
$pdf = App::make('dompdf.wrapper');
$pdf->loadHTML('<h1>Test</h1>');
return $pdf->stream();
```

**Comment by jonathantjh** [comment]
@barryvdh 
I'm sorry for my english.

As in i would like to use 
PDF::loadHTML($html)->setPaper('a4')->setOrientation('landscape')->setWarnings(false)->save('myfile.pdf')

return PDF::loadFile(public_path().'/myfile.html')->save('/path-to/my_stored_file.pdf')->stream('download.pdf');

 but without facades or is there anyway i can use those code without setting up a facades

**Comment by barryvdh** [comment]
Yeah, see the example. Replace the facade with the App::make call.
