### ISSUE TITLE
Assets (images, css etc.) not working when you have a redirect in htaccess

### ISSUE THREAD

**Issue by felyx** [barryvdh/laravel-dompdf#148]
I have a redirect due to ssl requirements in my htaccess and now the generated pdf does not find images, css included in the view with the asset helper or via direct url. If I remove the htaccess redirect everything works fine. I am not sure how to fix this. And this issue is only present in the pdf. On the website itself everything works just fine even with the redirect.

**Comment by felyx** [comment]
Well after some time I found a solution:

```php
<img src="<?php echo $_SERVER["DOCUMENT_ROOT"]; ?>img/image.png" alt="image"/>
```

This works for me.

**Comment by barryvdh** [comment]
Can't you just use the asset helper?

**Comment by felyx** [comment]
I already stated that I used the asset helper. Without redirect it worked fine, with redirect it didn't.

**Comment by barryvdh** [comment]
Also not when using the secure flag to force https?

**Comment by felyx** [comment]
Do you mean the secure_asset() helper? I did not know about that until now but let me give it a try.

**Comment by felyx** [comment]
Well I tried with secure asset:

````php
<img src="{{ secure_asset('img/eszerzodes-logo-fekete.png') }}" alt="Eszerzodes.hu"/>
````

Still did not work.

**Comment by dutchiexl** [comment]
I am having the same issue, did you find a solution ?

**Comment by felyx** [comment]
I did but its rather simple and messy, but works:

`<link href="<?php echo $_SERVER["DOCUMENT_ROOT"]; ?>css/pdf.css" rel="stylesheet">`

**Comment by dutchiexl** [comment]
Ah yes, I see. for me this works as well. Thx !
