### ISSUE TITLE
Argument 1 passed to DOMNode::appendChild() must be an instance of DOMNode, null given

### ISSUE THREAD

**Issue by belapie** [barryvdh/laravel-dompdf#149]
Hi,

When i tried to create a PDF from a simple HTML view, like the 'welcome.blade.php' i have this exception.

**Exception** :
    ErrorException in frame.cls.php line 765: 
    Argument 1 passed to DOMNode::appendChild() must be an instance of DOMNode, null given, called in C:\Projets\Test7\laravel\vendor\dompdf\dompdf\include\table_frame_decorator.cls.php on line 312 and defined

**Steps to reproduce** :
1. Create a new laravel project `composer create-project laravel/laravel`
2. Install dompdf `composer require barryvdh/laravel-dompdf`
3. Add `Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class` to _providers_ in app.php
4. Add `'PDF'       => Barryvdh\DomPDF\Facade::class` to _aliases_ in app.php
5. `php artisan vendor:publish`
6. Change routes.php to `Route::get('/', function () { $pdf = PDF::loadView('welcome'); return $pdf->stream(); });`
6b. It's not working either using `download('test.pdf')`.. (`Route::get('/', function () { $pdf = PDF::loadView('welcome'); return $pdf->download('test.pdf'); });`)
7. Go to http://localhost/laravel/ ... wait a bit (5-10 secs) and then the exception occurs.

To see if i had a error in my configuration i changed my routes.php to `Route::get('/', function () { $pdf = PDF::loadHTML('<b>Test</b>'); return $pdf->stream(); });`. With this i can see my "Test" in a PDF, so no exception.

I did not modify config/dompdf.php.

**Comment by belapie** [comment]
**Update**

1. If i remove the `<link href="//fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">` from welcome.blade.php i have the exception immediately counter to 5-10 secs. 
2. If i remove the `<style>` block, my PDF is shown.

It's seem that stylesheet (link href) are not supported. CSS attribute `display` seems to be causing the issues.

**Comment by allanjhonne** [comment]
Friend, I am having this same problem. How you solved the problem?

**Comment by riyaas** [comment]
As belapie mentioned, some CSS attributes creating issues. CSS attribute display (eg:- display: table) created same error for me.

**Comment by SinuheM** [comment]
There are some CSS attributes, see this page https://github.com/dompdf/dompdf/wiki/CSSCompatibility
and I solved putting inline styles

**Comment by volserverRay** [comment]
I have this issue is because `<o:p>` element tag appear in the HTML.
have to "sanitize" the html before passing it for render
