### ISSUE TITLE
Can't pass variables to template

### ISSUE THREAD

**Issue by gwilymgj** [barryvdh/laravel-dompdf#15]
Love this package, works great but for some reason I get an error when trying to pass to the template

In controller:

```
$order = Order::find($id);
$pdf = PDF::loadView('pdf.invoice', $order)->setPaper('a4')->setOrientation('portrait');
return $pdf->stream('invoice.pdf');
```

In the template:

```
{{$order->id}}
```

And I get an error:

```
Method Illuminate\View\View::__toString() must not throw an exception
```

If I remove the {{$order->id}} from the template the PDF works perfectly. Any help much appreciated - I must have misunderstood something..again... :)

**Comment by Penderis** [comment]
Just to clarify , this means the $data parameter must be a associative array?

**Comment by barryvdh** [comment]
Yeah it's just the same as a normal Laravel view..

**Comment by lebafu** [comment]
netm  bieeen ntm gracias :D
