### ISSUE TITLE
Call to a member function build_tree() on null issue still happening for me on 0.5.* - 0.6.*

### ISSUE THREAD

**Issue by sixteenstudio** [barryvdh/laravel-dompdf#150]
I am doing nothing different to those with this issue previously, I'm still getting this error:

```
PHP Fatal error:  Call to a member function build_tree() on null in /var/www/vhosts/website.com/httpdocs/vendor/dompdf/dompdf/include/dompdf.cls.php on line 676



[Symfony\Component\Debug\Exception\FatalErrorException]
Call to a member function build_tree() on null
```

I've tried with all versions and only 0.3.1 works, however this does not have support for Laravel 5 integration so I can't use this. Any ideas? It would be helpful to know what this is caused by so I could understand how my project might cause this whilst others don't...

**Comment by sunibnesazzad** [comment]
I am also facing the same Problem here .
