### ISSUE TITLE
Miss coding when called with Ajax

### ISSUE THREAD

**Issue by DanLuevano** [barryvdh/laravel-dompdf#151]
Hi, 
Env:
Windows 7 64, Laravel 5, xampp, Chrome/Firefox

Issue:
I have a listed items that allow to export the current line report (id) to PDF so on my button event I have an AJAX post call to my Controller. 
On the controller, I'm using this code:
$pdf = \PDF::loadView('create.template.formReportePDF',['data' => $data]);
return $pdf->download('report.pdf');

on my template.formReportePDF.blade.php I have just this:
@foreach ($data as $dato)
<p>$dato->name</p>
@endforeach

I'm not seeing the download window and on the 'Network' tab of my debugger I get this:
"%PDF-1.3
1 0 obj
<< /Type /Catalog
/Outlines 2 0 R
/Pages 3 0 R >>
endobj
2 0 obj
<< /Type /Outlines /Count 0 >>
endobj
3 0 obj
<< /Type /Pages
/Kids [6 0 R
]
/Count 1
/Resources <<....."

I use a similar code on other form, the only difference is the AJAX event.
Any suggestions?

**Comment by barryvdh** [comment]
I don't think you can force download a file with ajax.
