### ISSUE TITLE
Call to undefined method DOMText::getAttribute() when using certain <tags>

### ISSUE THREAD

**Issue by e11en** [barryvdh/laravel-dompdf#154]
When using `<thead>` or `<th>` in a table I get an error. Is there something I can do to make this work?

```
FatalErrorException in cellmap.cls.php line 437:
Call to undefined method DOMText::getAttribute()
```

**Comment by lezhnev74** [comment]
Have the same issue.

**Comment by ricardobarantini** [comment]
Me too.

**Comment by rianday** [comment]
so do I

**Comment by AgungPambudi** [comment]
in cellmap.cls.php

Change this code

// Determine where this cell is going
$colspan = $node->getAttribute("colspan");
$rowspan = $node->getAttribute("rowspan");

if ( !$colspan ) {
  $colspan = 1;
  $node->setAttribute("colspan",1);
}

if ( !$rowspan ) {
  $rowspan = 1;
  $node->setAttribute("rowspan",1);
}
to

$colspan = 1;
$rowspan = 1;

I tested it and the error was gone

**Comment by raxhet91** [comment]
I also have this problem and the solution of Agung is not working

**Comment by TheShah** [comment]
This could fix the error temporary:

changed the following lines (436-458) in cellmap.cls.php
from

```
// Determine where this cell is going
$colspan = $node->getAttribute("colspan");
$rowspan = $node->getAttribute("rowspan");

if ( !$colspan ) {
$colspan = 1;
$node->setAttribute("colspan",1);
}

if ( !$rowspan ) {
$rowspan = 1;
$node->setAttribute("rowspan",1);
}
```
to
```
// Determine where this cell is going
    if(method_exists($node, 'getAttribute')){
        $colspan = $node->getAttribute("colspan");
        $rowspan = $node->getAttribute("rowspan");
    }else{
        $colspan = false;
        $rowspan = false;
    }
    

    if ( !$colspan ) {
      $colspan = 1;
      if(method_exists($node, 'setAttribute')){
        $node->setAttribute("colspan",1);
      }
    }

    if ( !$rowspan ) {
      $rowspan = 1;
       if(method_exists($node, 'setAttribute')){
        $node->setAttribute("rowspan",1);
       }
    }

```
But this should be get fixed somewhere else!
On my side the error appeared when i had some open html-tags which were not closed properly.
Validate your html

**Comment by greedchikara** [comment]
Below worked for me:
setting `DOMPDF_ENABLE_HTML5PARSER => true` in dompdf config

**Comment by aljaber** [comment]
> Below worked for me:
> setting `DOMPDF_ENABLE_HTML5PARSER => true` in dompdf config

Worked for me too today, i encountered the same problem.

**Comment by juliocesar-oliveira** [comment]
I had the same problem, decided to do the following: I was using  **@php($variable)**, I needed to change it to:
**@php
  $variable
@endphp**
