### ISSUE TITLE
How to add date in each page of the Generated PDF

### ISSUE THREAD

**Issue by prabhakaran8737** [barryvdh/laravel-dompdf#155]
Is it possible to add date in each page of the generated PDF file? If possible how can I achieve it

**Comment by bebnev** [comment]
Hi.
You can achieve it with doing such steps:
1) Enable PHP in your dompdf by changing `DOMPDF_ENABLE_PHP` to `true` in `dompdf.php` config.
2) Add something like this to your pdf view:
```html
<h1>Test</h1>

<script type="text/php">
    if (isset($pdf)) {
        $size = 14;
        $text = date('d.m.Y');
        $font = Font_Metrics::get_font("helvetica");
        $text_height = Font_Metrics::get_font_height($font, $size);
        $width = Font_Metrics::get_text_width($text, $font, $size);
        $w = $pdf->get_width() - $width - 24;
        $y = $pdf->get_height() - $text_height - 24;

        $pdf->page_text($w, $y, $text, $font, $size);
    }
</script>
```
That script will add date to the bottom of the every page.

**Comment by prabhakaran8737** [comment]
@bebnev Thanks for your reply. Here is my code but it doesn't work it seems. I have enabled DOMPDF_ENABLE_PHP too

<script type="text/php">
    if (isset($pdf)) {
        $size = 14;
        $text = date('d.m.Y');
        $font = Font_Metrics::get_font("helvetica");
        $text_height = Font_Metrics::get_font_height($font, $size);
        $width = Font_Metrics::get_text_width($text, $font, $size);
        $w = $pdf->get_width() - $width - 24;
        $y = $pdf->get_height() - $text_height - 24;

        $pdf->page_text($w, $y, $text, $font, $size);
    }
</script>
<div style="width:auto">
	<div style="float:left;width:10%">testing</div>
	<div style="float:left;width:10%">testing123</div>
</div>

**Comment by bebnev** [comment]
@prabhakaran8737 Try to wrap your script tag in a `div` or `html body`:
```html
<div>
<script type="text/php">
    if (isset($pdf)) {
        $size = 14;
        $text = date('d.m.Y');
        $font = Font_Metrics::get_font("helvetica");
        $text_height = Font_Metrics::get_font_height($font, $size);
        $width = Font_Metrics::get_text_width($text, $font, $size);
        $w = $pdf->get_width() - $width - 24;
        $y = $pdf->get_height() - $text_height - 24;

        $pdf->page_text($w, $y, $text, $font, $size);
    }
</script>
</div>
<div style="width:auto">
    <div style="float:left;width:10%">testing</div>
    <div style="float:left;width:10%">testing123</div>
</div>
```
```html
<html><body>
<script type="text/php">
    if (isset($pdf)) {
        $size = 14;
        $text = date('d.m.Y');
        $font = Font_Metrics::get_font("helvetica");
        $text_height = Font_Metrics::get_font_height($font, $size);
        $width = Font_Metrics::get_text_width($text, $font, $size);
        $w = $pdf->get_width() - $width - 24;
        $y = $pdf->get_height() - $text_height - 24;

        $pdf->page_text($w, $y, $text, $font, $size);
    }
</script>

<!-- some html content goes here -->
</body></html>
```
or put script tag after some html:
```html
<div style="width:auto">
    <div style="float:left;width:10%">testing</div>
    <div style="float:left;width:10%">testing123</div>
</div>
<script type="text/php">
    if (isset($pdf)) {
        $size = 14;
        $text = date('d.m.Y');
        $font = Font_Metrics::get_font("helvetica");
        $text_height = Font_Metrics::get_font_height($font, $size);
        $width = Font_Metrics::get_text_width($text, $font, $size);
        $w = $pdf->get_width() - $width - 24;
        $y = $pdf->get_height() - $text_height - 24;

        $pdf->page_text($w, $y, $text, $font, $size);
    }
</script>
```

**Comment by prabhakaran8737** [comment]
Thanks it works

**Comment by igordrnobrega** [comment]
I could not get this working. Enabled:

"DOMPDF_ENABLE_PHP" => true,
"DOMPDF_ENABLE_JAVASCRIPT" => true,

no option worked for me.
Can u help?

**Comment by prabhakaran8737** [comment]
@igordrnobrega can you show us what you have tried other than these

**Comment by igordrnobrega** [comment]
@prabhakaran8737 after enabling this two options I tried what @bebnev proposed wrapping it in various places of the view.
https://github.com/barryvdh/laravel-dompdf/issues/37 With this thread and @etmind comment I could add the pages number.
