### ISSUE TITLE
How do you download PDF on event?

### ISSUE THREAD

**Issue by forddyce** [barryvdh/laravel-dompdf#156]
Details of the question can be found here: http://stackoverflow.com/questions/32439034/laravel-5-1-download-pdf-with-event

I just need to download the PDF through event. How to do it?

**Comment by Stefany93** [comment]
What kind of an event exactly?

**Comment by forddyce** [comment]
Never mind, just close this issue, I got a workaround.
The event is Laravel's event, a background process. See the question for the details.
