### ISSUE TITLE
Update documentation. 

### ISSUE THREAD

**Issue by Stefany93** [barryvdh/laravel-dompdf#157]
The documentation is very misleading, which cost me more than hour to figure out what is wrong. 
For example, for the installation, it says this:

> After updating composer, add the ServiceProvider to the providers array in config/app.php

> 'Barryvdh\DomPDF\ServiceProvider',

> You can optionally use the facade for shorter code. Add this to your facades:

> 'PDF' => 'Barryvdh\DomPDF\Facade',

However, this is WRONG for Laravel 5.1+ because the **providers** array has a different structure and the **facades** is renamed to "aliases".

So to make this work on Laravel 5.1, I had to add this code to the providers array:

` Barryvdh\DomPDF\ServiceProvider::class,`

And to add this line to the aliases array:

` 'PDF'       => Barryvdh\DomPDF\Facade::class, `

However, since the documentation hasn't been updated to Laravel 5.1 it took me a long time to figure it out, and I am guessed for other people as well. Please update. 

Or better yet, **add** a section for installation for Laravel 5.1

**Comment by barryvdh** [comment]
They're the same thing..

**Comment by Stefany93** [comment]
Ummm, no they are not o_O

**Comment by barryvdh** [comment]
Barryvdh\DomPDF\ServiceProvider::class is exactly the same as 'Barryvdh\DomPDF\Facade'.
It could be that the config key is named differently, but it just says, add em to the facades. It should be relatively clear, because all other package providers and facades are similar..

**Comment by Stefany93** [comment]
Yes, but for the classes for Laravel 5.1 there are two differences:

1. You add **::class** at the end;
2. You remove the quotes;

If you just add 'Barryvdh\DomPDF\ServiceProvider' into the providers array, as it is explained into the documentation, you will get an error. 

Same for the facades/aliases.

I just think this will safe newbies to laravel and not just them, but experienced people a lot of headache when they try to install this plugin to Laravel 5.1 and it throws them errors.

**Comment by barryvdh** [comment]
`SomClass::class` just returns the full namespace string. See http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class

It has the same result: https://3v4l.org/OcZ7J#v550

**Comment by Stefany93** [comment]
I suppose it is just giving me the error then for some reason, unless I do it with L 5.1 code style guides. My apologies.

**Comment by barryvdh** [comment]
Updated docs

**Comment by petidesoftwares** [comment]
where can i get the updated documentation
