### ISSUE TITLE
"Frame not found in cellmap"

### ISSUE THREAD

**Issue by J1Duran** [barryvdh/laravel-dompdf#161]
Any idea to avoid "Frame not found in cellmap"? When trying to print more than 100 records.

https://guides.github.com/features/mastering-markdown/
![captura de pantalla de 2015-09-11 13 03 23](https://cloud.githubusercontent.com/assets/13131609/9821665/8fa7e4ba-5885-11e5-9122-6f83af0a134f.png)
![captura de pantalla de 2015-09-11 13 03 26](https://cloud.githubusercontent.com/assets/13131609/9821666/8fabfbae-5885-11e5-8d8b-69394a0d6be1.png)

**Comment by martinlazarov** [comment]
I have this issue too. What is the solution?

**Comment by J1Duran** [comment]
The problem is with CSS. I solved it by adapting an example of DOMPDF.
Seeks that best suits your needs.
Here:http://pxd.me/dompdf/www/examples.php

**Comment by RosnelAlejandra** [comment]
pxd me dompdf examples en Google
ERR_CONNECTION_TIMED_OUT

Can you sent me the example please? aleja_2092@hotmail.com
