### ISSUE TITLE
Not able to install dompdf on Laravel Framework version 5.1.10 (LTS)

### ISSUE THREAD

**Issue by omprakashu** [barryvdh/laravel-dompdf#164]
I have changed in composer.json file   "barryvdh/laravel-dompdf": "0.6.*" but after updating composer i got the following error:

> php artisan clear-compiled
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel/framework v5.1.19
    - Conclusion: don't install laravel/framework v5.1.18
    - Conclusion: don't install laravel/framework v5.1.17
    - Conclusion: don't install laravel/framework v5.1.16
    - Conclusion: don't install laravel/framework v5.1.15
    - Conclusion: don't install laravel/framework v5.1.14
    - Conclusion: don't install laravel/framework v5.1.13
    - Conclusion: don't install laravel/framework v5.1.12
    - Conclusion: don't install laravel/framework v5.1.11
    - Conclusion: remove laravel/framework v5.1.10
    - Conclusion: don't install laravel/framework v5.1.10
    - Conclusion: don't install laravel/framework v5.1.9
    - Conclusion: don't install laravel/framework v5.1.8
    - Conclusion: don't install laravel/framework v5.1.7
    - Conclusion: don't install laravel/framework v5.1.6
    - Conclusion: don't install laravel/framework v5.1.5
    - Conclusion: don't install laravel/framework v5.1.4
    - Conclusion: don't install laravel/framework v5.1.3
    - Installation request for braunson/laravel-html5-forms dev-master -> satisf
iable by braunson/laravel-html5-forms[dev-master].
    - Conclusion: don't install laravel/framework v5.1.2
    - Conclusion: don't install laravel/framework v5.1.1
    - braunson/laravel-html5-forms dev-master requires illuminate/support 4.2.*
-> satisfiable by illuminate/support[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2,
v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - don't install illuminate/support v4.2.1|don't install laravel/framework v5
.1.0
    - don't install illuminate/support v4.2.12|don't install laravel/framework v
5.1.0
    - don't install illuminate/support v4.2.16|don't install laravel/framework v
5.1.0
    - don't install illuminate/support v4.2.17|don't install laravel/framework v
5.1.0
    - don't install illuminate/support v4.2.2|don't install laravel/framework v5
.1.0
    - don't install illuminate/support v4.2.3|don't install laravel/framework v5
.1.0
    - don't install illuminate/support v4.2.4|don't install laravel/framework v5
.1.0
    - don't install illuminate/support v4.2.5|don't install laravel/framework v5
.1.0
    - don't install illuminate/support v4.2.6|don't install laravel/framework v5
.1.0
    - don't install illuminate/support v4.2.7|don't install laravel/framework v5
.1.0
    - don't install illuminate/support v4.2.8|don't install laravel/framework v5
.1.0
    - don't install illuminate/support v4.2.9|don't install laravel/framework v5
.1.0
    - Installation request for laravel/framework 5.1.\* -> satisfiable by laravel
/framework[v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v5.1.14, v5.1.15,
 v5.1.16, v5.1.17, v5.1.18, v5.1.19, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.
1.7, v5.1.8, v5.1.9].

**Comment by QWp6t** [comment]
This isn't a bug with `barryvdh/laravel-dompdf`. This is a problem on your end.

**Comment by HoangTrung** [comment]
Try to install lower version 
`composer require barryvdh/laravel-dompdf:0.7.0`
