### ISSUE TITLE
PDF creation and image

### ISSUE THREAD

**Issue by Cannonb4ll** [barryvdh/laravel-dompdf#165]
Hello,

I am currently succesfully generating a PDF with a system im building. There is only 1 problem, loading in images from the storage folder inside the PDF.

Is there any practical way of doing this? I am currently using intervention like following:

return Image::make(storage_path($logo_path))->response('jpg');

If I visit the route in my browser I succesfully see the image, but the PDF is telling me it has a unknown image type. What to do in this kind of situation?

**Comment by joaomlopes** [comment]
+1

**Comment by mangrovestudios** [comment]
see also #221
