### ISSUE TITLE
Greek language problem

### ISSUE THREAD

**Issue by nicsmyrn** [barryvdh/laravel-dompdf#167]
I am using Laravel 5.1 and I ve installed laravel-dompdf to my project. Unfortunately dompdf is not working for Greek characters. 
I am using a simple view with lite html code and I have added in my header the meta tag charset utf8.
My view is working correctly as html page but when I use pdf stream or download dompdf methods Greeks are like question marks 
Is there any solution?
Thank u

**Comment by nicsmyrn** [comment]
[Solved]= the only think i added is the DeJaVu font-family.
<pre>
   <style>
      body { font-family: DejaVu Sans, sans-serif; }
    </style>
</pre>

**Comment by Lordin** [comment]
I tried the above, but it's not working for me.
