### ISSUE TITLE
extra black pages

### ISSUE THREAD

**Issue by celiakessassi** [barryvdh/laravel-dompdf#172]
I have  a large content in html and every time I stream the pdf file their is blank pages and sometime i could find some texte above the other, it's so weard it's like the format rendred is not correct.

**Comment by PunitSaharan** [comment]
@celiakessassi hi you solve this issue ?? i am getting same problem... Please help if you have solution

**Comment by celiakessassi** [comment]
I have used this repository niklasravnsborg\LaravelPdf.

**Comment by nguyenlegh** [comment]
Have you guys fix this yet? i met this problem, when export pdf, there's always one more blank page

**Comment by nguyenlegh** [comment]
I fixed this by remove some stylesheet class which made blank page

**Comment by celiakessassi** [comment]
Hi there sorry for the late answer, I have tried to fix that by removing stylesheet class but as I remember it just fixed the issue partly it minimize only the number of blank pages , and I didn't get any answer about it so end up using an other repository that one niklasravnsborg\LaravelPdf.

**Comment by error500** [comment]
Had same issue :+1: 
Resolved by minifying blade view :
```
<table>
    <tr>
        <td >
            SomeValue
        </td>
        <td >
               {{ $data->somedata }}
         </td>
    </tr>
</table>
```


After minifying


```
<table><tr><td  >Value</td><td >{{ $data->ROOM_NAME }}</td></tr></table>
```

**Comment by error500** [comment]
Could be nice to "filter" blade view while using [this minify trick in PDF::loadView](http://laravel-tricks.com/tricks/minify-html-output)

http://laravel-tricks.com/tricks/minify-html-output

**Comment by HoracioEspinosa** [comment]
You can override the method loadView as 

`public function loadView($view, $data = array(), $mergeData = array(), $encoding = null){
        $html = MinifyView::sanitize_output($this->view->make($view, $data, $mergeData)->render());
        return $this->loadHTML($html, $encoding);
    }`

when MinifyView::satinize_output is this function in the MinifyView class:

` public static function sanitize_output($buffer) {

        $search = array(
            '/\>[^\S ]+/s',     // strip whitespaces after tags, except space
            '/[^\S ]+\</s',     // strip whitespaces before tags, except space
            '/(\s)+/s',         // shorten multiple whitespace sequences
            '//' // Remove HTML comments
        );

        $replace = array(
            '>',
            '<',
            '\\1',
            ''
        );

        $buffer = preg_replace($search, $replace, $buffer);

        return $buffer;
    }`
