### ISSUE TITLE
How do i install dompdf on Lavaravel 5.1 without composer?

### ISSUE THREAD

**Issue by danteblink** [barryvdh/laravel-dompdf#175]
Hi,

I don't have composer on my production server, however, i need to install domPDF. Is there any way to install it manually? 

Thanks in advance!

**Comment by slayerfat** [comment]
if i understand correctly, you want a script or manually download the sources:

https://github.com/barryvdh/laravel-dompdf/tree/master/src

https://github.com/barryvdh/laravel-dompdf/releases/tag/v0.6.0

those are the sources.

if you have shell access you can do a bash script to download the sources, if you dont, you can download it to your pc and FTP/SSH to your server.

**Comment by danteblink** [comment]
Thanks! But i managed to do it by installing dompdf locally via composer and then rewriting the 'vendor' dir on my production server.

i Know it wasn't the best solution but I had to do it because i don't have shell access on my production server.

**Comment by vioclick** [comment]
Hi danteblink. Besides copy app\vendor\dompdf\ and app\vendor\barryvdh\laravel-dompdf directories, and append classes to app.config, did you add or change other file(s)??

Thanks!

**Comment by danteblink** [comment]
Hi, 

Im not really sure but i just copied these directories you mention and it worked. Do yo have any errors?

**Comment by Cendra123** [comment]
> Thanks! But i managed to do it by installing dompdf locally via composer and then rewriting the 'vendor' dir on my production server.
> 
> i Know it wasn't the best solution but I had to do it because i don't have shell access on my production server.

it doesnt work in laravel 5.8
