### ISSUE TITLE
RuntimeException in AbstractGenerator.php 

### ISSUE THREAD

**Issue by iamkallolpratim** [barryvdh/laravel-dompdf#181]
I used '<addr>"barryvdh/laravel-snappy": " 0.2.x"</addr>' for generate pdf from from html. When I compiled the code I got this error

#The exit status code '127' says something went wrong:
#stderr: "sh: 1: /usr/local/bin/wkhtmltopdf: not found
#"stdout: ""
#command: /usr/local/bin/wkhtmltopdf --lowquality --orientation 'landscape' --page-size 'a4' '#/tmp/knp_snappy566fed16b148c7.75113245.html' 'invoices/9.pdf'.

**Comment by barryvdh** [comment]
So does `/usr/local/bin/wkhtmltopdf` exist? Otherwise, change the path in the config or install it.

**Comment by iamkallolpratim** [comment]
how can i install wkhtmltopdf  through composer

**Comment by barryvdh** [comment]
As linked in the readme on https://github.com/barryvdh/laravel-snappy
https://github.com/KnpLabs/snappy#wkhtmltopdf-binary-as-composer-dependencies
If you keep having this issue, please create an issue on laravel-snappy instead of dompdf

**Comment by iamkallolpratim** [comment]
thank you very much
