### ISSUE TITLE
css is not loaded when pass html data

### ISSUE THREAD

**Issue by iamkallolpratim** [barryvdh/laravel-dompdf#182]
Now there's a new issue. The CSS is not loaded in that generated pdf. How can I fix this issue in dompdf

**Comment by barryvdh** [comment]
Use full url (including http://)

**Comment by iamkallolpratim** [comment]
can u please give me example. My code is here:


$html = $request->html;
$invoice_id = $request->invoice_id;
 $pdf = PDF::loadHTML($html)->setPaper('a4')->setOrientation('landscape')
             ->setWarnings(false)>save('invoices/'.$invoice_id.'.pdf');
 return $pdf->stream();

**Comment by barryvdh** [comment]
Do you have inline css in your view?

**Comment by iamkallolpratim** [comment]
no

**Comment by barryvdh** [comment]
So where do you put your css? Try putting it in a `<style>` tag as a style link.

**Comment by iamkallolpratim** [comment]
can i link the css file on that perticuler html file that I was sending through dompdf

**Comment by barryvdh** [comment]
Sorry, I don't understand. Just insert CSS in your HTML, as you alwasy do (either inline or linked with the full url).
See for examples here; https://github.com/dompdf/dompdf/tree/master/www/test

**Comment by iamkallolpratim** [comment]
thank you very much.
