### ISSUE TITLE
$pdf->stream() not rendering pdf.

### ISSUE THREAD

**Issue by ashokkumarjuly** [barryvdh/laravel-dompdf#183]
The pdf not rendering on browser, it displaying the below error. any idea why it happens?

%PDF-1.3 1 0 obj << /Type /Catalog /Outlines 2 0 R /Pages 3 0 R >> endobj 2 0 obj << /Type /Outlines /Count 0 >> endobj 3 0 obj << /Type /Pages /Kids [6 0 R ] /Count 1 /Resources << /ProcSet 4 0 R /Font << /F1 8 0 R >> >> /MediaBox [0.000 0.000 595.280 841.890] >> endobj 4 0 obj [/PDF /Text ] endobj 5 0 obj << /Creator (DOMPDF) /CreationDate (D:20151216093337+00'00') /ModDate (D:20151216093337+00'00') >> endobj 6 0 obj << /Type /Page /Parent 3 0 R /Contents 7 0 R >> endobj 7 0 obj << /Filter /FlateDecode /Length 84 >> stream xœã2Ð300P@&‹Ò¹œBŒMôÍÌ-ÍôLÌ,BRôÝôBÒ¢5ŠósS RÒ’óóJRóJ2R‹R5cB¼\C;6— endstream endobj 8 0 obj << /Type /Font /Subtype /Type1 /Name /F1 /BaseFont /Times-Roman /Encoding /WinAnsiEncoding >> endobj xref 0 9 0000000000 65535 f 0000000008 00000 n 0000000073 00000 n 0000000119 00000 n 0000000273 00000 n 0000000302 00000 n 0000000416 00000 n 0000000479 00000 n 0000000634 00000 n trailer << /Size 9 /Root 1 0 R /Info 5 0 R >> startxref 744 %%EOF 

The code to generate  is 
    $pdf_content = "some pdf content here";
    $html = $pdf_content ;

$pdf = App::make('dompdf');
$pdf->loadHTML($html)->setPaper('a4')->setOrientation('portrait');
 return $pdf->stream();

It works well in local machine (ubuntu machine with xampp)
but not working in production server (WHM cPanel)

**Comment by dondiegodelavega** [comment]
could you fix the issue , its working for me on desktop but getting same result on mobile chrome . thanks

**Comment by barryvdh** [comment]
Check that the headers are sent correctly. Perhaps a echo which messes up the result? (Some server use output buffering, some dont)

**Comment by dondiegodelavega** [comment]
Thanks for the response . seems the headers are sent correctly. and works perfectly fine n desktop. however in stream when i set 'Attachment' => 0 , i get the same result as what i get on mobile phone( im using chrome, firefox and sofari on iphone). there might bean for streaming on phones.

**Comment by gwiji** [comment]
I have the same issue but with little data. For large data it works fine.

**Comment by BostonKenne** [comment]
Same problem!! how to fix??

**Comment by vdxas** [comment]
I am still having the same Issue

**Comment by chellem** [comment]
Hello,

Am having the same problem, the issue come with return carriage not taking into consideration.

A quick fix:

```php
$pdf = PDF::loadView('pdf.invoice', [])->setPaper('a4', 'landscape')->setWarnings(false);

return response()->streamDownload(function () use ($pdf) {
    echo $pdf->output();
}, 'invoicepdf');
```
Hope it helps

**Comment by deepaksaini2** [comment]
Same problem!! how to fix??

**Comment by radgezito** [comment]
I'm having the same problem. I'm using laravel dompdf with dockerfile, i need install some extra fonts?

**Comment by SynfonyBugs** [comment]
For anyone having still this issue. Check if u have added exit(), after the stream(). So the script ends there.

```
$dompdf->stream("mypdf.pdf", [
            "Attachment" => false
 ]);
        **exit();**
```

**Comment by drico83** [comment]
> For anyone having still this issue. Check if u have added exit(), after the stream(). So the script ends there.
> 
> ```
> $dompdf->stream("mypdf.pdf", [
>             "Attachment" => false
>  ]);
> 
>  exit();
> ```

it's work fo me, thanks

**Comment by CSMmohamed** [comment]
$dompdf->stream("mypdf.pdf", [
            "Attachment" => false
 ]);

 exit();
Done successfully !!

**Comment by jarestrepot** [comment]
En verdad llevaba horas buscando este problema y con el exit() después de stream me ha funcionado, gracias!!
