### ISSUE TITLE
Maximum execution time of 60/120/600 seconds exceeded

### ISSUE THREAD

**Issue by baljeetbhinder** [barryvdh/laravel-dompdf#184]
Hi I am trying to generate pdf from view

$incomes = Income::all();
set_time_limit(600); //also have tried setting it to 60 and 120 earlier
$pdf = PDF::loadView('incomes.index', ['incomes'=>$incomes]);
return $pdf->download('sample.pdf');

![600 seconds exceeded](https://cloud.githubusercontent.com/assets/8347607/11846082/ea5bc914-a43c-11e5-87bb-457495fa3c12.png)

![120 seconds exceeded](https://cloud.githubusercontent.com/assets/8347607/11846096/fd39d8c8-a43c-11e5-873f-06e6998e24fe.png)

images are attached here with, can you please check the code and provide some solution .
Thanks.

**Comment by nicksmetBagaar** [comment]
+1

**Comment by michaelachrisco** [comment]
I am having the same issue. If you are using Laravel, there is a couple ways around the issue. One is to generate the PDF's on a report runner and email the user when finished. 

Other than that, the library is a bit on the slow side.

**Comment by michaelachrisco** [comment]
Bit of an update. 

Found out this line is causing a huge slowdown:
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet"  crossorigin="anonymous">

Makes sense that outside resources cause a slowdown.

**Comment by noOnEeLLez** [comment]
Hello! I also have the same error when fetching all the data in my table. I don't have bootstrap included in my blade file. How can I fixed it? TIA

**Comment by michaelachrisco** [comment]
How long does the retrieval of the data take without the creation of the PDF? Any outside resources such as css files or partials may cause a huge slowdown with this library.

**Comment by noOnEeLLez** [comment]
If I just loading the same function in an empty view it takes no seconds to load it. But when converting to a pdf file it result to an error.

**Comment by komakino** [comment]
I also have the problem. Seems like when a table grows taller than one page there is a major memory leak.

**Comment by noOnEeLLez** [comment]
Actually I don't show any table. What I mean in table is the table from db.

**Comment by hellfull** [comment]
'Bit of an update.

Found out this line is causing a huge slowdown:

<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet"  crossorigin="anonymous">
Makes sense that outside resources cause a slowdown.'

bootstrap is not related with the cause of the problem . You need to search for max_execution_time in your php configuration usually php.ini and change the value as it fits for you.
