### ISSUE TITLE
I got message "Class 'PDF' not found"

### ISSUE THREAD

**Issue by mrnonz** [barryvdh/laravel-dompdf#185]
in config/app.php

Barryvdh\DomPDF\ServiceProvider::class, 
'PDF'       => Barryvdh\DomPDF\Facade::class,

and in composer.json

"require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "barryvdh/laravel-dompdf": "0.6.*"
    },

but I got this message "Class 'PDF' not found"
How to fix this bug?

**Comment by olifolkerd** [comment]
Did you get class PDF not found, when trying to use the plugin or when you were installing it?

If you are using Laravel 5 you will need to take account of the namespacing of the facade. The PDF facade is in the global namespace so when using it you would either need to include the following line near the top of the file where you use the PDF facade.
```php
use \PDF;
```

or specify the namespace when using the facade:
```php
\PDF::loadView('pdf.invoice', $data);
```

**Comment by mrnonz** [comment]
In my Controller file included about that line
```php
<?php

namespace App\Http\Controllers\Backend;

use App;
use PDF;
```

And I tried about this code
```php
\PDF::loadView('pdf.invoice', $data);
```

I got same error message

**Comment by olifolkerd** [comment]
Did you run ```composer update``` in the console, in the root dir of the project after you updated the composer.json file?

**Comment by mrnonz** [comment]
Sure, I run this command `sudo composer update -vvv` and I saw ` - Installing barryvdh/laravel-dompdf (v0.6.1)`

**Comment by mrnonz** [comment]
But when use this code 
```php
use Barryvdh\DomPDF\Facade as PDF;
```

I got a new error like this

`
Class dompdf.wrapper does not exist
`

**Comment by mrnonz** [comment]
I can solve this issue, try this solution
`
 php artisan cache:clear 
`
and
`
 php artisan config:cache
`
