### ISSUE TITLE
Permission denied on Windows

### ISSUE THREAD

**Issue by J03Bukowski** [barryvdh/laravel-dompdf#186]
That is what it is happening with Windows:

```
ErrorException in font_metrics.cls.php line 366:
unlink(H:\xampp\htdocs\project\storage\temp//049952fa0c110b2f9e38d468b1a08d06): Permission denied
```

I tried in every way to change the permission but it was useless.

**Comment by olifolkerd** [comment]
are you using IIS or apache?

**Comment by J03Bukowski** [comment]
Xampp, so with Apache

**Comment by blackorwhite123** [comment]
I have same issue with @J03Bukowski !

**Comment by olifolkerd** [comment]
have you given apache write permission to the storage directory?

**Comment by SharpKode** [comment]
Same here.
It can create the file, so Apache should have write permissions.
Also Laravel is working in this directory when generating views and etc, and it never had a problem with unlinking.

**Comment by nont65** [comment]
I fixed code on file font_metrics.cls.php on line 366 from
unlink($local_temp_file);

to

if (!$local_temp_file) {
   unlink($local_temp_file);
   return false;
}

and it work.

**Comment by fido78** [comment]
I have same issue any fix?

**Comment by interstellarDust** [comment]
we need a fix for this issue ASAP. or we should stop using this library???

**Comment by barryvdh** [comment]
Try it upstream in the dompdf report.

**Comment by barryvdh** [comment]
*repository

**Comment by lerzenit** [comment]
Same issue, I tried setting TEMP_DIR PATH to the project public directory and it didn't work. Alwways saying permission denied.

**Comment by 0x1ad2** [comment]
Also had this error, checked my permissions, tried to reinstall all my vendor packages and republished configurations. Turned out it has something to do with link and script tags dompdf didn't like it.

**Comment by delahappy** [comment]
Was there any resolution to this? I am experiencing it as well. When I generated a very plain html document I didn't get the error but as soon as I included the bootstrap css framework I got the error.

**Comment by delahappy** [comment]
Actually, the suggestion from nont65 worked.  Is it possible to get this fix in the repository so that I don't have to edit the vendor code in my project?

**Comment by MateEke** [comment]
nont65's solution works for me. Thanks!

**Comment by alessandrobelli** [comment]
nont65's solution works for me too!

**Comment by MyintThuLwin** [comment]
Thanks nont65 yours one work for me.

I fixed code on file font_metrics.cls.php on line 366 from
unlink($local_temp_file);

to

if (!$local_temp_file) {
unlink($local_temp_file);
return false;
}

**Comment by bakuryuthem0** [comment]
where is the file "font_metrics.cls.php"? i searched in the laravel-dmpf folder in vendor, and there's no file font_metrics.cls.php

**Comment by nont65** [comment]
@bakuryuthem0 

If your problem is dompdf and you used it by Composer package barryvdh/laravel-dompdf version "0.6.*", I think it should be in vendor/dompdf/dompdf/include 

But if you used recent version, I'm not sure about it's path.
