### ISSUE TITLE
Getting blank pages with simple example

### ISSUE THREAD

**Issue by pxcjs** [barryvdh/laravel-dompdf#187]
[Dossier_Sun Jan 03 2016 20-16-33 GMT+0200 (EET).pdf](https://github.com/barryvdh/laravel-dompdf/files/76697/Dossier_Sun.Jan.03.2016.20-16-33.GMT.0200.EET.pdf)
Hi,

I've tried to make this work but with no luck. I am surely missing something.
I use your example:
```php
$pdf = App::make('dompdf.wrapper');
$pdf->loadHTML('<h1>Test</h1>');
return $pdf->stream();
```

Need to mention the following configuration:
* CentOS release 6.7 (Final)
* PHP 5.6.14
* Apache/2.2.15 
* Laravel 5.1.*

Do i need special extensions for php to make **laravel-dompdf** to work?

**All I get is blank pages.** 
Example attached.
Need help!

**Comment by pxcjs** [comment]
**Issue is caused by nginx proxy.**

**Comment by venkateshcontus** [comment]
How to solve this issue

**Comment by ThunderBirdsX3** [comment]
@pxcjs 

> Issue is caused by nginx proxy.

How to config Nginx in this case.
