### ISSUE TITLE
File type HTML document (text/html) is not supported

### ISSUE THREAD

**Issue by Harrrrry** [barryvdh/laravel-dompdf#189]
Hyy, i am using dompdf with laravel 5
My view code is
<?php
$dompdf = new DOMPDF();
$dompdf->load_html($html);
$dompdf->render();
$dompdf->stream("hello_world.pdf");
?>

Pdf generated but nothing show in pdf except a below error.
Unable to open document “file:///tmp/hello_world-2.pdf”.
File type HTML document (text/html) is not supported

Thanks in advance

**Comment by bebnev** [comment]
@Harrrrry check if webserver user has write permissions on the `DOMPDF_FONT_DIR (lib/fonts by default)` path.

**Comment by Harrrrry** [comment]
@bebnev  I don't think this error because of permission, actually i am using dompdf in my application and its working fine like this
$pdf = PDF::loadView('viewfile',array('user_data' => $user_data));
        return $pdf->download('example.pdf');
But this code in controller
I want to use dompdf in view file

**Comment by belov91** [comment]
@Harrrrry did you find a solution for this, I have the same problem?
