### ISSUE TITLE
strftime() error in php-font-lib

### ISSUE THREAD

**Issue by SharpKode** [barryvdh/laravel-dompdf#190]
It may be an issue in php-font-lib, but maybe someone has a solution here too.

When trying to export a PDF file, I get this error:
`ErrorException in Font_Binary_Stream.php line 249: strftime() expects parameter 2 to be integer, float given`

After I checked the code, it seems, it loads a wrong number when processing the font file. When reading a datetime, `readUInt32()` returns a negative number (which should be a positive timestamp in my opinion), from which it subtracts `2082844800`, making it overflow and creating a float instead of an int.

Has any of you met this error? Any idea how to solve it the right way?
I'm using PHP 7.0.2 by the way.

Thank you.

**Comment by watercayman** [comment]
Confirm, same error with PHP 7.0.2

**Comment by barryvdh** [comment]
This is probably an error in dompdf itself. Can you reproduce it with stand-alone dompdf?

Can you submit an issue there? https://github.com/dompdf/dompdf

**Comment by barryvdh** [comment]
See https://github.com/PhenX/php-font-lib/pull/43

Which includes a fix. Can you guys checkout that fix and provide feedback in the linked issue?

**Comment by watercayman** [comment]
The fix above does successfully resolve the strftime() issue.  However, I don't believe this is actually a bug.  The issue in #191 seems to be the root cause.  If I remove calls to external fonts (in this case bootstrap css), the strftime() issue goes away, regardless of including the fix or not.

**Comment by barryvdh** [comment]
Please reply in the upstream issue.

**Comment by watercayman** [comment]
I did Barry, and also sent in a report on the dompdf page.  I've now switched to your snappy package and it works great. Many thanks.

**Comment by barryvdh** [comment]
Ok, thanks!

**Comment by arnabrahman** [comment]
Yup when i remove bootstrap css files it works. But now pdf isn't using css, doesn't look good. Need to explore Snappy to see if it solves the problem.
