### ISSUE TITLE
how can i use  page-break-after: always; for table in laravel ?

### ISSUE THREAD

**Issue by hamelraj89** [barryvdh/laravel-dompdf#193]
im getting error so if i use page-break i can solve this but i don't know how to use i tried many way but it won't work

```
DOMPDF_Exception in cellmap.cls.php line 244:
Frame not found in cellmap
```

My method -

```
public function invoice($id){
        $job = Job::find($id);
        $sum = DB::table('charges')
            ->where('job_id', $job->id)
            ->sum('amount');
        $charges = Charge::select('charges.*','consignees.name')
            ->leftJoin('jobs','jobs.id','=','charges.job_id')
            ->leftJoin('consignees','consignees.id','=','jobs.consignee_id')
            ->where('job_id', $job->id)
            ->get();
        $invoice = DB::table('jobs')
            ->where('id',$id)
            ->sum('invoice_value');
        $total = $sum - $invoice ;
        $pdf = \PDF::loadView('jobs.invoice',compact('job','sum','charges','total'));
        return $pdf->download('invoice.pdf');
    }
```

my invoice -

```
 <tbody>
        <?php $i=0 ?>
        @foreach($charges as $expense)
            <?php $i++ ?>
            <tr>

                <td class="id">{!! $expense->id !!}</td>
                <td class="date">{!! $expense->date!!}</td>
                <td class="charge">{!! $expense->charge!!}</td>
                <td class="cat">{!! $expense->category!!}</td>
                <td class="amount">{!! $expense->amount!!}</td>

            </tr>

        @endforeach
        <tr>
            <td colspan="4">TOTAL EXPENSES</td>
            <td class="total">{!!  $sum !!}</td>
        </tr>
        <tr>
            <td colspan="4">INVOICE VALUE</td>
            <td class="total">{!! $job->invoice_value!!}</td>
        </tr>
 </tbody>
```

**Comment by aaesis** [comment]
Pravansik,

I share to you on how it will break nicely and cleanly:

if( $i % 10 == 0 ){
            echo '<div class="breakNow"></div>';
 ....
}

In your css code:
 div.breakNow {
       page-break-inside:avoid; 
       page-break-after:always;            
 }

I break the table on every 10, you can customize it in your own :)

**Comment by Pravinslk** [comment]
aaesis im really confuse you are telling use your idea.... i have publish my whole code so if you can tell me to how  to put your code with mine ????

**Comment by Pravinslk** [comment]
i tried but i wont work can u compine with my code and give me idea ?

**Comment by Pravinslk** [comment]
Thanks its working :)

**Comment by sayali05** [comment]
howz dis working?

**Comment by Pravinslk** [comment]
This is the way to page break if you show your code can try to help you 
```
<style>
.page-break {
    page-break-after: always;
}
</style>
<h1>Page 1</h1>
<div class="page-break"></div>
<h1>Page 2</h1>
```

**Comment by sayali05** [comment]
Hi,

  Thanks for your reply. But its not working in my code.

**Comment by Pravinslk** [comment]
Hi @sayali05 post ur questions stack or laracast tag me ? then can help

**Comment by sayali05** [comment]
hi, there is so mant issue in my dompdf page. First i want to set top in all page excluding first page. Is it possible.

**Comment by Pravinslk** [comment]
bro @sayali05 if you really want solve ur issues just post ur questions somewhere. without showing your codes no one can't help u :( [Add Margin Link](http://stackoverflow.com/questions/11649052/print-margins-in-dompdf)

**Comment by sayali05** [comment]
Where should i put my issue. Actually i am new for github. i dont know exactly what to do. Can you tell me.

**Comment by Pravinslk** [comment]
post ur quz here [http://stackoverflow.com/](http://stackoverflow.com/) or [https://laracasts.com/](https://laracasts.com/)

**Comment by kapilpaul** [comment]
@Pravinslk can you please give me an idea or can you please paste your codes so that I can get an Idea?

**Comment by Pravinslk** [comment]
@kapilpaul if you installed **laravel-dompdf**
then create view file in view path `resource/view/invoice.blade.php`
then paste this code 
```
<!DOCTYPE html>
<html>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<style>
.page-break {
    page-break-after: always;
}
</style>
<body>

<h1>Page 1</h1>
<div class="page-break"></div>
<h1>Page 2</h1>

</body>
</html>
```
your route like this `Route::get('/invoice', 'HomeController@createInvoice');`
in your **HomeController**
```
public function createInvoice() {
$pdf = \PDF::loadView('invoice');
return $pdf->download('invoice.pdf');
}
```
this is basic try and let me know

**Comment by hamelraj89** [comment]
@aaesis aaesis has answered

**Comment by ph4t0o0o0om** [comment]
@hamelraj89  Hi I have same problem would you help me

**Comment by ph4t0o0o0om** [comment]
@aaesis  Hi sir would you please help me? This is my problem . https://stackoverflow.com/questions/72371363/automatic-page-break-using-laravel-mpdf . thank you

**Comment by hamelraj89** [comment]
@ph4t0o0o0om check your question [Link]( https://stackoverflow.com/questions/72371363/automatic-page-break-using-laravel-mpdf)

**Comment by boyadmin** [comment]
![image](https://user-images.githubusercontent.com/33852279/200489384-d232b13a-ec3e-4541-96ba-a319bece02cf.png)

I have same problem ,table   td rowspan

![image](https://user-images.githubusercontent.com/33852279/200489496-310a8993-b6f4-4708-a1a5-21b81b3d7458.png)
