### ISSUE TITLE
cannot render qr code

### ISSUE THREAD

**Issue by engelfarillas** [barryvdh/laravel-dompdf#194]
hi i cant seem to render a qr code through this package. i am using https://github.com/SimpleSoftwareIO/simple-qrcode qr code generator. i have tried to render the qr code in different formats(svg, png, eps) but png and eps renders a bunch of random characters. in the case of svg, there is no output at all to the page. i have called it as follows:
**$pdf = PDF::loadView('emails.applicationformpdf');
    return $pdf->stream();**
where the qr code is in a blade template(using laravel v4.2 btw):
**{{ QrCode::size(250)->format('png')->generate('Hello') }}**

am i doing something wrong??

**Comment by stokic** [comment]
You could do this:

`<img src="data:image/png;base64, {{ base64_encode(QrCode::format('png')->size(100)->generate('Make me into an QrCode!')) }} ">`

**Comment by lenh** [comment]
I had a similar issue where the QR code simply would not render in a pdf. The above approach fixed it for me, although I'm using https://github.com/barryvdh/laravel-snappy

**Comment by AdiPP** [comment]
> You could do this:
> 
> `<img src="data:image/png;base64, {{ base64_encode(QrCode::format('png')->size(100)->generate('Make me into an QrCode!')) }} ">`

it works, thanksss

**Comment by palaciosdiego** [comment]
> > You could do this:
> > `<img src="data:image/png;base64, {{ base64_encode(QrCode::format('png')->size(100)->generate('Make me into an QrCode!')) }} ">`
> 
> it works, thanksss

Works for me to!

**Comment by vishaldamasiya** [comment]
my QR code path 

![image](https://user-images.githubusercontent.com/99727207/155128277-ce179ba7-f992-4b61-9d3f-0ac8518fc7cf.png)


and invoice pdf download in not show QR code

--------------------------------------------------------

controller code

use SimpleSoftwareIO\QrCode\Facades\QrCode;


public function print($id)
{
$invoice = $this->invoiceRepository->findOrFail($id);
$html = view('admin::sales.invoices.pdf', compact('invoice'))->render();

return PDF::loadHTML($this->adjustArabicAndPersianContent($html))
->setPaper('a4')
->download('invoice-' . $invoice->created_at->format('d-m-Y') . '.pdf');
}

private function adjustArabicAndPersianContent($html)
{
$arabic = new \ArPHP\I18N\Arabic();

$p = $arabic->arIdentify($html);

for ($i = count($p) - 1; $i >= 0; $i -= 2) {
$utf8ar = $arabic->utf8Glyphs(substr($html, $p[$i - 1], $p[$i] - $p[$i - 1]));
$html = substr_replace($html, $utf8ar, $p[$i - 1], $p[$i] - $p[$i - 1]);
}
return $html;
}

----------------------------------------------------
but download invoice pdf in not Show QRcode
