### ISSUE TITLE
pass value to the PDF

### ISSUE THREAD

**Issue by Pekinese** [barryvdh/laravel-dompdf#195]
How can I pass some values to the PDF and render them into the PDF file?
Here's what I tried already:

```
$test = 'test';
$pdf = PDF::loadView('invoices.invoice', $test);
return $pdf->stream('invoice.pdf');
```

In my view I tried to get this value using:

`{{ $test }}`

Where's my fault?

**Comment by annajeanine** [comment]
How did you manage to fix it?

**Comment by barryvdh** [comment]
PDF::loadView('invoices.invoice', ['test' =>$test]);

**Comment by annajeanine** [comment]
Thank you!
