### ISSUE TITLE
set author, set application

### ISSUE THREAD

**Issue by ghost** [barryvdh/laravel-dompdf#196]
Is there any way I can modify the application and set some value to the author field?
Here's a picture of what I mean:
![48e12a23a3 1](https://cloud.githubusercontent.com/assets/10235040/13118702/c4734926-d5a5-11e5-9f46-b2a00da5456c.png)

**Comment by julianstark999** [comment]
Author can be set by adding the author meta tag to your head

`<meta name="author" content="AUTHOR_NAME">`
