### ISSUE TITLE
Unable to Get the Canva

### ISSUE THREAD

**Issue by TheJackMachine** [barryvdh/laravel-dompdf#197]
To make a Encrypted PDF, we need to get the canvas.

The canvas is available after a render, but your render method is protected, maybe you need to change this to a public method.

With RENDER() as public, i can generate an encrypted PDF with password using $pdf->getDomPDF()->get_canvas()->get_cpdf()->setEncryption('openpass','changepass',array('copy','print'));

**Comment by mtaki14** [comment]
I've came accross the same issue while trying to encrypt a pdf. @barryvdh is there an workaround?
