### ISSUE TITLE
laravel-dompdf chinese unreadable code

### ISSUE THREAD

**Issue by 51yourdream** [barryvdh/laravel-dompdf#198]
i have set meta utf-8 bug not worker 

if i shoult move vendor/dompdf/dompdf/lib/fonts/\*  to storage/fonts/ ?

who can help me

**Comment by Harrrrry** [comment]
I have the same problem, when i generate the pdf form html which contain burmese language( நான் என் முதலாளி வீட்டில் ஜன்னல்கள் வெளிப்புறம் சுத்தம் செய்ய தேவையில்லை என்று புரிந்துகொள்ளுங்கள் . ) then in pdf its show ???????????????????????????????????????????????

**Comment by lipengyihao** [comment]
@Harrrrry you shouid install someone font to support your language.i did like that ,but dompdf did not support some tags (like <em> <i>)
if you fixed it please tell me.thank you!

**Comment by mani95lisa** [comment]
I have the same problem too, and I found the official demo is failed too:
![image](https://cloud.githubusercontent.com/assets/1968989/13519385/60a662b0-e212-11e5-8291-623edee11de9.png)

I have tried to use official demo to install font, but still can't work.

**Comment by ckwong** [comment]
I found same problem, anyone have answer

**Comment by totoleo** [comment]
i import a custom font for Chinese document. Maybe we could add a console command for import font file. And pay attention to the subsetting config. It will significantly reduce the size of document.

**Comment by githubstarit** [comment]
不支持中文

**Comment by zhuojiawei** [comment]
暂时解决不了

**Comment by josephdicdican** [comment]
Had the same issue and just want to share solution I got from searching over the net. 

At first I was confused if I have to use the existing `php load_font.php font font.ttf` flow. But I realized this is only to install the font to laravel dompdf fonts automatically. This is very much useful. But another quick solution is below:

1. First you need to download font that supports Chinese chars. 
  > You can find Chinese fonts here: https://cooltext.com/Fonts-Unicode-Chinese

2. After downloading, just put the the `.ttf` file to your font assets folder.
3. Then use the css `@font-face` to explicitly declare your font supporting the Chinese characters.

Just for example (using `simhei.ttf`). FYI, this is in my `template.blade.php` file
```html
<style type="text/css">
@font-face {
   font-family: SimHei;
   src: src: url('{{base_path().'/public/report_assets/'}}fonts/simhei.ttf') format('truetype');
}

* {
  font-family: SimHei
}
</style>

<body>
有用
...
```

Result:
![image](https://user-images.githubusercontent.com/15903512/34707850-bdd62a7c-f54a-11e7-95b3-5a9ef45d9c5f.png)

That's all!

**Comment by Maple-Ro** [comment]
Thank you very much!

**Comment by lipengyihao** [comment]
Thanks




| |
李鹏
|
|
邮箱：lpjustdoit@163.com
|

签名由 网易邮箱大师 定制

On 01/19/2018 05:41, liutsing wrote:

Thank you very much!

**Comment by jgamao** [comment]
thanks @josephdicdican, this is very useful!

**Comment by goforwork** [comment]
> Had the same issue and just want to share solution I got from searching over the net.
> 
> At first I was confused if I have to use the existing `php load_font.php font font.ttf` flow. But I realized this is only to install the font to laravel dompdf fonts automatically. This is very much useful. But another quick solution is below:
> 
> 1. First you need to download font that supports Chinese chars.
> 
> > You can find Chinese fonts here: https://cooltext.com/Fonts-Unicode-Chinese
> 
> 1. After downloading, just put the the `.ttf` file to your font assets folder.
> 2. Then use the css `@font-face` to explicitly declare your font supporting the Chinese characters.
> 
> Just for example (using `simhei.ttf`). FYI, this is in my `template.blade.php` file
> 
> ```
> <style type="text/css">
> @font-face {
>    font-family: SimHei;
>    src: url('{{base_path().'/public/report_assets/'}}fonts/simhei.ttf') format('truetype');
> }
> 
> * {
>   font-family: SimHei;
> }
> </style>
> 
> <body>
> 有用
> ...
> ```
> 
> Result:
> ![image](https://user-images.githubusercontent.com/15903512/34707850-bdd62a7c-f54a-11e7-95b3-5a9ef45d9c5f.png)
> 
> That's all!

**Comment by goforwork** [comment]
![Uploading image.png…]()
i use your method.
but it seems no use.
