### ISSUE TITLE
Use of undefined constant DOMPDF_TEMP_DIR - assumed 'DOMPDF_TEMP_DIR'

### ISSUE THREAD

**Issue by iamtekeste** [barryvdh/laravel-dompdf#20]
Use of undefined constant DOMPDF_TEMP_DIR - assumed 'DOMPDF_TEMP_DIR'

**Comment by swordf1zh** [comment]
From the DOMpdf documentation at [GitHub](https://github.com/dompdf/dompdf#install-with-composer):
> Before you can use the Composer installation of DOMPDF in your application you must disable dompdf's default auto-loader, include the Composer autoloader, and load the dompdf configuration file:
> ```php
// somewhere early in your project's loading, require the Composer autoloader
// see: http://getcomposer.org/doc/00-intro.md
require 'vendor/autoload.php';

> // disable DOMPDF's internal autoloader if you are using Composer
define('DOMPDF_ENABLE_AUTOLOAD', false);

> // include DOMPDF's default configuration
require_once '/path/to/vendor/dompdf/dompdf/dompdf_config.inc.php';
```
