### ISSUE TITLE
Class 'Barryvdh\DomPDF\ServiceProvider' not found

### ISSUE THREAD

**Issue by mmaffet** [barryvdh/laravel-dompdf#200]
FatalErrorException in ProviderRepository.php line 146:
Class 'Barryvdh\DomPDF\ServiceProvider' not found
in ProviderRepository.php line 146

**Comment by WindSaber** [comment]
Which Laravel Version are you working on?
Could you give more details in order to detect what's wrong?

**Comment by mmaffet** [comment]
Sorry, problem solved with composer update

**Comment by sathikanna** [comment]
Hi..
i am getting the same error. and using laravel 4.2

**Comment by emersonsimoes-dev** [comment]
I have this problem in laravel 6.8

**Comment by emersonsimoes-dev** [comment]
Installation failed, reverting ./composer.json to its original content.

I have this problem in laravel 6.8

**Comment by Dieu2002** [comment]
I have the same problem in laravel 8.1. How can I solve this?

**Comment by sofianev** [comment]
I have the same problem in laravel 8.1. How can I solve this?

**Comment by Rhaima96** [comment]
> same problem here with laravel 7.4, works fine in my local but received the errors once I deployed to production. ran php artisan cache:clear
> 
> config/app.php : Barryvdh\DomPDF\ServiceProvider::class, 'PDF' => Barryvdh\DomPDF\Facade::class,

same problem sir
