### ISSUE TITLE
Error 500 on generating a PDF

### ISSUE THREAD

**Issue by Slader10** [barryvdh/laravel-dompdf#204]
Help please 

im using dompdf for while and all was working fine, but when I try to create a PDF with a lot of data just return 500 error.

did someone have the same issue or someone already fix it ?

**Comment by luisalvarez** [comment]
i am in the same issue i send it a lot of data 6000 records and it chrashed

**Comment by leikxile** [comment]
I got 400 records and it crashed.

**Comment by tweeklabs-isaac** [comment]
i have the same issue, any idea how to fix this? The most number of pages I get is only up to 10 and I need to generate more than that.

**Comment by kfulk14** [comment]
Same I have 25 records with the page landscape and I get a 500 error when trying to view the pdf.

**Comment by tweeklabs-isaac** [comment]
I ended up generating 1 file at a time and used another package to merge all the files to a single pdf, not the best solution but works for me

**Comment by wcadena** [comment]
Yo tengo el mismo problema en
I have the same problem in
$pdf->stream

**Comment by elppe1** [comment]
Laravel kill the procces that aproximated at limit execution time of server
