### ISSUE TITLE
please update to dompdf 0.7.x 

### ISSUE THREAD

**Issue by vesper8** [barryvdh/laravel-dompdf#205]
pretty please with a cherry on top?

**Comment by GrahamCampbell** [comment]
This is already done...

**Comment by GrahamCampbell** [comment]
Instead 0.7.x of this package to get it.

**Comment by vesper8** [comment]
Oh yes I see.. I tried to pull from dev-master of this package and then it said it couldn't find dompdf/dompdf 0.7.x

So then I specifically added "dompdf/dompdf": "0.7.x@beta" with dev-master of this package and then this is working... BUT.. now it's causing a conflict with "yajra/laravel-datatables-oracle" which has a hard dependency on 0.6.1 of dompdf :( And I'm using that a lot in my application... so can't use 0.7 until that's updated :( sigh

There's no way to make it ignore that dependency eh? It's barely using dompdf (laravel-datatables-oracle) and I could do without it entirely.. plus it probably doesn't even break with dompdf 0.7

but thanks for the super quick response!
