### ISSUE TITLE
How to print the '₹' in pdf generation

### ISSUE THREAD

**Issue by pavankumarkatakam** [barryvdh/laravel-dompdf#207]
Currently im using the package for genertaing the PDF for Invoice, so I want to print the '₹' symbol but when directly copy paste the ₹ symbol in blade it is printing as `?`.  So how to print special characters in pdf.

**Comment by pavankumarkatakam** [comment]
is anybody there?

**Comment by barryvdh** [comment]
You probably need a different font. But please ask on the dompdf repo, this is just a wrapper.

**Comment by himanshutecstub** [comment]
See http://stackoverflow.com/questions/19830914/inr-currency-symbol-on-pdf-using-dompdf

**Comment by parthvaghasiya119** [comment]
* { font-family: DejaVu Sans, sans-serif; }
