### ISSUE TITLE
Bootstrap 3 Support

### ISSUE THREAD

**Issue by iamtekeste** [barryvdh/laravel-dompdf#21]
Why is not reading my css...it generates the pdf but it is all mixed up. It is not reading my css.

**Comment by giovanny2009** [comment]
HE notado que todos lo pdf tiene problema con bootstrap no he encontrado ninguna libreria que no tenga porble @media de bootstrap toca pasar todo el css pero no es lo mismo mane defectos :/ si alguien tiene una libreria enviar  link giovanny_1416@hotmail.com
