### ISSUE TITLE
Transparent image background not working.

### ISSUE THREAD

**Issue by pavankumarkatakam** [barryvdh/laravel-dompdf#211]
Im using this pack to generate an invoice with an image logo as watermark of that pdf, but im getting the black color for transparent area of the image.
The css & image im using is 

```
 .outer_proxy {
        width: 100%;
        height: 100%;
        opacity: 0.15;
        top: 0;
        left: 0;
        bottom: 0;
        right: 0;
        position: fixed;
        background: transparent url("https://www.elivio.com/assets/elivio.png") no-repeat fixed center center;
    } 
```

Bu the pdf generated is 
[1459783923.78034300Invoice.pdf](https://github.com/barryvdh/laravel-dompdf/files/202740/1459783923.78034300Invoice.pdf)

If you check that pdf , the watermark is surrounded with black area actually it is transparent.

**Comment by conradobarbera** [comment]
i have de the same problem. The black for transparency

![image](https://user-images.githubusercontent.com/35975676/89186603-6b375d80-d572-11ea-9533-e93185e27f4f.png)

**Comment by AbrahamBrookes** [comment]
Same issue - development env:
![image](https://user-images.githubusercontent.com/8340776/91814154-0eb18600-ec77-11ea-8c80-24ab456fcbeb.png)

live env:
![image](https://user-images.githubusercontent.com/8340776/91814185-196c1b00-ec77-11ea-8399-862e621574a2.png)

Same code, same config, same composer stack, same PHP versions, different env (development vs production) and may be some different server-level configurations. Any hints as to where to start looking?

**Comment by AbrahamBrookes** [comment]
Solved - this is caused by ImageMagick. I disabled the extension on my hostings cpanel account (under "Select PHP version"):
![image](https://user-images.githubusercontent.com/8340776/91817663-b11e3900-ec78-11ea-94b3-2449f44c7d15.png)
