### ISSUE TITLE
can I stream an already created pdf without regenerating it first?

### ISSUE THREAD

**Issue by vesper8** [barryvdh/laravel-dompdf#212]
I tried using PDF::loadFile on an existing pdf so I could then stream it but I keep getting permission denied. I did some searching around and found an issue where you said you cannot use loadFile on an existing pdf, only on an html file.

I know I can create a download with my existing pdf with Response::download but can I use the stream() functionality of dompdf on an existing pdf file?

This is probably easy but I'm just not finding how and google's not being helpful.

If you could let me know what I'm doing wrong that would be great. Thanks!

**Comment by vesper8** [comment]
Well.. I did find a way to do it and this is it. You can close this issue unless you wanted to include a way to do it with the built-in functionalities of dompdf. Though I suppose dompdf is only meant to generate pdfs, not load existing ones

```
            $headers = [
                'Content-Type' => 'application/pdf',
                'Content-Disposition' => 'inline; ' . $fileName,
            ];

            return Response::make(File::get($filePath . $fileName), 200, $headers);
```

**Comment by admont28** [comment]
I found this way:

`return response()->file($pathToFile);`
`return response()->file($pathToFile, $headers)`

[Source](https://stackoverflow.com/questions/25938294/laravel-display-a-pdf-file-in-storage-without-forcing-download)
