### ISSUE TITLE
Nginx & PHP-FPM issue (headers not correctly set, plain pdf output)

### ISSUE THREAD

**Issue by matrad** [barryvdh/laravel-dompdf#213]
On nginx and php-fpm there is an issue when overwriting existing php Headers.
When we output the PDF in the controller this way:

`$dompdf->stream('deliverynote-'.$id, ['Attachment'=> 0] );`

We'll get a text/html header in nginx from laravel (because the headers cannot be overwritten, may be also a current php-fpm issue.

So the wrapper should use the laravel-default-response methods.

I did it in the controller this way (but it should be done inside the wrapper):

```
        $content = $dompdf->output(['compress' => 0]);
        $filename = 'pdf-'.$id.'.pdf';
        return (new Response($content, 200))
                  ->header('Content-Type', 'application/pdf')
                  ->header('Cache-Control', 'private')
                  ->header('Pragma', 'no-cache')
                  ->header('Expires', '0')
                  ->header('Content-Length',strlen($content) )
                  ->header('Content-Disposition', 'inline; filename='.rawurlencode($filename).'; filename*=UTF-8\'\''.rawurlencode($filename).'\'');
```

My configuration:
PHP Version 5.6.17-0+deb8u1
FPM/FastCGI

**Comment by mickeychu** [comment]
I have the same problem when streaming the PDF from larvel :
**Error: Invalid XRef stream header**
Here's my code in the controller: 
``$order = Order::with('customer')->find($id);
        $message = nl2br($order->cover_letter);
        $company = $order->customer->company;
        $contact = $order->customer->first_name." ".$order->customer->last_name;
        $date = date('Y-m-d');
        $view =  \View::make('order', compact('date', 'order', 'company', 'contact', 'message'))->render();
        $pdf = \App::make('dompdf.wrapper');
        $pdf->loadHTML($view);
        /*unlink("pdf/order.pdf");
        file_put_contents("pdf/order.pdf", $pdf->output());*/

        return $pdf->download('order.pdf');``

How can I fixed this?
