### ISSUE TITLE
How to pass multiple arrays/objects into DOMPDF?

### ISSUE THREAD

**Issue by kmsch** [barryvdh/laravel-dompdf#215]
Currently, when I pass arrays/objects into a view I do it like this: 

``` php
return view('factuur.show')->with(compact('factuur', 'factuurregels', 'totaalprijs'));
```

However, the readme.md says I should use DOMPDF like this: 

``` php
$pdf = PDF::loadView('pdf.invoice', $data);
```

How do I pass my three objects into this view? Should I create a multidimensional array and call it $data? 

Kind regards,
Koen

**Comment by mrdaano** [comment]
I have the same question.

**Comment by tomhoad** [comment]
$pdf = PDF::loadView('pdf.invoice', compact('factuur', 'factuurregels', 'totaalprijs'));

**Comment by mrdaano** [comment]
Thanks it works

**Comment by joao-vieira** [comment]
Thanks @tomhoad , this worked for me!
