### ISSUE TITLE
I have problem with Khmer Unicode(កម្ពុជា or Cambodia)

### ISSUE THREAD

**Issue by samnangdbd** [barryvdh/laravel-dompdf#216]
Dear Sir,

  PLease help me to display Khmer Unicode in dompdf of laravel 5

**Comment by jacob-arlington** [comment]
you can use font face like this

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link href="https://fonts.googleapis.com/css?family=Khmer&display=swap" rel="stylesheet">
<style type="text/css">
	.khmer {
		font-family: 'Khmer', cursive;
	}

</style>
</head>
<body>

<p>Please complete all the questions below</p>
<p class="khmer">{Please complete all the questions below:value}</p>

<p>Personal Details</p>
<p class="khmer">{Personal Details:value}</p>

<p>Personal Full Name</p>
<p class="khmer">{Personal Full Name:caption}</p>
<p class="khmer">{Personal Full Name:value}</p>

<p>National ID Passport Number</p>
<p class="khmer">{National ID Passport Number:caption}</p>
<p class="khmer">{National ID Passport Number:value}</p>


</body>
</html>
