### ISSUE TITLE
ErrorException in font_metrics.cls.php line 366:

### ISSUE THREAD

**Issue by Kamparia** [barryvdh/laravel-dompdf#218]
ErrorException in font_metrics.cls.php line 366:
unlink(C:\Users\ROI_DI~1\AppData\Local\Temp/6ed5261475a72ba92983868bca0014c4): Permission denied

Someone please help with this.

**Comment by smartbar** [comment]
Do you know the solution now? I have the same problem :/

**Comment by fearrr** [comment]
I also get this error. I tried to change the config
// "DOMPDF TEMP_DIR" => sys_get_temp_dir (),
to
"DOMPDF_TEMP_DIR" => storage_path ( 'temp'),
But that does not work

**Comment by fearrr** [comment]
Error disappears only when the line commented out
unlink($local_temp_file);

**Comment by achillesp** [comment]
The solution proposed here: [https://github.com/barryvdh/laravel-dompdf/issues/186] seems to be working.
