### ISSUE TITLE
Russian language problem

### ISSUE THREAD

**Issue by AstafievAndrey** [barryvdh/laravel-dompdf#219]
Instead, Russian characters signs '?'.

`public function invoice() 
    {
        $data = $this->getData();
        $date = date('Y-m-d');
        $invoice = "2222";
        $view =  \View::make('pdf.invoice', compact('data', 'date', 'invoice'))->render();
        $html = mb_convert_encoding($view, 'HTML-ENTITIES', "UTF-8");
        $pdf = \App::make('dompdf.wrapper');
        $pdf->loadHTML($view);
        return $pdf->stream('invoice');
    }`

`<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Пример</title>
  <body>
        <h2>Калорийность питания</h2>
  </body>
</html>`

**Comment by ZAZmaster** [comment]
Same problem... @AstafievAndrey have you fixed this?

**Comment by AstafievAndrey** [comment]
Unfortunately no

**Comment by vata** [comment]
open `/config/dompdf.php` and set `DOMPDF_DEFAULT_FONT` to one of the this:
`dejavu sans`, `dejavu sans condensed`, `dejavu sans mono`, `dejavu serif`, `dejavu serif condensed`.
Or add your own:
Copy your fonts in your dompdf fonts folder `/vendor/dompdf/dompdf/lib/fonts/`
Edit `/vendor/dompdf/dompdf/lib/fonts/dompdf_font_family_cache.dist.php`

`
'arial' => array (
    'normal' => DOMPDF_FONT_DIR . 'Arial',
    'bold' => DOMPDF_FONT_DIR . 'Arial',
    'italic' => DOMPDF_FONT_DIR . 'Arial',
    'bold_italic' => DOMPDF_FONT_DIR . 'Arial'
)
`

**Comment by schel4ok** [comment]
not working for me.
I tried all these methods
1) `"DOMPDF_DEFAULT_FONT" => "dejavu sans"`  but anyway instead, Russian characters signs '?'.
2) And I tried to add cyrillic font using load_font.php, but I could not finish this process due to errors
https://github.com/dompdf/utils/issues/1

**Comment by sbahmet** [comment]
`dejavu sans` worked well. Thanks

**Comment by rorc** [comment]
`dejavu serif` beautiful font, works correct without meta tag 😄

**Comment by anton4ik8374** [comment]
> open `/config/dompdf.php` and set `DOMPDF_DEFAULT_FONT` to one of the this:
> `dejavu sans`, `dejavu sans condensed`, `dejavu sans mono`, `dejavu serif`, `dejavu serif condensed`.
> Or add your own:
> Copy your fonts in your dompdf fonts folder `/vendor/dompdf/dompdf/lib/fonts/`
> Edit `/vendor/dompdf/dompdf/lib/fonts/dompdf_font_family_cache.dist.php`
> 
> `'arial' => array ( 'normal' => DOMPDF_FONT_DIR . 'Arial', 'bold' => DOMPDF_FONT_DIR . 'Arial', 'italic' => DOMPDF_FONT_DIR . 'Arial', 'bold_italic' => DOMPDF_FONT_DIR . 'Arial' )`
> 
> more about this read here: http://stackoverflow.com/questions/990181/dompdf-problem-with-cyrillic-characters

Thanks, your advice helped.

**Comment by it-sev-shmatok** [comment]
Проблема отображения `???` вместо кириллических символов решена при следующих настройках.

Исходные данные:
- Laravel 6.15.0
- barryvdh/laravel-dompdf версии 0.8.5

В наследуемом (родительском) blade-шаблоне следующая разметка:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Объекты</title>
  <style>
    @font-face {
      font-family: "DejaVu Sans";
      font-style: normal;
      font-weight: 400;
      src: url("/fonts/dejavu-sans/DejaVuSans.ttf");
      /* IE9 Compat Modes */
      src: 
        local("DejaVu Sans"), 
        local("DejaVu Sans"), 
        url("/fonts/dejavu-sans/DejaVuSans.ttf") format("truetype");
    }
    body { 
      font-family: "DejaVu Sans";
      font-size: 12px;
    }
  </style>
</head>
  <body>
      @yield('content')
  </body>
</html>
```
Шрифт расположен в каталоге `/public/fonts/dejavu-sans/...`

**Comment by Sasha1Revnuk** [comment]
> Проблема отображения `???` вместо кириллических символов решена при следующих настройках.
> 
> Исходные данные:
> 
> * Laravel 6.15.0
> * barryvdh/laravel-dompdf версии 0.8.5
> 
> В наследуемом (родительском) blade-шаблоне следующая разметка:
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
> <head>
>   <meta charset="UTF-8">
>   <meta name="viewport" content="width=device-width, initial-scale=1.0">
>   <title>Объекты</title>
>   <style>
>     @font-face {
>       font-family: "DejaVu Sans";
>       font-style: normal;
>       font-weight: 400;
>       src: url("/fonts/dejavu-sans/DejaVuSans.ttf");
>       /* IE9 Compat Modes */
>       src: 
>         local("DejaVu Sans"), 
>         local("DejaVu Sans"), 
>         url("/fonts/dejavu-sans/DejaVuSans.ttf") format("truetype");
>     }
>     body { 
>       font-family: "DejaVu Sans";
>       font-size: 12px;
>     }
>   </style>
> </head>
>   <body>
>       @yield('content')
>   </body>
> </html>
> ```
> 
> Шрифт расположен в каталоге `/public/fonts/dejavu-sans/...`

Лучший!

**Comment by ghulamakbar14** [comment]
This issue is still not working for me. I tried font-family config variable suggested above but still facing same issue.

**Comment by theqewk** [comment]
https://github.com/barryvdh/laravel-dompdf/issues/875#issuecomment-1861454665
