### ISSUE TITLE
Loading an image via an API call

### ISSUE THREAD

**Issue by stueynet** [barryvdh/laravel-dompdf#221]
Our app loads all secure images via api calls. Example:

   api/uploads/12345

This returns the image using:

```
return Image::make($path)->response();
```

So our normal image tags look like

```
<img src="/api/uploads/1234">
```

This works great in the application. However when we try to embed same image into a pdf, we get the not found error. Can you think of a way to get this to work with the above setup?

**Comment by mangrovestudios** [comment]
Same issue here: [how-to-load-image-from-storage-folder](http://stackoverflow.com/questions/37079529/laravel-dompdf-how-to-load-image-from-storage-folder)

**Comment by stueynet** [comment]
@mangrovestudios yup but no response as of yet.

**Comment by mangrovestudios** [comment]
#165

**Comment by barryvdh** [comment]
You aren't using the php cli server, right?

**Comment by stueynet** [comment]
Hey @barryvdh. Nope I am using vagrant and homestead

**Comment by mangrovestudios** [comment]
@barryvdh that's correct

**Comment by barryvdh** [comment]
And using the full url? Or just absolute path? Can you use the `asset()` helper to generate the url?

**Comment by mangrovestudios** [comment]
@barryvdh For me using relative or absolute paths result in the same error

**Comment by yabdab** [comment]
One thing I just discovered is that the **img** needs to be wrapped in another DOM object, like **<div>**

When I wrapped my <img> tag with a <div>, the image was then rendered in the PDF.

Also make sure your path is correct too.

Here is exact code I used.

`<div>
<img src="{{ public_path() }}/assets/img/logo.png" style="height: 100px;">
</div>`

**Comment by sebastienrichoz** [comment]
Don't know if it is still actual but in my opinion, your `src` attribute isn't readable for dompdf. The [return value](http://image.intervention.io/api/response) for response() method is 

> Encoded image data after raw HTTP header is sent. If you are in a Laravel framework environment the method will return a Illuminate\Http\Response with the corresponding header fields already set.

Try to set your `src` attribute as a base64 encoded image : 
`<img src="data:image/png;base64,'. $b64 .'" >`, 
where `$b64 = base64_encode($yourImageContent);`
You just need to retrieve the image content from the Illuminate\Http\Response. I would use this same principle for stored image (retrieve the image and base64 encode it).

Be also sure that the config variable `"DOMPDF_TEMP_DIR" = storage_path('app/public/temp')` or any writable temp folder visible by your server.
