### ISSUE TITLE
Exporting large data

### ISSUE THREAD

**Issue by kikz4life** [barryvdh/laravel-dompdf#222]
Hi,

First of all I want to thank you for this wonderful library. 

I have a problem in exporting large data (20,000+ records). It gave me an Maximum execution time of 60 seconds exceeded. I tried increasing my max_execution_limit to 300 and even set it to 0. But same result, it all points to /frame_tree.cls error. Do you have any idea how to get over this?

Regards

**Comment by rudychevez** [comment]
I have the same problem, the connection is reset with large files, did you fix it?

**Comment by kikz4life** [comment]
I haven't found a fix for this yet.

**Comment by KarmaGraphic** [comment]
Same problem here. Any good new?

**Comment by poonamBordiya** [comment]
I have the same problem,in printing large data with dompdf.

**Comment by barryvdh** [comment]
Try https://github.com/barryvdh/laravel-snappy for larger HTML

**Comment by Shahin1993** [comment]
barryvdh/laravel-snappy   liver server is not working 

config/snappy.php

<?php

return [
    'pdf' => array(
        'enabled' => true,
       'binary'  => 'vendor\wemersonjanuario\wkhtmltopdf-windows\bin\64bit\wkhtmltopdf',
        'timeout' => false,
        'options' => array(),
        'env' => array(),
    ),
    'image' => array(
        'enabled' => true,
        'binary' => 'vendor\wemersonjanuario\wkhtmltopdf-windows\bin\64bit\wkhtmltoimage',
        'timeout' => false,
        'options' => array(),
        'env' => array(),
    ),
];
