### ISSUE TITLE
file_put_contents error

### ISSUE THREAD

**Issue by mrdaano** [barryvdh/laravel-dompdf#223]
Hello,

When I generate a new PDF with the following code:
`return $pdf->setPaper(array(0,0,452,296))->stream();`

I get the error:

> file_put_contents(): Filename cannot be empty

The file where the error is located: /vendor/dompdf/dompdf/include/image_cache.cls.php
What can I do to fix this error?

Thanks,
Daan

**Comment by mrdaano** [comment]
Fixed it, it was a error in my XAMPP for mac.

**Comment by trangchuvn** [comment]
can you tell me how to fix please?

**Comment by anavgire4** [comment]
Same Error i got on mac machine. Please let me know the solution for this.

**Comment by mrdaano** [comment]
I started working on a vagrant machine and changed the php version to 7.x.
That was the solution for me.

**Comment by sebastienrichoz** [comment]
Same error happened to me with XAMPP on Mac.

I solved it by setting `DOMPDF_TEMP_DIR = storage_path('app/public/temp')` (in dompdf.php) and gave full permission to this `temp` folder.

The thing is all about this temporary folder which must be a known writable folder for your server where your stream can be written.

For XAMPP on MAC, you could also set it as 
`DOMPDF_TEMP_DIR = '/Applications/XAMPP/xamppfiles/temp'`

**Comment by Oyelamin** [comment]
@sebastienrichoz That really works..
Thanks man!
