### ISSUE TITLE
PDF rendering problem

### ISSUE THREAD

**Issue by Mohsin360** [barryvdh/laravel-dompdf#225]
Hello Sir,
     I am using barryvdh/laravel-dompdf it is working absolutely fine but the issue occurs when I try to embed some image into it actually I am trying to add image which are stored in database and i want to show that image into the pdf view. Currently I am using
<img src=" uploads/ " {{ $admission->directory }} />
the $admission->directory contains the name of the image file with extension and the original image is stored in uploads directory please help me get through ir

**Comment by tiagobrilhante** [comment]
same issue here.

**Comment by barryvdh** [comment]
What if you use the full url (including http://..)
