### ISSUE TITLE
UTF-8 issue

### ISSUE THREAD

**Issue by iwbace777** [barryvdh/laravel-dompdf#226]
I am exporting as Polish. But Polish letters are not showing on the PDF.
Is there any solution to solve this?

I am using Laravel 4.2. So I use 0.4 version.
I added `<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>` on the header.
But not working.

**Comment by pooranravabe** [comment]
same with me

**Comment by ksdev-pl** [comment]
Hi. Try:
```css
body {
    font-family: DejaVu Sans;
}
```

**Comment by im424** [comment]
You need to install a font that support your language letters into dompdf first.

**Comment by melihovv** [comment]
@ksdev-pl Thanks for solution. Where can I find a list of all fonts, which support utf-8, like DejaVu Sans?

**Comment by barryvdh** [comment]
See https://github.com/dompdf/dompdf#about-fonts--character-encoding

> #### About Fonts & Character Encoding
> PDF documents internally support the following fonts: Helvetica, Times-Roman, Courier, Zapf-Dingbats, & Symbol. These fonts only support Windows ANSI encoding. In order for a PDF to display characters that are not available in Windows ANSI you must supply an external font. Dompdf will embed any referenced font in the PDF so long as it has been pre-loaded or is accessible to dompdf and reference in CSS @font-face rules. See the font overview for more information on how to use fonts.

> The DejaVu TrueType fonts have been pre-installed to give dompdf decent Unicode character coverage by default. To use the DejaVu fonts reference the font in your stylesheet, e.g. body { font-family: DejaVu Sans; } (for DejaVu Sans). The following DejaVu 2.34 fonts are available: DejaVu Sans, DejaVu Serif, and DejaVu Sans Mono.

**Comment by IftakharBappy** [comment]
Its not working for my bangla fonts :/ what can I do ? Please give me in details . Thanks

**Comment by huyit218** [comment]
please help me to resolve my problem, i type my vietnamese but display ? ? character, i'm using dompdf, so how can i do to display m data. thanks all

**Comment by EbtehalHasan** [comment]
please

**Comment by sagirr** [comment]
this is solved my problem thanks

 body {
    font-family: DejaVu Sans;
}

**Comment by mimehedi166** [comment]
hello guys,
I think i found the solution of this problem. i've tried some library (dompdf, TCPDF,FPDF,mPDF) which support PHP but not all of them are work properly. I didn't find any unicode support with dompdf, 
tcpdf worked but the fonts are broken. so i tried mPDF and it gave me my expected output. 
i'm using this library to my laravel project. To using mPDF with laravel project you need to follow the documentation of laravel-mpdf.
 link: https://github.com/niklasravnsborg/laravel-pdf

after installed the library successfully what you have to do this following steps for other language or bangla support.

1. first download the fonts for your supported language (i.e: for bangla i've downloaded solaimanLipi.ttf) and keep it to your fonts folder inside the resources folder. if there is no fonts folder just create it.
2.In config/pdf.php file add these codes inside of return array


```
'font_path' => base_path('resources/fonts/'),
	'font_data' => [
		'examplefont' => [
			'R'  => 'ExampleFont-Regular.ttf',    // regular font
			'B'  => 'ExampleFont-Bold.ttf',       // optional: bold font
			'I'  => 'ExampleFont-Italic.ttf',     // optional: italic font
			'BI' => 'ExampleFont-Bold-Italic.ttf' // optional: bold-italic font
			'useOTL' => 0xFF,    
			'useKashida' => 75, 
		]
		// ...add as many as you want.
	]
```


examplefont is your attribute name whatever you want to use. but inside this attribute paste your font name.

Example:
```
'bangla' => [
			'R'  => 'SolaimanLipi.ttf',    // regular font
			'B'  => 'SolaimanLipi.ttf',       // optional: bold font
			'I'  => 'SolaimanLipi.ttf',     // optional: italic font
			'BI' => 'SolaimanLipi.ttf' // optional: bold-italic font
			'useOTL' => 0xFF,   
			'useKashida' => 75, 
		]
```


now in your view file use this CSS Scripts:

```
<style>
body {
	font-family: 'examplefont', sans-serif;
}
</style>
```


In Your Controller:

```
function generate_pdf() {
	$data = [
		'foo' => 'bar'
	];
	$pdf = PDF::loadView('pdf.document', $data);
	return $pdf->stream('document.pdf');
}

```

Hints: pdf.document is your view file name.
Use PDF at the top in your namespace

If you follow this step correctly ,it will work 100%.
**This is my output**
![sample](https://user-images.githubusercontent.com/7956469/38672220-5a533d82-3e6f-11e8-85ba-3bbcf449b07b.PNG)


N.B: This is my first post. if i did any mistakes to write review in correct format please consider it take it lightly. 
Thank You, 
Mahabubul Islam Mehedi

**Comment by m7ammad7assan** [comment]
> 'font_data' => [ 'examplefont' => [ 'R' => 'ExampleFont-Regular.ttf', // regular font 'B' => 'ExampleFont-Bold.ttf', // optional: bold font 'I' => 'ExampleFont-Italic.ttf', // optional: italic font 'BI' => 'ExampleFont-Bold-Italic.ttf' // optional: bold-italic font 'useOTL' => 0xFF, 'useKashida' => 75, ] // ...add as many as you want. ]

Not working !

**Comment by mimehedi166** [comment]
Show the path of your stored Arabic fonts in base path section . it will
work then.

**Comment by redo99** [comment]
Hi,
i try to call the following method
`function generateSEPA() {
        $pdf = PDF::loadHtml("<h1>My page title</h1>");
        return response()->json($pdf->download()->content());
  }`
Unfortunately i'm facing the following exception "Malformed UTF-8 characters, possibly incorrectly encoded"

plz, is there a way to send the pdf with json ?

**Comment by abutaleb23** [comment]
hi @mimehedi166 It is working fine for only Bangla. Since I've Bangla and English mixed. I'm not getting the English when Bangla is perfect in the same report

**Comment by reflexit2020** [comment]
not supported something like that  

![bangla](https://user-images.githubusercontent.com/62537005/84558968-cf187500-aceb-11ea-908b-2b14d789a281.JPG)

**Comment by hridoy100** [comment]
Made it work with bangla. You can use any font by this process.

1.  by default it uses your **storage>fonts** folder to store fonts. For bangla I'll use SolaimanLipi.ttf font. Download the fonts from this URL [solaimanlipi](https://www.wfonts.com/font/solaimanlipi) and save them into your storage>fonts folder.
2. unzip the file and the fonts will have name like this **"SolaimanLipi_29-05-06.ttf"** ..etc. Rename it to "SolaimanLipi.ttf"
3. Go to the file named **storage/fonts/dompdf_font_family_cache.php**
If you don't have this file make sure you've ran this command 
**php artisan vendor:publish --provider="Barryvdh\DomPDF\ServiceProvider"**
4. Now inside the file **storage/fonts/dompdf_font_family_cache.php** add the following lines:

Example: 

    'bangla' => array(
        'R' => $fontDir . '/SolaimanLipi',    // regular font
        'B' => $fontDir . '/SolaimanLipi',       // optional: bold font
        'I' => $fontDir . '/SolaimanLipi',     // optional: italic font
        'BI' => $fontDir . '/SolaimanLipi', // optional: bold-italic font
        'useOTL' => 0xFF,
        'useKashida' => 75,
    )

You have to specify this font family into your HTML or body tag like this:

    body {
        font-family: Arial, sans-serif, 'bangla';
    }

You can also use **'kalpurush'** and other bangla fonts this way. By specifying more families in the font-family group you can print multiple languages into your pdf.

**Comment by reflexit2020** [comment]
Who are you ???
