### ISSUE TITLE
Flex rendered invisible

### ISSUE THREAD

**Issue by code-mc** [barryvdh/laravel-dompdf#227]
Using `display: flex;` on an element renders it invisible inside the generated pdf.

**Comment by elarion** [comment]
Hi, I had the same problem using display flex or float, You should use Table tr td, annoying but it does the job

**Comment by wojcikm** [comment]
Same there.

**Comment by mshaikh-navitas** [comment]
same issue

**Comment by Angel-Ponce** [comment]
Same issue

**Comment by ayyobro** [comment]
👍 still seeing same issue

**Comment by abdelmoula17** [comment]
there is any alternative solution ?

**Comment by fartoot** [comment]
😕

**Comment by Komleviv** [comment]
Alternatively, use `display: inline-block` with a specified width for each block.

**Comment by agricreation** [comment]
Same issue here.

**Comment by GANONTHA** [comment]
use <table> element. it does the job.
