### ISSUE TITLE
[0.7] No way to set paper and orientation

### ISSUE THREAD

**Issue by bioteck** [barryvdh/laravel-dompdf#228]
In v0.6, the `setPaper()` method was setting `$paper` and `$orientation` attributes, and these were applied in the `render()` method with this call:

```
$this->dompdf->setPaper($this->paper, $this->orientation);
```

In v0.7, the `setPaper()` method directly calls `$this->dompdf->setPaper()` instead of setting `$this->paper` and `$this->orientation`:

```
public function setPaper($paper, $orientation = 'portrait'){
    $this->dompdf->setPaper($paper, $orientation);
    return $this;
}
```

But the `render()` method still calls `$this->dompdf->setPaper($this->paper, $this->orientation)`

**Comment by barryvdh** [comment]
Can you submit a PR?

**Comment by bioteck** [comment]
Ok, I'll do it when I get some free time.

**Comment by bioteck** [comment]
It's resolved. Thanks to relmar.
