### ISSUE TITLE
Can only install one of: phenx/php-font-lib[...

### ISSUE THREAD

**Issue by beilsma** [barryvdh/laravel-dompdf#23]
Composer returns the following error upon installation/update:

```
- barryvdh/laravel-dompdf dev-master requires phenx/php-font-lib 0.2.* -> satisfiable by phenx/php-font-lib[0.2, 0.2.1].
- Can only install one of: phenx/php-font-lib[dev-master, 0.2].
- Can only install one of: phenx/php-font-lib[dev-master, 0.2.1].
- dompdf/dompdf dev-master requires phenx/php-font-lib dev-master -> satisfiable by phenx/php-font-lib[dev-master].
- barryvdh/laravel-dompdf dev-master requires dompdf/dompdf dev-master -> satisfiable by dompdf/dompdf[dev-master].
- Installation request for barryvdh/laravel-dompdf dev-master -> satisfiable by barryvdh/laravel-dompdf[dev-master].
```

**Comment by pierrocknroll** [comment]
Hi,
The problem comes back when updating from 0.7.0 to 0.8.0.

    - Can only install one of: phenx/php-svg-lib[v0.2, 0.1].
    - Can only install one of: phenx/php-svg-lib[v0.2, 0.1].
    - Can only install one of: phenx/php-svg-lib[v0.2, 0.1].
    - dompdf/dompdf v0.8.0 requires phenx/php-svg-lib 0.2.* -> satisfiable by phenx/php-svg-lib[v0.2].
    - Installation request for dompdf/dompdf v0.8.0 -> satisfiable by dompdf/dompdf[v0.8.0].
    - Installation request for phenx/php-svg-lib (locked at 0.1) -> satisfiable by phenx/php-svg-lib[0.1].

Thanks
