### ISSUE TITLE
Access setHttpContext() method

### ISSUE THREAD

**Issue by sasha13** [barryvdh/laravel-dompdf#230]
Is there a way to access dompdf's 'setHttpContext' method?

**Comment by barryvdh** [comment]
`$pdf->getDomPDF()->setHttpContext($context)`?

**Comment by sasha13** [comment]
Apologies.. I cannot quite remember what was my issue with this method.. but I remember solving my original problem (no images showing in the pdf) in the meantime.. 

Feel free to close the issue.
