### ISSUE TITLE
ReflectionException in Container.php line 734: Class dompdf does not exist on Laravel 5.2

### ISSUE THREAD

**Issue by Krisnasw** [barryvdh/laravel-dompdf#232]
My Composer.json

"require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2._",
        "uxweb/sweet-alert": "~1.1",
        "laravelcollective/html": "5.2._",
        "barryvdh/laravel-debugbar": "^2.2",
        "barryvdh/laravel-dompdf": "0.6.*",
        "gloudemans/shoppingcart": "dev-master"
    },

What's wrong ?

**Comment by gsc89** [comment]
Also got this :(

**Comment by GregKeaney** [comment]
Ugh.  I have tried all of the above but still get a reflection error.

ReflectionException in Container.php line 741:
Class dompdf does not exist

Is there anyway to further debug the issue?

Thanks!
