### ISSUE TITLE
How to set PDF to print with no scaling ?

### ISSUE THREAD

**Issue by nikunjit101** [barryvdh/laravel-dompdf#236]
When I print out the PDF from Adobe Reader i have to set the scaling property. Is there any option to set scaling , so i do not have to set that scaling at the time of printing ?

**Comment by ShaileshLadumoR** [comment]
I have a similar problem. have any option for configuring print settings as a default?

**Comment by Dharmesh1311** [comment]
I print out the PDF from HTML page but i want option with no scaling at printing time
