### ISSUE TITLE
merge two pdf

### ISSUE THREAD

**Issue by ripu123** [barryvdh/laravel-dompdf#238]
i am using barryvdh/laravel-dompdf library to generate pdf..but my issue is that in my application i have to upload pdf file...and library is creating a pdf file also ...and how i merge or join these two pdf

plz suggest ..its urgent

**Comment by arasmit2453** [comment]
Check this library: https://packagist.org/packages/iio/libmergepdf

**Comment by rohantapiyawala** [comment]
@ripu123  did you find a solution for that? Please do let me know, if so.

Even Im trying to create something similar but haven't found a working solution yet. Thinking about writing my own custom solution using TCPDF, since thats what all these libraries are using. 

Thanks in advance.

**Comment by ammarax** [comment]
use this guide to install a merger
https://itsolutionstuff.com/post/laravel-merge-multiple-pdf-files-exampleexample.html

here the example code

`

use LynX39\LaraPdfMerger\Facades\PdfMerger;
use Illuminate\Support\Facades\Storage;

public function export() {
$document = 'example'; //blade file
$params = ['obj' => $obj];
$pdf = PDF::loadView($document, $params)->setPaper('a4', 'portrait');
$dom_pdf = $pdf->getDomPDF();
$canvas = $dom_pdf->get_canvas();
$this->pageNumber($canvas, $lang);

$path = 'newFileName.pdf';
Storage::disk('local')->put($path, $pdf->output()) ;
$pdfmerged = new \LynX39\LaraPdfMerger\PdfManage;

$pdfmerged->addPDF(Storage::disk('local')->path($path), 'all');
$pdfmerged->addPDF(Storage::disk('local')->path($path), 'all');
$pdfmerged->merge();
 
return $pdfmerged->stream(); //return $pdfmerged->download();
}`

**Comment by vicenterivero2021** [comment]
a

**Comment by Maninder33** [comment]
if anyone still looking for how to merge pdf to your exported pdf. use this library

(https://packagist.org/packages/iio/libmergepdf
)

`public function downloadPdf(Request $request, int $article_id)
    {
        $article = Article::findOrFail($article_id);

        $genPdf = Pdf::loadView('articles.pdf', compact('article'))->output();

        $merger = new Merger();
        $merger->addRaw($genPdf);

        foreach ($article->files as $file) {
            if (pathinfo($file->file_path, PATHINFO_EXTENSION) === 'pdf') {
                $pdfPath = storage_path('app/article-files/' . $file->file_path);
                $merger->addFile($pdfPath);
            }
        }

        $mergedPdf = $merger->merge();

        return response($mergedPdf, 200, [
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => 'attachment; filename="Articolo_' . $article->code . '.pdf"',
        ]);
    }`
    
    this is how I used this easy to use.

**Comment by Ahmed-Aboud** [comment]
if you are looking for another way because **iio/libmergepdf** does not support PHP 8.4 for example here is the same code **libmergepdf** uses under the hood using **setasign/fpd**i

```
        $fpdi = new Fpdi();
        $sources = [$firstFile, $secondFile];
        foreach ($sources as $source) {
            $fpdi->setPrintHeader(false);
            $fpdi->setPrintFooter(false);
            $pageCount = $fpdi->setSourceFile($source);
            $pageNumbers = range(1, $pageCount);

            foreach ($pageNumbers as $pageNumber) {
                $templateId = $fpdi->importPage($pageNumber);
                $size = $fpdi->getTemplateSize($templateId);
                $fpdi->AddPage($size['orientation'], [$size['width'], $size['height']]);
                $fpdi->useTemplate($templateId);
            }
        }

        file_put_contents('merged.pdf', $fpdi->Output('', 'S'));
```

**Comment by Ahmed-Aboud** [comment]
if you are looking for another way because **iio/libmergepdf** does not support PHP 8.4 for example here is the same code **libmergepdf** uses under the hood using **setasign/fpd**i

```
        $fpdi = new Fpdi();
        $sources = [$firstFile, $secondFile];
        foreach ($sources as $source) {
            $fpdi->setPrintHeader(false);
            $fpdi->setPrintFooter(false);
            $pageCount = $fpdi->setSourceFile($source);
            $pageNumbers = range(1, $pageCount);

            foreach ($pageNumbers as $pageNumber) {
                $templateId = $fpdi->importPage($pageNumber);
                $size = $fpdi->getTemplateSize($templateId);
                $fpdi->AddPage($size['orientation'], [$size['width'], $size['height']]);
                $fpdi->useTemplate($templateId);
            }
        }

        file_put_contents('merged.pdf', $fpdi->Output('', 'S'));
```

you will need to install 
https://github.com/tecnickcom/TCPDF
too
