### ISSUE TITLE
Fix 'rem' CSS units 

### ISSUE THREAD

**Issue by devnitram92bcs** [barryvdh/laravel-dompdf#239]
I've  trying to fix by mysefl, but it's a general issue that you need to fix.

There is here some examples that I'd like to show you
`h1 {
  min-height: 1rem;
  font-size: 2rem;
}

h2 {
  font-size: 1.714rem;
}

h3 {
  font-size: 1.28rem;
} `

In special, I've had problems with the propierty **border-radius**
`border-radius: 0.28571429rem;`
I hope you can fix this.

**Comment by barryvdh** [comment]
Please submit to the dompdf repo

**Comment by rakeden** [comment]
I encountered this issue in the past days when I was setting fontSizes with the rem unit. The result was breaking my custom font rendering. After removing all rem units again, the font got rendered properly again
