### ISSUE TITLE
dom to pdf anchor tag

### ISSUE THREAD

**Issue by rohitRvDev** [barryvdh/laravel-dompdf#241]
Is there any way to create the link (anchor tag) when converting to pdf ? . You can check the screenshot bellow how's the link looks like . 
(https://cloud.githubusercontent.com/assets/20335042/16647039/e308f8e0-444a-11e6-83bd-997aa03f1f2e.png)

Thanks

**Comment by barryvdh** [comment]
Please ask here https://github.com/dompdf/dompdf

**Comment by rohitRvDev** [comment]
Okay thanks

On Thu, Jul 7, 2016 at 3:41 PM, Barry vd. Heuvel <notifications@github.com>
wrote:

> Please ask here https://github.com/dompdf/dompdf
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/barryvdh/laravel-dompdf/issues/241#issuecomment-231038291>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATZJwjXcZhEXGbo0MYP8-lN1p8dZJgJ4ks5qTNDYgaJpZM4JG2Nk>
> .
>



-- 
Thanks & Regards
 Rohit kumar
