### ISSUE TITLE
Call to undefined method Page_Frame_Decorator::add_line()

### ISSUE THREAD

**Issue by ghost** [barryvdh/laravel-dompdf#244]
The method 

> add_line()

does not exist in the page_frame_decorator.cls.php

**Comment by bmaqsood22** [comment]
Because you are trying to generate multiple PDF with the same PDF instance obeject. check this link for more info

https://stackoverflow.com/questions/79278206/call-to-undefined-method-dompdf-framedecorator-pageadd-line
