### ISSUE TITLE
DOMPDF_ENABLE_FONTSUBSETTING should be DOMPDF_ENABLE_FONT_SUBSETTING

### ISSUE THREAD

**Issue by yuqinz** [barryvdh/laravel-dompdf#246]
In config, DOMPDF_ENABLE_FONTSUBSETTING should be DOMPDF_ENABLE_FONT_SUBSETTING, otherwise this option won't recognized by DOMPDF

**Comment by barryvdh** [comment]
Can you PR?

**Comment by perkola** [comment]
I also need this working. See #247

**Comment by barryvdh** [comment]
Fixed with #247 :)
