### ISSUE TITLE
laravel 5.3 support

### ISSUE THREAD

**Issue by mohamedsharaf** [barryvdh/laravel-dompdf#250]
- Installation request for laravel/framework 5.3.\* -> satisfiable by laravel/framework[5.3.x-dev].
  - Installation request for barryvdh/laravel-dompdf 0.6.\* -> satisfiable by barryvdh/laravel-dompdf[v0.6.0, v0.6.1].

**Comment by barryvdh** [comment]
can you try `0.7.x@dev`?
