### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages. ---- Whats wrong ?

### ISSUE THREAD

**Issue by IftakharBappy** [barryvdh/laravel-dompdf#251]
$ composer require barryvdh/laravel-dompdf
Using version ^0.7.0 for barryvdh/laravel-dompdf
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: dompdf/dompdf[v0.7.0, v0.6.2].
    - Can only install one of: dompdf/dompdf[v0.7.0, v0.6.2].
    - Can only install one of: dompdf/dompdf[v0.7.0, v0.6.2].
    - barryvdh/laravel-dompdf v0.7.0 requires dompdf/dompdf ^0.7 -> satisfiable by dompdf/dompdf[v0.7.0].
    - Installation request for barryvdh/laravel-dompdf ^0.7.0 -> satisfiable by barryvdh/laravel-dompdf[v0.7.0].
    - Installation request for dompdf/dompdf (locked at v0.6.2) -> satisfiable by dompdf/dompdf[v0.6.2].

Installation failed, reverting ./composer.json to its original content.

**Comment by barryvdh** [comment]
laravel/dompdf 0.7 only supports dompdf 0.7. Try removing dompdf/dompdf from you composer file.

**Comment by mvpasarel** [comment]
I was using `"yajra/laravel-datatables-oracle": "^6.11"` which depends on `"dompdf/dompdf": "^0.6.1"` so I used composer aliases to fix it:

```json
        "barryvdh/laravel-dompdf": "^0.7.0",
        "dompdf/dompdf": "0.7.0 as 0.6.2",
        "phenx/php-font-lib": "0.4 as 0.2.2"
```

**Comment by barryvdh** [comment]
Ah,  I guess it would be best if the package from @yajra would also be updated.

**Comment by mvpasarel** [comment]
Exactly. But for now this made it work.

**Comment by mvpasarel** [comment]
Seems like its updated and I maybe using an older version of datatables https://github.com/yajra/laravel-datatables/issues/496.

**Comment by larsbo** [comment]
had the same error.

The solution for me was as simple as:
`composer remove barryvdh/laravel-dompdf`
`composer require barryvdh/laravel-dompdf`

**Comment by VickG** [comment]
@larsbo 

I tried what you suggested, but I am still getting:

    

```
>                                                        
>   [Symfony\Component\Debug\Exception\FatalThrowableError]  
>   Class 'Cpdf' not found                                   
>                                                            
> 
> Script php artisan ide-helper:generate handling the post-update-cmd event returned with an error
> 
>                       
>   [RuntimeException]  
>   Error Output:       
>                       
```
Any thoughts?

**Comment by kangyasin** [comment]
hello you can try with

```
"barryvdh/laravel-dompdf": "^0.8.0",
"dompdf/dompdf": "0.8.0 as 0.6.2"
```

work tested in laravel version 5.6 maybe same in 5.4

**Comment by lois-dowell** [comment]
hello
