### ISSUE TITLE
Laravel 5.3.2 : Cannot use Facade

### ISSUE THREAD

**Issue by lolotoobo** [barryvdh/laravel-dompdf#252]
If I try to use facade `I have Non-static method Barryvdh\DomPDF\PDF::loadView() should not be called statically`. I added the definition of the facade in the app.php. 

Otherwise it works perfectly.

In other words

```
    $data = ['popol' => 'poipol'];
    $pdf = App::make('dompdf.wrapper');
    $pdf->loadView('PDF.index', $data);
    return $pdf->stream();
```

works but

```
    return PDF::loadView('PDF.index')->stream();
```

fails

**Comment by barryvdh** [comment]
Are you importing the class? If so, don't do that.

**Comment by lolotoobo** [comment]
Of course I have `use Barryvdh\DomPDF\PDF;`

**Comment by mbuk** [comment]
+1 same problem here

**Comment by barryvdh** [comment]
> If so, don't do that.

Now you're not using the facade.

**Comment by mbuk** [comment]
On my mobile so don't have access to codebase but I'm following this implementation:

$pdf = PDF::loadView('pdf.invoice', $data);
return $pdf->download('invoice.pdf');

Get warning that loadView should be called statically

**Comment by barryvdh** [comment]
Yeah don't import `Barryvdh\DomPDF\PDF` but use the Facade `Barryvdh\DomPDF\Facade as PDF`, or `use \PDF;`

**Comment by mbuk** [comment]
Cheers - must have been going blind!

**Comment by lolotoobo** [comment]
It works perfectly by using \PDF

Thank you
