### ISSUE TITLE
Combine orientation page

### ISSUE THREAD

**Issue by xeroky** [barryvdh/laravel-dompdf#254]
Hello,

How can I combine in one document, horizontal and vertical pages?

**Comment by adecma** [comment]
Same problem, any tips for this?
Ex : 
Page 1 potrait
page 2 landscape

**Comment by xeroky** [comment]
Hi adecma,

I it solved as follows:

```
$m = new Merger();

$view1 = \View::make('pdf.informe1_vertical')->render();
$view2 = \View::make('pdf.informe2_horitzontal')->render();
$view3 = \View::make('pdf.informe3_vertical')->render();

$pdf = App::make('dompdf.wrapper');
$pdf->loadHTML($view1)->setPaper('a4', 'portrait');
$m->addRaw($pdf->output());

$pdf = App::make('dompdf.wrapper');
$pdf->loadHTML($view2)->setPaper('a4', 'landscape');
$m->addRaw($pdf->output());

$pdf = App::make('dompdf.wrapper');
$pdf->loadHTML($view3)->setPaper('a4', 'portrait');
$m->addRaw($pdf->output());

file_put_contents('informes/test_'.$user->id.'.pdf', $m->merge());
```

I hope you find it useful

**Comment by gregorip02** [comment]
HI xeroky, what is the Merge package you used?

**Comment by gregorip02** [comment]
He encontrado el paquete, usen  `composer require iio/libmergepdf`

**Comment by rajanpkr** [comment]
Does merging not affect the page numbering of the pdf files. I mean I want the page number to continue in the second pdf from the first pdf. I'm in a similar situation and its been days since I found a correct solution anywhere on the internet. Please somebody help me.

**Comment by kanhaiya508** [comment]
ssdds
