### ISSUE TITLE
css3 multiple columns

### ISSUE THREAD

**Issue by pat123456** [barryvdh/laravel-dompdf#255]
Hello,

Is there a way to use css3 multiple columns in laravel-dompdf ?

[http://www.w3schools.com/css/css3_multiple_columns.asp](http://www.w3schools.com/css/css3_multiple_columns.asp)

Thank

**Comment by barryvdh** [comment]
Not sure if dompdf supports that, You can ask on https://github.com/dompdf/dompdf.

**Comment by pat123456** [comment]
ok thank you, will look at dompdf (didn't understood that it was an other project...)
