### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by McGreeb** [barryvdh/laravel-dompdf#256]
My function works fine on windows to generate a pdf from a laravel view but in our debian environment we get the following error:

```
production.ERROR: ErrorException: Undefined index: /var/www/application/dev/vendor/dompdf/dompdf\lib\fonts\Helvetica-Bold in /var/www/application/dev/vendor/dompdf/dompdf/src/
Renderer/Text.php:97
```

here is my code:

```
$filepath = app_path().'/TestFiles/';
 $tempfilename = hash('sha1', Auth::user()->email)."-".hash('sha1', date(DATE_RFC2822)).'.pdf';

$file = $filepath . $tempfilename;

$pdf = PDF::loadView('Emails.quote', compact('quote', 'client', 'currency'));
$pdf->save($file);
```

My initial thought is the 3 slashes that are the wrong way in referencing the font

**Comment by mizansohag** [comment]
I have same issue. This work fine on windows but after transferred i got an error.
Error:
`local.ERROR: exception 'ErrorException' with message 'Undefined index: /home/smddtech/public_html/smshop/vendor/dompdf/dompdf\lib\fonts\Times-Bold' in /home/smddtech/public_html/smshop/vendor/dompdf/dompdf/src/Renderer/Text.php:97`
```
Code
         $pdf = \App::make('dompdf.wrapper');
         $pdf->loadHTML('<h1>Test</h1>');
         return $pdf->stream("invoice-$id.pdf");
```

**Comment by McGreeb** [comment]
there has been some discussion of the problem here: https://github.com/dompdf/dompdf/issues/1260
but nothing I could make work yet

**Comment by harsh1412** [comment]
Change backslash \ to forward slash / 
in fonts/dompdf_font_family_cache.php

**Comment by Eltyer** [comment]
Additionally:

In storage/fonts/dompdf_font_family_cache.php

change all "/" to "\"

You can do this with the "replace all" function of your text editor.

**Comment by Eltyer** [comment]
Correction:

All "\" to "/"

**Comment by Cedcomps** [comment]
Yes you saved me, from PC to Linux thanks to you

**Comment by surgiie** [comment]
I fixed this simply by deleting the `/storage/fonts` folder i created in windows and creating  it again, in my debian environment.

**Comment by temals** [comment]
@surgiie thanks thats work

**Comment by cristian495** [comment]
i fixed it delting the /storage/fonts/ from my new location proyect and creating again the folder /fonts.

**Comment by Attachai77** [comment]
So Thanks

**Comment by AkshayDigheGithub** [comment]
Additionally:

In storage/fonts/dompdf_font_family_cache.php

change all "/" to ""

You can do this with the "replace all" function of your text editor.


this works ...
Thanks man,

**Comment by sdkcodes** [comment]
Mine worked by just deleted the storage/fonts folder on the server

**Comment by mcornielly** [comment]
Solved...
delete dompdf_font_family_cache.php. root (storage/fonts/dompdf_font_family_cache.php)
or change name dompdf_font_family_cache_.php
and ready.

**Comment by Isaac2712** [comment]
Lo he arreglado cambiando "\" (la barra) por "/".

**Comment by Isaac2712** [comment]
Lo he arreglado cambiando "\\" (la barra) por "/".

**Comment by ericpereira** [comment]
> i fixed it delting the /storage/fonts/ from my new location proyect and creating again the folder /fonts.

Loguei só pra dizer que isso funcionou pra mim!
