### ISSUE TITLE
Failed to load PDF document

### ISSUE THREAD

**Issue by vtellez** [barryvdh/laravel-dompdf#261]
Hello,

I am trying to use this package with Laravel 4 ( I've used it successfully in other projects with Laravel 5.X)

I install it via composer and making changes to app.php file. Then I am trying this first sample:

```

Route::get('test', array('before' => 'auth', function(){
  $pdf = App::make('dompdf');
  $pdf->loadHTML('Test');
  return $pdf->stream();
}));
```

I am able to open the streaming when I load the page, but I am getting this error from the browser:

> Failed to load PDF document

I can't see any log in the laravel or apache logs files.

Any ideas?

Thanks in advance

**Comment by vtellez** [comment]
anyone can help me?

**Comment by barryvdh** [comment]
Can you view the source? Perhaps it's an error.
 Try `dd($pdf->output())` to perhaps see anything?

**Comment by vtellez** [comment]
Thanks for your response @barryvdh 

This is the output:

`1 0 obj
<< /Type /Catalog
/Outlines 2 0 R
/Pages 3 0 R >>
endobj
2 0 obj
<< /Type /Outlines /Count 0 >>
endobj
3 0 obj
<< /Type /Pages
/Kids [6 0 R
]
/Count 1
/Resources <<
/ProcSet 4 0 R
/Font << 
/F1 8 0 R
>>
>>
/MediaBox [0.000 0.000 595.280 841.890]
 >>
endobj
4 0 obj
[/PDF /Text ]
endobj
5 0 obj
<<
/Creator (DOMPDF)
/CreationDate (D:20160927121340+02'00')
/ModDate (D:20160927121340+02'00')
>>
endobj
6 0 obj
<< /Type /Page
/Parent 3 0 R
/Contents 7 0 R
>>
endobj
7 0 obj
<< /Filter /FlateDecode
/Length 67 >>
stream
x��2�300P@&�ҹ�B�M���-L�L�,BR����B��5BR�K4cB�\C���G
endstream
endobj
8 0 obj
<< /Type /Font
/Subtype /Type1
/Name /F1
/BaseFont /Times-Roman
/Encoding /WinAnsiEncoding
>>
endobj
xref
0 9
0000000000 65535 f 
0000000009 00000 n 
0000000074 00000 n 
0000000120 00000 n 
0000000274 00000 n 
0000000303 00000 n 
0000000417 00000 n 
0000000480 00000 n 
0000000618 00000 n 
trailer
<<
/Size 9
/Root 1 0 R
/Info 5 0 R
>>
startxref
727
%%EOF
' (length=982)`

**Comment by vtellez** [comment]
@barryvdh any idea?

**Comment by vtellez** [comment]
This issue is driving me crazy

I see absolutely nothing wrong in the apache log files, or system of laravel.

Any ideas?

**Comment by livigston-alexander** [comment]
Hola, tengo el mismo problema, tienen alguna solucion?

**Comment by livigston-alexander** [comment]
any idea?

b"""
%PDF-1.3\n
1 0 obj\n
<< /Type /Catalog\n
/Outlines 2 0 R\n
/Pages 3 0 R >>\n
endobj\n
2 0 obj\n
<< /Type /Outlines /Count 0 >>\n
endobj\n
3 0 obj\n
<< /Type /Pages\n
/Kids [6 0 R\n
]\n
/Count 1\n
/Resources <<\n
/ProcSet 4 0 R\n
/Font << \n
/F1 8 0 R\n
/F2 9 0 R\n
>>\n
>>\n
/MediaBox [0.000 0.000 595.280 841.890]\n
 >>\n
endobj\n
4 0 obj\n
[/PDF /Text ]\n
endobj\n
5 0 obj\n
<<\n
/Creator (DOMPDF)\n
/CreationDate (D:20170118182042-05'00')\n
/ModDate (D:20170118182042-05'00')\n
/Title (Example 2)\n

**Comment by oscarqpe** [comment]
I have the same problem :(

**Comment by venkateshcontus** [comment]
@vtellez are you fix that issue

**Comment by luernes** [comment]
controller code

    public function printletter( $text ){
        $data = array(
            'html' => $text
        );
        $pdf = App::make('dompdf.wrapper');        
        $pdf->loadView('emails.email_template', $data);        
        return base64_encode($pdf->stream('letter'));
    }

I use loadView because I use template for print document

.js code ussing ajax
        $.ajax({
            type: "POST",
            contentType: "application/json; charset=utf-8",
            url: "printletter",
...
      .complete(function (jqXHR, status) {
            base64EncodedPDF = jqXHR.responseText;
            var dataURI = "data:application/pdf;base64," +base64EncodedPDF;
            window.open(dataURI);

that work for me.

**Comment by wimurk** [comment]
New update with google chrome and dompdf stops working. It worked fine before. Anyone found a quick fix? A lot of websites can't use dompdf right now

**Comment by udemethegrtman** [comment]
> controller code
> 
> ```
> public function printletter( $text ){
>     $data = array(
>         'html' => $text
>     );
>     $pdf = App::make('dompdf.wrapper');        
>     $pdf->loadView('emails.email_template', $data);        
>     return base64_encode($pdf->stream('letter'));
> }
> ```
> 
> I use loadView because I use template for print document
> 
> .js code ussing ajax
> $.ajax({
> type: "POST",
> contentType: "application/json; charset=utf-8",
> url: "printletter",
> ...
> .complete(function (jqXHR, status) {
> base64EncodedPDF = jqXHR.responseText;
> var dataURI = "data:application/pdf;base64," +base64EncodedPDF;
> window.open(dataURI);
> 
> that work for me.

This did not work for me, it returned a blank page, how can i make it work for me.
