### ISSUE TITLE
Delay to Download

### ISSUE THREAD

**Issue by MyatHtut** [barryvdh/laravel-dompdf#262]
I am download pdf download process take couple minutes. Here is my code simple
in controller
`$sale = Sale::find($id);
        view()->share('sale', $sale);
        $pdf = PDF::loadview('sale.slip_out_pdf');
        return $pdf->download('slip_out.pdf');`
view
`<a href="{{ action('SaleController@pdf',[$sale->id]) }}">Download PDF</a>`
Routes
`Route::get('pdf/{id}', 'SaleController@pdf');`

**Comment by barryvdh** [comment]
Not sure what the question is?
