### ISSUE TITLE
Trying to render Lavacharts into PDF

### ISSUE THREAD

**Issue by Denn1992** [barryvdh/laravel-dompdf#263]
Everything is working fine but my lavacharts chart isnt getting rendered in the PDF.

<div id="{{ $baan->naam_div_modelmakerij }}" style="float:left;"></div>

{!! $baan->charts->render('BarChart', $baan->naam_tabel_modelmakerij, $baan-naam_div_modelmakerij) !!}

Someone has already fixxed this problem?

**Comment by barryvdh** [comment]
Try https://github.com/barryvdh/laravel-snappy

**Comment by harshdoshi999** [comment]
Same here, laracharts are not working. And when I use laravel-snappy, it shows error regarding wkhtmltopdf

**Comment by Denn1992** [comment]
Yes same for me, Im also still stuck on this issue. If someone finds it out can you post it here?

**Comment by barryvdh** [comment]
It will not happen on dompdf
