### ISSUE TITLE
ErrorException in Text.php line 97:

### ISSUE THREAD

**Issue by GregKeaney** [barryvdh/laravel-dompdf#264]
Got everything running smoothly on my dev machine.  Pushed to forge and am now getting this;

ErrorException in Text.php line 97:
Undefined index: /home/forge/myProject/vendor/dompdf/dompdf\lib\fonts\Helvetica-Bold

Anyone has a fix for this?
Thanks!

**Comment by mikeberb** [comment]
+1
Everything running smoothly and suddenly 
ErrorException in Text.php line 97: Undefined index: /var/www/myproject/vendor/dompdf/dompdf\lib\fonts\DejaVuSans

I deleted all the files in the /storage/fonts directory and I was able to create the pdf.

Thanks.
Mike

**Comment by Eltyer** [comment]
In storage/fonts/dompdf_font_family_cache.php

change all "/" to "\"

You can do this with the "replace all" function of your text editor.

**Comment by ratatatKE** [comment]
@Eltyer's comment fixed it for me.
