### ISSUE TITLE
Maximum execution time of 60 seconds exceeded on `php artisan serve`

### ISSUE THREAD

**Issue by rossjcooper** [barryvdh/laravel-dompdf#265]
I get the following error when using this library through `php artisan serve` but it works fine if I host using an Apache.

``` php
FatalErrorException in Helpers.php line 432:
Maximum execution time of 60 seconds exceeded
in Helpers.php line 432
at FatalErrorException->__construct() in HandleExceptions.php line 133
at HandleExceptions->fatalExceptionFromError() in HandleExceptions.php line 118
at HandleExceptions->handleShutdown() in HandleExceptions.php line 0
at Helpers::record_warnings() in Stylesheet.php line 340
at file_get_contents() in Stylesheet.php line 340
at Stylesheet->load_css_file() in Dompdf.php line 631
at Dompdf->processHtml() in Dompdf.php line 730
at Dompdf->render() in PDF.php line 187
at PDF->render() in PDF.php line 133
at PDF->output() in PDF.php line 156
at PDF->download() in EstimatesController.php line 130
```

**Comment by neutt22** [comment]
Having the same problem here.

**Comment by neutt22** [comment]
Got mine solved. How are you loading images?

**Comment by deferdie** [comment]
You need to modify the PHP's 'max_execution_time' in the php.ini file or place this 'ini_set('max_execution_time', 300)' at the start of your PHP file. Obviously without the quotes.

Hope that works.

**Comment by PrafullaKumarSahu** [comment]
> You need to modify the PHP's 'max_execution_time' in the php.ini file or place this 'ini_set('max_execution_time', 300)' at the start of your PHP file. Obviously without the quotes.
> 
> Hope that works.

Better to think why it is exceeding the time, right?

**Comment by rossjcooper** [comment]
Wow I completely forgot about this issue, if anyone is interested I stopped using this package and built a Puppetter based node service that saves html as a PDF, was much easier, faster and supports modern CSS a lot better as it runs on Chromium

**Comment by PrafullaKumarSahu** [comment]
@rossjcooper then you should make a package with that.

**Comment by PrafullaKumarSahu** [comment]
@rossjcooper  let me know if you have created any package or planning to create one.

**Comment by rossjcooper** [comment]
@PrafullaKumarSahu https://github.com/rossjcooper/node-pdf

**Comment by abdulrehman25** [comment]
dompdf does not work on 

php artisan server

You should go through xampp server. 
**It solved my problem**
