### ISSUE TITLE
Maximum execution time exceeded

### ISSUE THREAD

**Issue by yoksanherlie** [barryvdh/laravel-dompdf#266]
I'm using this laravel/dompdf to send an email to my customer about their invoice in pdf format. So it is a big html. The issue is that sometimes the process is successful but sometimes it throws the error above (maximum execution time exceeded)

I've read some issues that say to increase the php execution time, but for me, it is making it worse, it's not a good solution for production

I've read abot laravel/snappy, is it more stable and powerful than laravel/dompdf ? And do I have to install the wkhtmltopdf on my team's computer ?

**Comment by davidsuryaputra** [comment]
Me too, my view doesn't render.

I read some blog it says this issue exists because nested table.

`
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Export</title>
  
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

  
  <link rel="stylesheet" href="{{ url('bootstrap/css/bootstrap.min.css') }}">
  <style>
  .height {
      min-height: 200px;
  }

  .icon {
      font-size: 47px;
      color: #5CB85C;
  }

  .iconbig {
      font-size: 77px;
      color: #5CB85C;
  }

  .table > tbody > tr > .emptyrow {
      border-top: none;
  }

  .table > thead > tr > .emptyrow {
      border-bottom: none;
  }

  .table > tbody > tr > .highrow {
      border-top: 3px solid;
  }
  </style>


</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  
  <div class="container">
      <div class="row">
          <div class="col-xs-12">
              <div class="text-center">
                  <i class="fa fa-search-plus pull-left icon"></i>
                  <h2>Invoice #{{ $transaction->id }}</h2>
              </div>
              <hr>
              <div class="row">
                <div class="col-xs-12 col-md-6 col-lg-6">
                  <div class="panel panel-default">
                    <img src="{{ url($showroom->logo) }}" width="200" height="100">
                    <br /><br />
                    {{ $showroom->name }}<br />
                    {{ $showroom->address }}<br />
                    {{ $showroom->city }}<br />
                    {{ $showroom->phone }}<br />
                  </div>
                </div>
                <div class="col-xs-12 col-md-6 col-lg-6">
                  <div class="panel panel-default center">
                    <img src="{{ url('mobix/images/logo.png') }}" width="200" height="100">
                    <br />
                    <br />
                    <h3>Faktur Layanan Cuci Mobil</h3>
                  </div>
                </div>
              </div>
              <div class="row">
                  <div class="col-xs-12 col-md-6 col-lg-6">
                      <div class="panel panel-default">
                        
                        <table class="table">
                          <tr>
                            <td>Nomor Faktur</td>
                            <td>:</td>
                            <td>{{ $transaction->id }}</td>
                          </tr>
                          <tr>
                            <td>Nomor Polisi</td>
                            <td>:</td>
                            <td>{{ $transaction->description }}</td>
                          </tr>
                          <tr>
                            <td>Nama Pelanggan</td>
                            <td>:</td>
                            <td>{{ $transaction->customer->name }}</td>
                          </tr>
                        </table>
                      </div>
                  </div>
                  
                  <div class="col-xs-12 col-md-6 col-lg-6">
                      <div class="panel panel-default">
                        <table class="table">
                          <tr>
                            <td>Tanggal</td>
                            <td>:</td>
                            <td>{{ $transaction->created_at->format('d-M-Y') }}</td>
                          </tr>
                          <tr>
                            <td>Jam</td>
                            <td>:</td>
                            <td>{{ $transaction->created_at->format('H:i:s') }}</td>
                          </tr>
                          <tr>
                            <td>Nama Kasir</td>
                            <td>:</td>
                            <td>{{ $transaction->operator->name }}</td>
                          </tr>
                        </table>
                        
                      </div>
                  </div>
              </div>
          </div>
      </div>
      <div class="row">
          <div class="col-md-12">
              <div class="panel panel-default">
                  <div class="panel-heading">
                      <h3 class="text-center"><strong>Order summary</strong></h3>
                  </div>
                  <div class="panel-body">
                      <div class="table-responsive">
                          <table class="table table-condensed">
                              <thead>
                                  <tr>
                                      <td><strong>No</strong></td>
                                      <td class="text-center"><strong>Rincian</strong></td>
                                      <td class="text-center"><strong>Jumlah</strong></td>
                                      <td class="text-center"><strong>Harga</strong></td>
                                      <td class="text-right"><strong>Sub Total</strong></td>
                                  </tr>
                              </thead>
                              <tbody>
                                @foreach($transactionDetails as $index => $item)
                                  <tr>
                                      <td>{{ $index+1 }}</td>
                                      <td>{{ $item->item->name}}</td>
                                      <td class="text-center">{{ $item['quantity'] }}</td>
                                      <td class="text-center">{{ $item->item->value }}</td>
                                      <td class="text-right">{{ $item['sub_total'] }}</td>
                                  </tr>
                                @endforeach
                                  <tr>
                                      <td class="emptyrow"><i class="fa fa-barcode iconbig"></i></td>
                                      <td class="emptyrow"></td>
                                      <td class="emptyrow"></td>
                                      <td class="emptyrow text-center"><strong>Grand Total</strong></td>
                                      <td class="emptyrow text-right">{{ $transaction->total }}</td>
                                  </tr>
                              </tbody>
                          </table>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>

  

</div>

</body>
</html>
`

**Comment by barryvdh** [comment]
Try https://github.com/barryvdh/laravel-snappy

**Comment by davidsuryaputra** [comment]
@yoksanherlie @barryvdh 

The problem for me exactly local resource, like css, image, js. I develop in localhost.
Anyway laravel snappy result more good than laravel dompdf so now I'm using laravel snappy. There is no broken design.

So thanks, all of you my problem has been fixed.

What about you @yoksanherlie, Have you try laravel snappy?

**Comment by Hegun58** [comment]
I just found out this issue,
Try to remove the line 
<link rel="stylesheet" href="{{ url('bootstrap/css/bootstrap.min.css') }}">
in order to make it work.

**Comment by burakkaraoglu** [comment]
I wanna two column in content automaticly if need
<div style="-webkit-column-count: 2;-moz-column-count: 2;column-count: 2;">

</div>
can i use this?

**Comment by burakkaraoglu** [comment]
I wanna two column in content automaticly if need
can i use this?
`<div style="-webkit-column-count: 2;-moz-column-count: 2;column-count: 2;">bla bla....</div>`

**Comment by BRVK** [comment]
1. While you are using DOMPDF you have to write out put in entire html format.
  Like: <html><body></body></html>
2. I hope that external CSS links will not work.
3. If any images inside the pdf . Run project from http:localhost// (run in htdocs) (Don't Use $ php artisan serve, b'cause on serve images will not gonna work).
I hope these will work.
my side these are working fine.
Thank yu

**Comment by Subhra2018** [comment]
I am generating a large dynamic PDF with 31 pages. It's working but the execution time is too long (almost 2 minutes). Please help me to reduce the execution time.
