### ISSUE TITLE
handleError('8', 'Undefined index: ', 'url/vendor/dompdf/dompdf/lib/Cpdf.php', '3547', array('size' => '12')) in

### ISSUE THREAD

**Issue by arthurchiakh** [barryvdh/laravel-dompdf#268]

**Comment by arthurchiakh** [comment]
Solved...
delete dompdf_font_family_cache.php.
and let the renderer regenerate the cache

**Comment by normeno** [comment]
Thanks, I had been looking for the solution for hours and this worked

**Comment by pcfjojo** [comment]
I have the same problem.. but does not work even after delete cache or delete vendor file completely

**Comment by xhuang9** [comment]
I don't know if its a bit late or not. But what you could do is find the "dompdf_font_family_cache.php" and replace "\" to "/". That hopefully will fix the issue.

**Comment by sugoireed** [comment]
Replacing  "\" with "/" in the dompdf_font_family_cache.php file found in the storage\fonts folder sorted it out for me.

**Comment by ajatdarojat45** [comment]
/laravel/vendor/dompdf/dompdf/lib/fonts\Helvetica-Oblique

how to change \ to / ? 

please help me

**Comment by jam1e** [comment]
@sugoireed not only did I have to replace the backslashes with a forward slash but also correct the directory to where my fonts were installed. Thank you for the tip!

**Comment by mcornielly** [comment]
Solved...
delete dompdf_font_family_cache.php.  root (storage/fonts/dompdf_font_family_cache.php)
or change name dompdf_font_family_cache_.php
and ready.

**Comment by othmaan100** [comment]
i have followed  the suggestions above. am using PHP 7.4 with laravel 7 trying to print simple pdf. It give the error below

file_get_contents(C:\xampp\htdocs\logistics\vendor\facade\ignition\src\ErrorPage/../../resources/compiled/ignition.js): failed to open stream: No such file or directory
 Undefined index: in file C:\\xampp\\htdocs\\logistics\\vendor\\dompdf\\dompdf\\lib\\Cpdf.php on line 3928.
I have made the 5ab413ede0c0d14abbb48febee3bfdfb.ufm in **storage** folder. but i couldnt locate   dompdf_font_family_cache_.php in my project

**Comment by Amer-cealliance** [comment]
I am unable to find file in dompdf_font_family_cache my laravel project
