### ISSUE TITLE
fopen(/var/www/public_html/woods/storage/fonts//5ab413ede0c0d14abbb48febee3bfdfb.ufm): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by jayeshrwo** [barryvdh/laravel-dompdf#269]
I am trying to load external css in my html  using <link href="{{ url('css/bootstrap.min.css') }}" rel="stylesheet">.

But it giving me an error.

ErrorException in AdobeFontMetrics.php line 45: 

fopen(/var/www/public_html/woods/storage/fonts//5ab413ede0c0d14abbb48febee3bfdfb.ufm): failed to open stream: No such file or directory.

If i load bootstrap using cdn its working correctly.  

When i looked into storage directory there are no any fonts folder. creating fonts folder manually fix issue. but this is not proper way to do this manually.

Any one have idea how to fix this issue?

**Comment by annajeanine** [comment]
I have the same problem! Anyone?

**Comment by VivyGuo** [comment]
I have the same problem，too！How to solve？

**Comment by deferdie** [comment]
Paste the code you are executing here.

**Comment by syoukaihou** [comment]
create 'fonts' folder under 'storage' and make sure your server can access this folder.
``` chmod mode 777 fonts ````

**Comment by jaydip17** [comment]
thanks syoukaihou . Solved this issue using your advice.

**Comment by ashish135** [comment]
Hello,

I'm getting this error after creating a fonts folder inside the storage folder with chmod 777.

Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Additionally, a 503 Service Temporarily Unavailable error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by MohanrajSecqureone** [comment]
Same Error !

**Comment by ashish135** [comment]
You need to create a fonts folder inside storage folder.

**Comment by chisumo2016** [comment]
Can someone help please, I have tried the above instructions still doesnt work for me
(1/1) ErrorExceptionfopen(C:\laragon\www\sumotube\storage/uploads/): failed to open stream: No such file or directory
--
in UploadImage.php (line 45)
at HandleExceptions->handleError(2, 'fopen(C:\\laragon\\www\\chisumotube\\storage/uploads/): failed to open stream: No such file or directory', 'C:\\laragon\\www\\chisumotube\\app\\Jobs\\UploadImage.php', 45, array('path' => 'C:\\laragon\\www\\chisumotube\\storage/uploads/', 'fileName' => '.png'))
at fopen('C:\\laragon\\www\\chisumotube\\storage/uploads/', 'r+')

**Comment by barotrahulh123** [comment]
Solution :

fopen(/var/www/public_html/woods/storage/fonts//5ab413ede0c0d14abbb48febee3bfdfb.ufm): failed to open stream: No such file or directory.


**STEPS**

1) crate "fonts" Folder inside storage
2) create file "5ab413ede0c0d14abbb48febee3bfdfb.ufm" or other "File Name" Which show in error  inside "fonts" Folder
3) Giving Permission "fonts" Folder

**NOW IT'S RUN**

**Comment by sunitaphpdev** [comment]
Thanks...Its working for me.

**Comment by mattrabe** [comment]
This seems to happen upon first usage when using font-face CSS declarations to declare a custom font.

Manually creating a fonts/ folder under storage/ works to resolve the issue, but I feel the code should be creating this directory if it does not exist. This is problematic for rolling out to numerous servers.

**Comment by sharmaanand086** [comment]
I was getting the error fopen(/var/www/public_html/woods/storage/fonts//5ab413ede0c0d14abbb48febee3bfdfb.ufm): failed to open stream: No such file or directory.

 public function fun_pdf(Request $request,$form_id)
{ 
 $applicantdata = applicants::where('form_id', $form_id);
    $pdf =PDF::loadView('admin/Applicantform',compact('applicantdata'));    
    return $pdf->download('Applicantform.pdf'); 
}
And i did these  
STEPS:
crate "fonts" Folder inside storage
create file "5ab413ede0c0d14abbb48febee3bfdfb.ufm" or other "File Name" Which show in error inside "fonts" Folder
Giving Permission "fonts" Folder
It works  but pdf is not as i expected

My view
![image](https://user-images.githubusercontent.com/38725515/39247255-8427e166-48b6-11e8-9cc9-5c9feeb1afe3.png)
 
And Am getting this 
![image](https://user-images.githubusercontent.com/38725515/39247307-a451bb1a-48b6-11e8-8620-ab706ba94dd2.png)

**Comment by isometriq** [comment]
`/storage/fonts/.gitignore`
```
*
!.gitignore
```

@barryvdh is it possible to create this file with `vendor:publish` ?

**Comment by albertogaldames** [comment]
What if you don't have permission in the production server?

**Comment by uresh** [comment]
hi is any one know why this fonts folder need. because my laravel works fine without it but recently came this issues

**Comment by CezarDev** [comment]
crate "fonts" Folder dentro do armazenamento criar arquivo "5ab413ede0c0d14abbb48febee3bfdfb.ufm" ou outro "Nome do arquivo" que mostram erro dentro da pasta "fonts" Dando permissão "fonts" Folder AGORA É FUNCIONADO

**Comment by l0rb** [comment]
@albertogaldames you don't need 777. depending on the executing users group and who owns the folder in your environment even 600 might be enough. more likely you need 660 at least though

**Comment by wisnubaldas** [comment]
> create 'fonts' folder under 'storage' and make sure your server can access this folder.
> `chmod mode 777 fonts``

not work for me :(

**Comment by elianbarci** [comment]
In my case (i'm on Windows 10) just creating the folder "fonts" and the exact file of the error works wells

**Comment by Rolf** [comment]
> > create 'fonts' folder under 'storage' and make sure your server can access this folder.
> > `chmod mode 777 fonts``
> 
> not work for me :(

https://github.com/dompdf/dompdf/issues/2017#issuecomment-578531584

But in new version use like this:
`
new Option([
'fontCache' => ''/path/to/font/cache/directory'',
'fontDir' =>''/path/to/font/directory",
])
`

**Comment by angelwayne** [comment]
@barotrahulh123 excelente, me sirvió tu solución, Gracias.

**Comment by qhdctod** [comment]
Ran into this problem, creating the folder definitely solves it - however surely this should be handled by the `vendor:publish` command.

**Comment by Mohan-Patidar** [comment]
STEPS


[pdf.pdf](https://github.com/barryvdh/laravel-dompdf/files/5709017/pdf.pdf)
create "fonts" Folder inside storage
create file "5ab413ede0c0d14abbb48febee3bfdfb.ufm" or other "File Name" Which show in error inside "fonts" Folder
Giving Permission "fonts" Folder

It works but pdf is not as i expected

**Comment by mayuri-acesnws** [comment]
No need to create any such fonts folder.
$pdf = PDF::loadView('letter.view', $data)->setOptions(['defaultFont' => 'sans-serif']);
Just set default font. It works.

**Comment by Eversonv4** [comment]
> Solution :
> 
> fopen(/var/www/public_html/woods/storage/fonts//5ab413ede0c0d14abbb48febee3bfdfb.ufm): failed to open stream: No such file or directory.
> 
> **STEPS**
> 
> 1. crate "fonts" Folder inside storage
> 2. create file "5ab413ede0c0d14abbb48febee3bfdfb.ufm" or other "File Name" Which show in error  inside "fonts" Folder
> 3. Giving Permission "fonts" Folder
> 
> **NOW IT'S RUN**

Works just fine for me. I created the folder and the file, I renamed the new file with the name of the file the application was trying to reach and worked perfectly. Thank you so much!

**Comment by AhmedAlaa8** [comment]
$pdf = Pdf::loadView('your_file_load')->setOptions(['defaultFont' => 'sans-serif']);

use this
