### ISSUE TITLE
CSS Float doesn't work

### ISSUE THREAD

**Issue by nasirouwagana** [barryvdh/laravel-dompdf#271]
I am working on Laravel 5.3.

I set in the file **config/dompdf.php** the key **DOMPDF_ENABLE_CSS_FLOAT** to **true** value. But CSS floating doesn't work.

Here is the block code in my blade view : 

```
<div style="font-size: 12px;">
    <p style="float: left;">
        <img src="{{ public_path("img/parametres/".$parametre->logo) }}" style="width: 60px;">
    </p>
    <p style="float: right;">
        <span><strong>{{ $parametre->nomStructure }}</strong></span><br>
        <span>Tel : {{ $parametre->telephone }}</span><br>
        <span>Email : {{ $parametre->email }}</span><br>
        <span>Adresse : {{ $parametre->adresse }}</span>
    </p>
</div>
```

How can fixed it ?

**Comment by barryvdh** [comment]
Try to make an issue in dompdf/dompdf

**Comment by rianokik** [comment]
same as me, if you have any solution please help me too, this is my code
`<h3>REPORT ALL MAN POWER</h3>
{{-- 	<table style="font-size: 10; margin: 0; width: 100%;">
		@for ($i = 0; $i < 5; $i++)
		<tr>
			<td width="50%">
				<table cellspacing="0" width="100%" class="tab" style="font-size: 9; border: solid">
					<tr>
						<td rowspan="5" width="30%">
							<center><div style="width: 3cm; height: 4cm; background-color: red">&nbsp;</div></center>
						</td>
						<th width="20%"><center>Nama</center></th>
						<td>: Okik Rian</td>
					</tr>
					<tr>
						<th><center>Divisi</center></th>
						<td>: MIS</td>
					</tr>
					<tr>
						<th><center>Grade</center></th>
						<td>: X-3</td>
					</tr>
					<tr>
						<th><center>Masakerja</center></th>
						<td>: 3 tahun 9 bulan</td>
					</tr>
					<tr>
						<th><center>Umur</center></th>
						<td>: 6 tahun 7 bulan</td>
					</tr>
				</table>
			</td>
			<td width="50%">
				<table cellspacing="0" width="100%" class="tab" style="font-size: 9; border: solid">
					<tr>
						<td rowspan="5" width="30%">
							<center><div style="width: 3cm; height: 4cm; background-color: red">&nbsp;</div></center>
						</td>
						<th width="20%"><center>Nama</center></th>
						<td>: Okik Rian</td>
					</tr>
					<tr>
						<th><center>Divisi</center></th>
						<td>: MIS</td>
					</tr>
					<tr>
						<th><center>Grade</center></th>
						<td>: X-3</td>
					</tr>
					<tr>
						<th><center>Masakerja</center></th>
						<td>: 3 tahun 9 bulan</td>
					</tr>
					<tr>
						<th><center>Umur</center></th>
						<td>: 6 tahun 7 bulan</td>
					</tr>
				</table>
			</td>
		</tr>
		@endfor
	</table> --}}
		<table width="50%" style="font-size: 9; border-collapse: collapse; border: 0px; float: left">
			<tr>
				<td style="border: 1px solid" rowspan="5" width="30%">
					<center><div style="width: 3cm; height: 4cm; background-color: red">&nbsp;</div></center>
				</td>
				<th style="border: 1px solid" width="20%"><center>Nama</center></th>
				<td style="border: 1px solid">: Okik Rian</td>
			</tr>
			<tr>
				<th style="border: 1px solid"><center>Divisi</center></th>
				<td style="border: 1px solid">: MIS</td>
			</tr>
			<tr>
				<th style="border: 1px solid"><center>Grade</center></th>
				<td style="border: 1px solid">: X-3</td>
			</tr>
			<tr>
				<th style="border: 1px solid"><center>Masakerja</center></th>
				<td style="border: 1px solid">: 3 tahun 9 bulan</td>
			</tr>
			<tr>
				<th style="border: 1px solid"><center>Umur</center></th>
				<td style="border: 1px solid">: 6 tahun 7 bulan</td>
			</tr>
		</table>
		<table width="50%" style="font-size: 9; border-collapse: collapse; float: left;">
			<tr>
				<td style="border: 1px solid" rowspan="5" width="30%">
					<center><div style="width: 3cm; height: 4cm; background-color: red">&nbsp;</div></center>
				</td>
				<th style="border: 1px solid" width="20%"><center>Nama</center></th>
				<td style="border: 1px solid">: Okik Rian</td>
			</tr>
			<tr>
				<th style="border: 1px solid"><center>Divisi</center></th>
				<td style="border: 1px solid">: MIS</td>
			</tr>
			<tr>
				<th style="border: 1px solid"><center>Grade</center></th>
				<td style="border: 1px solid">: X-3</td>
			</tr>
			<tr>
				<th style="border: 1px solid"><center>Masakerja</center></th>
				<td style="border: 1px solid">: 3 tahun 9 bulan</td>
			</tr>
			<tr>
				<th style="border: 1px solid"><center>Umur</center></th>
				<td style="border: 1px solid">: 6 tahun 7 bulan</td>
			</tr>
		</table>`

**Comment by rianokik** [comment]
```<h3>REPORT ALL MAN POWER</h3>
		<table width="50%" style="font-size: 9; border-collapse: collapse; border: 0px; float: left">
			<tr>
				<td style="border: 1px solid" rowspan="5" width="30%">
					<center><div style="width: 3cm; height: 4cm; background-color: red">&nbsp;</div></center>
				</td>
				<th style="border: 1px solid" width="20%"><center>Nama</center></th>
				<td style="border: 1px solid">: Okik Rian</td>
			</tr>
			<tr>
				<th style="border: 1px solid"><center>Divisi</center></th>
				<td style="border: 1px solid">: MIS</td>
			</tr>
			<tr>
				<th style="border: 1px solid"><center>Grade</center></th>
				<td style="border: 1px solid">: X-3</td>
			</tr>
			<tr>
				<th style="border: 1px solid"><center>Masakerja</center></th>
				<td style="border: 1px solid">: 3 tahun 9 bulan</td>
			</tr>
			<tr>
				<th style="border: 1px solid"><center>Umur</center></th>
				<td style="border: 1px solid">: 6 tahun 7 bulan</td>
			</tr>
		</table>
		<table width="50%" style="font-size: 9; border-collapse: collapse; float: left;">
			<tr>
				<td style="border: 1px solid" rowspan="5" width="30%">
					<center><div style="width: 3cm; height: 4cm; background-color: red">&nbsp;</div></center>
				</td>
				<th style="border: 1px solid" width="20%"><center>Nama</center></th>
				<td style="border: 1px solid">: Okik Rian</td>
			</tr>
			<tr>
				<th style="border: 1px solid"><center>Divisi</center></th>
				<td style="border: 1px solid">: MIS</td>
			</tr>
			<tr>
				<th style="border: 1px solid"><center>Grade</center></th>
				<td style="border: 1px solid">: X-3</td>
			</tr>
			<tr>
				<th style="border: 1px solid"><center>Masakerja</center></th>
				<td style="border: 1px solid">: 3 tahun 9 bulan</td>
			</tr>
			<tr>
				<th style="border: 1px solid"><center>Umur</center></th>
				<td style="border: 1px solid">: 6 tahun 7 bulan</td>
			</tr>
		</table>```

**Comment by ervaibhavsinghal** [comment]
same here... if anyone has the solution, do let me know. Thanks.
