### ISSUE TITLE
Cannot set file name

### ISSUE THREAD

**Issue by amismailz** [barryvdh/laravel-dompdf#274]
Using Lumen v5.2,
The following code runs successfully, but it downloads a file with name "response.pdf.pdf" although it should be named "admission.pdf" 

```
    $model = self::findModel($this->model, $id);
    $pdf = App::make('dompdf.wrapper');
    $pdf->loadView('pdfAdmission', ['model'=>$model]);
    return $pdf->download('admission.pdf');
```

**Comment by annajeanine** [comment]
Could you maybe include more code? I want to re-create the situation but get errors for the undefined property App\Http\Controllers\PDFController::$model.. 

I did get a pdf download with the specified name when I used this code: 

```
$pdf = App::make('dompdf.wrapper');
$pdf->loadView('pdfAdmission');
return $pdf->download('admission.pdf');
```

**Comment by amismailphp** [comment]
I tried your code exactly but with no changes, the file is named "response.pdf.pdf"

**Comment by annajeanine** [comment]
Could you post your config/dompdf.php?

**Comment by amismailphp** [comment]
[dompdf.php.zip](https://github.com/barryvdh/laravel-dompdf/files/521957/dompdf.php.zip)

**Comment by annajeanine** [comment]
Hmm. The only thing differing in our config files is the way we declare our fonts path. You use `fonts/` and I have `fonts` (folder in my public folder from Laravel). I am sorry I can't help you out.. Please notify me if you managed to solve the issue!

**Comment by amismailphp** [comment]
Finally I knew the reason, this was due to I was using Postman.
Thank you for help.

**Comment by shiromani2018** [comment]
Hi amismailz,

Did you manage to make it work in postman? if yes please can you share the joy.
