### ISSUE TITLE
The file could not be found under the directory specified by Options::chroot.

### ISSUE THREAD

**Issue by annajeanine** [barryvdh/laravel-dompdf#275]
Hi everyone!

For my newest application I want to add a feature where the user can enable a button, which returns a PDF file of the view. I will add the code so maybe you can see the mistake... 

## results.blade.php 

`<form method="POST" action="generatePDF">`
`<button type="hidden" name="_token" class="btn btn-default" value="{{ csrf_token() }}">Generate PDF</button><br>`
 `</form><br><br>`

## Routes.php
`Route::post('/generatePDF', 'PDFController@generatePDF');`

## PDFController.php
`namespace App\Http\Controllers;`
`use App\Http\Requests;`
`use Illuminate\Http\Request;`
`class PDFController extends Controller{`
         ` public function __construct(){`
                  `$this->middleware('auth');`
         `}`
         ` public function generatePDF(){`
                  `return \PDF::loadFile('/my-app-dir/resources/views/results')->save('uploads')->stream('download.pdf');`
        `}`
`}`

## dompdf.php

Here is changed the storage_paths to ('uploads'), which is a folder in my public folder.

## Error
Permission denied on /my-app-dir/resources/views/results. The file could not be found under the directory specified by Options::chroot.

Please help me out! :-)

**Comment by bryanedward** [comment]
how is the cache cleaned?

**Comment by ekntrtmz** [comment]
I got this error when using `loadFile()` instead of `loadView()`.

**Comment by hugeps** [comment]
> path_variable

Can you please be more specific... where is this path variable configured?!

**Comment by yogithesymbian** [comment]
i have same issue when using 
```{{-- @extends('view.theapps.app.layouts.pdf.app') --}}```
before its working but now i dunno why , if i put the code the erros is come.
