### ISSUE TITLE
Undefined variable from other Controller

### ISSUE THREAD

**Issue by annajeanine** [barryvdh/laravel-dompdf#276]
Hi everyone!

I have a problem where I can´t get out of. 
My application consists of a results.blade.php which contains different projects. These projects can be selected and are saved in an array. This array is passed on to resultsoneproject.blade.php through a resultcontroller.php. My PDF-generate code is the following±

```
public function GeneratePDF()
{
        $pdf = \PDF::loadView('home');
        $filename = "resultsoneproject";
        $pdf -> loadView($filename);

        return $pdf -> stream(); 
}
```

This results the following error: 

`Undefined variable: idarray (View: /opt/app/resources/views/resultsoneproject.blade.php)`

Does anyone know how I can solve this parameter problem? 
I'm using laravel 5.2

**Comment by JosephJose** [comment]
you are loading "resultsoneproject" partial into your PDF without its parent. this partial didn't inherit the "idarray" variable, so you need to pass the variable to the partial. I'm not sure how to pass the data when using $filename = "....", but in the documentation the data is passed like this:
$pdf = \PDF::loadView('viewf', $data);

**Comment by annajeanine** [comment]
Hi @JosephJose, thank you for helping me. I have tried this method but it says that 'idarray' is a undefined variable.. Should I pass this on somewhere else like in the route.php?

**Comment by JosephJose** [comment]
You need to look at the parent view, because 'idarray' is clearly passed to the parent view. Or you can simply store the 'idarray' value into the session and use it in the partial.

**Comment by M3ndes** [comment]
> Hi @JosephJose, thank you for helping me. I have tried this method but it says that 'idarray' is a undefined variable.. Should I pass this on somewhere else like in the route.php?

did you fixed it? i'm having the same issue!
