### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by ramirez456** [barryvdh/laravel-dompdf#286]
How can I do to include fonts?

**Comment by terrylow** [comment]
@ramirez456 

you can include your font like you always do in css, your font will be download and cached in /storage/fonts directory

**Comment by slimmen** [comment]
@ramirez456 @terrylow Little late but maybe worth noticing is that if you'd like to include a custom font. I was only able to do that by using the full url to my fonts folder in the public folder **(url('fonts/myfont.tff'))**. If I used the storage_path function in larvel and stored the font in storage/fonts instead that wouldn't work.

**Comment by ghsa** [comment]
This is not working for me, I'm trying to import from url as @slimmen said, but ends up in a infinity loop, anyone can help me?
