### ISSUE TITLE
Laravel 5.3  Class 'Barryvdh\DomPDF\ServiceProvider' not found

### ISSUE THREAD

**Issue by cruskai** [barryvdh/laravel-dompdf#288]
Hello,

I am getting the error Class 'Barryvdh\DomPDF\ServiceProvider' not found in Laravel 5.3 after installing via composer. I have read over a couple of other posts on the issue and couldn't find anything that helped me. I have attached my composer.json and config/app.php files. Any assistance is appreciated.

[composer and config.zip](https://github.com/barryvdh/laravel-dompdf/files/619955/composer.and.config.zip)

**Comment by diogogomeswww** [comment]
You need to add it to the ServiceProvider, as explained in [Readme](https://github.com/barryvdh/laravel-dompdf/blob/master/readme.md)

After updating composer, add the ServiceProvider to the providers array in config/app.php
`Barryvdh\DomPDF\ServiceProvider::class,`

**Comment by jomalago3788** [comment]
como puedo solucionar este error

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Barryvdh\DomPDF\ServiceProvider' not found

**Comment by toschuss** [comment]
Same problem here, with Laravel 5.7.

_Class 'Barryvdh\DomPDF\ServiceProvider' not found_ after adding Barryvdh\DomPDF\ServiceProvider::class to config/app.php...

**Comment by pooya-alen1990** [comment]
I have this problem too, 
My Laravel version is 5.6

**Comment by emersonsimoes-dev** [comment]
I have this problem in laravel 6.8

"Class 'Barryvdh\DomPDF\ServiceProvider' not found"

**Comment by AshleyLlamas** [comment]
Aquí 2021 Laravel 8 con el mismo problema y ninguna solución -.-

**Comment by djgraphics28** [comment]
Undefined type 'PDF'

please help , I am using laravel 8.8
I already put all the providers and aliases in config/app.php and run php artisan vendor:publish

what should i do to fix this sir?
