### ISSUE TITLE
Using jQuery 

### ISSUE THREAD

**Issue by gemox94** [barryvdh/laravel-dompdf#289]
Hi, I'm new in this and I want to add a class to a div depending on the table height with jQuery. When I check the page it works fine but when the view is converted to PDF the div has no class.
`<script>`
   `if ($("table").height() >= 490){`
       `$("#footer").removeClass('footerFixed').addClass('footer');`
   `}else{`
       `$("#footer").removeClass('footer').addClass('footerFixed');`
   `}`
`</script>`
Any suggestions or there is no way to use jQuery with dompdf?

**Comment by barryvdh** [comment]
Nope, try laravel-snappy
