### ISSUE TITLE
<th>星期一</th>Unicode does not support

### ISSUE THREAD

**Issue by syoukaihou** [barryvdh/laravel-dompdf#290]
```
<html>
    <head>
        <title>测试pdf</title>

        <style>
            @font-face {
                font-family: 'msyh';
                font-style: normal;
                font-weight: normal;
                src: url(http://www.test.com/fonts/msyh.ttf) format('truetype');
            }
            
            body {  font-family: 'msyh';  }
            
        </style>
    </head>
    <body>
        <div class=\"container\">
            <div class=\"content\">
                <div class=\"title\"><p>（2016年12月报）本月运营方向</p></div>
                
                <table>
                      <tr>
                        <th>星期一</th>
                        <th>星期二</th>
                      </tr>
                    <tr>
                        <td>1号</td><td>2号</td>
                    </tr>
                </table>
            </div>
        </div>
    </body>
</html>
```

but the web page show "???",
<img width="1197" alt="qq20161201-0 2x" src="https://cloud.githubusercontent.com/assets/16933900/20787900/355a26f2-b7e9-11e6-892e-3b216953d2fe.png">

**Comment by terrylow** [comment]
what is the result if you add
`<meta charset="UTF-8">` ?

**Comment by syoukaihou** [comment]
I have try add <meta charset="UTF-8">, but it don't work. @terrylow 

can you give me a demo ,if you use the same method .

**Comment by meditatorzhang** [comment]
I have the same problem, even serious. All Chinese words display "?", not only in &lt;table&gt;

**Comment by terrylow** [comment]
@syoukaihou @meditatorzhang do you have the chinese font installed ? i have tested, without proper chinese supported font (xx.ttf, xx.ufm, and xx.ufm.php), you will get ?? or square characters

**Comment by terrylow** [comment]
Step to install your font to dompdf

1. download [load_font.php](https://github.com/dompdf/utils) and place in ur project root
2. edit load_font.php
 - change the line `require_once "autoload.inc.php";`
to `require_once "vendor/autoload.php"`
- add `$fontDir = "storage/fonts"`;
3. download your chinese supported font at eg: [Fonts-Unicode-Chinese](https://cooltext.com/Fonts-Unicode-Chinese) and place at your project root
4. run in commandline `php load_font.php xxxfont xxxfont.ttf`
eg: you have download simsun.ttf you will do ` php load_font.php simsun simsun.ttf` then you font will be installed to storage/fonts directory

**Comment by ZK998** [comment]
@terrylow,
that is great!! it works in chinese fonts.
thanks a lot !

**Comment by meditatorzhang** [comment]
@terrylow,
I operate as your method and run in commandline `php load_font.php xxxfont xxxfont.ttf`, but this command returns:
```
Unable to find bold face file.
Unable to find italic face file.
Unable to find bold_italic face file.
Copying simsun.ttf to storage/fonts/simsun.ttf...
Generating Adobe Font Metrics for storage/fonts/simsun...
```
at last, pdf file also display "?" in Chinese character postion.

@ZK998 
Could you tell me how do you solve this problem, thanks a lot!

**Comment by ZK998** [comment]
@meditatorzhang 
Do you set ur page charset "<meta charset="UTF-8">"?
and can you find the font file in  ""storage/fonts" directory

**Comment by meditatorzhang** [comment]
@ZK998 
I set the page charset, such as '<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>',
there are simsun.ttf and simsun.ufm files in 'storage/fonts' directory.

**Comment by terrylow** [comment]
@meditatorzhang did you set font-family in your page ?

**Comment by meditatorzhang** [comment]
@terrylow 
There are simsun.ttf and sumsun.ufm files in storage/fonts and view file as following,but also display "?"
```
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>测试pdf</title>

    <style>
        @font-face {font-family: 'simsun'; font-style: normal; font-weight: normal; }
        html, body {  height: 100%;  }
        body {  margin: 0;  padding: 0;  width: 100%; font-weight: 100;  font-family: 'msyh';  }
        .container {  text-align: center; vertical-align: middle;  }
        .content {  text-align: center;  display: inline-block;  }
        .title {  font-size: 96px;  }
    </style>
</head>
<body>
<div class="container">
    <div class="content">
        <div class="title">xiao中华人民共和国</div>
    </div>
</div>
</body>
</html>
```

**Comment by terrylow** [comment]
instead of `@font-face {font-family: 'simsun'; font-style: normal; font-weight: normal; }`
try 
`body {font-family: 'simsun'}`

you need to tell the browser, you want to use simsun font instead of 'msyh' in your case

**Comment by meditatorzhang** [comment]
@terrylow 
That's great. Chinese Spring Festival is approachng, Happy New Year, thanks a lot!

**Comment by schel4ok** [comment]
I don't know if it works with chinese, but with Russian it is enough just to change setting in config/dompdf.php

```
"DOMPDF_DEFAULT_FONT" => "DejaVu Sans",
```

**Comment by dodacvan** [comment]
@schel4ok  thanks . it work for me .

**Comment by Cyrille37** [comment]
It works like @terrylow say at https://github.com/barryvdh/laravel-dompdf/issues/290#issuecomment-265673491.

I use "[simhei](https://cooltext.com/Download-Font-%e9%bb%91%e4%bd%93+Sim+Hei)" that works fine with mixed Chinese and Latin characters.

- Then use `load_font.php` but becarefull : https://github.com/dompdf/utils/issues/3
    - the file `dompdf_font_family_cache.php` is the important file !
- Then just use `font-family:simhei;`

Cheers

**Comment by huyit218** [comment]
please help me to resolve my problem, i type my vietnamese but display ? ? character, i'm using dompdf, so how can i do to display m data. thanks all

**Comment by khanhhbit** [comment]
@huyit218 you add before </head>
<style>
  body { font-family: DejaVu Sans, sans-serif; }
</style>

**Comment by MuhammadTalha944** [comment]
you just need to add font-family: DejaVu Sans; in your body or also you can set the font family to any specific div in which you are going to display the Unicode Characters.

For body: `body{font-family: DejaVu Sans;}`

And for a specific div: `<div style="font-family: DejaVu Sans;"> --- </div>`

Hope this would help.

**Comment by zong0828** [comment]
hello i have same problem, then i have no idea which chinese font can be used.
I try to use 
`php load_font.php simsun 'simsun.ttf'`
then it always show that ....
`PHP Fatal error:  Uncaught Dompdf\Exception: Unable to read 'simsun.ttf'. in /Users/zonghan/Applications/dev-backend/source-code/ubss/load_font.php:77
Stack trace:
#0 /Users/zonghan/Applications/dev-backend/source-code/ubss/load_font.php(192): install_font_family(Object(Dompdf\Dompdf), 'simsun', 'simsun.ttf')
#1 {main}
  thrown in /Users/zonghan/Applications/dev-backend/source-code/ubss/load_font.php on line 77

Fatal error: Uncaught Dompdf\Exception: Unable to read 'simsun.ttf'. in /Users/zonghan/Applications/dev-backend/source-code/ubss/load_font.php:77
Stack trace:
#0 /Users/zonghan/Applications/dev-backend/source-code/ubss/load_font.php(192): install_font_family(Object(Dompdf\Dompdf), 'simsun', 'simsun.ttf')
#1 {main}
  thrown in /Users/zonghan/Applications/dev-backend/source-code/ubss/load_font.php on line 77`

**Comment by zong0828** [comment]
hello , I have same problem, then i have no idea which chinese font can be used.
however, i try to use `load_font.php.php` to get some fonts testing

```
PHP Fatal error:  Uncaught Dompdf\Exception: Unable to read 'simsun.ttf'. in /Users/zonghan/Applications/dev-backend/source-code/ubss/load_font.php:77
Stack trace:
#0 /Users/zonghan/Applications/dev-backend/source-code/ubss/load_font.php(192): install_font_family(Object(Dompdf\Dompdf), 'simsun', 'simsun.ttf')
#1 {main}
  thrown in /Users/zonghan/Applications/dev-backend/source-code/ubss/load_font.php on line 77

Fatal error: Uncaught Dompdf\Exception: Unable to read 'simsun.ttf'. in /Users/zonghan/Applications/dev-backend/source-code/ubss/load_font.php:77
Stack trace:
#0 /Users/zonghan/Applications/dev-backend/source-code/ubss/load_font.php(192): install_font_family(Object(Dompdf\Dompdf), 'simsun', 'simsun.ttf')
#1 {main}
  thrown in /Users/zonghan/Applications/dev-backend/source-code/ubss/load_font.php on line 77

```
