### ISSUE TITLE
Attach generated pdf to email

### ISSUE THREAD

**Issue by nschurmann** [barryvdh/laravel-dompdf#292]
Hello guys!, i have this code:

```php
	public function enviar_producto_por_correo(Request $request, $id) {
		$producto = ProductoPadre::find($id);
		$solicitud = json_decode($request->get('solicitud'), true);
		$fileName = md5($producto->id);
		$email = $request->get('email');
		PDF::loadView('pdf.producto', array(
			'producto' => $producto,
			'solicitud' => $solicitud))->save('./files/'.$filename.'.pdf');
		Mail::send('sitio.enviar_producto', array(), function($message) use ($email, $fileName) {
			$message
				->from('ventas@aloprint.cl', 'AloPrint')
				->to($email)
				->attach('./files/'.$fileName.'.pdf')
				->subject('Cotización en línea');
		});

		return 200;
	}
```
This will find a product by it's ID, then populate the pdf view (this actually works, i've tried it without sending it to an email) but it get a timeout. Any help with this?

**Comment by baqirfarooq** [comment]
Define complete url in attach (Public, Storage) etc.
`public_path('/files/'.$fileName.'.pdf);`

**Comment by JonayMedina7** [comment]
hi, you solve the problem?? in my case I manage to attach the mail but, the pdf arrives damaged

**Comment by brauliobernardo** [comment]
@JonayMedina7 in this case try using the `attach()` method instead of `attachData()` to make sure it doesn't come blank
