### ISSUE TITLE
Call to undefined method Barryvdh\DomPDF\PDF::setOptions()

### ISSUE THREAD

**Issue by luizlahr** [barryvdh/laravel-dompdf#293]
Hi, I am trying to set Headers to the PDF but getting the error 
Call to undefined method Barryvdh\DomPDF\PDF::setOptions()

I have tried this way
```
\PDF::setOptions(['header-html'=> $header]);
$pdf = \PDF::loadView($view, compact('dados'));
```

And 
`$pdf = \PDF::loadView($view, compact('dados'))->setOptions(['header-html'=> $header]);`

Both returns the same error.

Any help?

**Comment by francisortega** [comment]
Hey luizlahr, I am also trying to set a header for my pdf.
Thing is if you look into setOptions method for the PDF model, 'header-html' is not in one of the arrays that can be set as an option. That being said, I don't think headers for the pdf are not really implemented. I can be wrong though.

**Comment by luizlahr** [comment]
Hey, I did some research and just got it, but using HTML and CSS...

Example:

`@page{
    margin: 1cm 1.5cm;
}

body { padding-top: 3.5cm; }

.header {
    position: fixed; 
    top: 0px;
    height: 2.3cm;
    border-bottom: 1px solid gray;
    padding-bottom: .5cm ;
}

.cover:after {
    counter-reset: page 0;
}

.footer {
    /*background-color: #000;*/
    text-align: center;
    padding-top: 0.3cm; 
    border-top: 1px solid gray; 
    position: fixed; 
    bottom: 0.2cm;
}


.cover {
    page-break-after: always;
    height: 100%;
}

.cover h1 {
    padding-top: 35%; 
    width: 100%; 
    text-align: center;
}

.cover h1 small {
    display: block;
    margin-top: 30px;
    font-size: 20px;
    width: 100%;
}

p {
    /*padding-top: 0.3cm;*/
    /*background-color: #aaa;*/
    text-align: justify;
}

h3 {
    font-weight: bold;
    margin-top: 1.3cm;
    background-color: #aaa;
    padding: 0.1cm;
    font-size: 16px;
}

.assinatura { border-collapse: separate; border-spacing: 0.5cm; }
.assinatura td.text-center { border-top: 1px solid black; padding-top: 0.2cm }

p.break { page-break-after: always; }`

`<div class="cover">
	<h1>
		EMPRESA
		<small>
			INSTRUMENTO PARTICULAR DE CONTRATO
			<br>
			[EVENTO-DESCRICAO]
		</small>
	</h1>
</div>`

`<div class="footer">
	Page: <span class="pagenum"></span>
	<span class="pagetotal"></span>
</div>`

`<div class="header">
	<table>
		<tr>
			<td class="w50"> 
				{{ Html::image('painel/img/logo_contrato.png') }}
			</td>
			<td class="w50 text-right header-right">

			</td>
		</tr>
	</table>
</div>`

**Comment by luizlahr** [comment]
Hey, I've done some research, and I got it, but with CSS and HTML.

`@page{
    margin: 1cm 1.5cm;
}

body { padding-top: 3.5cm; }

.header {
    position: fixed; 
    top: 0px;
    height: 2.3cm;
    border-bottom: 1px solid gray;
    padding-bottom: .5cm ;
}

.cover:after {
    counter-reset: page 0;
}

.footer {
    /*background-color: #000;*/
    text-align: center;
    padding-top: 0.3cm; 
    border-top: 1px solid gray; 
    position: fixed; 
    bottom: 0.2cm;
}


.cover {
    page-break-after: always;
    height: 100%;
}

.cover h1 {
    padding-top: 35%; 
    width: 100%; 
    text-align: center;
}

.cover h1 small {
    display: block;
    margin-top: 30px;
    font-size: 20px;
    width: 100%;
}

p {
    /*padding-top: 0.3cm;*/
    /*background-color: #aaa;*/
    text-align: justify;
}

h3 {
    font-weight: bold;
    margin-top: 1.3cm;
    background-color: #aaa;
    padding: 0.1cm;
    font-size: 16px;
}

.assinatura { border-collapse: separate; border-spacing: 0.5cm; }
.assinatura td.text-center { border-top: 1px solid black; padding-top: 0.2cm }

p.break { page-break-after: always; }`

**Comment by francisortega** [comment]
oh okay, if they are set up with HTML and CSS then I don't have an issue at all. My issue is that I am using '.page-break' class to create a new page. And the DOM just wouldn't render properly for some reason. Anyway thanks for this.
