### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by ScooterSam** [barryvdh/laravel-dompdf#294]
```
ErrorException in Block.php line 714:
A non-numeric value encountered
```

I'm not sure why. It was working 100% fine yesterday on XAMPP. Then today I upgraded to Homestead and it no longer works, and throws this error. I can't find anything on google to resolve the error neither.

I stripped all PHP from my View and it still throws the error. So I believe it's something to do with the dompdf package itself.. 

Any ideas?

Thanks

**Comment by barryvdh** [comment]
Which php version?

**Comment by ScooterSam** [comment]
7.1

**Comment by barryvdh** [comment]
See https://github.com/dompdf/dompdf/issues/1272

**Comment by suretarget** [comment]
Same issue. I'm using L5.2.
On my local machine, I have downgraded from php 7.1 to php 5.6.29 but still got error.
On production server I'm using php 5.6.5, it's working fine.
Testing the package with v0.6.* and 0.7.* both got the same issue.

**Comment by fureszk** [comment]
they've fixed the problem at dompdf, can you please merge the fix?

**Comment by ysupr** [comment]
I've got this error today, on style.php and it was solved on dompdf develop branch https://github.com/dompdf/dompdf/pull/1378

i know this is not issue with laravel-dompdf, but is there anyway to use laravel-dompdf with that branch (develop on dompdf) ?

we don't know when will the PR merged into master, but the error are real here.

**Comment by MightySCollins** [comment]
Took me a while to workout but you can use a [composer inline alias](https://getcomposer.org/doc/articles/aliases.md#require-inline-alias). Add the following to your `composer.json`

    "dompdf/dompdf": "dev-master as 0.7.0"

**Comment by suretarget** [comment]
Thanks @MightySCollins took me for almost a month lol. Now it's working fine. Tested with php 7.1.1.

**Comment by barryvdh** [comment]
You should also be able to use `"dompdf/dompdf": "0.7.x@dev"`

**Comment by bsweeney** [comment]
Just popping in for a quick FYI. The Dompdf team just tagged release 0.8.0 which includes changes to improve PHP 7.1 compatibility.

**Comment by ysupr** [comment]
Thanks so much, Will check it

**Comment by barryvdh** [comment]
I also tagged 0.8.0 with dompdf 0.8 support. Don't think anything breaking changed, but improved HTML/CSS support. So let me know if there are any problems!

**Comment by barryvdh** [comment]
I also tagged 0.8.0 with dompdf 0.8 support. Don't think anything breaking changed, but improved HTML/CSS support. So let me know if there are any problems!

**Comment by imraxyDots** [comment]
Hi Barryvdh,

I have installed 0.8.0, can you please also share the config detail for the class, that I can added into laravel project.

**Comment by barryvdh** [comment]
Which config details? Just follow the readme. Default config is here: https://github.com/barryvdh/laravel-dompdf/blob/master/config/dompdf.php

**Comment by imraxyDots** [comment]
Thanks for your quick reply.

Earlier I have installed 0.7.1, and added Barryvdh\DomPDF\ServiceProvider::class, and 'PDF' => Barryvdh\DomPDF\Facade::class, into config file. but I was getting error in block.php regarding non numeric  value. then I have upgrade domPDF with 0.8.0. currently it is showing the error "Class 'Barryvdh\DomPDF\ServiceProvider' not found".. Can you please advice the about full installation process of demoPDF 0.8.0. So that I can implement it.

**Comment by barryvdh** [comment]
You probably installed dompdf directly instead of my wrapper.

**Comment by imraxyDots** [comment]
Can you provide me dom PDF URL, where I can implement it directly..

**Comment by barryvdh** [comment]
Just follow the readme completely

**Comment by imraxyDots** [comment]
"barryvdh/laravel-dompdf": "^0.8.0", I have added it in composer file.

**Comment by imraxyDots** [comment]
I have installed latest 0.8.0 version, Still I am getting error "A non numeric value encountered" in block.php line number 594. Again I have recognized and review the block.php. Error is generating from line no:- 593, there is "$frameBox = $frame->get_frame()->get_border_box();", Can you please do typecasting on that like "$frameBox = (float)$frame->get_frame()->get_border_box();" and push code again on git. so that we can use latest.

**Comment by sharmasaurabh1** [comment]
Yes It true, I have also suffer from same error and found that @imraxyDots are saying right,

@barryvdh Can you please push the code with lil change it the 0.8.0

**Comment by barryvdh** [comment]
No I can't, please create a Pull Request in dompdf/dompdf

**Comment by helenaEngstrom** [comment]
Do you know when a version with the fixed will be released?

**Comment by octaaugusto** [comment]
After hours, we up php 'memory_limit' flag and error gone away.
From 10 to 100MB.
Success!

**Comment by barryvdh** [comment]
Are you using the latest dompdf? Are you on 0.8.2 of dompdf (not my package)

**Comment by sayanthkoroth** [comment]
I just followed the instructions from [](https://github.com/barryvdh/laravel-dompdf)

**Comment by innoviussoftware** [comment]
"A non-numeric value encountered" pdf issue dompdf

Php Version=>5.6
