### ISSUE TITLE
Fatal error: Call to a member function make() on null

### ISSUE THREAD

**Issue by francisortega** [barryvdh/laravel-dompdf#296]
Hi,

I am having this issue on Lumen. The error occurs on loadView() call line 23 on PDF.php. 

`$html = $this->view->make($view, $data, $mergeData)->render();`

The statement above gives this error. I don't know where 'null' is coming from exactly.
My code is something like this:
```
$data = ['test' => 'hello'];
$pdf = PDF::loadView('hello', $data);
```

where 'hello' in loadView is under my 'resources/views' directory...
Any idea why? Is there anything I am missing? Thanks in advance!

**Comment by barryvdh** [comment]
Is the View serviceprovider registered?

**Comment by francisortega** [comment]
I added `$app->register(\Illuminate\View\ViewServiceProvider::class);` Still no luck.

**Comment by brunocascio** [comment]
@francisortega Did you get working this?

**Comment by francisortega** [comment]
Hi @brunocascio yeah, I did it differently but still worked

```
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\View;

function getPDF() {
        ...
        $layout = View::make('layouts.pdf_cart', ['results' => $results, 'user' => $user, 'host' => $host]);

        /* Create PDF */
        $pdf = App::make('dompdf.wrapper');
        $pdf->loadHTML($layout->render());

        return $pdf->stream();
}
```

Basically, you create a view instance (with the template you made) as well as PDF instance and you load that html view using the pdf. Hope that helps.

**Comment by brunocascio** [comment]
Cool, Thanks @francisortega 👍
