### ISSUE TITLE
First Row of Table in Header

### ISSUE THREAD

**Issue by whereisjefe** [barryvdh/laravel-dompdf#297]
``` html
<table width="100%">
    <thead>
        <th>User Id</th>
        <th>Role Id</th>
    </thead>
    <tbody>
      <tr>
          <td>{!! $courseSession->id !!}</td>
          <td>{!! $courseSession->id !!}</td>
      </tr><tr>
          <td>{!! $courseSession->id !!}</td>
          <td>{!! $courseSession->id !!}</td>
      </tr><tr>
          <td>{!! $courseSession->id !!}</td>
          <td>{!! $courseSession->id !!}</td>
      </tr><tr>
          <td>{!! $courseSession->id !!}</td>
          <td>{!! $courseSession->id !!}</td>
      </tr><tr>
          <td>{!! $courseSession->id !!}</td>
          <td>{!! $courseSession->id !!}</td>
      </tr><tr>
          <td>{!! $courseSession->id !!}</td>
          <td>{!! $courseSession->id !!}</td>
      </tr>
    </tbody>
</table>
```
the view renders a normal table as would be expected but when i use 

``` php 
$pdf = PDF::loadView('courseSessions.signin', compact('courseSession'));
return @$pdf->stream();
``` 

i get the following output

<img width="756" alt="screen shot 2016-12-14 at 7 54 26 pm" src="https://cloud.githubusercontent.com/assets/22965241/21211302/57dc30fa-c237-11e6-8bf0-d48050a283ef.png">

I've tried the css tricks mentioned in other posts but they didn't work. It's also worth mentioning that  this is straight html table, no other css is applied to the view.

Not sure if im missing something simple but any help would be appreciated, thanks

**Comment by whereisjefe** [comment]
To add a bit more info i have tested this on both my Mac and Windows environments and get the same behavior 

MAC is running php 7.1 with valet
WIN is running php 7.0 running artisan

**Comment by barryvdh** [comment]
The css you can use it pretty limited, so try to be as oldskool as possible.

**Comment by whereisjefe** [comment]
@barryvdh yeah ok that seemed to do the trick, less is more i suppose. Looks like setting the css to work for print fixed the issues i was having,  Thanks for your response.

**Comment by kieranheadley** [comment]
I know this was closed but cannot find a solution for the issue, I am having the same issue, I have remove all styling from the page and the first row of every table is being moved into the header.

**Comment by diegogand** [comment]
I have the same problem, I delete all the styles and the first row is putting in the table head

**Comment by diegogand** [comment]
I can resolve the problem, I put tr inside thead

**Comment by paulocuambe** [comment]
> The css you can use it pretty limited, so try to be as oldskool as possible.

Hey @barryvdh i tried my best but i cannot figure out a proper way to render my table, could you provide a piece of the css properties you use?

**Comment by tkd5041** [comment]
This is my HTML stylesheet and code: When it outputs the pdf it has this same issue. Has anyone figured out how to address this yet? I am not having any luck and this is as basic as it comes!

`<style>
        #student
        {
            border-collapse: collapse;
            width: 100%;
        }
        #student td, #student th
        {
            border: 1px solid #ddd;
            padding: 8px;
        }
        #student tr:nth-child(even)
        {
            background-color: #0bfdfd;
        }
        #student th
        {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #4caf50;
            color: #fff;
        }
    </style>

    <table id="student">
        <thead>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
        </thead>
        <tbody>
            @foreach ($students as $student)
                <tr id="body">
                    <td>{{$student->id}}</td>
                    <td>{{$student->name}}</td>
                    <td>{{$student->email}}</td>
                    <td>{{$student->phone}}</td>
                </tr>
            @endforeach
        </tbody>
    </table>`

**Comment by ronmrcdo** [comment]
For those who are looking for answer. You can fix it by adding <tr> on the <thead>

ex.

`
<table id="student">
    <thead>
       <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Email</th>
          <th>Phone</th>
      </tr>
    </thead>
    <tbody>
        @foreach ($students as $student)
            <tr id="body">
                <td>{{$student->id}}</td>
                <td>{{$student->name}}</td>
                <td>{{$student->email}}</td>
                <td>{{$student->phone}}</td>
            </tr>
        @endforeach
    </tbody>
</table>`
`
