### ISSUE TITLE
Loading taking ages

### ISSUE THREAD

**Issue by MaximeDawn** [barryvdh/laravel-dompdf#301]
Here's my issue. I'm trying to load a view giving it a database row.

`$valide = ReportValid::where([['order_id', '=', $order_id], ['id', '=', $report_id]])->first();`
`$pdf = \App::make('dompdf.wrapper');`
`$pdf->loadView('reports.prints.valide', ['valide' => $valide]);`
`return $pdf->stream('testpdf.pdf');`

The problem is that it's very very long, and i can't know if the problem comes from me or not. When i try to render a basic` <h1>Test<h1>` it workks like a charm, but not with my view...

And when I just forget DOMPDF and render only my view using `return view('reports.prints.valide', ['valide' => $valide]);` it works too. And it's real quick. 

I already tried to `compact('valide')` but I don't master that command and when I do I got a `$valide does not exists` . Any suggestions ?

**Comment by MaximeDawn** [comment]
Ok, the problem just come from DOMPDF, Snappy solve it ! Better use Snappy than DOMPDF now !

**Comment by abrar-gsoc** [comment]
Can you explain how you solve longer loading time error?

**Comment by MaximeDawn** [comment]
I just switched to use Snappy PDF instead of DOMPDF.
