### ISSUE TITLE
empty page when rendering view as pdf 

### ISSUE THREAD

**Issue by fulgorit** [barryvdh/laravel-dompdf#302]
Hello

I have a blank page with this code:
```

 $pdf = PDF::loadView('checkout', ['rec_rooms' => $rec_rooms]);
 return $pdf->download('check_out_.pdf');
```

[check_out_(7).pdf](https://github.com/barryvdh/laravel-dompdf/files/675305/check_out_.7.pdf)

What should I do ?

Regards

**Comment by barryvdh** [comment]
Does rendering to html work?

```
 return view('checkout', ['rec_rooms' => $rec_rooms]);
```

**Comment by fulgorit** [comment]
Yes I think there were problems in the HTML/CSS code but this time I haven't any debugging informations. I wrote the code for the view again without foundation CSS and it is working.

**Comment by jpkontreras** [comment]
any updates on this ?

**Comment by Roshu91** [comment]
blank pdf generated 
   

 $pdf = \App::make('dompdf');
        $view = view('system-mgmt.report.emp_details', ['employees' => $employees]);
        $pdf->loadHTML($view);
return $pdf->output();

**Comment by Roshu91** [comment]
Any solution??

**Comment by SiroDiaz** [comment]
I have exactly the same error. Solutions?

**Comment by SiroDiaz** [comment]
I have solved the problem. It was a <section> tag. it seems that dompdf doesn't support all HTML5 tags. I wish it helped you.

**Comment by VivekShingala** [comment]
@SiroDiaz, thank you. Your solution worked for me.

**Comment by adnansiddiq** [comment]
i have facing same issue in docker container. 
Code:
`PDF::loadHTML('<h1>Test</h1>')->save(public_path('test1.pdf'));`

empty pdf is generated. and no error is showing on console.

**Comment by tsulatsitamim** [comment]
> i have facing same issue in docker container.
> Code:
> `PDF::loadHTML('<h1>Test</h1>')->save(public_path('test1.pdf'));`
> 
> empty pdf is generated. and no error is showing on console.

try set isHtml5ParserEnabled to false

**Comment by richdear** [comment]
Call to undefined method Barryvdh\DomPDF\PDF::isHTML5ParserEnabled()

**Comment by AndreyAlves** [comment]
using grid in css is a problem.
