### ISSUE TITLE
Image not found or type unknown

### ISSUE THREAD

**Issue by karlpatrickespiritu** [barryvdh/laravel-dompdf#303]
After updating the version to `0.7.0`. The images (.png) are broken ("Image not found or type unknown").

![imgnotfoumd](https://cloud.githubusercontent.com/assets/10472504/21879084/5f19f220-d8d1-11e6-81ac-968cebeb653b.png)

**Comment by aodzylp** [comment]
You need to add **'isRemoteEnabled' => true** 


_**Sample**_
` return PDF::setOptions(['isHtml5ParserEnabled' => true, 'isRemoteEnabled' => true])->loadView('reports.invoiceSell')->stream();`

**Comment by AliveCorpse** [comment]
@aodzylp It doesn't help, form me :disappointed:

**Comment by Padmore51** [comment]
I get the same message when i print an image to pdf using laravel.
Can you show a sample code of how to print an image to pdf.

**Comment by sonamsingh28** [comment]
Enabling remote by setting options helped me fix this.
...
$html = <img src="http://www.domain.com/path/to/image/image.png" />';
$options = new Options();
**$options->setIsRemoteEnabled(true);
$dompdf = new Dompdf($options);**
$dompdf->loadHtml($html);
$dompdf->output();
...

**Comment by raheemmiyasin** [comment]
I solved it after changed this:
`<img src="{{ base_path() }}/location/to/image/image.png" />`

**Comment by rafaelxavierborges** [comment]
@noriega9807 is right. I used <img src="{{ url('/images/image.png') }}"> and worked fine.

**Comment by cuonghuynh** [comment]
Seems that it does not work in the local domain. it worked fine in the public domain.

**Comment by amadeann** [comment]
I think it doesn't work when you customize options in any way.

`laravel-dompdf` defines a set of default options in `config-dompdf`. Whenever you customize these options either through `setOptions` method or a custom `dompdf.php` config file, all the defaults are ignored. Most likely some of the defaults are responsible for proper handling of images. 

If this is true, then the issue can be solved changing the behavior of the library to append-merge new options to the defaults.

**Comment by amadeann** [comment]
Added a [PR](https://github.com/barryvdh/laravel-dompdf/pull/428) fixing this.

**Comment by kduszczy** [comment]
If you still have problem with it. It might be due to something with ssl certificate, I just install one and the images stop showing.
To fix it:
`
        $contxt = stream_context_create([ 
            'ssl' => [ 
                'verify_peer' => FALSE, 
                'verify_peer_name' => FALSE,
                'allow_self_signed'=> TRUE
            ] 
        ]);
        $pdf = PDF::setOptions(['isHtml5ParserEnabled' => true, 'isRemoteEnabled' => true]);
        $pdf->getDomPDF()->setHttpContext($contxt);
`

**Comment by Santoshge-Reddy** [comment]
Got The issue if there are spaces in the image name or URL's

So replace the image-name with %20 it will be solved

$image = str_replace(' ', '%20', $items->image);

**Comment by SatishDanda** [comment]
run it on htdocs. don't run using composer php artisan serve and give currect path url("/public/foldername/image.png").

**Comment by truffolone** [comment]
Solved with the allow remote. Fun fact is that some images from remote were still rendering correctly due to the pagespeed mod on apache2 which was caching the data. I narrowed down the issue after disabling all my cache mods.

I also was on an older version of dompdf (really old project and no time to refractor)

**Comment by josesotomayor** [comment]
Solution: Convert the image to base 64 

image src=""data:image/png;base64, iVBORw0....." />

**Comment by josesotomayor** [comment]
Solution: Convert the image to base64

image src=""data:image/png;base64, iVBORw0....." />

**Comment by josesotomayor** [comment]
Solution: Convert the image to base64

image src="data:image/png;base64, iVBORw0....." />

**Comment by josesotomayor** [comment]
Solution: Convert the image to base64

<img src=""data:image/png;base64, iVBORw0....." />

**Comment by KobiMontague** [comment]
'isRemoteEnabled' => true

Worked for me..thanks aodzylp

**Comment by vctls** [comment]
I'm on a Symfony 3.4 project on a Docker environment, and nothing of the above fixed it.
I ended up using the absolute path on the server, something like this:
```twig
<img src="{{ project_dir ~ '/web' ~ asset('bundles/acme/img/logo.png') }}">
```

**Comment by juancarlosestradanieto** [comment]
I used josesotomayor suggest. 
I created a custom class with the method that gets the base64.

`<?php
namespace App\Custom;

class Archivos
{
	public static function imagenABase64($ruta_relativa_al_public)
	{
			$path = $ruta_relativa_al_public;

			$type = pathinfo($path, PATHINFO_EXTENSION);
			$data = \File::get($path);

			$base64 = "";
			if ($type == "svg") {
					$base64 = "data:image/svg+xml;base64,".base64_encode($data);
			} else {
					$base64 = "data:image/". $type .";base64,".base64_encode($data);
			}

			return $base64;
	}

}
`
Then in the view i did this.

`
@php
use App\Custom\Archivos;
@endphp

<img src="{{Archivos::imagenABase64('assets/img/logo_empresa_contrato.jpg')}}" width="200px" >

`

**Comment by edomeru** [comment]
I've been having this problem for 3 days now, cant show image on pdf(used dompdf),i just wanna fetch the image locally using XAMPP on MAC, the image (goku.jpg) is located inside htdocs/images folder, already set the options, i guess the problem is with the path on src, tried everypath but still doesnt show, tried everything online but nothing seems to work.please help

<img width="854" alt="2018-10-04 11 00 15" src="https://user-images.githubusercontent.com/25947206/46449015-bd679600-c7c4-11e8-98d0-f731abc2b47e.png">

<?php


require("config.inc.php");
// Include autoloader
require_once 'dompdf/autoload.inc.php';
// $_dompdf_show_warnings = true;
// $_dompdf_warnings = [];

use Dompdf\Dompdf;
use Dompdf\Options;
//if posted data is not empty
$options = new Options();
$options->set('defaultFont', 'Courier');
$options->set('isRemoteEnabled', TRUE);
$options->set('debugKeepTemp', TRUE);
$options->set('isHtml5ParserEnabled', TRUE);
$options->set('chroot', '/');
$options->setIsRemoteEnabled(true);

$dompdf = new Dompdf($options);
$dompdf->set_option('isRemoteEnabled', TRUE);

$auth = base64_encode("username:password");

$context = stream_context_create(array(
  'ssl' => array(
    'verify_peer' => FALSE,
    'verify_peer_name' => FALSE,
    'allow_self_signed'=> TRUE
  ),
  'http' => array(
    'header' => "Authorization: Basic $auth"
  )
));

$dompdf->setHttpContext($context);

$agent = "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"; ini_set('user_agent', $agent);

if (isset($_GET['firstName'])){


   $fileName = "https://i.ytimg.com/vi/1z3MA54hRW4/maxresdefault.jpg";

    $root ='file:///kabushikikaishahaimessodo'. $_SERVER["DOCUMENT_ROOT"];
    //$root = realpath(__DIR__);
    $tempDir = $root.'/images/'; 

   $fileName = 'goku.jpg';
    $pngAbsoluteFilePath = $tempDir.$fileName; 
 
 $output = "<table border='1' width='100%' style='border-collapse: collapse;'>
 <tr>
	 <td>Name</td>
	 <td>Address</td>
	 <td>Contact number</td>
	 <td>Primary Key</td>
 </tr>
 ";

$fnme = $_GET['firstName'];

 $query = " 
            SELECT 
                primarykey, firstName, lastName, address, contactNumber
            FROM booking 
            WHERE 
                firstName = :firstName ORDER BY primarykey DESC LIMIT 1
        ";
    
$query_params = array(
        ':firstName' => $_GET['firstName']
    );         
            

//execute query
try {
    $stmt   = $db->prepare($query);
    $result = $stmt->execute($query_params);
}
catch (PDOException $ex) {
    $response["success"] = 0;
    $response["message"] = "Database Error!";
    die(json_encode($response));
}

$rows = $stmt->fetchAll();


if ($rows) {
    $response["success"] = 1;
    $response["message"] = "User exist!";
    $response["users"]   = array();
    
    foreach ($rows as $row) {
        $users             = array();
        $output .='<tr>
                         <th>'.$row['firstName'].' '.$row['lastName'].'  </th>
                         <th>'.$row['address'].'</th>
                         <th>'.$row['contactNumber'].'</th>
                         <th>'.$row['primarykey'].'</th>
                    </tr>';

    }
     $output .='</table><br/><br/>';
 
   $output .= "<center><img src='".$pngAbsoluteFilePath ."' width='128' height='128' /></center>";
$dompdf->loadHtml($output);
$dompdf->setPaper('A4','portrait');
$dompdf->render();
$dompdf->stream("spl",array("Attachment" => 0));

} else {
    $response["success"] = 0;
    $response["message"] = "No Users!";
    die(json_encode($response));
}

}
?>

**Comment by edomeru** [comment]
`I've been having this problem for 3 days now, cant show image on pdf(used dompdf),i just wanna fetch the image locally using XAMPP on MAC, the image (goku.jpg) is located inside htdocs/images folder, already set the options, i guess the problem is with the path on src, tried everypath but still doesnt show, tried everything online but nothing seems to work.please help

<img width="854" alt="2018-10-04 11 00 15" src="https://user-images.githubusercontent.com/25947206/46449241-e9cfe200-c7c5-11e8-8570-4797e0cfa4f8.png">


<?php


require("config.inc.php");
// Include autoloader
require_once 'dompdf/autoload.inc.php';
// $_dompdf_show_warnings = true;
// $_dompdf_warnings = [];

use Dompdf\Dompdf;
use Dompdf\Options;
//if posted data is not empty
$options = new Options();
$options->set('defaultFont', 'Courier');
$options->set('isRemoteEnabled', TRUE);
$options->set('debugKeepTemp', TRUE);
$options->set('isHtml5ParserEnabled', TRUE);
$options->set('chroot', '/');
$options->setIsRemoteEnabled(true);

$dompdf = new Dompdf($options);
$dompdf->set_option('isRemoteEnabled', TRUE);

$auth = base64_encode("username:password");

$context = stream_context_create(array(
  'ssl' => array(
    'verify_peer' => FALSE,
    'verify_peer_name' => FALSE,
    'allow_self_signed'=> TRUE
  ),
  'http' => array(
    'header' => "Authorization: Basic $auth"
  )
));

$dompdf->setHttpContext($context);

$agent = "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"; ini_set('user_agent', $agent);

if (isset($_GET['firstName'])){


   $fileName = "https://i.ytimg.com/vi/1z3MA54hRW4/maxresdefault.jpg";

    $root ='file:///kabushikikaishahaimessodo'. $_SERVER["DOCUMENT_ROOT"];
    //$root = realpath(__DIR__);
    $tempDir = $root.'/images/'; 

   $fileName = 'goku.jpg';
    $pngAbsoluteFilePath = $tempDir.$fileName; 
 
 $output = "<table border='1' width='100%' style='border-collapse: collapse;'>
 <tr>
	 <td>Name</td>
	 <td>Address</td>
	 <td>Contact number</td>
	 <td>Primary Key</td>
 </tr>
 ";

$fnme = $_GET['firstName'];

 $query = " 
            SELECT 
                primarykey, firstName, lastName, address, contactNumber
            FROM booking 
            WHERE 
                firstName = :firstName ORDER BY primarykey DESC LIMIT 1
        ";
    
$query_params = array(
        ':firstName' => $_GET['firstName']
    );         
            

//execute query
try {
    $stmt   = $db->prepare($query);
    $result = $stmt->execute($query_params);
}
catch (PDOException $ex) {
    $response["success"] = 0;
    $response["message"] = "Database Error!";
    die(json_encode($response));
}

$rows = $stmt->fetchAll();


if ($rows) {
    $response["success"] = 1;
    $response["message"] = "User exist!";
    $response["users"]   = array();
    
    foreach ($rows as $row) {
        $users             = array();
        $output .='<tr>
                         <th>'.$row['firstName'].' '.$row['lastName'].'  </th>
                         <th>'.$row['address'].'</th>
                         <th>'.$row['contactNumber'].'</th>
                         <th>'.$row['primarykey'].'</th>
                    </tr>';

    }
     $output .='</table><br/><br/>';
 
   $output .= "<center><img src='".$pngAbsoluteFilePath ."' width='128' height='128' /></center>";
$dompdf->loadHtml($output);
$dompdf->setPaper('A4','portrait');
$dompdf->render();
$dompdf->stream("spl",array("Attachment" => 0));

} else {
    $response["success"] = 0;
    $response["message"] = "No Users!";
    die(json_encode($response));
}

}
?>
`

**Comment by Aswini-Venugopal** [comment]
<td style="border: 1px solid; padding:12px;"><img src="public_path() ./uploads/ http://127.0.0.1:8000/uploads/normal-chicken-biryani.jpg" width="10px" height="10px"></td>
this is my image tag and i cannot view the image

**Comment by josesotomayor** [comment]
Solution: Convert to base 64 the image:

Example:

 <img src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUA
AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
    9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Example" />

**Comment by ACvijic** [comment]
Base 64 conversion is not a good solution for when images are dynamic. In that case you'd have to store them encoded somewhere or encode on the fly.. :disappointed:

**Comment by ACvijic** [comment]
What solved it for me was using `public_path('path/to/image.png')`.

**Comment by jorgeorisan** [comment]
$options = new Options();
$options->set('isHtml5ParserEnabled', true);
$options->set('isRemoteEnabled', true);
$dompdf = new Dompdf($options);

**Comment by mahmuddin** [comment]
@ACvijic Thanks, it's very simple way..

**Comment by CalvinGrain** [comment]
One way is to add domain to hosts file pointing to localhost

**Comment by LendisFabri** [comment]
`public_path('path/to/image.png')` work for me, thanks @ACvijic

**Comment by userlond** [comment]
It works for me this way (PHP5.6, DomPdf 0.8)
```php
<?php
// set some options
$options = [];
// ....
$pdf = new \Dompdf\Dompdf($options);
// set base url for the relative links,
// it's document root from environment variable in my case 
$pdf->setBasePath($_SERVER['DOCUMENT_ROOT']);
```
Next I place my image into `$_SERVER['DOCUMENT_ROOT'] . '/files/img.png'`

And my html template is
```html
<html>
  <head>
    <title>Example</title>
  </head>
  <body>
    <img src="files/img.png">
  </body>
</html>
```

**Comment by Gkiokan** [comment]
It can be done though base_path() also:

`{{ base_path() . '/storage/app/public/images/logo.png' }}`

**Comment by rekcX** [comment]
I had the same issue and applied the solutions above. Still no luck until I figured out that the problem might be due to the use of **htaccess**. 
My site is protected by user password auth, which might have prohibited dompdf to access the image files. The base64 encoding might be a workaround for that, but increases workload. 

Finally I could solve the issue by adding the line:
`Require local`
to my .htaccess file and now it works like a charm.

My .htacces file looks like this:
````[...]
AuthType      Basic
AuthName      "Alpha-Access"
AuthUserFile  [...]
Require user demo, admin
Require local
Require valid-user

**Comment by bogdanpatrasescu** [comment]
> 'isRemoteEnabled' => true
> 
> Worked for me..thanks aodzylp

where can i add this option? in which file? Thanks!

**Comment by daanlo** [comment]
This won't solve the underlying problem, but turning the **png** file into a **jpg** file did the trick for me.

For my very specific use case that was the quickest solution.

**Comment by aqeelnuces** [comment]
its not working for me. i have tried .jpg file. i have tried 'isRemoteEnabled' => true but still keep giving me error

**Comment by Abdul-fatai** [comment]
Solved it by setting the options `PDF::setOptions(['isHtml5ParserEnabled' => true, 'isRemoteEnabled' => true])->loadView('models.receipt', ['receipt' => $receipt]
        )->setPaper('a5', 'portrait'); `

**Comment by pmochine** [comment]
Out of the blue I got this error as well. `public_path('path/to/image.png')` works before that I used `asset('path/to/image.png')`

**Comment by Dilshan97** [comment]
public_path('path/to/image.png') work for me Thanks

**Comment by phildkevin** [comment]
In my case. I need to add canvas(graph) to my pdf. what i did is convert the canvas to base64 image, but It does not render the converted image on downloaded pdf.
How can i render a non locally stored base64 image?

**Comment by sayhicoelho** [comment]
> What solved it for me was using `public_path('path/to/image.png')`.

solved the issue! thanks!

**Comment by tomaslucena** [comment]
Just did a clean installation on my laravel project... Have tried all the solutions above and nothing worked so far :(

**Comment by reinaldoagf** [comment]
this worked for me:
http://alfonsorv.com/dompdf-y-las-imagenes/

**Comment by andrebhas** [comment]
> I used @josesotomayor suggest.
> I created a custom class with the method that gets the base64.
> 
> `<?php
> namespace App\Custom;
> 
> class Archivos
> {
> public static function imagenABase64($ruta_relativa_al_public)
> {
> $path = $ruta_relativa_al_public;
> $type = pathinfo($path, PATHINFO_EXTENSION);
> $data = \File::get($path);
> 
> ```
> 	$base64 = "";
> 	if ($type == "svg") {
> 		$base64 = "data:image/svg+xml;base64,".base64_encode($data);
> 	} else {
> 		$base64 = "data:image/". $type .";base64,".base64_encode($data);
> 	}
> 	return $base64;
> }
> ```
> 
> }`
> 
> Then in the view i did this.
> 
> ` @php use App\Custom\Archivos; @endphp <img src="{{Archivos::imagenABase64('assets/img/logo_empresa_contrato.jpg')}}" width="200px" >`

it work for me, thanks @josesotomayor

**Comment by Rah1x** [comment]
Just upgraded laravel to 7x and hence also upgraded 
barryvdh/laravel-dompdf to v0.8.7
dompdf/dompdf to v0.8.6

Now nothing works.

1) `assets` cant be found due to chroot issue. This can be solved using "asset()" method in blade
2) Cant load `url` inside the css file

3) cant load non-public file. I save user files for my project in a non-public location for certain reasons. Everything has worked fine for last 4 years and now right after this upgrade those files cant be loaded due to chroot.

**Comment by midoridge** [comment]
If your environment is using dompdf/dompdf version 0.8.6, this version is strict checking local path more than previous version.

This version checks "open_basedir" in php.ini via realpath method. So, you need to set "chroot" option.

For example,

document root is "/var/www/html"

php.ini

```
open_basedir = /var/www/:/var/lib/php/session/:/var/lib/php/wsdlcache/:/tmp/
```

example.blade.php

```
<img src="{{ public_path('images/example.png') }}">
```

caller as PdfController

```
use Barryvdh\DomPDF\Facade as PDF;

class PdfController
    public function pdf()
    {
        return PDF::loadView('example')
                  ->setPaper('a4')
                  ->setOptions([
                      'tempDir' => public_path(),
                      'chroot'  => '/var/www',
                  ]);
    }
```

If public_path() is "/var/www/html", you can also write the following

```
use Barryvdh\DomPDF\Facade as PDF;

class PdfController
    public function pdf()
    {
        return PDF::loadView('example')
                  ->setPaper('a4')
                  ->setOptions([
                      'tempDir' => public_path(),
                      'chroot'  => public_path(),
                  ]);
    }
```

**Comment by nix1128** [comment]
I have set the options like  
 


```   setOptions([
    'tempDir' => public_path(),
    'chroot'  => public_path(),
    ]);
```

and have acess the image like 

```<img src="{{ public_path('/path/to/'.$foo->field) }}"> ```

But id doesnt work.  Still getting "" Image not found or type unknown ""

**Comment by tripexito** [comment]
Hi, I am having issues to download pdf file generated with png images, in chrome download dialog shows as .html instead of .pdf

![image](https://user-images.githubusercontent.com/2284599/95668788-de4ee880-0b4e-11eb-9741-db2dd1b76d6d.png)

![image](https://user-images.githubusercontent.com/2284599/95668793-e60e8d00-0b4e-11eb-9af5-0ae4a25e1d28.png)

I've been trying using images as base64 and its working the pdf file download in chrome but the images does not showing on pdf file downloaded. In Firefox Pdf Viewer there's no issues. Please tell how can I solve. Thanks.

**Comment by marouane44** [comment]
> I solved it after changed to this:

require_once 'dompdf/autoload.inc.php';
use Dompdf\Dompdf;

use Dompdf\Options;
<----------------------------------------------------------------------------------------------------------->
> this worked for me: <img src="http://192.168.1.70:8080/invoice_project2/cat.jpg" />
<----------------------------------------------------------------------------------------------------------->






 $options = new Options();
 $options->set('isRemoteEnabled',true);

  $pdf = new Dompdf($options);
 $contxt = stream_context_create([
     'ssl' => [
         'verify_peer' => FALSE,
         'verify_peer_name' => FALSE,
         'allow_self_signed'=> TRUE
     ]
 ]);
 $pdf->setHttpContext($contxt);
 
  $file_name = 'Invoice-'.$row["order_no"].'.pdf';
  $pdf->loadHtml(utf8_decode($output));
  $pdf->render();
  $pdf->stream($file_name, array("Attachment" => false));

**Comment by KristianI** [comment]
You have to ask yourself, is the PDF package (that runs on the backend) able to access the image on the URL when calling from the _backend_. (I know it sounds stupid obvious).

I was running this from inside a docker container. The image I was trying to fetch was using the URL specified in the APP_URL configuration, that worked from the outside world, as that domain was mapped in my /etc/hosts file on my development machine.

The hostname was not mapped inside the container though.

Temporarily hardcoding the domain in the image URL to "localhost" confirmed, that it indeed was the case.

In my case updating the /etc/hosts _inside_ the docker container solved it.

Are you using custom port numbers for your docker containers, you have another problem.

**Comment by jecfarolan360** [comment]
> public_path('path/to/image.png')
Hello u use that as src like this <img src="public_path('path/to/image.png')" alt="Image">

**Comment by munchy5132** [comment]
> I think it doesn't work when you customize options in any way.
> 
> `laravel-dompdf` defines a set of default options in `config/dompdf.php`. Whenever you customize these options either through `setOptions` method or a custom `dompdf.php` config file, all the defaults are ignored. Most likely some of the defaults are responsible for proper handling of images.
> 
> If this is true, then the issue can be solved by changing the behavior of the library to append-merge new options to the defaults.

For me this worked

**Comment by jhonatasgaragnani** [comment]
Pessoal Solucionei o problema em Laravel passando a url assim: <img  width="205" height="115" src="{{ env('APP_URL') }}/logo/logo.png"/>

**Comment by jhonatasgaragnani** [comment]
Pessoal, Solucionei o problema passando a url da imagem assim no Laravel:  "{{ env('APP_URL') }}/logo/logo.png"

**Comment by gutoholiveira** [comment]
Hello guys. for me this code works:

IN CONTROLLER:
```
public function report2()
    {
        $html = view('your_view');
        $options = new Options();
        $options->set('isRemoteEnabled', true);
        $options->set('chroot', realpath(base_path()));
        $options->set('enable_font_subsetting', false);
        $options->set('pdf_backend', 'CPDF');
        $options->set('default_media_type', 'screen');
        $dompdf = new Dompdf($options);
        $dompdf->loadHtml($html);
        $dompdf->render();
        $this->setEncryption($dompdf);
        $dompdf->stream('name_file');
    }

    public function setEncryption($dompdf)
    {
        $dompdf->get_canvas()->get_cpdf()->setEncryption('userpass', 'ownerpass', array('print'));
    }
```

IN VIEW TEMPLATE:
`...
<img src="{{ public_path('images/logo.png') }}">
...`

**Comment by janitzed** [comment]
Worked for me by setting the: chroot.

$options->set('chroot', '/var/www/html/project/');

$html = $this->renderView('Pdf/template.html.twig', [
    'image_path' => '/var/www/html/project/_files/Images/image.jpg', // absolute path !
]);

**Comment by NexampleGitHub** [comment]
Just Replace ( dompdf\src\Image\Cache.php ) From dompdf 0.8.5 To All New Version Dompdf !

dompdf 0.8.5 : https://github.com/dompdf/dompdf/releases/tag/v0.8.5

you can see here : https://youtu.be/bM3y5TY-7_k

**Comment by williamzh721** [comment]
Yo estoy intentando  con el siguiente código, pero siempre me sale el error de 
Image not found or type unknown 


<?php
require_once("pdf2/autoload.inc.php");
ob_start();
include(dirname('__FILE__').'/gen_certificacionpdf.php');
use Dompdf\Dompdf;
use Dompdf\Options;
$dompdf = new Dompdf();
$options = new Options();
$options->setIsRemoteEnabled(true);
$dompdf = new Dompdf($options);
		$html = ob_get_clean();
		$dompdf->loadHtml($html);
		$dompdf->output();
		$dompdf->setPaper('letter', 'portrait');
		$dompdf->render();
		$dompdf->stream("Certificacion_contrato");
 ?>

**Comment by aleruide** [comment]
Yo tengo el mismo problema. Antes no me fallaba y desde que tuve que actualizar la versión de php me falla. He cambiado a varias versiones superiores a la que tenía al principio y me sigue fallando. He añadido el código de $Options y sigue igual. Todas las posibilidades que habéis comentado y sigo sin encontrar la solución al problema

**Comment by RayhanYulanda** [comment]
I'm running on SSL in local it doesn't work and give me this error "Image not found or type unknown" but when i tried to turn off the SSL in local it works perfectly!
It run as well in server by the way

**Comment by danielbehrendt** [comment]
I've got the same problem and all the above mentioned solutions didn't work. The problem seems to be that my images may contain query strings (when trying to embed signed images from S3). My current workaround is to make these images public and don't sign them.

**Comment by JenryUMG** [comment]
This work for me.

<img src="data:image/png;base64,{{ base64_encode(file_get_contents(public_path('img/example.png'))) }}">

Reference link:
https://github.com/barryvdh/laravel-dompdf/issues/761

**Comment by Dlogon** [comment]
> I used @josesotomayor suggest.
> I created a custom class with the method that gets the base64.
> 
> `<?php
> namespace App\Custom;
> 
> class Archivos
> {
> public static function imagenABase64($ruta_relativa_al_public)
> {
> $path = $ruta_relativa_al_public;
> $type = pathinfo($path, PATHINFO_EXTENSION);
> $data = \File::get($path);
> 
> ```
> 	$base64 = "";
> 	if ($type == "svg") {
> 		$base64 = "data:image/svg+xml;base64,".base64_encode($data);
> 	} else {
> 		$base64 = "data:image/". $type .";base64,".base64_encode($data);
> 	}
> 	return $base64;
> }
> ```
> 
> }`
> 
> Then in the view i did this.
> 
> ` @php use App\Custom\Archivos; @endphp <img src="{{Archivos::imagenABase64('assets/img/logo_empresa_contrato.jpg')}}" width="200px" >`

Thanks, works for me too

**Comment by Nexample-G** [comment]
Real and Working solution
https://github.com/Nexample-G/Image-not-found-or-type-unknown-dompdf-

**Comment by vsalguero** [comment]
> What solved it for me was using `public_path('path/to/image.png')`.

Excelent! this option solved my problem 👏👏

**Comment by ARCHI207** [comment]
> Enabling remote by setting options helped me fix this. ... $html = '![](https://camo.githubusercontent.com/8b183973a6fe1110ab1b922f3c11ac46627f3dd3436fa4a096a76836e179decf/687474703a2f2f7777772e646f6d61696e2e636f6d2f706174682f746f2f696d6167652f696d6167652e706e67)'; $options = new Options(); **$options->setIsRemoteEnabled(true); $dompdf = new Dompdf($options);** $dompdf->loadHtml($html); $dompdf->output(); ...

Thank you.. this worked for me.

**Comment by mubahood** [comment]
if you are using laravel, consider excluding public folder in .htacccess from folders that laravel control. do it like this  

`# Exclude directory from rewriting
RewriteRule ^(public/) - [L]`

**Comment by SynysterGrowly** [comment]
I use {{URL::to('/storage/'.$data)}} for dinamic image by user

**Comment by jagp-afimex** [comment]
Hello, the next works for me:

1. Put your image inside the storage/app/public folder.
2. Get your image using the get method from the Storage's facade.
`use Illuminate\Support\Facades\Storage;`
`$image = Storage::get("public/image.png");`

3. Covert it to base64.
`$img_to_base64 = base64_encode($image);`

4. Use it in your HTML code.
`<img src="data:image/png;base64, {{ $img_to_base64  }}"> `

**Comment by simplywebinc** [comment]
> Solution: Convert to base 64 the image:
> 
> Example:
> 
> <'img' src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUA AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO 9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Example" />

For those who are like me and had no idea what base64 was, it's a file format.  I found a simple png to base64 converter here https://onlinepngtools.com/convert-png-to-base64 and then just copy the output and replace the following section with the new output

"data:image/png;base64, PASTE OUPUT HERE"

**Comment by gtresnandika** [comment]
Hi..Im facing the same problems..my solution is to know where is your image
mine, using laravel 7 having upload form and placed on storage/app/uploads/..../image.png
so, for me, im using
{{storage_path('app/upload/image.png')}}

**Comment by harinderratton** [comment]
> {{ public_path('path/to/image.png') }}

It worked like a charm,
Remember it will only work after when pdf is downloaded

**Comment by Jeffersonjcl** [comment]
Guys, I had this problem after uploading the system to the Hostinger server, where the report was normal showing the image but the server does not show the image, has anyone had this problem? How did you solve it?

**Comment by felixpenrose** [comment]
I've just figured this out ⬆️ 
I can simply replace my image urls to equal `https://dompdftest-internal/my-image.jpg` instead of `https://dompdftest.local` which is where my web browser points.

Just to add clarity this is my dockers apache container

```yml
  webserver:
    env_file: .env
    platform: ${WEB_PLATFORM}
    container_name: ${PROJECT_NAME}-webserver
    image: httpd:2.4-alpine
    restart: 'no'
    depends_on:
      - app
    tty: true
    expose:
      - 80
    volumes:
      - ${PROJECT_ROOT}:/var/www
      - ./docker/apache/default.conf:/usr/local/apache2/conf/httpd.conf
      - ./docker/apache/custom-config.conf:/usr/local/apache2/conf/extra/custom-config.conf
    networks:
      default:
        aliases:
          # use this hostname when sending requests to this container
          # from other containers within the same network.
          - ${PROJECT_NAME}-web-internal
```

**Comment by SameeraPrasantha** [comment]
> Enabling remote by setting options helped me fix this. ... $html = '![](https://camo.githubusercontent.com/8b183973a6fe1110ab1b922f3c11ac46627f3dd3436fa4a096a76836e179decf/687474703a2f2f7777772e646f6d61696e2e636f6d2f706174682f746f2f696d6167652f696d6167652e706e67)'; $options = new Options(); **$options->setIsRemoteEnabled(true); $dompdf = new Dompdf($options);** $dompdf->loadHtml($html); $dompdf->output(); ...



> After updating the version to `0.7.0`. The images (.png) are broken ("Image not found or type unknown").
> 
> ![imgnotfoumd](https://cloud.githubusercontent.com/assets/10472504/21879084/5f19f220-d8d1-11e6-81ac-968cebeb653b.png)

**Comment by SameeraPrasantha** [comment]
$options = new Options();
$options->setIsRemoteEnabled(true);
$dompdf = new Dompdf($options);

my solution and it's works.!

**Comment by txg** [comment]
Works for me: change file extension from .jpg to .jpeg

**Comment by GonzoTBA** [comment]
https://github.com/dompdf/dompdf

See "Limitations". There you have the solution (worked for me).

**Comment by GuilhermeSTrydeR** [comment]
> public_path

works for me! in my case, the directory doesn't exists! i just download a new DOMPDF and replace it!

**Comment by GuilhermeSTrydeR** [comment]
> Just Replace ( dompdf\src\Image\Cache.php ) From dompdf 0.8.5 To All New Version Dompdf !
> 
> dompdf 0.8.5 : https://github.com/dompdf/dompdf/releases/tag/v0.8.5
> 
> you can see here : https://youtu.be/bM3y5TY-7_k

works for me! in my case, the directory doesn't exists! i just download a new DOMPDF and replace it!

**Comment by muradbdinfo** [comment]
<img width="150" height="150" src="data:image/png;base64,{{ base64_encode(file_get_contents(public_path($Downloadapplicant->pictures))) }}" style="border-radius: 5px;" >

this settings solved my error..

![image](https://github.com/barryvdh/laravel-dompdf/assets/56858449/09807192-b6a4-4fa7-b13e-38b9b8e29ba1)

**Comment by muradbdinfo** [comment]
<img width="150" height="150" src="data:image/png;base64,{{ base64_encode(file_get_contents(public_path($Downloadapplicant->pictures))) }}" style="border-radius: 5px;"
