### ISSUE TITLE
composer updation problem

### ISSUE THREAD

**Issue by virusismine** [barryvdh/laravel-dompdf#305]
my composer //
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "laravel/framework": "4.2.*",
        "swiftmailer/swiftmailer": "5.x-dev",
        "aws/aws-sdk-php-laravel": "1.*"
        
    },
    "autoload": {
        "classmap": [
            "app/config/commands",
            "app/controllers",
            "app/models",
            "app/library",
            "app/database/migrations",
            "app/database/seeds",
            "app/tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "minimum-stability": "stable",
    "require-dev": {
		 "hybridauth/hybridauth": "^2.8",
         "way/generators": "^3.0"
		
				
	}

}

my cmd//
C:\xampp\htdocs\warranty>composer require barryvdh/laravel-dompdf
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "C:\ProgramData\ComposerSetup\bin\composer.phar self-update" to get the latest version.
Using version ^0.7.0 for barryvdh/laravel-dompdf
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for barryvdh/laravel-dompdf ^0.7.0 -> satisfiable by barryvdh/laravel-dompdf[v0.7.0].
    - Conclusion: remove laravel/framework v4.2.22
    - Conclusion: don't install laravel/framework v4.2.22
    - barryvdh/laravel-dompdf v0.7.0 requires illuminate/support 5.1.x|5.2.x|5.3.x -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - don't install illuminate/support v5.1.1|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.1.13|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.1.16|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.1.2|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.1.20|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.1.22|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.1.25|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.1.28|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.1.30|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.1.31|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.1.41|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.1.6|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.1.8|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.0|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.19|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.21|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.24|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.25|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.26|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.27|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.28|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.31|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.32|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.37|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.43|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.45|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.6|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.2.7|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.3.0|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.3.16|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.3.23|don't install laravel/framework v4.2.22
    - don't install illuminate/support v5.3.4|don't install laravel/framework v4.2.22
    - Installation request for laravel/framework (locked at v4.2.22, required as 4.2.*) -> satisfiable by laravel/framework[v4.2.22].

Installation failed, reverting ./composer.json to its original content.

**Comment by Bolandish** [comment]
Same problem here 

```
.... 
 - Conclusion: don't install laravel/framework v5.2.5
    - Conclusion: don't install laravel/framework v5.2.4
    - Conclusion: don't install laravel/framework v5.2.3
    - Conclusion: don't install laravel/framework v5.2.2
    - Conclusion: don't install laravel/framework v5.2.1
    - barryvdh/laravel-dompdf v0.5.2 requires illuminate/support 5.0.x|5.1.x -> satisfiable by laravel/framework[v5.1.45], illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - barryvdh/laravel-dompdf v0.5.1 requires illuminate/support 5.0.x|5.1.x -> satisfiable by laravel/framework[v5.1.45], illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - barryvdh/laravel-dompdf v0.5.2 requires illuminate/support 5.0.x|5.1.x -> satisfiable by laravel/framework[v5.1.45], illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8].
    - barryvdh/laravel-dompdf v0.5.0 requires illuminate/support 5.0.x -> satisfiable by illuminate/support[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4].
    - Can only install one of: laravel/framework[v5.2.0, v5.1.45].
....

**Comment by virusismine** [comment]
@any solution

**Comment by kjfdebruin** [comment]
The following works on a PHP 7.0 with Laravel 5.2 stack
`        "dompdf/dompdf": "0.8.2 as 0.6.1",
        "barryvdh/laravel-dompdf" : "0.8.2 as 0.6.1",`
