### ISSUE TITLE
Class 'Barryvdh\DomPDF\ServiceProvider' not found

### ISSUE THREAD

**Issue by virusismine** [barryvdh/laravel-dompdf#306]
C:\xampp\htdocs\warranty>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - barryvdh/laravel-dompdf v0.6.1 requires dompdf/dompdf 0.6.* -> satisfiable by dompdf/dompdf[v0.6.0, v0.6.1, v0.6.2] but these conflict with your requirements or minimum-stability.
    - barryvdh/laravel-dompdf v0.6.0 requires dompdf/dompdf 0.6.* -> satisfiable by dompdf/dompdf[v0.6.0, v0.6.1, v0.6.2] but these conflict with your requirements or minimum-stability.
    - Installation request for barryvdh/laravel-dompdf 0.6.* -> satisfiable by barryvdh/laravel-dompdf[v0.6.0, v0.6.1].

**Comment by karlpatrickespiritu** [comment]
Also having this issue on the when using the latest release.
