### ISSUE TITLE
Laravel 5.4 update

### ISSUE THREAD

**Issue by yathit** [barryvdh/laravel-dompdf#308]
Not able to update to 5.4 since

```
 - Installation request for barryvdh/laravel-dompdf (locked at v0.7.0, required as ^0.7.0) -> satisfiable by barryvdh/laravel-dompdf[v0.7.0].
```

**Comment by EdnaldoNeimeg** [comment]
+1

**Comment by barryvdh** [comment]
What is in your composer file?

**Comment by Umelev** [comment]
How I fixed this was that I removed my composer.lock file and deleted the whole vendor folder, then ran composer update. That fixed some conflict in my packages that was blocking the installation.

**Comment by netdelight** [comment]
I fixed the problem specifying to use the 0.7 version in the composer.json :
`"barryvdh/laravel-dompdf": "0.7.*"`

**Comment by ChamuSomu** [comment]
@netdelight  Thanks for the solution

**Comment by leandro-parice** [comment]
@netdelight Thanks
