### ISSUE TITLE
A non well formed numeric value encountered - Table.php line 460:

### ISSUE THREAD

**Issue by itzikbenh** [barryvdh/laravel-dompdf#309]
This happens only in production using PHP 7.1. On my local machine with PHP 7.0 it works fine.
Any ideas for the cause?
I'm using the latest version of this package.

**Comment by barryvdh** [comment]
Yeah see https://github.com/barryvdh/laravel-dompdf/issues/294 and https://github.com/dompdf/dompdf/issues/1272
Should be good when dompdf tags new version.
Or you can try

**Comment by barryvdh** [comment]
Or you can try to install dompdf `0.7.x@dev`

**Comment by itzikbenh** [comment]
Thank you :)

**Comment by mpixelz** [comment]
hi,
im trying to use dompdf/dompdf on develop branch as they have created new tags for php 7.1
when i do ``composer require dompdf/dompdf`` it works fine.. but when i do ``composer require dompdf/dompdf dev-master``
i get:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: phenx/php-svg-lib[v0.2, 0.1].
    - Can only install one of: phenx/php-svg-lib[v0.2, 0.1].
    - Can only install one of: phenx/php-svg-lib[v0.2, 0.1].
    - dompdf/dompdf dev-master requires phenx/php-svg-lib 0.2.* -> satisfiable by phenx/php-svg-lib[v0.2].
    - Installation request for dompdf/dompdf dev-master -> satisfiable by dompdf/dompdf[dev-master].
    - Installation request for phenx/php-svg-lib (locked at 0.1) -> satisfiable by phenx/php-svg-lib[0.1].


Installation failed, reverting ./composer.json to its original content.
```
