### ISSUE TITLE
thead table issue in writing pdf

### ISSUE THREAD

**Issue by mubashirsiddique** [barryvdh/laravel-dompdf#311]
There is an issue of thead table position in generating pdf. In html string, I have 
`<html>        
            <head>
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
                <link type="text/css" media="all" rel="stylesheet" href="C:/xampp/htdocs/snipe-it/public/assets/css/bootstrap.min.css">
                <link type="text/css" media="all" rel="stylesheet" href="C:/xampp/htdocs/snipe-it/public/assets/css/bootstrap-table.css">
                <style type="text/css">
                    thead:before, thead:after { display: none; } tbody:before, tbody:after { display: none; }
                    .header{
                        height: 30px;
                        position: fixed;
                        width: 100%;
                        top:0;
                    }
                    .content{
                        margin-top: 30px;
                        height: 100%;
                        width: 100%;
                    }
                    .footer{
                        height: 20px;
                        position: fixed;
                        bottom: 0;
                        width: 100%;
                    }
                </style>
            </head>
            <body>
                    <table class="table table-nobordered">
                        
                                

                                <div class="content">
                                <table class="table table-bordered table-striped style="margin-top: 30px">
                                    <thead>
                                        <tr>Analysis: Category</tr>
                                        
                                            <col>
                                            <col>
                                            <colgroup span="4"></colgroup>
                                            <colgroup span="4"></colgroup>
                                            
                                            <tr> 
                                                
                                                <th data-sortable="true" data-field="id" data-visible="true" scope="col">'.  trans("general.id")  .'</th>
                                                <th data-sortable="true" data-field="name" data-visible="true" scope="col">'.  trans("general.category")  .'</th>

                                                <th data-sortable="false" colspan="4" scope="colgroup" style="border: 1px; text-align: center;">'.  trans("admin/depreciations/table.cost")  .'</th>
                                                <th data-sortable="false" colspan="4" scope="colgroup" style="border: 1px; text-align: center;">'.  trans("admin/depreciations/table.acc_depreciation")  .'</th>

                                                <th data-sortable="false" data-field="nbv" data-searchable="true" scope="col">'.  trans("general.net_book_value")  .'</th>
                                            </tr>
                                            <tr>
                                                <td colspan="2"> </td>
                                                <th data-field="openingbalance" data-visible="true" scope="col">'.  trans("admin/depreciations/table.opening_balance")   .'</th>
                                                <th data-field="additions" data-visible="true" scope="col">'.   trans("admin/depreciations/table.additions")   .'</th>
                                                <th data-field="disposals" data-visible="true" scope="col">'.   trans("admin/depreciations/table.disposals")   .'</th>
                                                <th data-field="closingbalance" data-visible="true" scope="col">'.   trans("admin/depreciations/table.closing_balance")   .'</th>
                                                <th data-field="openingbalanced" data-visible="true" scope="col">'.   trans("admin/depreciations/table.opening_balance")   .'</th>
                                                <th data-field="additionsd" data-visible="true" scope="col">'.   trans("admin/depreciations/table.additions")   .'</th>
                                                <th data-field="disposalsd" data-visible="true" scope="col">'.   trans("admin/depreciations/table.disposals")   .'</th>
                                                <th data-field="closingbalanced" data-visible="true" scope="col">'.   trans("admin/depreciations/table.closing_balance")   .'</th>
                                                <td colspan="1"> </td>
                                            </tr>
                                        
                                    </thead>
                                    <tbody>
                                        '. $htmlStreamTable .'
                                    </tbody>
                                </table>
                                </div>

                                <div class="header" style="margin: 0px">
                                
                                    <div class="col-md-offset-0">
                                        <h3 class="text-center container-fluid col-md-12"> <u> Statutory Disclosure Report </u> </h3>
                                        <h4 class="text-center container-fluid col-md-12"> <u> All Assets </u> </h4>
                                    </div>
                                    <h5 > <label class="col-md-12" name="companypl">'. $company->name .'</label> </h5>
                                    <div class="row">
                                        <div class="col-md-6 nopadding">
                                            <label class="col-md-12 col-md-offset-0" name="depdaterange"> Year: ( '.$depdatefrom.' - '.$depdateto.' ) </label> 
                                        </div>
                                        <div class="col-md-6 nopadding">
                                            <div class="col-md-4 nopadding" name="themonth"> Period: ' .$policy.' </div>  
                                            <div class="col-md-4 col-md-offset-0" name="user"> '. Auth::user()->username .'-'. Auth::user()->first_name .' </div>
                                            <div class="col-md-4 col-md-offset-0" name="currentdate"> '.Date("Y-m-d").' - '.Date("H:i:s").' </div>
                                        </div>
                                    </div>     
                                    <hr size=4 noshadow>
                                
                                </div> 

                    <div class="footer"><span style="font-size: 8pt;">BBB Ltd: </span><span style="font-size: 8pt;">Postbank Tans</span><span style="font-size: 8pt;">,</span><span style="font-size: 8pt;"> IBAN: TA44 3335 BB88</span><span style="font-size: 8pt;"> </span><span style="font-size: 8pt;">7933 04</span><span style="font-size: 8pt;">,</span><span style="font-size: 8pt;"> BIC: DDEEEFF</span><span style="font-size: 8pt;">, </span><span style="font-size: 8pt;">KRN: Nuaga Duru</span>
                    </div>
                

                </table>
            </body>
            </html>`

The table inside content div  is miss placed or overlapped on header div and **we can not adjust its position**. I think there are logical issues in Dompdf in handling special elements.

it should be rendering as : 
![image](https://cloud.githubusercontent.com/assets/11260955/22427548/744ee738-e725-11e6-99c9-8fc8cff721b5.png)

**Comment by karandatwani92** [comment]
Same with me if i'm creating two tables, the second one overlaps

**Comment by ttomdewit** [comment]
It seems to me that both `thead` and `tbody` don't work. Removing them from my HTML and using `tr` and `th` instead seems to do the trick for me.

**Comment by KarlMacz** [comment]
What I did is I applied an `overflow: hidden;` style to the `table`. It worked perfectly for me.
