### ISSUE TITLE
A non-numeric value encountered" in PHP 7.1

### ISSUE THREAD

**Issue by keevitaja** [barryvdh/laravel-dompdf#313]
DomPdf fails on php7.1

There is a tmp fix. Any way to implement this with the laravel-dompdf package?

https://github.com/dompdf/dompdf/issues/1272

**Comment by barryvdh** [comment]
`composer require "dompdf/dompdf@0.7.x@dev" ` does that work?

**Comment by barryvdh** [comment]
I mean `composer require "dompdf/dompdf:0.7.x@dev`, that would get dev-develop and still fall within our constraints.

**Comment by keevitaja** [comment]
nope, it still fails

**Comment by barryvdh** [comment]
Explain fails

**Comment by keevitaja** [comment]
Sorry, it did not update deps. all use command

`composer require dompdf/dompdf:0.7.x@dev --update-with-dependencies`
