### ISSUE TITLE
vue component not saved in PDF

### ISSUE THREAD

**Issue by schel4ok** [barryvdh/laravel-dompdf#315]
I have calculator form with all html completely rendered in vue component

so in my blade I just have
```
@section('content')
<div class="row">
   <calculator></calculator>
</div><!-- row -->
@endsection
```

And when I try to save this to PDF I have just nothing.

```
	public function pdf()
	{
		$pdf = PDF::loadView('frontend.calculator');
		return $pdf->download('calculator.pdf');
	}
```

Is there any other solution to do what I want?

**Comment by barryvdh** [comment]
Yes laravel-snappy

**Comment by schel4ok** [comment]
why you maintain 2 projects dedicated to one purpose - make pdf?

**Comment by barryvdh** [comment]
Well, both are just wrapper for php PDF libraries. Different libraries have different purposes. Snappy uses wkhtmltopdf to render with WebKit and save as pdf, so more js/CSS support but heavier and more difficult to install. Dompdf is great for table based PDFs like invoices.

**Comment by jalawes** [comment]
Has anyone managed to find a solution for this?

I've tested and confirmed that I am able to load the CSS and JS from other Laravel views; however, I can't seem to get Snappy to play nice with custom Vue components.

**Comment by michug** [comment]
imposible to make snappy work, I cant believe how hard it is to print the html of my vue component, anyone had any luck?
im getting error 127
