### ISSUE TITLE
laravel-dompdf with angularjs

### ISSUE THREAD

**Issue by badrsh** [barryvdh/laravel-dompdf#316]
Hi ,
is there is anyway to convert html page working with angularjs to pdf ? ? 

what i mean is all the data it come from client side (backend to angularjs)

    $pdf = PDF::loadView('employeeDownloadCv');
    return $pdf->download('CV.pdf');

this is my code 

Any help please ? ? 
and is it possible to do some timeout in the current page before convert it to pdf 

 thanks

**Comment by barryvdh** [comment]
Try laravel-snappy
