### ISSUE TITLE
cannot pass variable to view

### ISSUE THREAD

**Issue by schel4ok** [barryvdh/laravel-dompdf#318]
in controller I have
```
$data = (array)$this->request['specification'];
$pdf = PDF::loadView('emails.calculators.specification', $data)->save('pdf/specification.pdf');
```

then in my emails/calculators/specification.blade.php I have 
```
<html><head></head>
<body>
{{ $data }}
</body>
</html>
```

and I got error
```
ErrorException in 797a29aaa57922fd27c0799cbf71e801ab3cfeef.php line 19: Undefined variable: data (View: D:\OpenServer\domains\site.new\resources\views\emails\calculators\specification.blade.php)
```

**Comment by schel4ok** [comment]
solved. in case someone needs help, because it is not obvious from tutorial
```
$pdf = PDF::loadView('emails.calculators.specification', array('data' => $data) )->save('pdf/specification.pdf');
```

**Comment by jonjie0317** [comment]
You can also use `compact()` to pass it to the view, like so

`$pdf = PDF::loadView('emails.calculators.specification', compact('data') )->save('pdf/specification.pdf');`

**Comment by jagdishabhiandroid** [comment]
how to show data in view then

**Comment by juniorsotto** [comment]
If you are using `return view()` to make proves, example:

`return view('pdf.tracking');`

You must be sure of include there your `$consolidated` variable. That was my error:

` $pdf = \PDF::loadView( 'pdf.tracking', [ 'consolidated' => $consolidated ] );`
`return view('pdf.tracking');` 

Returned: `Undefined variable: consolidated`

My solution: 

` $pdf = \PDF::loadView( 'pdf.tracking', [ 'consolidated' => $consolidated ] );`
`return view('pdf.tracking', [ 'consolidated' => $consolidated ] );`

- Regards!
