### ISSUE TITLE
Class 'Barryvdh\DomPDF\ServiceProvider' not found

### ISSUE THREAD

**Issue by karthikw3cert** [barryvdh/laravel-dompdf#319]
In Composer, i added the following Line and update.
"dompdf/dompdf": "v0.7.0" 

After Update i added the providers and aliases.

Barryvdh\DomPDF\ServiceProvider::class,

'PDF' => Barryvdh\DomPDF\Facade::class,

When i run the Application i got Following Error.

**FatalErrorException in ProviderRepository.php line 201: 

Class 'Barryvdh\DomPDF\ServiceProvider' not found**

My Configuration is 

Laravel 5.4, 
PHP 7.0

**Comment by barryvdh** [comment]
Make sure it's properly installed with composer and clear your caches/bootstrap files.

**Comment by karthikw3cert** [comment]
I Cleared Cache.. But Not Working...

**Comment by Kaukov** [comment]
Okay, first of all - did you issue `composer require barryvdh/laravel-dompdf` or did you just requier `dompdf/dompdf`? Because this package requires dompdf/dompdf, you don't need to pull it.

Second - when typing versions in packagist, don't add `v.0.7`, just type it as `0.7`.

Third - Are you really sure you pulled *THIS* package and not the standalone `dompdf/dompdf` one ?

**Comment by barryvdh** [comment]
`0.8.x` in this case (not just `0.8`)

**Comment by Kaukov** [comment]
@barryvdh indeed, but by looking at his post, I think he pulled the wrong project through composer, but let's wait to see what the response is :)

**Comment by ciscolybon** [comment]
Script php artisan optimize handling the post-update-cmd event returned with error code 1

**Comment by hhsadiq** [comment]
Having the same issue

```
In ProviderRepository.php line 208:
                                                     
  Class 'Barryvdh\DomPDF\ServiceProvider' not found  
                                                     
```

**Comment by jomalago3788** [comment]
Ejecute el comando composer require jenssegers / dompdf
me da este error:
[InvalidArgumentException]
  Could not find package jenssegers.

  Did you mean one of these?
      jenssegers/date
      jenssegers/agent
      jenssegers/proxy
      jenssegers/model
      jenssegers/blade


require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

**Comment by geraldmuvengei06** [comment]
`composer require barryvdh/laravel-dompdf`
This fixes!

**Comment by WandaPeruzzo2808** [comment]
genio esto arreglo todo! gracias
composer require barryvdh/laravel-dompdf

**Comment by SilvaEngComp** [comment]
I solved this problem habiliting "ITL" extension in php,ini
