### ISSUE TITLE
loadView Function Not Working

### ISSUE THREAD

**Issue by jatiyanon** [barryvdh/laravel-dompdf#321]
It seems that can not load with complex elements (HTML + CSS) in view blade file, it will infinite load and get apache error. but work correctly with a few elements.

**Comment by jatiyanon** [comment]
maybe because of DOMPDF not this wrapper .

**Comment by barryvdh** [comment]
Probably memory or timeout

**Comment by barryvdh** [comment]
You can try laravel-snappy for complex HTML
