### ISSUE TITLE
Static function call error

### ISSUE THREAD

**Issue by dilumdarshana** [barryvdh/laravel-dompdf#322]
When I tried to call the following function, I am getting the following error,

$pdf = PDF::loadView('customer.wishlist.printAndExport', $data);

Error:
Non-static method Barryvdh\DomPDF\PDF::loadView() should not be called statically, assuming $this from incompatible context

Any idea. How to avoid this ?

**Comment by barryvdh** [comment]
Use the facade, not the actual class.

**Comment by dilumdarshana** [comment]
Ok. thanks

**Comment by sabre96** [comment]
What? In the documention it says that this IS the facade: $pdf = PDF::loadView('pdf.invoice', $data);

Be more specific please?

**Comment by clonemeagain** [comment]
FYI: the "use the facade" is mentioned here https://github.com/barryvdh/laravel-dompdf/issues/158

Basically change the namespace to the facade, ie: 

```php
use Barryvdh\DomPDF\Facade as PDF;
```

Now, in your method, you can use your code as is.

**Comment by sunarto20** [comment]
i have code

<?php

namespace App\Http\Controllers;



use App\Item;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Barryvdh\DomPDF\Facade as PDF;



class ReportController extends Controller
{
    public function reportItemIndex()
    {
        return view('report.itemindex');
    }

    public function reportItem(Request $request)
    {


        $item = new Item;
        $item = $item->with(['unit', 'unit.room']);
        $date = $request->date;

        if ($date) {
            $range = explode('-', $date);
            $start = Carbon::parse($range[0]);
            $end = Carbon::parse($range[1])->endOfDay();

            $item = $item->whereBetween('created_at', [$start, $end]);
        }

        $item = $item->get();
        $view = view('tes', compact('item'))->render();
        $pdf = PDF::loadView('tes');
        return $pdf->download('invoice.pdf');

    }
}

this page not response when i try

**Comment by sunarto20** [comment]
<?php

namespace App\Http\Controllers;



use App\Item;
use Carbon\Carbon;
use Illuminate\Http\Request;
use \Barryvdh\DomPDF\Facade as PDF;



class ReportController extends Controller
{
    public function reportItemIndex()
    {
        return view('report.itemindex');
    }

    public function reportItem(Request $request)
    {


        $item = new Item;
        $item = $item->with(['unit', 'unit.room']);
        $date = $request->date;

        if ($date) {
            $range = explode('-', $date);
            $start = Carbon::parse($range[0]);
            $end = Carbon::parse($range[1])->endOfDay();

            $item = $item->whereBetween('created_at', [$start, $end]);
        }

        $item = $item->get();
        $view = view('tes', compact('item'))->render();
        $pdf = PDF::loadView('tes');
        return $pdf->download('invoice.pdf');

        // return $item;
        // return response()->json($item);
        // return view('tes', ['item' => $item]);
    }
}
