### ISSUE TITLE
How to setBasePath of DomPDF object

### ISSUE THREAD

**Issue by tomrlh** [barryvdh/laravel-dompdf#323]
Hi.
I know that some issues discussed this, but none of them have solved my problem.
I just want to set the base path for my pdf object, this way I can link css/img files without writing it directly to my pdf view. But I'm getting this error:

`Call to undefined method Barryvdh\DomPDF\PDF::setBasePath()`

I tried to use the methods names:
```
set_base_path()
setBasePath()
```
and some others.

My code is:

```
$pdf = PDF::loadView('layouts.pdfview');
pdf->setBasePath('path_here');
return $pdf->stream();
```

Viewing the class methods, it shows:

```
array:12 [▼
  0 => "__construct"
  1 => "getDomPDF"
  2 => "setPaper"
  3 => "setWarnings"
  4 => "loadHTML"
  5 => "loadFile"
  6 => "loadView"
  7 => "setOptions"
  8 => "output"
  9 => "save"
  10 => "download"
  11 => "stream"
]
```

But not the setBasePath method.

What am I forgetting?

Thanks in advance

**Comment by ArtbyArjan** [comment]
```
$pdf = PDF::loadView('layouts.pdfview');
pdf->setBasePath('path_here');
return $pdf->stream();
```

Aren't you missing a `$` on the second line, in front of pdf?

**Comment by vertisan** [comment]
`Call to undefined method Barryvdh\DomPDF\PDF::setBasePath()`

**Comment by kaiweispacebib** [comment]
use `setOption` or `setOptions`
