### ISSUE TITLE
How can i customize the page counter

### ISSUE THREAD

**Issue by soniclasser** [barryvdh/laravel-dompdf#324]
Hi, I'm trying to generate a pdf, but I need the page to start in a certain number.
                      
$ countContent = $ pdfContent-> getDomPDF () -> get_canvas () -> get_cpdf () -> numPages;
$ text = 'page: $countContent / {PAGE_COUNT}';
  $ font = Font_Metrics :: get_font ("helvetica", "bold");
  $ pdf-> page_text (36, 18, $ text, $ font, 9);

I hope a prompt reply

**Comment by SergioReis97** [comment]
Did you ever find a work around?
