### ISSUE TITLE
Styling not applied to PDF

### ISSUE THREAD

**Issue by leglinc** [barryvdh/laravel-dompdf#325]
Hello, we're using this with Laravel 5.2.

PDF creation is working beautifully, but styles aren't being applied.

Here's how we're creating the PDF: `PDF::loadHTML($contract)->save($user_directory."/".$pdf_file);`

```
$contract = '
		<style>
			.text-center {text-align: center;}
			.fw600 {font-weight: 600;}
			.mb8 {margin-bottom: 8px;}
			.default-list-upper-alpha {
				list-style-type: upper-alpha;
				list-style-position: inside;
				margin-left: 8px;
			}			
		</style>
			<h4 class="text-center fw600">
				WEBSITE DESIGN AGREEMENT
			</h3>
			<p>
		This Agreement is made and entered into by and between ' ...
```

In the generated PDF, our styling is being ignored. 

Any ideas?

**Comment by leglinc** [comment]
Solved: Needed to use `<style type="text/css" media="all">` rather than `<style>`.

**Comment by csnaomi** [comment]
Yes, That was the only reason. I got same issue and solved using type="text/css" media="all" in style tag. Thankyou.

**Comment by Wilsonabdiel** [comment]
I'm having an issue with this but not all of my styles are responding. Please Is there a specific way I need to write the css?
