### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by ankitsakhareliya** [barryvdh/laravel-dompdf#326]
**Hello Sir,**

I want to set font (https://fonts.googleapis.com/css?family=Cedarville+Cursive) to PDF but I can't able to do it.

When I try to set external font then it is return error, Please check attachment

So please let me know right process to set and use fonts

![code](https://cloud.githubusercontent.com/assets/18410358/23609930/7f66e972-0296-11e7-9c4b-6f120ac1d2dc.png)
![error](https://cloud.githubusercontent.com/assets/18410358/23609931/7f67f524-0296-11e7-8847-c7fed6b15bd6.png)

**Comment by wowthemes** [comment]
I am having the same issue when tried to stream the output.


![Failded to open the stream](https://lh5.googleusercontent.com/Smwzgoh_CNhsNQyGRs8A_6Xx1HhwLcBCRdwTltB30eE21xW8-FHPd-AOEg27Uk5LMn93HWcncKl0k1I=w1366-h662-rw)



Is there any fix for that.
