### ISSUE TITLE
Problem with Hungarian "ő" and "ű" letters

### ISSUE THREAD

**Issue by subi77** [barryvdh/laravel-dompdf#329]
**It is not actual more, because I see that the cause of it the underlying DOMPDF library and not the wrapper.**

I experienced problems with some Hungarian letters which are part of utf-8. If I create a PDF from this:
áéíöóőúűÁÉÍÖÓŐÚŰ

It will be this:
áéíöó?ú?ÁÉÍÖÓ?Ú?

The library doesn't handle the "ő", "ű", "Ő" and "Ű" letters correctly.

The only workaround that I found if I use this style in the templates:
```
<style>
    *{font-family: DejaVu Sans !important;}
</style
```
However DejaVu Sans font could be a great limitation.

**Comment by adam1920** [comment]
Works for me as well:
<style>
    *{font-family: DejaVu Sans !important;}
</style>
