### ISSUE TITLE
Load multiple views 

### ISSUE THREAD

**Issue by vinigarcia87** [barryvdh/laravel-dompdf#330]
Hi!

I'm loading an view to convert to PDF like this:

```
        $pdf = \PDF::loadView('isencoes.contrato', [
			'nome' => 'Vinicius Garcia',
			'img'  => storage_path('image003.png'),
		]);
        $pdf->save(storage_path('invoice.pdf'));
        return $pdf->download('invoice.pdf');
```

What I want to do is append a new view to the original view, something like this:

```
        $pdf = \PDF::loadView('isencoes.contrato', [
			'nome' => 'Vinicius Garcia',
			'img'  => storage_path('image003.png'),
		]);

        $pdf->appendView('isencoes.anothercontrato', ['nome' => 'Vinicius Garcia']);

        $pdf->save(storage_path('invoice.pdf'));
        return $pdf->download('invoice.pdf');
```

There is a way of doing it?

**Comment by barryvdh** [comment]
You can pass the entire HTML with `$pdf->loadHTML($view1 . $view2);`

**Comment by ArthurvS** [comment]
@barryvdh nice solution, used laravel view()->render(); to get the html of my views and chained them all together with your solution, works great! thanks for this solution and for the package

**Comment by LucasCardial** [comment]
@barryvdh thanks for solution! It's working great!

**Comment by LeonardoAlfonso88** [comment]
HI, I have a trouble because y make a string with the views, but the pdf only download the first page:

    protected function PDFcreator(Request $requestFilter)
    {
        $pagesCollect = collect([]);
        $idLogs = $this->consultFilterLogs($requestFilter);
        $logs = Log::whereIn('idLog', $idLogs)->get();
        $pdf = App::make('dompdf.wrapper');

        $logsPage = $logs->chunk(8);
        foreach ($logsPage as $page)
        {
            $viewLog = view('log.secondPage')
                            ->with('logs', $page);
            $viewLog = $viewLog->render();
            $pagesCollect->push($viewLog);  
        }

        $pagesCollect->each(function($item, $key) use(&$stringViews){
            $stringViews = $stringViews . $item;
        });

        $pdf->loadHTML($stringViews);  
        return $pdf->download("test.pdf");
    }

**Comment by murph133** [comment]
This is a very good, working solution. Thanks @barryvdh 

Please note that if you only see 1 page, you may need to change your settings in config/dompdf.

I changed:
- From:  "DOMPDF_DEFAULT_MEDIA_TYPE" => "screen",
- To: "DOMPDF_DEFAULT_MEDIA_TYPE" => "all",

**Comment by murph133** [comment]
Create a method that does the following:

$html = $start_html; // This will be your open <html> <head> and <body> # RENDER

foreach($items as $item){

$html .= $content; // RENDER view for the invoice content between the two body tags.

// At the end of each loop, except for the last one, add a <div class="page-break"></div>
// Add .page-break { page-break-after: always; } to the css in the $start_html section.
}

$html.= $end_html; // Your closing tags. E.g. </body></html>

$pdf = PDF::loadHTML($html);
return $pdf->download('test.pdf');

----------

This will include all of them in one file.
It will also separate them onto separate pages, rather than all one continuous, ugly stream of content.

**Comment by joaoreis2017** [comment]
> You can pass the entire HTML with `$pdf->loadHTML($view1 . $view2);`

In my case i am doing something like this: 

![image](https://user-images.githubusercontent.com/33705106/141170311-3fa660ef-5067-4525-ab0b-1a383e7c7f62.png)

i wold like to make a pdf with different headers and footers.
Any solution?

**Comment by ramonribeiro96** [comment]
> > You can pass the entire HTML with `$pdf->loadHTML($view1 . $view2);`
> 
> In my case i am doing something like this:
> 
> ![image](https://github.com/assets/33705106/3fa660ef-5067-4525-ab0b-1a383e7c7f62)
> 
> i wold like to make a pdf based on different blades and with different headers and footers. Any solution?

some solution @joaoreis2017 ?

**Comment by joaoreis2017** [comment]
> 

yes, i've find a package called 'libmergepdf.' this worked for me
