### ISSUE TITLE
HTTP Error 500

### ISSUE THREAD

**Issue by danjswade** [barryvdh/laravel-dompdf#332]
I just wanted to test everything, so passing a simple view with no variables:

`public function pdf($invoice)
    {
        $pdf = PDF::loadView('pages.home');
        return $pdf->download('invoice.pdf');

    }`

However, when I go to the page, all I get is a 500 error. Any idea where I'm going wrong? I'm running laravel 5.1,

**Comment by wimurk** [comment]
I have the same issue with laravel 5.4, please fix this

**Comment by barryvdh** [comment]
Can you save the pdf? Can you load the view with `view('pages.home');` directly?

**Comment by danjswade** [comment]
It doesn't give you the chance to save the pdf, simply gives the 500 error. Yes, I can load the view just fine normally, but when I run:

`$pdf = PDF::loadView('pages.home');
  return $pdf->download('invoice.pdf');`

It gives the 500 error

**Comment by wimurk** [comment]
I somehow fixed it by removing the whole vendor folder and reinstall it with composer install

**Comment by danjswade** [comment]
Unfortunately, didn't help me, I'm still getting the same 500 error message.

**Comment by wimurk** [comment]
Well then your PDF is to large. 
Add ini_set('max_execution_time', 300); above your function

**Comment by danjswade** [comment]
Unfortunately, they hasn't worked either.

The view I'm passing is a basic file. Hardly any lines so if the PDF is too large then it certainly won't be able to copy with a normal document.

**Comment by NagarajRaju** [comment]
HTTP Error 500 due to ErrorException in Cpdf.php line 3855: Undefined index: for me.

**Comment by pietro-sanjines-coderoad-com** [comment]
I have the same problem, the pdf is to large and didn't charge tha page stays loading in white and suddenly stops

**Comment by avambro** [comment]
someone found some solution to this error ?

**Comment by heavyrick** [comment]
For me worked this way:

XisController.php
   
    $data = 'Data';
    $pdf = PDF::loadView('pdf.test', ['data' => $data]);
    return $pdf->download('teste.pdf');

pdf/test.blade.php

    <h1>RELATÓRIO PDF</h1>
    <p>{{$data}}</p>

**Comment by Luthfiansyah** [comment]
@heavyrick This works but is very long

**Comment by keiwerkgvr** [comment]
ini_set('max_execution_time', 300);
ini_set("memory_limit","512M");

this works for me

**Comment by ShekhSaifuddin007** [comment]
@keiwerkgvr Thanks Buddy It's Work for me also...

**Comment by AhmadRaid** [comment]
Hello Gays 
the error its shows for me although  I run this command 
![image](https://user-images.githubusercontent.com/52861533/151693305-3ebc109c-75e3-4927-852c-d201704b3f97.png)

**Comment by yuyenkan** [comment]
This happen when there is a compile error on your view file, try to remove all content and place every piece of them to track the issue and it could happen when using unsupported css like `white-space: pre-wrap`.

**Comment by TantelyLinux** [comment]
ini_set('max_execution_time', 300);
ini_set("memory_limit","512M");

This works for me
