### ISSUE TITLE
Class 'Font_Metrics' not found

### ISSUE THREAD

**Issue by maurocasas** [barryvdh/laravel-dompdf#333]
Hello!

I've been struggling to get this fixed, but I cannot seem to find a way on how-to.
This is actually running on a staging server, so I don't know what's the difference locally

Currently running on Homestead mirroring the servers's specs.

`
[2017-03-29 19:24:34] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Font_Metrics' not found in /home/vagrant/Code/projectdox/vendor/dompdf/dompdf/src/PhpEvaluator.php(55) : eval()'d code:3
Stack trace:
#0 /home/vagrant/Code/projectdox/vendor/dompdf/dompdf/src/PhpEvaluator.php(55): eval()
#1 /home/vagrant/Code/projectdox/vendor/dompdf/dompdf/src/PhpEvaluator.php(63): Dompdf\PhpEvaluator->evaluate('\n\t\t\t\tif ( isset...')
#2 /home/vagrant/Code/projectdox/vendor/dompdf/dompdf/src/Renderer.php(293): Dompdf\PhpEvaluator->render(Object(Dompdf\FrameDecorator\NullFrameDecorator))
#3 /home/vagrant/Code/projectdox/vendor/dompdf/dompdf/src/Renderer.php(138): Dompdf\Renderer->_render_frame('php', Object(Dompdf\FrameDecorator\NullFrameDecorator))
#4 /home/vagrant/Code/projectdox/vendor/dompdf/dompdf/src/Renderer.php(194): Dompdf\Renderer->render(Object(Dompdf\FrameDecorator\NullFrameDecorator))
#5 /home/vagrant/Code/projectdox/vendor/dompdf/dompdf/src/Renderer.php(194): Dompdf\Renderer->render(Object(Dompdf\FrameDecorator\Block))
#6 /home/vagrant/Code/projectdox/vendor/dompdf/dompdf/src/FrameReflower/Page.php(148): Dompdf\Renderer->render(Object(Dompdf\FrameDecorator\Block))
#7 /home/vagrant/Code/projectdox/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(893): Dompdf\FrameReflower\Page->reflow(NULL)
#8 /home/vagrant/Code/projectdox/vendor/dompdf/dompdf/src/Dompdf.php(831): Dompdf\FrameDecorator\AbstractFrameDecorator->reflow()
#9 /home/vagrant/Code/projectdox/vendor/barryvdh/laravel-dompdf/src/PDF.php(200): Dompdf\Dompdf->render()
#10 /home/vagrant/Code/projectdox/vendor/barryvdh/laravel-dompdf/src/PDF.php(146): Barryvdh\DomPDF\PDF->render()
#11 /home/vagrant/Code/projectdox/app/Document_Version.php(42): Barryvdh\DomPDF\PDF->output()
#12 /home/vagrant/Code/projectdox/app/Transaction.php(103): CompliDocs\Document_Version->generatePdf(Object(CompliDocs\Transaction), '1_IN-1674124999...', false)
#13 /home/vagrant/Code/projectdox/app/Http/Controllers/Platform/Provider/API.php(360): CompliDocs\Transaction->generatePdf()
#14 [internal function]: CompliDocs\Http\Controllers\Platform\Provider\API->post_multiprint_documents(Object(Illuminate\Http\Request))
#15 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#16 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('post_multiprint...', Array)
#17 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(CompliDocs\Http\Controllers\Platform\Provider\API), 'post_multiprint...')
#18 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#19 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Routing/Router.php(559): Illuminate\Routing\Route->run()
#20 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /home/vagrant/Code/projectdox/app/Http/Controllers/Platform/Provider/API.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(131): CompliDocs\Http\Controllers\Platform\Provider\API->CompliDocs\Http\Controllers\Platform\Provider\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#23 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Routing/Router.php(561): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#26 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Routing/Router.php(520): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#27 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Routing/Router.php(498): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#28 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(174): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#29 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#30 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#50 /home/vagrant/Code/projectdox/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#51 /home/vagrant/Code/projectdox/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#52 {main}  
`

Thanks a lot in advance for any tips/help.

**Comment by maurocasas** [comment]
Anyone? This is still happening

**Comment by davorpeic** [comment]
I just got this issue when updated to v0.8.0. 

I had in my view 
`$font = Font_Metrics::get_font("arial", "normal");` I moved that in my controller like this `PDF::setOptions(['dpi' => 150, 'defaultFont' => 'arial']);` and that fixed issue.

Also you can check this issue in dompdf repo: https://github.com/dompdf/dompdf/issues/1054

dp
