### ISSUE TITLE
Trying To Install DomPDF withour composer

### ISSUE THREAD

**Issue by AliBakhshi** [barryvdh/laravel-dompdf#335]
hi ,
i am Trying To Install DomPDF without composer , I Copied dompdf Folder To vendor folder (barryvdh/laravel-dompdf)

i copied 
'PDF' => Barryvdh\DomPDF\Facade::class,
and 
Barryvdh\DomPDF\ServiceProvider::class,
to config/app.php

and i copied this lines at end of composer autoload classmap

 'Barryvdh\\DomPDF\\Facade' => $vendorDir . '/barryvdh/laravel-dompdf/src/Facade.php',
    'Barryvdh\\DomPDF\\ServiceProvider' => $vendorDir . '/barryvdh/laravel-dompdf/src/ServiceProvider.php',

but when i using dompdf : 

namespace App\Http\Controllers;
use PDF;

class ExportController extends Controller
{
    public function pdf(){
        $pdf = PDF::loadView('pdf');
        return $pdf->download('invoice.pdf');
    }
}

i got this error : 

FatalThrowableError in ServiceProvider.php line 57: Class 'Barryvdh\DomPDF\PDF' not found

i cant use composer for now , what is my problem ! tnx

**Comment by barryvdh** [comment]
> i cant use composer for now
That is your problem.

**Comment by AliBakhshi** [comment]
but i am using a shared host , so i cant do composer job manually ?

**Comment by barryvdh** [comment]
Not sure. If you're on shared host, install composer dependencies on your local server and upload it all.
