### ISSUE TITLE
config/dompdf.php not used?

### ISSUE THREAD

**Issue by fabiancz** [barryvdh/laravel-dompdf#336]
Hello,

I'm trying to set paper size to A4.

It works, when I use it in controller like:
```
$pdf = PDF::loadView('files.some-pdf', [
            'data' => $data,
        ])->setPaper('a4', 'portrait');
```

But it would be nice to have paper configuration in one place. So I published dompdf.php to my config/, but nothin changed.

Also I tried to add:
```
$this->app->bind('dompdf', function() {
            $options = $this->app->make('dompdf.options');
            $dompdf = new \Dompdf\Dompdf($options);
            $dompdf->setBasePath(realpath(base_path('public')));
            $dompdf->setPaper('a4', 'portrait');

            return $dompdf;
});
```
to my AppServiceProvider.php, but generated PDFs are still in letter papersize.

When I dump $this->paper in vendor/barryvdh/laravel-dompdf/src/PDF.php in render() method, there is always null.

Can you please help me, what I'm doing wrong?

Thanks

**Comment by kohlerdominik** [comment]
I have the same issue. Although the config is loaded correctly (it’s show in dump on PDF->config->dompdf), it’s not used.
Are we doing something wrong or is it a bug?

**Comment by parabolart** [comment]
Same issue. It picks up on 'show_warnings' => true but not the rest of the configurations. Bug?

**Comment by audetcameron** [comment]
It looks like the package is looking on config.app['keynane'].       So having a file in config/dompdf.php does nothing.

The package would need to change this
```
    protected function mergeConfigFrom($path, $key)
    {
        $config = $this->app['config']->get($key, []);
        $this->app['config']->set($key, array_merge(require $path, $config));
    }
```
to use the config('dompdf.mykey')   helper

or you can copy the config keys into your config.app  file
