### ISSUE TITLE
Convert specific element to pdf

### ISSUE THREAD

**Issue by sabre96** [barryvdh/laravel-dompdf#337]
So in the docs it's only explained how to hardcode some HTML into the pdf. But how do I convert an element from the page i'm in right now? I have a view where there is certain data of a selected candidate, so I have to convert the source page not the view.

I have no idea how to use this for that. Anyone any ideas?

Thanks.

**Comment by iAlek** [comment]
You could try and create a view partial for the specific element you're trying to convert to pdf.

This way, you can still display the same element(s) in your main view(s) and have it avialable for it's individual export through another route/controller method. You'd be passing the same variables/queries to this partial view as you would the main one.
