### ISSUE TITLE
Release for Laravel 5.4

### ISSUE THREAD

**Issue by tokoiwesley** [barryvdh/laravel-dompdf#341]
I am getting this error when upgrading to laravel 5.4. Any fix out there?
![image](https://cloud.githubusercontent.com/assets/4052790/25146352/3fb65b7a-247c-11e7-8198-ec22aecd943b.png)

**Comment by barryvdh** [comment]
Probably you require dompdf directly?

**Comment by Umelev** [comment]
Cant require with composer:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - dompdf/dompdf v0.8.0 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - dompdf/dompdf v0.8.0 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - barryvdh/laravel-dompdf v0.8.0 requires dompdf/dompdf ^0.8 -> satisfiable by dompdf/dompdf[v0.8.0].
    - Installation request for barryvdh/laravel-dompdf ^0.8.0 -> satisfiable by barryvdh/laravel-dompdf[v0.8.0].

**Comment by Umelev** [comment]
Not working in 5.4 for me either:

FatalThrowableError in PDFHelper.php line 15:
Class 'PDF' not found

or with Facade, I get similar error..

I have the Service Provider and Facade set up in config app.php

Barryvdh\DomPDF\ServiceProvider::class,
'PDF' => Barryvdh\DomPDF\Facade::class,

So, what can I do to make Laravel recognize these packages?

**Comment by dweingart** [comment]
@Umelev did you include the following line at the top of the file in which you wanted to use the Facade?

`use Barryvdh\DomPDF\Facade as PDF;`

FWIW I am using the package successfully for rendering a fairly basic HTML page in Laravel 5.4.

**Comment by hakuno** [comment]
I do even use on my Lumen 5.4 with no problem :open_mouth: 

`$pdf = app('dompdf.wrapper');`
`$pdf->loadView($view, $model);`

Maybe you need a fresh installation.

**Comment by bbcreation** [comment]
I have the same problem, in addition php artisan vendor: publish does not put a configuration file.

**Comment by EnesCakir** [comment]
If you are using `yajra/laravel-datatables-oracle` package, it requires `dompdf 0.7`, but `laravel-dompdf` needs `dompdf 8.0`.
Probably you are upgrading from Laravel 5.3 to 5.4 , so your `yajra/laravel-datatables-oracle` package is version `6.x`. Just make it version `7.x` for Laravel 5.4. It fixs the issue with `dompdf` and upgrades it to `0.8`

**Comment by tokoiwesley** [comment]
Thank you @EnesCakir. Your solution works. 
I was using ```yajra/laravel-datatables-oracle``` in my project (Laravel 5.3) but figured out later - after upgrading to Laravel 5.4 - that it's application won't be necessary anymore due to a specific use case that emerged in the project. So I got rid of the package.
However it's important to note that this particular fix works for anyone using both ```yajra/laravel-datatables-oracle``` and ```barryvdh/laravel-dompdf``` packages and upgrading from Laravel 5.3 to 5.4

**Comment by kangyasin** [comment]
hello you can use this

```
"barryvdh/laravel-dompdf": "^0.8.0",
"dompdf/dompdf": "0.8.0 as 0.6.2"
```

work 100% in laravel version 5.6 maybe same in 5.4

**Comment by Prezi2907** [comment]
> hello you can use this
> 
> ```
> "barryvdh/laravel-dompdf": "^0.8.0",
> "dompdf/dompdf": "0.8.0 as 0.6.2"
> ```
> work 100% in laravel version 5.6 maybe same in 5.4

5.4 working

**Comment by andela-tolotin** [comment]
For migration to Laravel 5.4
>>>
"barryvdh/laravel-dompdf": "0.8.0 as 0.7.0",
 "dompdf/dompdf": "0.8.0 as 0.7.0",
works for me

**Comment by novitalia28** [comment]
Thank you @kangyasin , it's works for me!

**Comment by porloscerros** [comment]
Hi, I had this same issue to install the package on Laravel 5.4 (but php 7.2) today, and I could do it with composer require like this:

`composer require barryvdh/laravel-dompdf:0.8.2` 

All this dependencies were installed successfully too:

> sabberworm/php-css-parser (8.3.0)     
> phenx/php-svg-lib (v0.3.3)  
> phenx/php-font-lib (0.5.1)        
> dompdf/dompdf (v0.8.3)  
> barryvdh/laravel-dompdf (v0.8.2)

Just to provide another alternative to the proposal by kangyasin.
source: https://laracasts.com/discuss/channels/laravel/barryvdhlaravel-dompdf-not-installing-in-my-project
