### ISSUE TITLE
Non-numeric value

### ISSUE THREAD

**Issue by arjenduinhouwer** [barryvdh/laravel-dompdf#343]
I've read the issues on updating to v0.8.0 to resolve the conflict with PHP 7.1.x, but i'm still getting errors, what would be best way to proceed? 

```

ErrorException in SurfaceCpdf.php line 380:
A non-numeric value encountered

```

PHP 7.1.4
composer.json:
... 
"barryvdh/laravel-dompdf": "~0.8.0"
...

**Comment by misidore** [comment]
I have the same problem -- PHP 7.1.1

ErrorExecption in TableCell.php line 104:
A non-numeric value encountered

**Comment by Tagliatti** [comment]
Me too.

**Comment by barryvdh** [comment]
Needs to be fixed upstream

**Comment by Tagliatti** [comment]
composer require dompdf/dompdf:0.7.x@dev --update-with-dependencies work for me.

**Comment by rawrkats** [comment]
Can't use 0.7x dompdf with barryvdh 0.8.0

any other solutions?

getting non-numeric value as well.
