### ISSUE TITLE
how to print image with laravel-dompdf

### ISSUE THREAD

**Issue by Padmore51** [barryvdh/laravel-dompdf#344]
I get the message "image not found or type unkown" when i print an image to pdf using laravel.
Can you show a sample code of how to print an image to pdf.
this is my code:
`$html .='  <tr><td rowspan="5"><img src="http://localhost:8000/uploads/yanUMHcK4UqBp2Wg8EZ4fr87N.jpg"></td>></tr>';
`

**Comment by pablfr** [comment]
You can not use paths like this http://localhost:8000/

Use the real patch of your file :

`$html .=' <tr><td rowspan="5"><img src="/var/www/......./real_paths/uploads/yanUMHcK4UqBp2Wg8EZ4fr87N.jpg"></td>></tr>';`

**Comment by Krisnasw** [comment]
Use your real url

**Comment by aamsur** [comment]
This is works for me.

`$html .=' <tr><td rowspan="5"><img src="{{ public_path() }}/uploads/yanUMHcK4UqBp2Wg8EZ4fr87N.jpg"></td>></tr>';`

use public_path();

**Comment by HimakarPV** [comment]
Use asset, it solve your problem.

Ex:
<img src="{{asset('images/user.png')}}" alt="Logo" height="75px">

**Comment by Padmore51** [comment]
Thanks a lot to all those who contributed. I was able to solve it by using asset. This worked for me
`<img src="{{asset('images/user.png')}}" alt="Logo" height="75px">`
thanks @HimakarPV  and all

**Comment by HimakarPV** [comment]
Glad to help you @Padmore51 welcome..

**Comment by thibaultvanc** [comment]
I solved it after changed to this:
<img src="{{ base_path() }}/location/to/image/image.png" />

**Comment by thibaultvanc** [comment]
I solved it after changed to this:
`<img src="{{ base_path() }}/location/to/image/image.png" />`

**Comment by yoedusvanyh** [comment]
I solved with public_path + image path

**Comment by lorisleiva** [comment]
`asset` didn't work for me, this did:

```html
<img src="{{ public_path('my/image.png') }}">
```

**Comment by radzzii** [comment]
@barryvdh hallo sir, sorry to disturb you.
i used to use laravel below 5.7, everything works fine. but this one time, i use Laravel 5.7, and somehow it cant load the image.

ive tried to ways:
- first, using asset_path: 
error mesage: file_put_contents(): Filename cannot be empty
- second, using public_path:
error message: unlink(.png): No such file or directory

- third, i remove the unlink statement in Cpdf.php file, line 4948.
it works, but it shows no color.

thanks :D.

**Comment by alyjee** [comment]
Same problem like above:
PDF generation fails if I use URL {{ asset('image/path') }} for images in PDF, but it works fine while using absolute path to the image.

**Comment by grodrigo** [comment]
Just a note: I had to do
        $options = new Dompdf\Options();
        $options->set('isRemoteEnabled', TRUE);//https://github.com/dompdf/dompdf/wiki/Usage#sethttpcontext
        $dompdf = new Dompdf\Dompdf($options);
and to put public path to the image in the server, but in my local I had to put $_SERVER["DOCUMENT_ROOT"] to see it. Who knows.. it just work.

**Comment by Gajanan1992** [comment]
use .jpg instead of .png image...it works for me
{{public_path('/images/icons/logo.jpg')}}

**Comment by keemsanty27** [comment]
> use .jpg instead of .png image...it works for me
> {{public_path('/images/icons/logo.jpg')}}

Can't get this to work, even though my image is in public/image/theimageishere.jpg

**Comment by sharia-design** [comment]
Not working any of:
public_path
asset
base_path

shhiiit

**Comment by a-nikookherad** [comment]
> Not working any of: public_path asset base_path
> 
> shhiiit

me too

**Comment by ShibliRaihan** [comment]
> Not working any of: public_path asset base_path
> 
> shhiiit

same bro

**Comment by ThePlatinum** [comment]
> base_path

Same too, had to go crude:
``` blade
@if ($invoice->company->logo)
<img src="{{base_path().'/storage/app/public/company_logo/'.$invoice->company->logo}}" height="100">
@endif
```

**Comment by churchillotiende** [comment]
this worked for me  <img src="{{ public_path($saved_print_logo) }}" alt="Logo" class="logo">

**Comment by dheerajdch** [comment]
i am not getting the images in the pdf who's uploaded my s3 buckets, is there any solutions,

i am generating the pdf with lots of icon with png image and others,
but when i am try to generate the pdf i am not getting those images.

**Comment by mariocosttaa** [comment]
If not working, using full path of system folder, you need to check if **extension GD**, is active. This extension provides functionality for handling graphics directly from PHP scripts. It supports the PNG, JPEG, XPM formats as well as FreeType/ttf fonts.

for activation just need to edit php.ini and uncomment ;extension gd
