### ISSUE TITLE
Using font-face - unpack(): Type n: not enough input, need 2, have 0

### ISSUE THREAD

**Issue by maj0rr** [barryvdh/laravel-dompdf#345]
Hey I got a problem including a font like:

```
@font-face {
        font-family: 'myfont';
        src: url("assets/fonts/my-font.TTF") format("truetype");
        font-weight: normal;
        font-style: normal;
}
```
and then
```
h1{
        font-size: 18px;
        font-family: "myfont", "Helvetica", "Arial", sans-serif;
}
```
I get the error 
`unpack(): Type n: not enough input, need 2, have 0`

Maybe it's related to this one here:
[https://github.com/dompdf/dompdf/issues/1412](https://github.com/dompdf/dompdf/issues/1412)

Im also using php 7 with the newest laravel.

Any idea about this?

Thanks

**Comment by VivekShingala** [comment]
Hey, how did you fix it?

**Comment by mvavrina** [comment]
In storage you will find dompdf_font_family_cache.php file, where is listed every font youre using.  I ran npm install and using font were added/registred.
