### ISSUE TITLE
ErrorException in Cpdf.php line 3855: Undefined index:

### ISSUE THREAD

**Issue by NagarajRaju** [barryvdh/laravel-dompdf#346]
Getting current font issue at Cpdf file at line number 3855.

**Comment by willlaw** [comment]
I'm getting this issue as well. Did you figure out the fix?

**Comment by SuchittraHimakar** [comment]
I have the same issue on digital ocean server

**Comment by HimakarPV** [comment]
@NagarajRaju  @willlaw  by deleting cache file from fonts folder fixed my issue. Make sure the directory path in dompdf.php file is correctly referenced.

**Comment by teodor-ionesco** [comment]
Hi ! 

I am experiencing the same issue. I have deleted the cache file from '/fonts' however now [this error](https://www.dropbox.com/s/2jzzidb27l6ejyp/1.png?dl=0) pops up. How can I regenerate fonts cache?

**Comment by fjkorjkeriopwgtjeruiog** [comment]
Any idea how fix this problem?
