### ISSUE TITLE
Problem with print "<" character

### ISSUE THREAD

**Issue by wello84** [barryvdh/laravel-dompdf#347]
Hi
How can i print in pdf the character "<" (minor) in a pdf, when i try to print it, by PDF::loadView ( the chars "<" are write satitaclly in view file, not pass by params), the pdf result don't print "<" and the following chars , i think because it redefines the character "<" as opening tag?
The view file has in head "<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />"

thank you Nicola

**Comment by pablfr** [comment]
Hi,
As you try to use `&lt;` ?

http://www.htmlhelp.com/reference/html40/entities/special.html

Pabl
