### ISSUE TITLE
PDF with a different between download and stream

### ISSUE THREAD

**Issue by pablfr** [barryvdh/laravel-dompdf#349]
Hi,

I have the possibility to download or send by mail an invoice

For download I use :
`$pdf = PDF::loadView(
            'invoices',
            $data
        );
return $pdf->download('invoice.pdf');`

For send by email, I use :
`$file = PDF::loadView('invoices', $data)->stream();
$message->attachData($file, $filename, [
                    'mime' => 'application/pdf',
                ]);`

The images work on the version donwload version, but does not work for sending

`image not found or type unknown`

Have you ever had the case?

Thank you !

**Comment by Vakil-Parth** [comment]
@pablfr did you find solution to this?

when I send stream() content to mail attachment then its mime type is octet-stream.

I want it as application/pdf

**Comment by erickcrus** [comment]
Same here

**Comment by joelstein** [comment]
This works for me in a Mailable class.

```php
public function attachments(): array
{
    return [
        Attachment::fromData(fn () => $this->pdf->output(), 'Some filename.pdf')->withMime('application/pdf'),
    ];
}
```
