### ISSUE TITLE
Why float not working?

### ISSUE THREAD

**Issue by moschel26** [barryvdh/laravel-dompdf#350]
I use Laravel 5.3

I use :

> "barryvdh/laravel-debugbar": "^2.3",
> 
> "barryvdh/laravel-dompdf": "^0.7.0",
> 

In myapp\config\dompdf.php, I set :

> "DOMPDF_ENABLE_CSS_FLOAT" => true,

In my html pdf, I try : 

    <!DOCTYPE html>
    <html>
    	<head>
    		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    		<title>Test</title>
    
    		<style type="text/css"> 
    
    			body {  
    			    font-family: "Arial", Helvetica, sans-serif !important;
    			    font-size: 9px;
    			    margin-bottom: 100px;
    			}
    			.container {
    			    background:#fff;
    			    overflow:auto;
    			}
    
    			.left {float:left;}
    			.right {float:right;}
    
    		</style>
    
    		
    	</head>
    	<body>
    		<div class="container">
    		    <div class="left">Float left</div>
    		    <div class="right">Float right</div>
    		</div>
    	</body>
    </html>

The float not working

How can I solve it?

**Update** :

The result of pdf is like this : 

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/CDH8Z.png

**Comment by 749** [comment]
This is a known dompdf issue, they are working on it.
