### ISSUE TITLE
How can I customize page number in laravel dompdf?

### ISSUE THREAD

**Issue by moschel26** [barryvdh/laravel-dompdf#352]
My controller is like this :

    public function listdata()
    {
        $pdf=PDF::loadView('print_tests.test_pdf');
        $pdf->setPaper('L', 'landscape');
        return $pdf->stream('test_pdf.pdf');
    }

My view is like this :

    <script type="text/php">
    
        if ( isset($pdf) ) {
            $x = 72;
            $y = 18;
            $text = "{PAGE_NUM} of {PAGE_COUNT}";
            $font = $fontMetrics->get_font("Arial", "bold");
            $size = 6;
            $color = array(0,0,0);
            $word_space = 0.0;  //  default
            $char_space = 0.0;  //  default
            $angle = 0.0;   //  default
            $pdf->page_text($x, $y, $text, $font, $size, $color, $word_space, $char_space, $angle);
        }
    
    </script>

I use this : 

> "barryvdh/laravel-dompdf": "^0.8.0",

When executed, the page number not display.

How can I solve it?

**Comment by barryvdh** [comment]
Did you enable the DOMPDF_ENABLE_PHP in the config?

**Comment by moschel26** [comment]
@barryvdh, Yes. "DOMPDF_ENABLE_PHP" => true, in myshop\config\dompdf.php

**Comment by mikevrind** [comment]
I have the same issue. PHP has been enabled via the configuration file but the pagenumber isn't showing up. The code I used is the same as @moschel26 posted.

**Comment by SergioReis97** [comment]
For anyone who stumbles into this, publish the dompdf config file, change DOMPDF_ENABLE_PHP as said above, run `php artisan config:cache` , and for example, in the view, inside the body tag ...
```
<body>
    <script type="text/php">
      if (isset($pdf)) {
        $font = $fontMetrics->getFont("Arial", "bold");
        $pdf->page_text(555, 740, "Page {PAGE_NUM}/{PAGE_COUNT}", $font, 7, array(0, 0, 0));
      }
    </script>
...
```
change the numbers to desired X,Y ofcourse

**Comment by Swamy-yadav** [comment]
What is $pdf in the script tag.
