### ISSUE TITLE
How to make converted process faster

### ISSUE THREAD

**Issue by muhammadbima** [barryvdh/laravel-dompdf#355]
hi, i'd like to ask how to make converted process faster ?
it take too much time until download alert.

![pdftime](https://cloud.githubusercontent.com/assets/20469572/26231827/e826d408-3c7b-11e7-84bb-e73187842a59.png)

my source code : 
` public function convert(){`
`$data = ModelName->function();`
`$pdf = App::make('dompdf.wraper');`
`$pdf->loadView('myview.blade.php', compact('data'));`
`return $pdf->stream();`
`}`

does my code is wrong or something??
help me pls.

thanks

**Comment by mikevrind** [comment]
DomPDF is slow with large documents, https://github.com/dompdf/dompdf#limitations-known-issues

**Comment by guiimarques18** [comment]
How you solve this problem?

**Comment by mikevrind** [comment]
I don't think there is a solution for the performance issue with large documents. You could use a background proces (queue or cronjob for example) to render a PDF. This way a user doesn't have to wait (look at a loading screen) for the PDF to be rendered and he/she can still browse the website or application while a background proces renders the PDF.
