### ISSUE TITLE
The package is not working for ajax request.

### ISSUE THREAD

**Issue by gullocean** [barryvdh/laravel-dompdf#357]
I love this package, but it's not working on my side.
Actually I have been using the AngularJs for front-end and Laravel for back-end..
I have posted the html data with ajax request, and then got it in back-end..
        $pdf = PDF::loadHTML('<h1>test</h1>');
        return $pdf->download('test.pdf');

So this is not working for ajax request?

**Comment by zaw-hlaing-bwar** [comment]
facing the same problem here,
goes to success response but doesn't downloading

**Comment by mariusedwin** [comment]
i have a same problem here, but i change it to form with post method.. and it works!

**Comment by barryvdh** [comment]
You cannot trigger a download for an Ajax request indeed. (Limitation of ajax requests itself). I would use a POST request or open the download link in a new tab.
