### ISSUE TITLE
Tempnam behavior on PHP upgrade

### ISSUE THREAD

**Issue by hakuno** [barryvdh/laravel-dompdf#358]
My PDF isn't loading after I upgraded to PHP 7.1 because of this:

> tempnam(): file created in the system's temporary directory

Is it related to DOMPDF, all right?

I found something that explains:
https://bugs.php.net/bug.php?id=69489

The `upload_tmp_dir` directive isn't enough to handle that. I see no effect yet.

**Comment by hakuno** [comment]
Currently I downgraded to PHP 7. I can't keep on production environment.

**Comment by hakuno** [comment]
upload_tmp_dir

**Comment by chaibialaa** [comment]
why this is closed ?

**Comment by libasoles** [comment]
This is happening to me also. Any clue?

**Comment by 4bd3ll4z1z** [comment]
what's the solution?

**Comment by hakuno** [comment]
First off, it is needed that `upload_tmp_dir` points to some folder with write permission. It's like the application cache folders you may be working on.

Also I had other problem in the past based on this [issue](https://github.com/dompdf/dompdf/issues/1494#issuecomment-330537376) with my Laravel/Lumen application.

The workaround was:

```
$pdf = app('dompdf');
$pdf->loadHtml(preg_replace('/>\s+</', '><', view($visao, $dados)->render()));
$pdf->setPaper('A4');
$pdf->render();
$pdf->stream();
```

I don't remember if it is related to the original trouble,  but if you go to the thread, the people say it is fixed.

Ps. Currently my applications runs on PHP 7.2 with no problem.

C/C @chaibialaa @libasoles @4bd3ll4z1z

**Comment by 4bd3ll4z1z** [comment]
thank you

**Comment by 4bd3ll4z1z** [comment]
@abiodunsulaiman694 that worked perfectly, thank you!
