### ISSUE TITLE
Undefined index: N in lib/class.pdf.php:2119

### ISSUE THREAD

**Issue by davidchubbs** [barryvdh/laravel-dompdf#36]
When trying to generate a PDF, I get the following error:

exception 'ErrorException' with message 'Undefined index: N' in MY_REPO_PATH/vendor/dompdf/dompdf/lib/class.pdf.php:2119
Stack trace:
#0 MY_REPO_PATH/vendor/dompdf/dompdf/lib/class.pdf.php(2119): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', 'MY_REPO_PATH...', 2119, Array)
#1 MY_REPO_PATH/vendor/dompdf/dompdf/lib/class.pdf.php(2196): Cpdf->openFont('MY_REPO_PATH...')
#2 MY_REPO_PATH/vendor/dompdf/dompdf/include/cpdf_adapter.cls.php(722): Cpdf->selectFont('MY_REPO_PATH...')
#3 MY_REPO_PATH/vendor/dompdf/dompdf/include/font_metrics.cls.php(105): CPDF_Adapter->get_text_width('??^ADMINS::1,??', 'MY_REPO_PATH...', 12, 0, 0)
#4 MY_REPO_PATH/vendor/dompdf/dompdf/include/text_frame_reflower.cls.php(376) : runtime-created function(1): Font_Metrics::get_text_width('??^ADMINS::1,??', 'MY_REPO_PATH...', 12, 0, 0)
#5 .... and so on ...

We've attempted this on multiple machines with different environments and got the same error. As you can see, the PDF does use a custom font, which is done via @font-face. I thought it was interesting though that the error came from an undefined index in lib/class.pdf.php

Any help would be much appreciated!

**Comment by abdulaziz100** [comment]
"error":"Undefined index: \/home\/bdprojapoti\/public_html\/application\/vendor\/dompdf\/dompdf\\lib\\fonts\\Times-Bold","file":"\/home\/bdprojapoti\/public_html\/application\/vendor\/dompdf\/dompdf\/src\/Renderer\/Text.php","line":97
