### ISSUE TITLE
I can't use thai language.

### ISSUE THREAD

**Issue by pcbimon** [barryvdh/laravel-dompdf#363]
I have add thai font
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    
    <style>
        @font-face {
            font-family: 'THSarabunNew';
            font-style: normal;
            font-weight: normal;
            src: url("file://{{ asset('fonts/THSarabunNew.ttf') }}") format('truetype');
        }
        body {
            font-family: "THSarabunNew";
        }
    </style>
```
<body>
    <table>
      <tr>
        <th>name</th>
        <th>email</th>
      </tr>
      @foreach ($customer as $c)
        <tr>
          <td>สวัสดี {{$c->name}}</td>
          <td>{{$c->email}}</td>
        </tr>
      @endforeach

    </table>
  </body>
```
Result in thai language "สวัสดี"=> "?????"

**Comment by patieru12** [comment]
Hi @pcbimon for me is generating Arabic characters I can't figure it out

**Comment by Cyrille37** [comment]
I found howto make Thaï working alone and mixed with Latin:
- Download a font at http://www.hawaii.edu/thai/thaifonts/, I use the Garuda one.
- Then use `load_font.php` but becarefull : https://github.com/dompdf/utils/issues/3
    - the file `dompdf_font_family_cache.php` is the important one !
- Then just use `font-family:Garuda;`

**Comment by SuchittraHimakar** [comment]
I am trying to use Kanit thai from google fonts. It didn't worked out for me. I am trying all the options suggesting by users here but no way for it.
Here is my code:
 /* kanit-regular - thai */
  @font-face {
    font-family: 'Kanit';
    font-style: normal;
    font-weight: 400;
    src: local('Kanit Regular'), local('Kanit-Regular'),
    url({{asset('storage/fonts/kanit-v2-thai-regular.ttf')}}) format('truetype'), /* Safari, Android, iOS */
  }
.thaifont{
    font-family: 'Kanit', sans-serif;
  }
In cache:
'kanit' => array(
    'normal' => $fontDir . '/191b5ff42fcf9b80af5b3791fc5c339c',
  ),

There is no error it shows but thai words are replaced by '????'
