### ISSUE TITLE
Dompdf or Snappy?

### ISSUE THREAD

**Issue by patrickpff** [barryvdh/laravel-dompdf#366]
Hi,

I'm trying to export some data into a PDF file, but it just takes to long with dompdf (it actually never finishes the construction of the file and never show an error). I think the problem is that the file would have something close to 150 pages of data, when I tried  with less data (that gives me something like 40 pages) it worked fine, but when I try to use all data it freezes and takes forever. I've search for a while and found some recommendations to use Snappy instead of Dompdf for large files - what will be a problem, because I have low access permissions, but I can make it work. 

My doubt is if Snappy really can generate such file, with 150 pages (or much more, because this is not the largest file I would need to generate).

**Comment by brunopulis** [comment]
Hey @patrickpff I have the same issue. But sadly I can't fix yet.

**Comment by patrickpff** [comment]
So, I can't figure out a way to use DomPDF with larger files and can't use Snappy because of my user permissions, so the partial solution I found was to generate a simple HTML page that could be printed on PDF or on the printer. It was not the perfect way, but it worked.
