### ISSUE TITLE
Not getting same design in PDF

### ISSUE THREAD

**Issue by Ashubgs90** [barryvdh/laravel-dompdf#369]
Hi,

I have created a blade file in Laravel using internal and inline CSS only. When I tries to make PDF of that PDF, Design is not same as blade.

[https://sc.wellcertified.com/projects/23355/scorecard/review](url)

[22295-reviewDetails (1).pdf](https://github.com/barryvdh/laravel-dompdf/files/1135109/22295-reviewDetails.1.pdf)

This is how I am making PDF to download 

`$pdf = \PDF::loadView('pdf.review', compact('reviewData', 'project'));`
`return $pdf->download($projectId. '-reviewDetails.pdf');`

Please help me on urgent basis. 
Thanks

**Comment by avambro** [comment]
can you do something for this issue ?  i'm in the same problem :(

**Comment by Ashubgs90** [comment]
@avambro Try https://github.com/barryvdh/laravel-snappy 
It resolved my issue
