### ISSUE TITLE
Page count and page number

### ISSUE THREAD

**Issue by wemersonjanuario** [barryvdh/laravel-dompdf#37]
How to access Page count and page number inside blade views?

**Comment by IuliaStefu** [comment]
Hi,
I couldn't either. 
I extended the service provider and the PDF class in my application and chose to overwrite the PDF's render method, so after $this->dompdf->render(); I added:

$canvas = $this->dompdf->get_canvas();
$canvas->page_text(5, 5, "Page {PAGE_NUM} of {PAGE_COUNT}", $this->config->get('dompdf.defines.DOMPDF_DEFAULT_FONT'), 8, array(0, 0, 0));  

This will display the text in the upper left corner. 
You can access $canvas->get_height() and $canvas->get_width() to control where the text will be displayed. 

Hope this helps.

**Comment by stathisg** [comment]
Just to add that there is also a way to do what @IuliaStefu suggests without extending the service provider (although you probably won't be able to access some internal variables in case you need to do something more complex). Instead of using the PDF facade in a controller, you can do something among the lines of:

```php
$pdf = App::make('dompdf');
$pdf->loadView('whatever', $data);
$pdf->output();
$dom_pdf = $pdf->getDomPDF();

$canvas = $dom_pdf ->get_canvas();
$canvas->page_text(0, 0, "Page {PAGE_NUM} of {PAGE_COUNT}", null, 10, array(0, 0, 0));

//then do whatever you want with $pdf
````

**Comment by helgator** [comment]
@IuliaStefu: How would you prevent the $canvas->page_text being printed on the first page but on all others? Thanks.

**Comment by ksdev-pl** [comment]
Another way to solve this problem:

* publish vendor files for this package: `php artisan vendor:publish`
* edit `/config/dompdf.php` and enable `DOMPDF_ENABLE_PHP`
* now you can add inline php code in your view (taken from https://code.google.com/p/dompdf/wiki/FAQ)
```php
<script type="text/php">
    if ( isset($pdf) ) {
        $font = Font_Metrics::get_font("helvetica", "bold");
        $pdf->page_text(72, 18, "Header: {PAGE_NUM} of {PAGE_COUNT}", $font, 6, array(0,0,0));
    }
</script>
```

You can write the rest of the code like earlier:
```php
$pdf = PDF::loadView('whatever', $data);
$pdf->save($filePath);
```

**Comment by alfhan** [comment]
@ksdev-pl 
where i must place 
<script type="text/php">
    if ( isset($pdf) ) {
        $font = Font_Metrics::get_font("helvetica", "bold");
        $pdf->page_text(72, 18, "Header: {PAGE_NUM} of {PAGE_COUNT}", $font, 6, array(0,0,0));
    }
</script>

**Comment by ksdev-pl** [comment]
@alfhan Inside the view file.

**Comment by helgator** [comment]
Has anyone figured out how to print the $canvas->page_text on all pages but not on the first page? Thanks.

**Comment by etmind** [comment]
Hello,
$pdf = App::make('dompdf');
$pdf->loadView('whatever', $data);
$pdf->output();
$dom_pdf = $pdf->getDomPDF();

$canvas = $dom_pdf ->get_canvas();
$canvas->page_text(0, 0, "Page {PAGE_NUM} of {PAGE_COUNT}", null, 10, array(0, 0, 0));
return $pdf->stream();

This returns me pdf with unreadable font

**Comment by larsbo** [comment]
the code example
```javascript
<script type="text/php">
    if ( isset($pdf) ) {
        $font = Font_Metrics::get_font("helvetica", "bold");
        $pdf->page_text(72, 18, "Header: {PAGE_NUM} of {PAGE_COUNT}", $font, 6, array(0,0,0));
    }
</script>
```
 doesn't work on laravel-dompdf 0.7.x.

I found a working solution for displaying the page number:
```javascript
<script type="text/php">
    if ( isset($pdf) ) {
        $font = $fontMetrics->getFont('helvetica', 'bold');
        $pdf->text(72, 18, "Header: $PAGE_NUM of $PAGE_COUNT", $font, 6);
    }
</script>
```
But the problem is that```$PAGE_NUM```and ```$PAGE_COUNT```are always the same on every page.

**Comment by danrichards** [comment]
### PHP / Laravel:

```
$pdf = app('dompdf.wrapper');
$pdf->getDomPDF()->set_option("enable_php", true);
$pdf->loadView('admin.work_orders.pdf', $data);
```

### Blade Template

```
<body>
<script type="text/php">
    if (isset($pdf)) {
        $x = 250;
        $y = 10;
        $text = "Page {PAGE_NUM} of {PAGE_COUNT}";
        $font = null;
        $size = 14;
        $color = array(255,0,0);
        $word_space = 0.0;  //  default
        $char_space = 0.0;  //  default
        $angle = 0.0;   //  default
        $pdf->page_text($x, $y, $text, $font, $size, $color, $word_space, $char_space, $angle);
    }
</script>
...
```

**Comment by Rah1x** [comment]
This is the worst way to generate page counts to be honest. 
Anyway, here are some additional notes:

1. The font colour is NOT (0-255) RGB here. its (0-1) RGB. So light gray is not (183, 183, 183), its (0.75, 0.75, 0.75).

2. To print on Footer use get_height method like this:
`$y = $pdf->get_height()-35`

3. instead of `Font_Metrics::get_font`, you need `$fontMetrics->get_font`

**Comment by Rah1x** [comment]
Still cant figure out how to skip first page when printing the footer. `$PAGE_NUM>1` has no effect in the blade layout

**Comment by PazkaL** [comment]
I was able to skip the pagenumber on the first page with the following code:

```
<script type="text/php">
    if (isset($pdf)) {
        $pdf->page_script('
             if ($PAGE_COUNT > 1) {
                 $font = $fontMetrics->getFont("Lato", "regular");
                 $pdf->page_text(522, 770, "Page {PAGE_NUM} / {PAGE_COUNT}", $font, 8, array(.5,.5,.5));
            }
        ');
   }
</script>
```

**Comment by alperyazgan** [comment]
In body tag;

  <script type="text/php">

  if (isset($pdf)) {
      $pdf->page_script('
        $font = $fontMetrics->get_font(\'DejaVu Sans, Arial, Helvetica, sans-serif\', \'normal\');
        $pageText = $PAGE_NUM . \' / \' . $PAGE_COUNT;
        $y = 770;
        $x = 290;
        $size = 7;
        $pdf->text($x, $y, $pageText, $font, $size);
      ');
  }

  </script>

works fine.

**Comment by helgator** [comment]
@alperyazgan: Thanks, but even after setting "DOMPDF_ENABLE_PHP" => true I get 
`Fatal error: Call to undefined method DOMPDF::page_script() in ...`
Any idea what I did forget to set? Thanks.

**Comment by alperyazgan** [comment]
You are using it in the body tag in blade view like I said, aren’t you ?

E.g. In view blade “sample.pdf.blade.php”

<!DOCTYPE html>
<html lang=“en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=11,chrome=1">
  <meta charset="UTF-8"/>

  <title>@lang('application.title')</title>
  <link href="{{ url('assets/css/pdf/nice.css') }}" rel="stylesheet">
</head>
<body>

<h1> Nice but Empty Page with Only Page Numbers</h1>

<h2>Look at the bottom </h2>

<div class="page-break"></div>

<div class="page-break"></div>

<script type="text/php">

  if (isset($pdf)) {
      $pdf->page_script('
        $font = $fontMetrics->get_font(\'DejaVu Sans, Arial,
Helvetica, sans-serif\', \'normal\');
        $pageText = $PAGE_NUM . \' / \' . $PAGE_COUNT;
        $y = 770;
        $x = 290;
        $size = 7;
        $pdf->text($x, $y, $pageText, $font, $size);
      ');
  }

</script>

</body>
</html>




*Alper YAZGAN*

On 28 June 2017 at 04:03:09 , helgator (notifications@github.com) wrote:

@alperyazgan <https://github.com/alperyazgan>: Thanks, but even after
setting "DOMPDF_ENABLE_PHP" => true I get
Fatal error: Call to undefined method DOMPDF::page_script() in ...
Any idea what I did forget to set? Thanks.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/barryvdh/laravel-dompdf/issues/37#issuecomment-311527596>,
or mute the thread

**Comment by MaximePinto** [comment]
> I was able to skip the pagenumber on the first page with the following code:
> 
> ```
> <script type="text/php">
>     if (isset($pdf)) {
>         $pdf->page_script('
>              if ($PAGE_COUNT > 1) {
>                  $font = $fontMetrics->getFont("Lato", "regular");
>                  $pdf->page_text(522, 770, "Page {PAGE_NUM} / {PAGE_COUNT}", $font, 8, array(.5,.5,.5));
>             }
>         ');
>    }
> </script>
> ```


`<script type="text/php">
                if (isset($pdf)) {
                    $pdf->page_script('
                        if($PAGE_COUNT > 1) {
                            $x = 480;
                            $y = 794;
                            $text = "{PAGE_NUM}/{PAGE_COUNT}";
                            {#$font = 'helvetica'#}
                            $size = 8;
                            $color = array(0,0,0);
                            $word_space = 0.0;  //  default;
                            $char_space = 0.0;  //  default;
                            $angle = 0.0;   //  default;
                            $pdf->page_text($x, $y, $text, $font = null, $size, $color, $word_space, $char_space, $angle);
                        }
                    ');
                }
            </script>`

it's ok for me ! thx a lot !

**Comment by MaximePinto** [comment]
to have a pagination on all pages except the first

> I was able to skip the pagenumber on the first page with the following code:
> 
> ```
> <script type="text/php">
>     if (isset($pdf)) {
>         $pdf->page_script('
>              if ($PAGE_COUNT > 1) {
>                  $font = $fontMetrics->getFont("Lato", "regular");
>                  $pdf->page_text(522, 770, "Page {PAGE_NUM} / {PAGE_COUNT}", $font, 8, array(.5,.5,.5));
>             }
>         ');
>    }
> </script>
> ```

thx for that https://github.com/barryvdh/laravel-dompdf/issues/37#issuecomment-307382120 , it's ok for me !!!

and below my code

```
         <script type="text/php">
                if (isset($pdf)) {
                    $pdf->page_script('
                        if($PAGE_COUNT > 1) {
                            $x = 480;
                            $y = 794;
                            $text = "{PAGE_NUM}/{PAGE_COUNT}";
                            {#$font = 'helvetica'#}
                            $size = 8;
                            $color = array(0,0,0);
                            $word_space = 0.0;  //  default;
                            $char_space = 0.0;  //  default;
                            $angle = 0.0;   //  default;
                            $pdf->page_text($x, $y, $text, $font = null, $size, $color, $word_space, $char_space, $angle);
                        }
                    ');
                }
         </script>
```

**Comment by FadelSylla** [comment]
g

**Comment by opanegro** [comment]
> ### PHP / Laravel:
> ```
> $pdf = app('dompdf.wrapper');
> $pdf->getDomPDF()->set_option("enable_php", true);
> $pdf->loadView('your.view.here', $data);
> ```
> 
> ### Blade Template
> ```
> <body>
> <script type="text/php">
>     if (isset($pdf)) {
>         $x = 250;
>         $y = 10;
>         $text = "Page {PAGE_NUM} of {PAGE_COUNT}";
>         $font = null;
>         $size = 14;
>         $color = array(255,0,0);
>         $word_space = 0.0;  //  default
>         $char_space = 0.0;  //  default
>         $angle = 0.0;   //  default
>         $pdf->page_text($x, $y, $text, $font, $size, $color, $word_space, $char_space, $angle);
>     }
> </script>
> ...
> ```

thanks. it work very well

**Comment by deulizealand** [comment]
can i get only page num and page count value ? or how can i set that value to the div for example ?

**Comment by abePdIta** [comment]
Improved version that take into account translation and text centering.

```
<script type="text/php">
    if (isset($pdf)) {
        $pdf->page_script('
            $text = __("Page :pageNum/:pageCount", ["pageNum" => $PAGE_NUM, "pageCount" => $PAGE_COUNT]);
            $font = null;
            $size = 9;
            $color = array(0,0,0);
            $word_space = 0.0;  //  default
            $char_space = 0.0;  //  default
            $angle = 0.0;   //  default

            // Compute text width to center correctly
            $textWidth = $fontMetrics->getTextWidth($text, $font, $size);

            $x = ($pdf->get_width() - $textWidth) / 2;
            $y = $pdf->get_height() - 35;

            $pdf->text($x, $y, $text, $font, $size, $color, $word_space, $char_space, $angle);
        '); // End of page_script
    }
</script>
```
**But**: if you only need $pageNum, [using CSS counter](https://github.com/dompdf/dompdf/issues/1254#issuecomment-238308953) is a way simpler approach!

**Comment by doftwerks-west-african** [comment]
> Just to add that there is also a way to do what @IuliaStefu suggests without extending the service provider (although you probably won't be able to access some internal variables in case you need to do something more complex). Instead of using the PDF facade in a controller, you can do something among the lines of:
> 
> ```
> $pdf = App::make('dompdf');
> $pdf->loadView('whatever', $data);
> $pdf->output();
> $dom_pdf = $pdf->getDomPDF();
> 
> $canvas = $dom_pdf ->get_canvas();
> $canvas->page_text(0, 0, "Page {PAGE_NUM} of {PAGE_COUNT}", null, 10, array(0, 0, 0));
> 
> //then do whatever you want with $pdf
> ```

Nice one. This works for me

**Comment by rodrigopeixoto-web** [comment]
> Hi, I couldn't either. I extended the service provider and the PDF class in my application and chose to overwrite the PDF's render method, so after $this->dompdf->render(); I added:
> 
> $canvas = $this->dompdf->get_canvas(); $canvas->page_text(5, 5, "Page {PAGE_NUM} of {PAGE_COUNT}", $this->config->get('dompdf.defines.DOMPDF_DEFAULT_FONT'), 8, array(0, 0, 0));
> 
> This will display the text in the upper left corner. You can access $canvas->get_height() and $canvas->get_width() to control where the text will be displayed.
> 
> Hope this helps.

Thanks a lot! You really save my day!

**Comment by becem-alt** [comment]
> Has anyone figured out how to print the $canvas->page_text on all pages but not on the first page? Thanks.

it just happened to me, the solution is to move the script tag to the end of the body tag

**Comment by colewan-design** [comment]
> How to access Page count and page number inside blade views?

<header>  Page {PAGE_NUM} of {PAGE_COUNT}</header>

**Comment by davejuanes** [comment]
> Hola, Yo tampoco pude. Extendí el proveedor de servicios y la clase de PDF en mi aplicación y elegí sobrescribir el método de renderizado del PDF, así que después de $this->dompdf->render(); agregué:
> 
> $lienzo = $> this->dompdf-get_canvas(); $canvas->page_text(5, 5, "Page {PAGE_NUM} of {PAGE_COUNT}", $this->config->get('dompdf.defines.DOMPDF_DEFAULT_FONT'), 8, array(0, 0, 0));
> 
> Esto mostrará el texto en la esquina superior izquierda. Puede acceder a $canvas->get_height() y $canvas->get_width() para controlar dónde se mostrará el texto.
> 
> Espero que esto ayude.

Thank you so much, the code works perfectly
