### ISSUE TITLE
Compatibility with Laravel 5.5

### ISSUE THREAD

**Issue by jbartoszek** [barryvdh/laravel-dompdf#372]
Hi!;)
Package not working with laravel 5.5 now. Do you have plans to update package illuminate/support  to version compatiblity with actualy laravel version? If yes, tell me when? One of my project can`t migrate to new laravel version.

Best regards
Jacek

**Comment by barryvdh** [comment]
Sure, submit a pr

**Comment by khaledelmahdi** [comment]
@barryvdh I've just submitted a PR for 5.5

**Comment by raphaelbeckmann** [comment]
When will this PR be merged?

**Comment by dinoluck** [comment]
5.5 still not compatible it seems.

- barryvdh/laravel-dompdf v0.7.1 requires illuminate/support 5.1.x|5.2.x|5.3.x|5.4.x -> satisfiable by laravel/framework[v5.4.36], illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - barryvdh/laravel-dompdf v0.7.1 requires illuminate/support 5.1.x|5.2.x|5.3.x|5.4.x -> satisfiable by laravel/framework[v5.4.36], illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].


Any info on this?

**Comment by barryvdh** [comment]
Yeah use 0.8.1

**Comment by dinoluck** [comment]
Managed to get it working but the CSS is really messed up, like all the text and images have this bright blue background and spacing is all wrong, margin overlaying etc...
