### ISSUE TITLE
This package always writes log.htm

### ISSUE THREAD

**Issue by mushketer888** [barryvdh/laravel-dompdf#375]
This package always writes log.htm in /tmp/log.htm to which I dont have access...on WEb server
I tried to change it with:
```
PDF::setOptions(['logOutputFile'=>storage_path('logs/pdf.log')]);
$pdf = PDF::loadView('pdf.invoice', ['data' => $data]);
        return $pdf->download('invoice' . $id . '.pdf');
```
But it doesnt work too.
Anyway...why generate this useless log file?

**Comment by mushketer888** [comment]
Tried Also
```
 PDF::setOptions(['logOutputFile'=>storage_path('logs/pdf.log'),'tempDir'=>storage_path('logs/')]);
```

**Comment by mushketer888** [comment]
Solved!
by adding this to dompdf.php config:

```php
        "DOMPDF_TEMP_DIR" => storage_path('logs/'),//I need this
        "DOMPDF_LOG_OUTPUT_FILE" => storage_path('logs/log.htm'),
```

**Comment by dannyklaren** [comment]
I had the same issue, managed to fix it by reading the comments above and combining them.
Using the following code in my controllers:

```php
$pdf = \PDF::setOptions([
            'logOutputFile' => storage_path('logs/log.htm'),
            'tempDir' => storage_path('logs/')
        ])
        ->loadView('orders.pdf.order', compact('order'));

return $pdf->stream('aanmeldformulier.pdf');
```

This way I did not have to modify any files in the vendor folder.

**Comment by Lotuashvili** [comment]
@mushketer888 Thank you! Adding `"DOMPDF_LOG_OUTPUT_FILE"` to config/dompdf.php did the trick!

**Comment by paugarcia** [comment]
Thank you! I solve the fix!!

**Comment by qodeanil** [comment]
i added 
  ```
      "DOMPDF_TEMP_DIR" => storage_path('logs/'),//I need this
        "DOMPDF_LOG_OUTPUT_FILE" => storage_path('logs/log.htm'),
```
in dompdf.php 

and also tried 

```
$pdf = \PDF::setOptions([
            'logOutputFile' => storage_path('logs/log.htm'),
            'tempDir' => storage_path('logs/')
        ])
```
        ->loadView('orders.pdf.order', compact('order'));

but i am getting blank screen instead of generating pdf. what might be the reason . hope to get your help

**Comment by tpformybh** [comment]
Just to update, if you look through the dompdf source, you can see that if the logOutputFile is set to null, it will bypass the code causing the error

**Comment by ezekel** [comment]
above solution doesn't work for me

` "barryvdh/laravel-dompdf": "^0.9.0",`

**Comment by ezekel** [comment]
#https://github.com/barryvdh/laravel-dompdf/issues/807

**Comment by Mande-RS** [comment]
Thank you guys, it fixed my problem:
        in config/dompdf.php

    "DOMPDF_TEMP_DIR" => storage_path('logs/'),//I need this
     "DOMPDF_LOG_OUTPUT_FILE" => storage_path('logs/log.htm'),

**Comment by jcgfm4u** [comment]
Thank you! Fixed
