### ISSUE TITLE
Disable log.htm by Default

### ISSUE THREAD

**Issue by mushketer888** [barryvdh/laravel-dompdf#376]
As I was writing in : https://github.com/barryvdh/laravel-dompdf/issues/375
Please disable /tmp/log.htm output in Releases.

1) No one uses this (OK... 95%)
2) It can mess things up with "Permission denied to /tmp" stuff on shared hostings etc

P.S.
I guess its dompdf's fault itself (such default settings). Don't know about that

**Comment by Lotuashvili** [comment]
+1
