### ISSUE TITLE
Embeded Javascript does not work

### ISSUE THREAD

**Issue by tempe-goreng** [barryvdh/laravel-dompdf#38]
Hi,

I am trying to open up print dialog box on my generated pdf once it gets streamed to the user. I found out that it is possible to do using the dompdf with the following command https://github.com/dompdf/dompdf/issues/713. I tried to do the same thing with this library, it renders the pdf, but the javascript does not kick in. I wonder if there's anything else that I need to do.

I have the enable javascript settings set to true on the dompdf_config.inc.php 

```
def("DOMPDF_ENABLE_JAVASCRIPT", true);
```

My controller just get the html using Laravel View::make

```
$pdf = App::make('dompdf');
$pdfPage = View::make('some_view');
$pdf->loadHTML($mailPdf);
return $pdf->stream('file.pdf');
```

and it does not work even if I use simple view 

```
<html>

<head>
  <title>Javascript test</title>
</head>

<body>
  <h1>PDF JS Test</h1>
  <p>This page will call the print dialog on load.</p>
  <script type="text/javascript">
  try {
    this.print();
  }
  </script>
</body>

</html>
```

Is there something I did wrong? or if there's some other settings that need to be enabled? Thank you in advance.

**Comment by aminemrabet** [comment]
To make it work, you need to use this JS bloc inside your PDF Blade : 

<script type="text/javascript">
            try {
                this.print();
            } catch (e) {
                window.onload = window.print;
            }
</script>

I hope it helps !

**Comment by bryanEcuador** [comment]
I am using the js block inside my view with blade but it still does not work as it should.

**Comment by jovelquinones04** [comment]
<script type="text/javascript"> try { this.print(); } catch (e) { window.onload = window.print; } </script>

this code work properly, but when I try to show an alert message it doesn't work at all.,

**Comment by ShekhSaifuddin007** [comment]
`<script type="text/javascript"> try { this.print(); } catch (e) { window.onload = window.print; } </script>`
this line go directly in print window but I have other script for showing total amount in words but this pdf generator totally skip those lines. What should I do..??

**Comment by rickyviz** [comment]
Same this not work
I also try use
<script type="text/javascript"> try { this.print(); } catch (e) { window.onload = window.print; } </script>
