### ISSUE TITLE
Donmpdf Error 3154 undefined index

### ISSUE THREAD

**Issue by rafaelg21** [barryvdh/laravel-dompdf#383]
Good morning greetings, I stop working. and throws me this error when running the PDF.
Laravel 5.4.

I had worked and from one moment to another gave me the following error isn make changes.

`

(1/1)                                         ErrorException                                                                          Undefined index:
--
in class.pdf.php (line 3154)
at HandleExceptions->handleError(8, 'Undefined index: ', 'C:\\xampp\\htdocs\\sisalmacen\\vendor\\dompdf\\dompdf\\lib\\class.pdf.php', 3154, array('size' => 9.0))in class.pdf.php (line 3154)
at Cpdf->getFontHeight(9.0)in CPDF.php (line 971)

`

**Mi composer.**

`
"require": {
        "php": ">=5.6.4",
        "barryvdh/laravel-dompdf": "^0.8.1",
        "doctrine/dbal": "2.5.1",
        "dompdf/dompdf": "~0.8.0",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "laravelcollective/html": "^5.4.0",
        "maatwebsite/excel": "~2.1.0",
        "yajra/laravel-datatables-oracle": "^7.5"
    },
`

**Comment by daswanihimanshu010** [comment]
any update on this. receive same error
