### ISSUE TITLE
 (1/1) ErrorException Non-static method Barryvdh\DomPDF\PDF::loadView() should not be called statically

### ISSUE THREAD

**Issue by shahidkarimi** [barryvdh/laravel-dompdf#386]
Laravel 5.4

```
   $report = XReport::findOrFail($id);

       $pdf = PDF::loadView('patient.report',['report'=>$report]);

       return $pdf->download('invoice.pdf');

```
(1/1) ErrorExceptionNon-static method Barryvdh\DomPDF\PDF::loadView() should not be called statically
--

How to fix this shit error?

**Comment by josephmtinangi** [comment]
This happens because you are namespacing the wrong PDF class.
You are namespacing Barryvdh\DomPDF\PDF and try to use this class as "Facade" which is wrong.

To solve your problem

Set namespace to the facade:

`use Barryvdh\DomPDF\Facade as PDF;`

**Comment by saulquiroz** [comment]
Thanks @josephmtinangi  !!!

**Comment by gebrail** [comment]
Thanks @josephmtinangi

**Comment by fendiseptiawan0709** [comment]
Thanks @josephmtinangi 
Simple but effective.

BTW, Should this issue set to be closed? This issue has been answered correctly.

**Comment by eflames** [comment]
> use Barryvdh\DomPDF\Facade as PDF;

Yes, this works for me. For some reason my IDE don't recognize Facade as sugestion when I typed the class xDDD.

**Comment by jtomek** [comment]
Put this on the frontpage somewhere, please.

**Comment by bakumn** [comment]
Yes, this works for me.  Thanks

**Comment by bakumn** [comment]
> This happens because you are namespacing the wrong PDF class.
> You are namespacing Barryvdh\DomPDF\PDF and try to use this class as "Facade" which is wrong.
> 
> To solve your problem
> 
> Set namespace to the facade:
> 
> `use Barryvdh\DomPDF\Facade as PDF;`
Yes, this works for me. Thanks

**Comment by ganeshnayanajith** [comment]
> This happens because you are namespacing the wrong PDF class.
> You are namespacing Barryvdh\DomPDF\PDF and try to use this class as "Facade" which is wrong.
> 
> To solve your problem
> 
> Set namespace to the facade:
> 
> `use Barryvdh\DomPDF\Facade as PDF;`

Thanks

**Comment by hagios2** [comment]
Thank it also worked for me

**Comment by jnsakuv** [comment]
Thanks, it also worked for me too

**Comment by lonnyrichard27** [comment]
This works for me as well but the downloaded pdf is not catching the value of the input tags. Any help with this?

**Comment by Dilshan97** [comment]
Thank you. It's worked for me

**Comment by hendisantika** [comment]
Thank you. It's worked for me

**Comment by roxshivamsingh** [comment]
> use Barryvdh\DomPDF\Facade as PDF;

Thanks

**Comment by zakir7dipu** [comment]
Maximum execution time of 60 seconds exceeded, why it comes?

**Comment by jPingua** [comment]
I tried the above solutions. It didn't work for me. Please help.

**Comment by wallacegc** [comment]
> use Barryvdh\DomPDF\Facade as PDF;

Thanks!

**Comment by StilinskiCyril** [comment]
Thanks. ur a life saver

**Comment by MarcGaumont** [comment]
Use PDF;
This also works.

**Comment by Abidhossain** [comment]
Thank you. It's worked for me.

**Comment by chuoke** [comment]
A terrible way

**Comment by maulanakurnia** [comment]
> use Barryvdh\DomPDF\Facade as PDF;

thank u sir

**Comment by Gilangjanuar** [comment]
no eror but no download anything file, can help?

**Comment by dcgitx** [comment]
> This happens because you are namespacing the wrong PDF class.
> You are namespacing Barryvdh\DomPDF\PDF and try to use this class as "Facade" which is wrong.
> 
> To solve your problem
> 
> Set namespace to the facade:
> 
> `use Barryvdh\DomPDF\Facade as PDF;`

GH docs need updating with this man, it's 2021!

**Comment by ajitirto** [comment]
Thanks

**Comment by MarcusAfolabi** [comment]
not working for me error : `Class "Barryvdh\DomPDF\Facade" not found`

**Comment by Petsane** [comment]
I get to part of the unlucky few who the solution is not working for, the class is now undefined

**Comment by Petsane** [comment]
@MarcusAfolabi  
I solved it by creating an instance of the object
$pdf = app('dompdf.wrapper');
and then modified my line to this
$pdf->loadView('patient.report', $data); instead of $pdf = PDF::loadView('patient.report', $data);
