### ISSUE TITLE
@font-face is not working and not throwing any error

### ISSUE THREAD

**Issue by HimakarPV** [barryvdh/laravel-dompdf#387]
Hi @GrahamCampbell , I am trying to use "Open Sans" and "Kanit" fonts using .ttf files but not working in the output.
I am using laravel 5.4.36 and laravel-dompdf 0.8.1 versions. Loading view file and saving it as pdf.

Here my code goes..

View:

```
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

  <style type="text/css">
  /* kanit-regular - thai */
  @font-face {
    font-family: 'Kanit';
    font-style: normal;
    font-weight: 400;
    src: local('Kanit Regular'), local('Kanit-Regular'),
    url({{asset('storage/fonts/kanit-v2-thai-regular.ttf')}}) format('truetype');
  }
  /* open-sans-regular - latin */
  @font-face {
    font-family: 'Open Sans';
    font-style: normal;
    font-weight: 400;
    src: local('Open Sans Regular'), local('OpenSans-Regular'),
    url({{asset('storage/fonts/open-sans-v14-latin-regular.ttf')}}) format('truetype');
  }

  body {
    font-family: 'Open Sans', sans-serif;
  }
  .thaifont{
    font-family: 'Kanit', sans-serif;
  }
</style>
```
dompdf_font_family_cache.php:
```
'kanit' => array(
    'normal' => $fontDir . '/191b5ff42fcf9b80af5b3791fc5c339c',
  ),
  'open sans' => array(
    'normal' => $fontDir . '/6a7b72534ada1051a2ede3971e907b19',
    'italic' => $fontDir . '/6f160846a52871435d29203950cdf32d',
  ),
```
Even trying to use like this by updating the variable in dompdf.php file:
`"DOMPDF_DEFAULT_FONT" => "open sans",`

No error is shown but unable to use required font. Thai words are appearing like "????".

I even tried using load_font.php instead of using @font-face as suggested by other users but no result.

**Comment by ThomasRalee** [comment]
Does anyone has any clue on how to solve this?

**Comment by inxilpro** [comment]
I got it working with:

```css
@font-face {
  font-family: 'Family';
  src: url({{ storage_path('fonts/font.ttf') }}) format('truetype');
}
```

**Comment by MarkMaldaba** [comment]
I can confirm that I've been having a similar problem and that it also appears to be fixed by using the storage_path() hack.  However, this is not a usable solution for us as the same CSS file is used for both the live site and the PDF generation code.

This used to work prior to 0.8, so presumably it should be relatively easy to track down what's changed with regards to font location.

**Comment by MarkMaldaba** [comment]
Actually - scratch that.  Adding the storage_path() hack completely broke my CSS, but it meant that a different fall-back font was being used instead.  This meant it looked like it had worked, but actually hadn't.

storage_path() seems to be a Laravel function - I guess it results in the full disk path being used, which may have some benefit but doesn't help in my case.  I tried hard-coding the full path and this didn't resolve the issue for me.

Please ignore my intervention!

**Comment by HimakarPV** [comment]
I understand your concern. Comment is welcomed.

**Comment by MarkMaldaba** [comment]
I don't know if my issue is related to yours or not, but I've just logged #1976 which describes my problem in a lot of detail.  It may or may not help with this ticket.
