### ISSUE TITLE
Call to undefined method DOMDocument::hasAttribute()

### ISSUE THREAD

**Issue by ghost** [barryvdh/laravel-dompdf#393]
Previously I managed to create a PDF without any issue.

But after I ran `composer update` and this issue.

May I know how to rectify this?

**Comment by usmanbarefoot** [comment]
Same here

**Comment by WeeHong** [comment]
@usmanbarefoot 

Try to remove all the `<script>` and `<link>` and try to convert it again.

Refer to my post here.
https://github.com/dompdf/dompdf/issues/1551

**Comment by fsyauqy** [comment]
fixed by removing in bootstrap.css

`
.custom-file-control:lang(en)::before {
  content: "Browse";
}
`

**Comment by jamesprices** [comment]
I was also able to work around this issue in UIKit by removing the lines 
`.uk-overlay-area:not(:empty):before {
  content: '';
  display: inline-block;
  height: 100%;
  vertical-align: middle;
}`

It didn't like the `:not(:empty):before` part.

**Comment by ozzi-** [comment]
Would be nice if the parser could handle this.
