### ISSUE TITLE
Class 'Barryvdh\DomPDF\ServiceProvider' not found

### ISSUE THREAD

**Issue by amrshakya** [barryvdh/laravel-dompdf#406]
I did install the package via composer and also did tried to register in config/app.php provider yet i get this error Class 'Barryvdh\DomPDF\ServiceProvider' not found. Also when i tried vendor:publish nothing was publish on config directory.

Can any one help me out with it?

**Comment by laymont** [comment]
I have a same problem

**Comment by besereiter** [comment]
me to
