### ISSUE TITLE
Not working when using css

### ISSUE THREAD

**Issue by Quadriphobs1** [barryvdh/laravel-dompdf#408]
So I have been using this package now but I got stuck today while using it to generate a particular pdf from a view but it keeps getting maximum execution time exceeded if I should include my css files such as bootstrap and my custom css but if I font do that it's always fast. how can I go by these?

**Comment by Skaaal** [comment]
I had to create a dedicated CSS for the PDF report. Probably parsing the CSS of Bootstrap is too much work for the included parsers ? Anyways, you probably want a very different layout than bootstrap in your PDF file.

**Comment by magarrent** [comment]
Yeah, same here. Removed bootstrap css and more libs and it works
