### ISSUE TITLE
Background Generating?

### ISSUE THREAD

**Issue by simondotwhite** [barryvdh/laravel-dompdf#41]
Hi,

I'm playing around with print large-ish views (20 items in an array) and it seems to take ages to generate the 20 page PDF. 

I ran tests with a 10 page/item and it's returning a file that's 6.8MB in size and takes about 30 seconds to generate. 

Is there a way that I can offload the PDF Generating into the background before sending    via email, or even a way to speed up the generating?

**Comment by Devamit2016** [comment]
processing and processed is done but pdf is not generated...
   $data=['amit']; 	
        $pdf = PDF::loadView('testpdf', $data);
        return $pdf->download('testpdf.pdf');
this is my code in handle function

**Comment by nappalm** [comment]
what is the solution in this problem?

**Comment by vadimwe** [comment]
Laravel Queue should make a trick.
Use save instead download function.

**Comment by AdriWild** [comment]
When I create more than 150 jobs to render and save PDF, it works, but after this 150 aprox. the pdfs are broken and unformatted.
