### ISSUE TITLE
Question on dompdf, absolute stylesheet url and docker

### ISSUE THREAD

**Issue by godbout** [barryvdh/laravel-dompdf#410]
I got a problem but I solved it, now I'm just trying to understand what is happening.

I usually refer to my stylesheet using the *asset* help from Laravel. It works well for all my pages, but not when I generate a PDF through dompdf. The absolute url sent back by *asset* is correct, and is accessible through the browser, but dompdf doesn't get it. I had to replace *asset* by *public_path*, which seems weird to me.

I'm using docker so I thought that maybe for whatever reason, dompdf can't get the site URL from within the container? Although I have setup the domains in the */etc/hosts/* file.

If anyone had the same issue and have an idea of why this is happening, I'll be interested in learning a bit more :)

Problem is solved. It's just pure curiosity. Thanks!

**Comment by iraklisg** [comment]
@godbout I faced a similar issue recently... it seems that, when running via docker,  `dompdf` requires to link the required stylesheet using a relative URL that points to the asset that exists into the container... I am still looking at it :stuck_out_tongue:

**Comment by godbout** [comment]
👍️

Yes, that's what it seems. No idea why though. Let me know if you find out!

**Comment by aghwotu** [comment]
Dompdf renders a blank page when used with Docker. I am using an internal CSS tag in the blade file
