### ISSUE TITLE
Undefined index: border_bottom_width

### ISSUE THREAD

**Issue by m-shehata** [barryvdh/laravel-dompdf#412]
**ErrorException thrown with message "Undefined index: border_bottom_width"**
Iam using Jimmy-JS/laravel-report-generator to generate pdf using laravel-dompdf
Stacktrace:
**68 ErrorException in C:\xampp\htdocs\n\pdf\vendor\dompdf\dompdf\src\Css\Style.php:1363
**67 Illuminate\Foundation\Bootstrap\HandleExceptions:handleError in C:\xampp\htdocs\n\pdf\vendor\dompdf\dompdf\src\Css\Style.php:1363
**66 Dompdf\Css\Style:get_border_bottom_width in C:\xampp\htdocs\n\pdf\vendor\dompdf\dompdf\src\FrameReflower\AbstractFrameReflower.php:142
**65 Dompdf\FrameReflower\AbstractFrameReflower:_collapse_margins in C:\xampp\htdocs\n\pdf\vendor\dompdf\dompdf\src\FrameReflower\Block.php:785
**64 Dompdf\FrameReflower\Block:reflow in C:\xampp\htdocs\n\pdf\vendor\dompdf\dompdf\src\FrameDecorator\AbstractFrameDecorator.php:894
**63 Dompdf\FrameDecorator\AbstractFrameDecorator:reflow in C:\xampp\htdocs\n\pdf\vendor\dompdf\dompdf\src\FrameReflower\Block.php:846
**62 Dompdf\FrameReflower\Block:reflow in C:\xampp\htdocs\n\pdf\vendor\dompdf\dompdf\src\FrameDecorator\AbstractFrameDecorator.php:894
**61 Dompdf\FrameDecorator\AbstractFrameDecorator:reflow in C:\xampp\htdocs\n\pdf\vendor\dompdf\dompdf\src\FrameReflower\Block.php:846
**60 Dompdf\FrameReflower\Block:reflow in C:\xampp\htdocs\n\pdf\vendor\dompdf\dompdf\src\FrameDecorator\AbstractFrameDecorator.php:894
**59 Dompdf\FrameDecorator\AbstractFrameDecorator:reflow in C:\xampp\htdocs\n\pdf\vendor\dompdf\dompdf\src\FrameReflower\Block.php:846
**58 Dompdf\FrameReflower\Block:reflow in C:\xampp\htdocs\n\pdf\vendor\dompdf\dompdf\src\FrameDecorator\AbstractFrameDecorator.php:894
**57 Dompdf\FrameDecorator\AbstractFrameDecorator:reflow in C:\xampp\htdocs\n\pdf\vendor\dompdf\dompdf\src\FrameReflower\Page.php:141
**56 Dompdf\FrameReflower\Page:reflow in C:\xampp\htdocs\n\pdf\vendor\dompdf\dompdf\src\FrameDecorator\AbstractFrameDecorator.php:894
**55 Dompdf\FrameDecorator\AbstractFrameDecorator:reflow in C:\xampp\htdocs\n\pdf\vendor\dompdf\dompdf\src\Dompdf.php:832
**54 Dompdf\Dompdf:render in C:\xampp\htdocs\n\pdf\vendor\barryvdh\laravel-dompdf\src\PDF.php:200
**53 Barryvdh\DomPDF\PDF:render in C:\xampp\htdocs\n\pdf\vendor\barryvdh\laravel-dompdf\src\PDF.php:146
**52 Barryvdh\DomPDF\PDF:output in C:\xampp\htdocs\n\pdf\vendor\barryvdh\laravel-dompdf\src\PDF.php:169

**Comment by agvstin** [comment]
@m-shehata it looks like an issue with `dompdf`. They have an [open issue](https://github.com/dompdf/dompdf/issues/1604) about it.

You can work around it by adding a custom CSS rule to the report:

```php
PdfReport::of($title, $meta, $qb, $columns)
   ->setCss([
          '.head-content' => 'border-width: 1px',
   ])->download('report');
```

**Comment by NormanEdance** [comment]
@barryvdh Work around works. Thanks.
