### ISSUE TITLE
Using an existing PDF as a starting point?

### ISSUE THREAD

**Issue by stueynet** [barryvdh/laravel-dompdf#416]
I love this package. Thanks @barryvdh! I am just wondering f you have a way to use an existing PDF as the stating point and then in the view be able to overlay additional things on it instead of having to build the whole thing from scratch. Our issue is we have an insanely complex form and building that from scratch with html is basically impossible.

**Comment by SergioReis97** [comment]
Perhaps using the other PDF as an image ( you can convert it dynamicly in the case it is multiple pdfs) and overlay it.
FPDI does seem to make more sense in your case though
