### ISSUE TITLE
How to display images and charts in pdf

### ISSUE THREAD

**Issue by nitish1986** [barryvdh/laravel-dompdf#417]
I'm trying to build an application on `Laravel 5.4`, where I'm trying export data tables with graphs and images
I'm calling this in controller:

    public function investorReport()
    {
        $pdf = PDF::setOptions(['dpi' => 150,
                'defaultFont' => 'sans-serif',
                'enable-javascript' => true,
                'images' => true
            ])
            ->loadView('pdf.clientInvestorReport');
        return $pdf->stream('report.pdf');
    }

and my blade file contains: https://codeshare.io/5OWgmW

If I check view file individually everything is working fine. I'm able to get tables in pdf but unable to get images and chart-js elements, help me out in this.

Thanks

**Comment by SergioReis97** [comment]
I had troubles in the past using javascript / css loaded from files so i placed what i needed in tags and everything was fine. 
Still, since you're doing tables and graphs and stuff, i'm not entirely sure snappy pdf would be better for you.
https://github.com/barryvdh/laravel-snappy

**Comment by admicaa** [comment]
Here I have a documentation about how to make it 
https://medium.com/@almestaadmicadiab/laravel-snappy-for-pdf-with-charts-e5c9b757d6dd

**Comment by aparedesBB** [comment]
Does Laravel snappy works with lavacharts?

**Comment by bhattraideb** [comment]
@barryvdh won't it work for chart/graphs? For me, I am getting tables but not charts/graphs.

**Comment by mgarcia96** [comment]
For external images I have to convert the url to a b64 string

`<img src="data:image/png;base64,base64_encode(file_get_contents('yourURL'))">`

**Comment by akildevs1001** [comment]
> I'm trying to build an application on `Laravel 5.4`, where I'm trying export data tables with graphs and images I'm calling this in controller:
> 
> ```
> public function investorReport()
> {
>     $pdf = PDF::setOptions(['dpi' => 150,
>             'defaultFont' => 'sans-serif',
>             'enable-javascript' => true,
>             'images' => true
>         ])
>         ->loadView('pdf.clientInvestorReport');
>     return $pdf->stream('report.pdf');
> }
> ```
> 
> and my blade file contains: https://codeshare.io/5OWgmW
> 
> If I check view file individually everything is working fine. I'm able to get tables in pdf but unable to get images and chart-js elements, help me out in this.
> 
> Thanks
