### ISSUE TITLE
How to open the pdf in new tab ?

### ISSUE THREAD

**Issue by prudhvi-php** [barryvdh/laravel-dompdf#419]
Actually i am able to create the pdf and save it using laravel-dompdf but, my requirement is when the pdf is generated it has to automatically open in a new tab using laravel-dompdf. I am unable to find any solution regarding it.

**Comment by SergioReis97** [comment]
Well that you can do with the `->stream();` at the end of the chain.

"Full" example
```
//Routes  (web.php in case laravel version >= 5.4)
Route::get('/pdf', 'PdfController@pdfStream')->name('pdfStream');

//PdfController.php
public function pdfStream(Request $request){
   $data["info"] = "I is usefull!";
   $pdf = PDF::loadView('whateveryourviewname', $data);
   return $pdf->stream('whateveryourviewname.pdf');
}


//yourViewPage.blade.php
<a href="{{route("pdfStream")}}" target="_blank" > click me to pdf </a>
```

**Comment by prudhvi-php** [comment]
Thank you @SergioReis97 this is what i am looking for.

**Comment by kevinryanr** [comment]
thank youu

**Comment by Erick-robogenius** [comment]
is very easy in your form 
add formtarget="_blank" target="_blank"
<form method="post" action="{{route('nameroute')}}" formtarget="_blank" target="_blank">

**Comment by vikashdukeinfo** [comment]
it show error
Malformed UTF-8 characters, possibly incorrectly encoded
