### ISSUE TITLE
Allowed memory size of ... bytes exhausted

### ISSUE THREAD

**Issue by carlituxman** [barryvdh/laravel-dompdf#42]
I'm traying to render a table with aprox 50 rows with loop in blade, and throw error:

Allowed memory size of 33554432 bytes exhausted...

**Comment by bosz** [comment]
I had up to 1k records to export. dompdf always gave me max size reached so on one of the discussion on same project, i was refered to [**snappy**](https://github.com/barryvdh/laravel-snappy). 

This was how i set my max exec time and memory size just for that function
```
ini_set('max_execution_time', 300); //300 seconds = 5 minutes
ini_set('memory_limit', '3000M'); //300 seconds = 5 minutes
```

**Comment by devsquad-leonardo-mengue** [comment]
I tried to export a pdf with no styles, just table borders and column centered text.

With 128M in php, when exporting approx 430 records the memory is exceeded.

Is there any way to solve the problem without increasing the memory available to php?

**Comment by devsquad-leonardo-mengue** [comment]
I'm using laravel 8.7 and the latest version of dompdf.

**Comment by RobertoLanzeni** [comment]
Same problem. 
My php.ini memory_limit= -1 (unlimited)
