### ISSUE TITLE
maximum execution time of 60 seconds exceeded (when iclude small image)

### ISSUE THREAD

**Issue by jorgemorgado25** [barryvdh/laravel-dompdf#425]
Hi,
I have the error when include any image in the view.
if I dont include the image works fine. Image size is: 255 x 255px
Image is very small....
I've increased max_execution_time to 300 in php.ini
Please help!!!!!

**Comment by jackrsantana** [comment]
Same problem here

**Comment by osvaldoalvaradodev** [comment]
Same problem here.

But when i insert img from remote url dont generate this issue.

**Comment by channox32** [comment]
If you guys are generating tables on your PDF, then might consider as a factor on this issue.
