### ISSUE TITLE
dompdf UT8 with database records with accents

### ISSUE THREAD

**Issue by mourareaupro** [barryvdh/laravel-dompdf#430]
I have a problem with utf8 with my stored data 

My colomun collation is set to utf8mb4_unicode_ci 

my html file i put

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/> 

So when i right in my html file : éééé and i generate the PDF it's fine but when i display my stored data the accents are displayed by : ?

In my config/dompdf.phpI have set :  

"DOMPDF_UNICODE_ENABLED" => true,    
"DOMPDF_PDF_BACKEND" => "CPDF", 

What i'm doing wrong ? 

The problem only come from my stored datas.. hope someone could help thanks a lot in advance.

**Comment by admont28** [comment]
try to put the UTF-8 Metatag in your HTML.

[Tip: UTF-8 support](https://github.com/barryvdh/laravel-dompdf#tip-utf-8-support)
