### ISSUE TITLE
Can't render chart.js charts in luman

### ISSUE THREAD

**Issue by AkshayBaldia** [barryvdh/laravel-dompdf#435]
I followed all steps, as mentioned in docs.

I'm using this for pdf :-

$pdf = app()->make('dompdf.wrapper');
$pdf->loadview('page_name');
return $pdf->download('pdf_name.pdf');

pdf is downloading but charts and images are not rendering for pdf but I can see it on my page.

This is my page :- 
![image](https://user-images.githubusercontent.com/26133334/35038345-8ddde362-fba0-11e7-9875-1d1bb81b6735.png)

and this is my pdf :- 
![image](https://user-images.githubusercontent.com/26133334/35038384-b0ab0a96-fba0-11e7-9a98-8d253a92402d.png)

**Comment by LasseRafn** [comment]
I'm pretty sure that you cannot generate graphs in a PDF. You must save the graph as a image and attach that 👍
