### ISSUE TITLE
Font doesn't come when save.

### ISSUE THREAD

**Issue by ThunderBirdsX3** [barryvdh/laravel-dompdf#438]
I work about generate slip in laos language, And I already add lao's font with `load_font.php`.

When I view the result in web browser, Every was fine.

But when I save PDF file to my computer, All of font didn't show.

In web browser.
![screen shot 2018-01-18 at 1 38 57 pm 2](https://user-images.githubusercontent.com/6513358/35084137-168952aa-fc55-11e7-9a58-8911d1d4b1ad.png)

In my computer.
![screen shot 2018-01-18 at 1 38 57 pm](https://user-images.githubusercontent.com/6513358/35084142-1a259fb8-fc55-11e7-846f-5414a021c01e.png)

In storage/fonts/dompdf_font_family_cache.php
```
...
'phetsarathot' => array(
    'normal' => $fontDir . '/phetsarath_ot',
    'bold' => $fontDir . '/phetsarath_ot',
    'italic' => $fontDir . '/phetsarath_ot',
    'bold_italic' => $fontDir . '/phetsarath_ot',
  ),
...
```

In html file.
```
body {
    font-family: phetsarathot;
    font-size: 11px;
}
```

**Comment by Morpheus-ro** [comment]
I have the same problem. @ThunderBirdsX3 did you manage to find any solution?

**Comment by ThunderBirdsX3** [comment]
@Morpheus-ro No.
