### ISSUE TITLE
Timeout generating PDF

### ISSUE THREAD

**Issue by javiersm79** [barryvdh/laravel-dompdf#440]
When i'm developing wiht internal server that come with LARAVEL there is problem {{asset}} 
ONLY with internal server, whit servers like apache for example it's work

**Comment by dvdhoek** [comment]
Same problem here

**Comment by willianmbotacin** [comment]
I have this problem, I solved it by using {{ public_path() }} instead of {{ asset() }}.
For example:
<img src="{ {public_path('imgs\img.png') }}" alt="Logo">

I hope it helps!

**Comment by AnaxAndrade** [comment]
Thanks @willianmbotacin  I had the same problem and the solution was also to replace the asset() helper. Looks like dompdf having some issues with asset helper function?!
