### ISSUE TITLE
Web Freezing after action when printing bunch of data 

### ISSUE THREAD

**Issue by billxcode** [barryvdh/laravel-dompdf#441]
`$data['bunch_of_user'] = User::get(); `
 `view()->share($data);`
`$pdf = PDF::loadView('dashboard.laporan.laporan_user');`
`return $pdf->stream();`

my above code always make my website freezing, and infinite loading but when it doesnt any data store to view, its going normal. is this a bug? please explain this. thank you

**Comment by sntlln93** [comment]
Did you find a solution?

**Comment by billxcode** [comment]
Iam not sure. its been a year ago. but maybe if you have seem issue, try another options.
