### ISSUE TITLE
How to get count of each viewed page 

### ISSUE THREAD

**Issue by KarthikMadathil96** [barryvdh/laravel-dompdf#445]
I have a pdf, and i want to know how many pages the user covered in that pdf.
how will i impliment, is there any idea to return count .

**Comment by musman92** [comment]
i did this, and it works

place that div where you want 
```<div class="pagenum-container">Page <span class="pagenum"></span></div>```

and add this in your css
```
<style>
.pagenum:before {
    content: counter(page);
}
</style>
```

**Comment by KarthikMadathil96** [comment]
and how will i return this to backend.?
