### ISSUE TITLE
Running slow when using Laravel methods

### ISSUE THREAD

**Issue by x2luilop** [barryvdh/laravel-dompdf#45]
DOMPDF runs slow when streaming or downloading a PDF, this happens when I use any Laravel 4 methods and when the environment is set to local.

On production it works ok, I've only enable support for css floats in the config file... any ideas?

**Comment by adiletmaks** [comment]
45
![full-hd-wallpapers-5a9](https://cloud.githubusercontent.com/assets/17255434/20624726/cd07e88c-b338-11e6-8d8d-8be21d8e9ae5.jpg)
[namaz_times (6).pdf](https://github.com/barryvdh/laravel-dompdf/files/613172/namaz_times.6.pdf)

**Comment by yann-yvan** [comment]
I'm facing this problem again, without css it's ok but with css very slow
