### ISSUE TITLE
Why the library take a long time, When generate a lot of PDF page.

### ISSUE THREAD

**Issue by ThunderBirdsX3** [barryvdh/laravel-dompdf#450]
I got a problem, When my PDF file have a lot of data. And a lot of page in PDF file.

It toke a long time for generate PDF file.

What is it? How can I make it faster.

```
  $pdf = PDF::loadView('view', $data);
```

Laravel: 5.5.*
PHP: 7.1.*
laravel-dompdf: v0.8.1
dompdf: v0.8.2

**Comment by deathnote332** [comment]
+1

**Comment by adrianoGaspar** [comment]
+1

**Comment by MichaelDeBoey** [comment]
We had our full CSS included.
Having a dedicated CSS-file for the PDF-view helped a lot for our use case. 🙂

**Comment by hardiksmy** [comment]
Same issue

**Comment by hardikraval24** [comment]
Same problem!

**Comment by vasymus** [comment]
+1

**Comment by hardikraval24** [comment]
I switched to Wkhtmltopdf Linux library and it's much faster than this.

**Comment by chintangrapes** [comment]
Same Issue !!

**Comment by chintangrapes** [comment]
> I switched to Wkhtmltopdf Linux library and it's much faster than this.

Do you any option with php 7.1 , because I tried it but it requires php 7.2

**Comment by cacacobra** [comment]
> We had our full CSS included.
> Having a dedicated CSS-file for the PDF-view helped a lot for our use case. 🙂

That solved my issue. Thanks!
