### ISSUE TITLE
dompdf view problem

### ISSUE THREAD

**Issue by ProtikHore** [barryvdh/laravel-dompdf#454]
In dompdf, when I want to download any file, it works but the variable I use in that view that wont work. After download it remains blank. And I could not able to use any css or table tag in view.

**Comment by DanielRTRD** [comment]
What does the log say?

**Comment by sunzid02** [comment]
I sent u the solution.

**Comment by sunzid02** [comment]
[protik_dom_pdf.zip](https://github.com/barryvdh/laravel-dompdf/files/1950851/protik_dom_pdf.zip)

please check the attached file
