### ISSUE TITLE
Direction:rtl not working

### ISSUE THREAD

**Issue by dv1r** [barryvdh/laravel-dompdf#459]
I have got this in my template.
The font is loaded correctly 
```
body {
    font-family: Alef;
    direction:rtl;
    text-align:right;
}
```
My code is very straight forward:

```
    $fontsLocation = Storage::disk('local')->getDriver()->getAdapter()->getPathPrefix()."fonts/";
    $pdf = PDF::setOptions(['fontDir'=>$fontsLocation,'defaultFont'=>'Alef-Regular']);
    $pdf->loadView('pdf/quota', $data);
    return $pdf->download($data["client"]."-".$data["id"].'.pdf');
```
Still the entire PDF is LTR... 
I have also tried to add  `direction:rtl;` to a single span to see if it helps, nothing.
I have even tried to change `$d["direction"] = "ltr";` to `$d["direction"] = "rtl";` in [Style.php](https://github.com/dompdf/dompdf/blob/5113accd9ae5d466077cce5208dcf3fb871bf8f6/src/Css/Style.php#L287)

Has anyone been able to overcome this issue?

**Comment by sadaqatullah** [comment]
I am still facing this issue. any solution?

**Comment by sadaqatullah** [comment]
![Screenshot 2024-10-30 005327](https://github.com/user-attachments/assets/2fa88f7b-12af-4d1f-aee4-7984911bb4a0)
Browser shows like this.

![Screenshot 2024-10-30 005416](https://github.com/user-attachments/assets/fbac5db8-51ea-4f88-9251-a6b458d7c792)
PDF shows like this.

I tried upgrading the package to latest but still the issue persist.
