### ISSUE TITLE
PHP Fatal error Helpers.php on line 506

### ISSUE THREAD

**Issue by drumer2142** [barryvdh/laravel-dompdf#461]
PHP Fatal error:  Maximum execution time of 60 seconds exceeded in

(directory)\vendor\dompdf\dompdf\src\Helpers.php on line 506

**Comment by thrazu** [comment]
+1

**Comment by MeesMaas** [comment]
+1

**Comment by CyberDracula** [comment]
no solution here?

**Comment by CyberDracula** [comment]
it was generated because of max_execution_time
