### ISSUE TITLE
ERROR GET_LINE_BOX NULL

### ISSUE THREAD

**Issue by labold** [barryvdh/laravel-dompdf#464]
hey, i found error "Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function get_current_line_box() on null" when download pdf. how to resolve ? thx

**Comment by irtzamazhar** [comment]
I also got same error. Please suggest some solution

**Comment by renansteles** [comment]
Same error!

**Comment by dinesh0666** [comment]
same error
