### ISSUE TITLE
utf8 support is doesnt work

### ISSUE THREAD

**Issue by mustafat0k** [barryvdh/laravel-dompdf#465]
Does allows to position text, except for styling it with margins. I think this feature really nice. I wanted to say but my text is not read. 
I was see from docs about with metatag but  it doesnt work. I already use`<meta charset="UTF-8"> `and 
`<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">`

_Some other pdf libraies doesn't allow you to positon but utf-8 supporting. I dont get it.  As a result:_

> 
> **Input** "Şükelayı ğ nedir ç ş i ğ ö dersek"
> **Output** "?ükelay? ? nedir ç ? i ? ö dersek " 
>

**Comment by beetlikeyg087** [comment]
I got the same issue,

anyone help?

**Comment by hacicavcav** [comment]
I fixed this problem with download to font from google. You can change your font family. Dompdf package have a lib folder. Maybe give it an idea. You can use ` font-family: Time-Roman;`  or `DejaVu Sans, sans-serif`

**Comment by hacicavcav** [comment]
And this link have few fix suggestion
[But it is turkish](http://forum.laravel.gen.tr/viewtopic.php?id=726)

**Comment by MuhammadTalha944** [comment]
Hi, you just need to add font-family: DejaVu Sans; in your body or also you can set the font family to any specific div in which you are going to display the Unicode Characters.

Hope this would help.
Talha Ishtiaq, Software Engineer
