### ISSUE TITLE
Digital sign PDF

### ISSUE THREAD

**Issue by ScriptMint** [barryvdh/laravel-dompdf#466]
Hello,

Is there any way to digitally sign PDF generated by this package?

**Comment by jor3l** [comment]
+1 on this. 👍

**Comment by setlec** [comment]
+1 too i need this like yesterday :p

**Comment by b-cil** [comment]
+1

**Comment by yurik94** [comment]
+1

**Comment by brazorf** [comment]
+1

**Comment by mohanrajdelta** [comment]
does the latest version of 0.8.0 have pdf signature feature

**Comment by AInME93** [comment]
+1

**Comment by juanmartinhernandez** [comment]
+1

**Comment by juanmartinhernandez** [comment]
+1

**Comment by samuferenc** [comment]
Hi, I'm working on it, but I need some help before pull request. Its not only signing, its a first step to AcroForm. Need some feedback
[test.pdf](https://github.com/barryvdh/laravel-dompdf/files/4615052/test.pdf)

**Comment by samuferenc** [comment]
Hi, I'm working on it, but I need some help before pull request. Its not only signing, its a first step to AcroForm. Need some feedback
https://github.com/samuferenc/dompdf
[test.zip](https://github.com/barryvdh/laravel-dompdf/files/4615073/test.zip)

**Comment by setlec** [comment]
> 
> 
> does the latest version of 0.8.0 have pdf signature feature

do you think that it could be ported to laravel?

**Comment by parallels999** [comment]
https://github.com/dealfonso/sapp
