### ISSUE TITLE
laravel/DomPdf writing-mode, rotation error

### ISSUE THREAD

**Issue by Cananau** [barryvdh/laravel-dompdf#468]
I have an error with        ` white-space: nowrap;    writing-mode: vertical-lr;  transform: rotate(-90deg);`
I my browser it works but when i do and pdf from that it makes just only the rotation and i have an big space that i dont't need.
Here i have some picture how is it in browser : [example](https://i.stack.imgur.com/rODu7.jpg)
Here i have the problem in dompdf : [problem](https://i.stack.imgur.com/PIbLb.jpg)

**Comment by fjrmdev** [comment]
did you solve it?
