### ISSUE TITLE
flexbox css is not rendered? why?

### ISSUE THREAD

**Issue by beetlikeyg087** [barryvdh/laravel-dompdf#469]
I use flexbox for creating a layout but the pdf that has been generated did not render flexbox property, so i messy the whole page.

I have test it with 3 columns equally using flexbox

This is the output look like in html

![selection_033](https://user-images.githubusercontent.com/26866007/37764279-e5302de8-2df3-11e8-97dc-3fd7a2b1fe84.png)

This is the output when it is generated

![selection_034](https://user-images.githubusercontent.com/26866007/37764304-f115177c-2df3-11e8-82a0-d7e364dda144.png)

Can anyone help?

**Comment by Maciastek** [comment]
dompdf does not support flexbox.

> dompdf supports the majority of CSS 2.1 properties and some CSS 3 properties

 source: https://github.com/dompdf/dompdf/wiki/CSSCompatibility

You are not the first to report this problem, please use search function. See #227 
Btw. this is just a dompdf wrapper. You shouldn't report problems with dompdf itself here.
