### ISSUE TITLE
Class dompdf.wrapper not found

### ISSUE THREAD

**Issue by mjemerson** [barryvdh/laravel-dompdf#470]
I'm trying desperately to get this to work, but everytime I get the error above. This is how I've written the code in my controller:

```
$case = $this->caseRepo->getOne($caseId);
$file_name = $case->reference . ".pdf";

$pdf = PDF::loadHTML($case->reference);

return $pdf->download($file_name);
```
The repo I am quoting here is where my data is, which is correct and available as I have logged that data and it's there. Whenever I load the page that this is linked to I get a 500 error with this in the network response:

> (1/1) ReflectionException
> 
> Class dompdf.wrapper does not exist

I am using Laravel 5.4

Any help with this would be appreciated as I cannot seem to find a definitive solution anywhere else.

**Comment by LeebranZadwell** [comment]
Hi @mjemerson,

I had the same issue just now - switching away from the Facade pattern helped me at least.

The [example should work]((https://github.com/barryvdh/laravel-dompdf#using) as is. I'm assuming you have [defined the class path in the providers array](https://github.com/barryvdh/laravel-dompdf#installation).

```
$pdf = App::make('dompdf.wrapper');
$pdf->loadHTML('<h1>Test</h1>');
return $pdf->stream();
```

I recommend getting the example working first, before adding additional complexity. Hope that helps!
