### ISSUE TITLE
RTL language

### ISSUE THREAD

**Issue by Egyptionl** [barryvdh/laravel-dompdf#471]
dompdf not support for RTL language ???

**Comment by ajmanco** [comment]
I have this problem too .  pleas help us .

**Comment by TimFoerster** [comment]
Looks like it is not supported yet.
https://github.com/dompdf/dompdf/issues/1697
https://github.com/dompdf/dompdf/issues/1009
and here you can find a solution 
https://github.com/dompdf/dompdf/issues/712

**Comment by mrezahamedani** [comment]
you can use this package which supports rtl languages such as persian and arabic perfectly

https://github.com/barryvdh/laravel-snappy

**Comment by hannanstd** [comment]
use below package:
https://github.com/mccarlosen/laravel-mpdf

i tested and works with persian well.
