### ISSUE TITLE
Call to a member function cloneNode() on integer

### ISSUE THREAD

**Issue by udayakumarappmocx** [barryvdh/laravel-dompdf#472]
$data = [
            'edit_encr_details' => $encr_details
        ];
            PDF::setOptions(['dpi' => 150, 'defaultFont' => 'sans-serif']);
        $html = \View::make('quality.encr_pdf', $data);
        return PDF::loadHTML($html)->download('invoice.pdf');

Above code giving the error, when i am loading loading data to view blade file

**Comment by bhuisumanta** [comment]
The same issue was coming for me because I forgot to write a closing tag for an HTML element.
