### ISSUE TITLE
Dont support persian

### ISSUE THREAD

**Issue by behroozbc** [barryvdh/laravel-dompdf#473]
hi 
i want export Persian but i cant.
 places add support to Persian language

**Comment by msadeghyan1996** [comment]
you can use load_font.php file for load your font's and use it but not support all persian font's and i think just support tahoma and aria font.

**Comment by hannanstd** [comment]
use below package:
https://github.com/mccarlosen/laravel-mpdf

i tested and works with persian well.

**Comment by nakarimi** [comment]
@msadeghyan1996
Could you give an example how to apply it with load_font.php?

**Comment by farhadrahmanii** [comment]
> use below package: https://github.com/mccarlosen/laravel-mpdf
> 
> i tested and works with persian well.

Thank you so much
