### ISSUE TITLE
How generate 50 files pdf? helpme please.

### ISSUE THREAD

**Issue by christiantigre** [barryvdh/laravel-dompdf#475]
public function formatoorden(){
        $i = 1;
        while ( $i<= 50) {
        //$i = 1;
        $numbers     = $this->generate_numbers($i, 1, 6);
        $numero_orden = implode("", $numbers);        
        $orden = "";
        $empresa = Empresa::first()->get();
        $hoy = "";
        $empresa = "";
        $tot_abonos = "";
        $pre_final = "";
        $clausulas = "";

        //print($numero_orden);
        $pdf     = \PDF::loadView('pdf.pdf', [
            'orden' => $orden, 
            'empresa' => $empresa,
            'secuencial'  => $numero_orden,
            'hoy' => $hoy,
            'clausulas'  => $clausulas]);
         
        return $pdf->stream();
/*
        return $pdf->download($numero_orden.'.pdf');
*/

         $i++;
       }
    }

**Comment by brokeyourbike** [comment]
Take a look at the laravel [Queues](https://laravel.com/docs/5.6/queues). Split every PDF that should be created to one job, and then process them in the separate process.
