### ISSUE TITLE
How to make a summary ( table of contents)?

### ISSUE THREAD

**Issue by tonicesar81** [barryvdh/laravel-dompdf#477]
Hi,
My Laravel application is generating a pdf document, and I need a table of contents page, listing all topics and their page numbers. I must be dynamic, because it may change accordly the document contents.

Thanks in advance, and sorry for my English. Is not my native language

**Comment by dimitribocquet** [comment]
Did you found a solution? I'd like also to make a TOC

**Comment by webnologie** [comment]
hello, im also interested to find a solution to make a TOC. maybe to generate manually but with a link to the correct page number?
