### ISSUE TITLE
Cannot create multiple PDF documents

### ISSUE THREAD

**Issue by lonnylot** [barryvdh/laravel-dompdf#48]
In 0.4.0 you are not able to create multiple PDF documents in one request. If you attempt to call `PDF::loadView()` twice in one request you receive:

```
DOMPDF_Exception
No block-level parent found. Not good.
```

This seems to be related to the `PDF::__construct()` and `PDF::init()` refactoring. If I comment out [this](https://github.com/barryvdh/laravel-dompdf/blob/master/src/Barryvdh/DomPDF/PDF.php#L197) it seems to work. I guess `DOMPDF` needs to be re-instantiated for each new use.

**Comment by dorinhila** [comment]
How to create multiple pdf documents with foreach statement.
Here are my code.
foreach($receipts as $key=>$receipt)
 {
   $data['receipt'] = AcReceiveMoney::find($receipt);
   $data['id'] = $i;
   $pdf = PDF::loadView( 'sc_bank.print_receipts_print', $data);
...
 }
