### ISSUE TITLE
laravel 5.5 Installation error

### ISSUE THREAD

**Issue by renatosistemasvc** [barryvdh/laravel-dompdf#480]
When executing the command 

`composer require barryvdh/laravel-dompdf`

I have the following error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for barryvdh/laravel-dompdf ^0.8.2 -> satisfiable by barryvdh/laravel-dompdf[v0.8.2].
    - Conclusion: remove sabberworm/php-css-parser 5.1.2
    - Conclusion: don't install sabberworm/php-css-parser 5.1.2
    - barryvdh/laravel-dompdf v0.8.2 requires dompdf/dompdf ^0.8 -> satisfiable by dompdf/dompdf[v0.8.0, v0.8.1, v0.8.2].
    - dompdf/dompdf v0.8.0 requires phenx/php-svg-lib 0.2.* -> satisfiable by phenx/php-svg-lib[v0.2].
    - dompdf/dompdf v0.8.1 requires phenx/php-svg-lib 0.3.* -> satisfiable by phenx/php-svg-lib[v0.3].
    - dompdf/dompdf v0.8.2 requires phenx/php-svg-lib 0.3.* -> satisfiable by phenx/php-svg-lib[v0.3].
    - phenx/php-svg-lib v0.2 requires sabberworm/php-css-parser 6.0.* -> satisfiable by sabberworm/php-css-parser[6.0.0, 6.0.1].
    - phenx/php-svg-lib v0.3 requires sabberworm/php-css-parser 8.1.* -> satisfiable by sabberworm/php-css-parser[8.1.0].
    - Can only install one of: sabberworm/php-css-parser[6.0.0, 5.1.2].
    - Can only install one of: sabberworm/php-css-parser[6.0.1, 5.1.2].
    - Can only install one of: sabberworm/php-css-parser[8.1.0, 5.1.2].
    - Installation request for sabberworm/php-css-parser == 5.1.2.0 -> satisfiable by sabberworm/php-css-parser[5.1.2].

```

What should I do?

**Comment by d0hn** [comment]
I have tried to install it on a fresh installation of Laravel 5.5 and it didn't error out.

    vagrant@homestead:~/dev/app$ composer require barryvdh/laravel-dompdf

    Using version ^0.8.2 for barryvdh/laravel-dompdf
    ./composer.json has been updated
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Package operations: 5 installs, 0 updates, 0 removals
      - Installing sabberworm/php-css-parser (8.1.0): Downloading (100%)
      - Installing phenx/php-svg-lib (v0.3): Downloading (100%)
      - Installing phenx/php-font-lib (0.5.1): Downloading (100%)
      - Installing dompdf/dompdf (v0.8.2): Downloading (100%)
      - Installing barryvdh/laravel-dompdf (v0.8.2): Downloading (100%)
    Writing lock file
    Generating optimized autoload files

As you can see I'm using php-css-parser 8.1.0 where you depend on 5.1.2
You should update that package and try again.
