### ISSUE TITLE
Pdf direction and Unicode problem for Arabic language.

### ISSUE THREAD

**Issue by ashrafuzzaman1973** [barryvdh/laravel-dompdf#483]
I am using barryvdh/laravel-dompdf version 0.8.When i print or generate a pdf file this time is not working good.Its has direction and unicode problem. How can i fixed it? Please suggest me.
![pdf_arabic](https://user-images.githubusercontent.com/24843288/39966443-c0ccc026-56cd-11e8-9108-10e4a12501b4.png)

**Comment by tannu13** [comment]
How did you got the Arabic version to display properly? In my case it is displayed as question marks?

**Comment by m7ammad7assan** [comment]
No solution yet

**Comment by mukesh17mj** [comment]
@tannu13 Did you find a solution to this issue ? @ashrafuzzaman1973 How did those Arabic Language displayed, in my case those appears as ??????

**Comment by ashrafuzzaman1973** [comment]
@mukesh17mj I have not found any solution yet. To solve this problem i used mpdf.

**Comment by akcharyou** [comment]
@ashrafuzzaman1973 
Hi , the best solution to support and fix arabic characters in dompdf Library you should integrate
ar-php library for khaled.alshamaa inside dompdf library , so

please follow these steps:

1- download the ar-php library for khaled.alshamaa from the following link
http://www.ar-php.org/ (its free arabic Library with LGPL license)

2 - extract and upload I18N folder inside dompdf folder

3- open Glyphs.php file in this path

               \dompdf\I18N\Arabic 
search

              public function utf8Glyphs($str, $max_chars = 50
replace to

             public function utf8Glyphs($str, $max_chars = 150
4-in text_renderer.cls.php file
dompdf/include/text_renderer.cls.php

before this line

       $this->_canvas->text($x, $y, $text 
add this code

 if ( ! class_exists( 'I18N_Arabic' ) ){

require_once( DOMPDF_DIR . "/I18N/Arabic/Glyphs.php" );
$Arabic = new I18N_Arabic_Glyphs('Glyphs');
$text = $Arabic->utf8Glyphs($text);

    }
also you should use any custom arabic font in your css file
this will fix Arabic problem forever and will display arabic letter correctly
example : احمد
will appear
احمد
not
د م ح ا

thanks

**Comment by ashrafuzzaman1973** [comment]
Thanks for your reply.

**Comment by khalidJA** [comment]
> @ashrafuzzaman1973
> Hi , the best solution to support and fix arabic characters in dompdf Library you should integrate
> ar-php library for khaled.alshamaa inside dompdf library , so
> 
> please follow these steps:
> 
> 1- download the ar-php library for khaled.alshamaa from the following link
> http://www.ar-php.org/ (its free arabic Library with LGPL license)
> 
> 2 - extract and upload I18N folder inside dompdf folder
> 
> 3- open Glyphs.php file in this path
> 
> ```
>            \dompdf\I18N\Arabic 
> ```
> 
> search
> 
> ```
>           public function utf8Glyphs($str, $max_chars = 50
> ```
> 
> replace to
> 
> ```
>          public function utf8Glyphs($str, $max_chars = 150
> ```
> 
> 4-in text_renderer.cls.php file
> dompdf/include/text_renderer.cls.php
> 
> before this line
> 
> ```
>    $this->_canvas->text($x, $y, $text 
> ```
> 
> add this code
> 
> if ( ! class_exists( 'I18N_Arabic' ) ){
> 
> require_once( DOMPDF_DIR . "/I18N/Arabic/Glyphs.php" );
> $Arabic = new I18N_Arabic_Glyphs('Glyphs');
> $text = $Arabic->utf8Glyphs($text);
> 
> ```
> }
> ```
> 
> also you should use any custom arabic font in your css file
> this will fix Arabic problem forever and will display arabic letter correctly
> example : احمد
> will appear
> احمد
> not
> د م ح ا
> 
> thanks

how to apply these steps in laravel ?
