### ISSUE TITLE
Generate pdf

### ISSUE THREAD

**Issue by shiromani2018** [barryvdh/laravel-dompdf#484]
Hi, 
I have been using your library  to generate pdf from a Laravel view template and trying to save in the database without saving in the disk.  Is there any method to save pdf on the fly  in the database?
Please find the code below:
view()->share('lab',$data);
    $pdf = PDF::loadView('lab.test');
    return $pdf->download('test_'. $request['Id'] . '_lab.pdf');

The above code allow me to generated the pdf but I cannot open it , and it is sending as an email attachment. I am using the postman though.

Thanking in Advanced.
Mani

**Comment by auralon** [comment]
Just to chip in.  I can attach a PDF to an email with no issue, like so...

    $pdf = PDF::loadView('emails/templates/invoice-pdf', $data);

    Mail::send('emails/templates/send-invoice', $messageData, function ($mail) use ($input, $emailAddress, $pdf) {
        $mail->from('bar@foo.com', 'Bar Foo');
        $mail->to(foo@bar.com);
        $mail->attachData($pdf->output(), 'test.pdf');
    });

... and the PDF opens without issue.  However, if I try to *download* the PDF, like so...

    $pdf = PDF::loadView('emails/templates/invoice-pdf', $data);
    return $pdf->download('test.pdf');

... I get a 'PDF is damaged' error (evince) and the PDF fails to open.  I examined the good and bad PDFs in ghex and they both look very similar, but with slightly differing endings.

After seeing this recent issue, I suspect there is a bug in the latest version.  Can anyone confirm?

**Comment by auralon** [comment]
bump!

I'm keen to find out if this is an error on my part, or if there is a problem here.

**Comment by shiromani2018** [comment]
I am also waiting for reply on my issues....

**Comment by auralon** [comment]
I expect the maintainer is busy, which is entirely understandable!  We all have lives and jobs to tend to, etc.

It'd be nice to workout the problem and solution though, so that I can get PDF downloads working before pushing my application code that relies on it to staging or production.  Hopefully we will hear something soon.

**Comment by shiromani2018** [comment]
I think you need to add header response to down pdf in Laravel, please see the link as below:
https://laracasts.com/discuss/channels/eloquent/downloading-a-file-from-blob-in-db

$file = File::findOrFail($id);
      $fileupload = $file->fileupload;
      $file_contents = base64_decode($fileupload->file);
      return response($file_contents)
        ->header('Cache-Control', 'no-cache private')
        ->header('Content-Description', 'File Transfer')
        ->header('Content-Type', $fileupload->type)
        ->header('Content-length', strlen($file_contents))
        ->header('Content-Disposition', 'attachment; filename=' . $file->name)
        ->header('Content-Transfer-Encoding', 'binary');
If you want to display in browser please comments out the attachment part of the code.
Hope it  will help you. I am still waiting for my query . :(

**Comment by shiromani2018** [comment]
Sorry it looks like I misunderstood your query .. I have tried myself and it is working for me. I m doing as below. Hope it will help..

view()->share('labs', $data);
 $pdf = PDF::loadView($viewTemplateName);
return $pdf->download($viewTemplateName.'_'. time().'test.pdf');

//blade template
<div>
{{$labs}}
</div>

Please let me know your feedback on this.
Cheers,

**Comment by shiromani2018** [comment]
I am just guessing .. your view file is having problem. For me it was the same and I had to remove all styling bit .. then add bit by bit .. it is working now. Hope it will help.

**Comment by auralon** [comment]
I stripped it right back to this...

    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
    <html>
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    </head>
    <body>
        test
    </body>
    </html>

... no joy.

**Comment by shiromani2018** [comment]
I think you are using DOCTYPE strict.. 
please try this..

<!DOCTYPE html>
<html>
<head>
    <title>Laravel</title>
    <link href="https://fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">

</head>
<body>
</body>
</html>

**Comment by shiromani2018** [comment]
```
<!DOCTYPE html>
<html>
<head>
    <title>Laravel</title>
    <link href="https://fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">



</head>
<body>
</body>
</html>

``

**Comment by auralon** [comment]
Tried adding `title`, and also removing everything and simply outputting 'test'.  Still having problems.

**Comment by shiromani2018** [comment]
There might be server issues .. it is hard to pin point the issues.. Sorry.

**Comment by auralon** [comment]
The google font threw an error, 

    <!DOCTYPE html>
    <html>
    <head>
        <title>Laravel</title>
        <link href="https://fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">
    </head>
    <body>
    </body>
    </html>

ErrorException in AdobeFontMetrics.php line 45:
fopen(/home/foo/www/test.com/storage/fonts//848842dcc5d80fbdc9480a865faab43f.ufm): failed to open stream: No such file or directory

but with the font removed it failed again.

    <!DOCTYPE html>
    <html>
    <head>
        <title>Laravel</title>
    </head>
    <body>
    </body>
    </html>

![screenshot](https://i.imgur.com/1THRzgG.png)

**Comment by auralon** [comment]
No worries.  The differences between attach and download produce different file content.  Comparing them with a hex editor shows that they are not the same, and one --for whatever reason-- is corrupt.

**Comment by shiromani2018** [comment]
I tried my end it is working .. anyway good luck!

**Comment by auralon** [comment]
Thanks for your time, if I get it working, I'll be sure to let you know!

**Comment by hardikraval24** [comment]
I have one weird issue!

I am generating PDF around 200 pages, which is working perfectly in my localhost(windows xampp) but the same thing is not working on a server and getting Chrom error -- ERR_EMPTY_RESPONSE.

I have show_warnings is true though it's not giving any errors.

I checked:
laravel.log -- no errors.
/var/logs/apache2/error.log -- no errors.
/var/logs/apache2/access.log -- no errors.

Can anybody please help me on this?
 
Thanks!

**Comment by sigues** [comment]
@auralon try saving the file as html, you're probably getting an exception, that way you can see it

**Comment by hyppark** [comment]
This is for future reference in case anyone runs into the same problem. I spent way too long reinstalling composer and clearing cache. Don't do that.

I encountered the same problem after I created a customer PHP helper with the steps stated in the comments below:
![image](https://user-images.githubusercontent.com/58623469/79626503-3938f180-8163-11ea-9ece-842fb823c9bd.png)
Those functions weren't even used in generating the pdf.

Little did I know, those comments should not be there in the first place. Deleting those comments, or placing them below <?php solved the problem for me.

**Comment by ivascumarius** [comment]
@auralon did you ever fix that problem with the corrupted downloaded pdf? I'm struggling with it also

**Comment by ludndev** [comment]
Same error in production environnement. 
Everything works fine on `APP_ENV=dev`, but on `APP_ENV=production`, it's not working anymore.
@ivascumarius @auralon

**Comment by ivascumarius** [comment]
@ludndev Fixed it. Look for any kind of output or comments before the $pdf->download() line. Remove it and it should all be good.

**Comment by ludndev** [comment]
@ivascumarius can you show your code ?

My code
`
public function invoice($id, Request $request)
    {
        $command = Command::findOrFail($id);

        if (!$command->payed()) {
            Session::flash('alertify', [
                'error' => 'Impossible de télécharger cette facture',
                'info' => 'Cette commande est impayée',
                'warning' => 'Veuillez procéder au paiement de votre commande'
            ]);
            return redirect()->route('user.command.pay', $command->id);
        }

        if ($request->query('download')== 'true') {
            $pdf = $this->generateInvoice($command);
            $filename = strtolower(env('APP_DOMAIN')) . "-facture-{$command->id}.pdf";

            return $pdf->stream($filename, ['attachment' => true]);
        } else {
            $logo = asset('assets/logo.png');
            return view('app.pdf.invoice', ['command' => $command, 'logo' => $logo]);
        }
    }

    private function generateInvoice(Command $command)
    {
        $logo = public_path() . '/assets/logo.png';

        $pdf = App::make('dompdf.wrapper');

        $pdf->loadView('app.pdf.invoice', ['command' => $command, 'logo' => $logo]);

        return $pdf;
    }
`

**Comment by ivascumarius** [comment]
@ludndev My code is way simpler. i just receive some params, load a view and download it.
The point is that both download() and stream() methods set a different header, so it's important NOT to have any kind of output on page before them.
You said that your code works with the dev ENV, but not with production.
You should check if anything changes in your app when you switch to production.

The point is that the problem is not in the PDF generation code.

**Comment by ludndev** [comment]
@ivascumarius just APP_ENV.
I retry it on local server, same error when switch to production. Nothing else have been changed.

**Comment by ludndev** [comment]
@ivascumarius try to set `APP_ENV` to production and test. If it succeeds, copy your code and configuration.

**Comment by ivascumarius** [comment]
@ludndev tried that. It works.
As I said, i do a simple thing, just generating a simple pdf with the user's info

`$pdf = PDF::setPaper('a4', 'portrait')->loadView( 'declaratie.declaratie', ['params' => $request->all(), 'semnatura' => $semnatura_file_path] );

        return $pdf->download( $filename.'.pdf' );`

As for config, I use the default config, but with a custom font.

**Comment by ludndev** [comment]
I will try it @ivascumarius
