### ISSUE TITLE
How to passe data?

### ISSUE THREAD

**Issue by mehdithemaker** [barryvdh/laravel-dompdf#485]
i'm new with this package
how to get values the values from my db to use themes in my view?
with this function i can get the data to show it the way i want it it's working
```
public function afficherconfirmer(){
    $professor = Auth::user();
    $exams = $professor->exams;
    $verifications = Verification::with('exam')->whereIn('exam_id', $exams->pluck('id') )->where([
    ['confirmation', 'non'],
    ['modifier', 'oui'],
    ])->get();
    return view('confirmations.confirmer',compact('verifications','professor'));
  }
```

I don't want to show this view anyway i just want to get my pdf with the data on it this is the function to get the pdf but when I tryed to passe the data it's not working any solution?
 ```
 public function confirmer(){
    $pdf = PDF::loadView('confirmations.confirmer');
    return $pdf->download('confirmation_changement_notes.pdf');
  }
```

**Comment by aadityamundhalia** [comment]
@mehdithemaker I got it working
        $data = Web::first();
        $pdf = PDF::loadView('web.pdf', array('data' => $data));
        return $pdf->download('web.pdf');

**Comment by Ralphkay** [comment]
This works fine. Use **compact** not just _array_.
` public function exportPDF(Member $member){
       $data= Member::findOrFail($member);

        $pdf = PDF::loadView('pdf_documents.print-view', compact('data',$data)); //use compact() 
        return $pdf->download('report.pdf');
    }`
