### ISSUE TITLE
rowspan fail when start new page

### ISSUE THREAD

**Issue by Andontae** [barryvdh/laravel-dompdf#489]
I'm working in Laravel project and I just trying to export table with many rows and some rows have rowspan attribute.

It just work fine whenever the row doesn't exceed to new page.

If it exceed to new page, it break the layout as show in image :

![screen shot 2018-06-06 at 10 15 31 am](https://user-images.githubusercontent.com/16976718/41025109-49b7e3b8-699b-11e8-9ce6-4228bbdf1bc6.png)

Can anyone suggest me how I can fix this?

**Comment by barryvdh** [comment]
No, please ask on dompdf repository if it's a bug.

**Comment by rUriarteDev** [comment]
Sorry to take this back, but im facing same the issue.
@hanahanami  do you found a solution for this?

**Comment by Azmi-ir** [comment]
anyone found a solution for this?
