### ISSUE TITLE
Call to undefined method DOMText::getAttribute() 

### ISSUE THREAD

**Issue by simpleann** [barryvdh/laravel-dompdf#49]
![image](https://cloud.githubusercontent.com/assets/6926400/3453023/32cff526-01be-11e4-99fe-ef82e8b5aa34.png)

Here is my error once I place a specified rowspan and colspan on my Blade view. I tried to run the Blade view without the dompdf and it's running. And also I tried to run the dompdf without using the laravel and it's woking also. Would you please help me regarding on this issue?

Thank you.

**Comment by mvalster** [comment]
This is still not fixed for Laravel 4 users, using the 0.5 tag is not possible due to dependency on Laravel 5.
