### ISSUE TITLE
Is CSS Grid supported or not?

### ISSUE THREAD

**Issue by jrmypttrsn** [barryvdh/laravel-dompdf#496]
The [css compatibility page](https://github.com/dompdf/dompdf/wiki/CSSCompatibility) says the only Display type not supported is `run-in`: ![screenshot_2018-07-18` dompdf dompdf](https://user-images.githubusercontent.com/16291625/42885146-d57855dc-8a65-11e8-9f83-e089453e06f7.png)

But when I try to apply CSS grid to a pdf I'm trying to generate all I get is a blank document, while the HTML view displays properly. Is CSS grid supported?

**Comment by barryvdh** [comment]
No

**Comment by Bassadin** [comment]
Are there any plans to support CSS Grid in the future?
