### ISSUE TITLE
Class 'Barryvdh\DomPDF\ServiceProvider' not found

### ISSUE THREAD

**Issue by daniwaxman** [barryvdh/laravel-dompdf#499]
Running Version 5.3
I have added :Barryvdh\DomPDF\ServiceProvider::class,
to my providers

I have added: 'PDF' => Barryvdh\DomPDF\Facade::class,
to my aliasses

I have run composer dump-autoload

I get the following error when I run composer update/install/dump-autoload.

 [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Barryvdh\DomPDF\ServiceProvider' not found

**Comment by joao-vieira** [comment]
Hi @daniwaxman 

I just added `Barryvdh\DomPDF\ServiceProvider::class` in my providers array (inside **<path_your_project>/config/app.php**) and `'PDF' => Barryvdh\DomPDF\Facade::class` in my aliases array (inside the same file) and it worked for me!

Note1: I'm using Laravel 5.4

Note2: don't forget of run this:
`composer require barryvdh/laravel-dompdf`

**Comment by daniwaxman** [comment]
@joao-vieira - Thanks.
I did run composer require barryvdh/laravel-dompdf

I am on 5.3 

Thanks

**Comment by vickymessii** [comment]
`php artisan vendor:publish`  try this it  will list all the packages then choose the number which one you want to publish

**Comment by toschuss** [comment]
Sorry but no. I have exactly the same problem here, on Laravel 5.7.

I just tried `php artisan vendor:publish` and nothing changes, the error is still there : Class 'Barryvdh\DomPDF\ServiceProvider' not found

Maybe something which can help : when I use composer require `barryvdh/laravel-dompdf`, everything goes right :
```
Using version ^0.8.3 for barryvdh/laravel-dompdf
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: beyondcode/laravel-dump-server
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Package manifest generated successfully.
```

But after this, when I open my composer.json, I can't find barryvdh/laravel-dompdf in the required packages. Is it normal?

**Comment by joao-vieira** [comment]
No, your composer.json must be like this:

```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "barryvdh/laravel-dompdf": "^0.8.1",
        "grimthorr/laravel-toast": "^1.1",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "laravelcollective/html": "^5.4",
        "maddhatter/laravel-fullcalendar": "^1.3",
        "phpoffice/phpword": "^0.13.0"
    },
....
```

I think it would be valid for you to try to run cleanup and auto-start commands, such as:

```
php artisan config:clear
```
```
php artisan cache:clear
```
```
composer dump-autoload
```

I hope this helps.
Regards

**Comment by barforever** [comment]
The problem is that they must execute the command inside their project folder

-> composer require barryvdh/laravel-dompdf

**Comment by elifelimo** [comment]
I have same problem but not solved. please give me the correct answer

**Comment by d3x773r** [comment]
Add this

```
$app->register(\Barryvdh\DomPDF\ServiceProvider::class);
class_alias(\Barryvdh\DomPDF\Facade::class, 'PDF');
```

inside your  `\bootstrap\app.php`

and it will work

**Comment by NimperX** [comment]
> `php artisan vendor:publish` try this it will list all the packages then choose the number which one you want to publish

This one solved my problem for this issue.Thank you @vickymessii

**Comment by sumeetprajapati1996** [comment]
For me the problem was in the vendor source folder,

Add , 
use Barryvdh\DomPDF\PDF;

to this file,
vendor\barryvdh\laravel-dompdf\src\ServiceProvider.php

It solved the problem for me.

**Comment by votranquy** [comment]
`composer require barryvdh/laravel-dompdf` saves my day.

**Comment by 3robi-vollebregt** [comment]
:(

**Comment by 3robi-vollebregt** [comment]
@d3x773r  remoer

**Comment by SilvaEngComp** [comment]
I solved this problem habiliting "ITL" extension in php,ini

**Comment by mecjos** [comment]
I have same problem on production. I uploaded /barryvdh and dompdf folders from vendor directly and config/app file. It gives that error. I can see it in composer.json. When I run 'php artisan cache:clear or composer dump-autoload' it gives same error, 'Barryvdh\DomPDF\ServiceProvider' not found...

**Comment by vickymessii** [comment]
@mecjos  did you run `composer dump-autoload`

**Comment by mecjos** [comment]
@vickymessii Yes. When I run it gives same error. By the way I am running that commands vie ssh connection to godaddy shared hosting. Is this can be reason?

**Comment by vickymessii** [comment]
@mecjos 

Okay. Try to clone Repo on localhost & install this package on localhost then try if it works.

**Comment by mecjos** [comment]
@vickymessii it works on local. There is No error on local.

**Comment by RosaEmily** [comment]
> @vickymessii it works on local. There is No error on local.

did you manage to solve the problem?

**Comment by vickymessii** [comment]
> > @vickymessii it works on local. There is No error on local.
> 
> did you manage to solve the problem?

Yes i did solved this problem 
Are you facing same issue ?

**Comment by robchava** [comment]
I was able to fix it this way:
Previous: `use Barryvdh\DomPDF\Facade as PDF;`
Updated: `use Barryvdh\DomPDF\Facade\Pdf as PDF;`

**Comment by haseebmirza** [comment]
well done @robchava
