### ISSUE TITLE
facade not work

### ISSUE THREAD

**Issue by ebrahimradi** [barryvdh/laravel-dompdf#50]
Hi
I've done all steps but when I use PDF::loadView, Laravel can not find PDF Class.
in addition,  I used ./composer.phar dump-autoload too.

**Comment by fordarnold** [comment]
Thanks. This worked for me :+1:

**Comment by baljeetbhinder** [comment]
worked for me too, was forgetting adding to aliases after i added it worked fine thanks allot (Y)

**Comment by AAgung** [comment]
Hi,
I've done all steps but Laravel can not find Dompdf Class.
What's the problem... Thanks.. :D

**Comment by nelsontubaina** [comment]
does not work at all for me.
