### ISSUE TITLE
not printing more than 2 pages

### ISSUE THREAD

**Issue by cypherinc** [barryvdh/laravel-dompdf#504]
Hi folks, I am generating a report which consist of 3 to 4 pages but due to some problem it only displays 2 pages and page cuts after 2 pages, please have a look at the code and suggest something.

`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" >
        <title>RushRide</title>
        <style>
            @import url('https://fonts.googleapis.com/css?family=Lato:300,400,700,900');
            html, body{margin: 0; padding: 0; font-family: 'Lato', sans-serif; background-color:#fff; font-weight:400;}
            h2{font-size:30px; color:#002c40; font-weight:900; line-height:30px; margin:25px 0 }
            h2 span{color:#fc6829; font-weight:900}
            .blue_label{background-color:#fff; border:#dadada 1px dashed; margin-bottom:10px; padding:10px 15px;  font-family: 'Lato', sans-serif; font-size:16px; color:#002c40;}
            .blue_label span{color:#fc6829}
            .detail_box{background-color:#fff; border:#dadada 1px dashed; margin-bottom:30px;}
            .detail_box .title{font-size:20px; color:#002c40; font-weight:900; line-height:28px; padding:10px 25px; border-bottom:#dadada 1px dashed; text-align:center; background-color:#f9f9f9}
            .detail_box .title span{color:#fc6829; font-weight:900}
            .detail_box .driver_photo{width:130px; height:130px; border:#f1f1f1 2px solid; border-radius:50%; padding:5px; margin:20px auto }
            .detail_box .driver_photo img{width:100%; border-radius:50%;}
            .detail_box .driver_name{font-size:18px; color:#002d41; line-height:20px; font-weight:400; padding:10px 0; text-align:center; }
            .detail_box .detail{ font-family: 'Lato', sans-serif; text-align:center; border-top:#dadada 1px dashed; font-size:14px; color:#002d41; line-height:18px; letter-spacing:0px; padding:8px 15px}
            .detail_box .detail span{color:#fc6829}
            .table_list{border:#f1f1f1 1px solid; margin-bottom:20px}
            .table_list thead tr th{background-color:#052e45; color:#fff;  font-size:18px; font-weight:900; border:#f1f1f1 1px solid !important; border-bottom:none; padding:5px 15px }
            .table_list tbody tr td{ font-size:16px; color:#7c7c7c; font-weight:400; line-height:30px; border:#f1f1f1 1px solid !important;  padding:5px 15px }
            .table_list tbody tr td span{color:#fc6829; font-weight:700}
            .nobreak{
            page-break-inside: avoid;
            }
        </style>
    </head>
    <body>
        <table class="nobreak" width="600" border="0" align="center" cellpadding="0" cellspacing="0">
            <tr style="background:#052e45; padding:20px; text-align:center">
                <td style="padding:20px;" ><img src="images/footer_logo.png" alt="" /></td>
            </tr>
            <tr>
                <td>
                    <h2 style="text-align:center">Vehicle <span>Inspection</span></h2>
                    <table class="nobreak" width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
                        <tbody>
                            <tr>
                                <td style="padding-right:10px">
                                    <div class="blue_label">Start Date <span>{{$inspection->updated_at->format('m-d-Y')}}</span></div>
                                </td>
                                <td>
                                    <div class="blue_label">Report Expires <span>{{$inspection->updated_at->addDays(180)->format('m-d-Y')}}</span></div>
                                </td>
                                <td style="padding-left:10px">
                                    <div class="blue_label">Inspection Status <span>@if($inspection->main_status == 1) Passed @elseif($inspection->main_status == 2) Failed @elseif($inspection->main_status == 0) Draft @endif</span></div>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding-right:10px">
                                    <div class="detail_box">
                                        <div class="title">Vehicle <span>Info</span></div>
                                        <div class="driver_name">{{$vehicle->year_detail->title}} {{$vehicle->make_detail->title}} {{$vehicle->model_detail->title}} {{$vehicle->engine_detail->title}}</div>
                                        <div class="detail"><span>Color :</span> {{$vehicle->color}}</div>
                                        <div class="detail"><span>License Plate Number :</span> {{$vehicle->license_plate_no}}</div>
                                        <div class="detail"><span>VIN :</span> {{$vehicle->vin}} </div>
                                    </div>
                                </td>
                                <td>
                                    <div class="detail_box">
                                        <div class="title">Driver <span>Info</span></div>
                                        <div class="driver_name">{{$driver->firstname}} {{$driver->lastname}}</div>
                                        <div class="detail"><span>Email :</span> {{$driver->email}}</div>
                                        <div class="detail"><span>Phone :</span> {{$driver->phone}}</div>
                                        <div class="detail"><span>Address :</span> {{$driver->address}} </div>
                                    </div>
                                </td>
                                <td style="padding-left:10px">
                                    <div class="detail_box">
                                        <div class="title">Inspector <span>Info</span></div>
                                        <div class="driver_name">{{$inspector->name}}</div>
                                        <div class="detail"><span>Email :</span> {{$inspector->email}}</div>
                                        <div class="detail"><span>Phone :</span> {{$inspector->phone}}</div>
                                        <div class="detail"><span>Address :</span> {{$inspector->address}} </div>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <table class="table_list nobreak" width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Vehicle Assessment</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td colspan="3" bgcolor="#f9f9f9"><span>Driver & Vehicle Documents</span></td>
                            </tr>
                            <tr>
                                <td>Drivers License Number</td>
                                <td>{{$driver_vehicle_info->drivers_license_number}}</td>
                            </tr>
                            <tr>
                                <td>Drivers License Expiration</td>
                                <td>{{$driver_vehicle_info->drivers_license_expiration}}</td>
                            </tr>
                            <tr>
                                <td>Vehicle VIN</td>
                                <td>{{$driver_vehicle_info->vehicle_vin}}</td>
                            </tr>
                            <tr>
                                <td>Vehicle Tag Number</td>
                                <td>{{$driver_vehicle_info->vehicle_tag_number}}</td>
                            </tr>
                            <tr>
                                <td>Vehicle Color</td>
                                <td>{{$driver_vehicle_info->color}}</td>
                            </tr>
                            <tr>
                                <td>Driver's Profile Picture</td>
                                <td>{{$driver_vehicle_info->driver_profile_pic}}</td>
                            </tr>
                            <tr>
                                <td colspan="3" bgcolor="#f9f9f9"><span>Car General Overview</span></td>
                            </tr>
                            <tr>
                                <td>Cleanliness</td>
                                <td>{{$car_general_overview->cleanliness}}</td>
                            </tr>
                            <tr>
                                <td>Comfort</td>
                                <td>{{$car_general_overview->comfort}}</td>
                            </tr>
                            <tr>
                                <td>Exterior and Interior</td>
                                <td>{{$car_general_overview->exterior_interior}}</td>
                            </tr>
                            <tr>
                                <td>Safety Features</td>
                                <td>{{$car_general_overview->safety}}</td>
                            </tr>
                            <tr>
                                <td colspan="3" bgcolor="#f9f9f9"><span>Breaks & Suspensions</span></td>
                            </tr>
                            <tr>
                                <td>Car Shocks Condition</td>
                                <td>{{$break_suspensions_report->car_shocks_condition}}</td>
                            </tr>
                            <tr>
                                <td>Parking Brakes Engages</td>
                                <td>{{$break_suspensions_report->parking_brakes_engages}}</td>
                            </tr>
                            <tr>
                                <td>No Grinding Noise</td>
                                <td>{{$break_suspensions_report->no_grinding_noise}}</td>
                            </tr>
                            <tr>
                                <td>Vehicle Alignment</td>
                                <td>{{$break_suspensions_report->vehicle_alignment}}</td>
                            </tr>
                            <tr>
                                <td>Steering Merchanism</td>
                                <td>{{$break_suspensions_report->steering_merchanism}}</td>
                            </tr>
                            <tr>
                                <td colspan="3" bgcolor="#f9f9f9"><span>Electronics</span></td>
                            </tr>
                            <tr>
                                <td>Brake Lights Operational</td>
                                <td>{{$electronics_report->brake_lights_operational}}</td>
                            </tr>
                            <tr>
                                <td>Turn Indicators Operational</td>
                                <td>{{$electronics_report->turn_indicators_operational}}</td>
                            </tr>
                            <tr>
                                <td>Dashboard Electrical Components Functional</td>
                                <td>{{$electronics_report->dashboard_electrical_components_functional}}</td>
                            </tr>
                            <tr>
                                <td>Headlights</td>
                                <td>{{$electronics_report->headlights}}</td>
                            </tr>
                            <tr>
                                <td>Taillights</td>
                                <td>{{$electronics_report->taillights}}</td>
                            </tr>
                            <tr>
                                <td colspan="3" bgcolor="#f9f9f9"><span>Engine</span></td>
                            </tr>
                            <tr>
                                <td>Brake Fluid Level</td>
                                <td>{{$engine_report->brake_fluid_level}}</td>
                            </tr>
                            <tr>
                                <td>Engine Coolant Check</td>
                                <td>{{$engine_report->engine_coolant_check}}</td>
                            </tr>
                            <tr>
                                <td>Windshield Washer Fluid</td>
                                <td>{{$engine_report->windshield_washer_fluid}}</td>
                            </tr>
                            <tr>
                                <td>Automatic Transmission Fluid</td>
                                <td>{{$engine_report->automatic_transmission_fluid}}</td>
                            </tr>
                            <tr>
                                <td>Cabin Air Filter</td>
                                <td>{{$engine_report->cabin_air_filter}}</td>
                            </tr>
                            <tr>
                                <td>Power Steering Fluid</td>
                                <td>{{$engine_report->power_steering_fluid}}</td>
                            </tr>
                            <tr>
                                <td>Engine Fan</td>
                                <td>{{$engine_report->engine_fan}}</td>
                            </tr>
                            <tr>
                                <td colspan="3" bgcolor="#f9f9f9"><span>Emergency & Safety</span></td>
                            </tr>
                            <tr>
                                <td>Horn</td>
                                <td>{{$emergency_safety_report->horn}}</td>
                            </tr>
                            <tr>
                                <td>Safety Belts for Driver and Passenger</td>
                                <td>{{$emergency_safety_report->safety_belts}}</td>
                            </tr>
                            <tr>
                                <td>Fire Extinguisher</td>
                                <td>{{$emergency_safety_report->fire_extinguisher}}</td>
                            </tr>
                            <tr>
                                <td>Hazard Warning Triangle</td>
                                <td>{{$emergency_safety_report->hazard_warning_triangle}}</td>
                            </tr>
                            <tr>
                                <td>Jack and Accessories</td>
                                <td>{{$emergency_safety_report->jack_accessories}}</td>
                            </tr>
                            <tr>
                                <td>Spare Tyre</td>
                                <td>{{$emergency_safety_report->spare_tyre}}</td>
                            </tr>
                            <tr>
                                <td colspan="3" bgcolor="#f9f9f9"><span>Interior</span></td>
                            </tr>
                            <tr>
                                <td>Air Conditioner Functional</td>
                                <td>{{$interior_report->air_conditioner_functional}}</td>
                            </tr>
                            <tr>
                                <td>Floor and Foot Mat Condition</td>
                                <td>{{$interior_report->mat_condition}}</td>
                            </tr>
                            <tr>
                                <td>Interior & Exterior Rear View Mirrors</td>
                                <td>{{$interior_report->exterior_interior_mirros}}</td>
                            </tr>
                            <tr>
                                <td>Mirrors Adjustment</td>
                                <td>{{$interior_report->mirrors_adjustment}}</td>
                            </tr>
                            <tr>
                                <td>Odour Free</td>
                                <td>{{$interior_report->odour_free}}</td>
                            </tr>
                            <tr>
                                <td>Windscreen (Noise Free)</td>
                                <td>{{$interior_report->windscreen_noise_free}}</td>
                            </tr>
                            <tr>
                                <td>Vehicle Stereo Functional</td>
                                <td>{{$interior_report->vehicle_stereo_functional}}</td>
                            </tr>
                            <tr>
                                <td colspan="3" bgcolor="#f9f9f9"><span>Tyres</span></td>
                            </tr>
                            <tr>
                                <td>Correct Tyre Pressure</td>
                                <td>{{$tyres_report->correct_tyre_pressure}}</td>
                            </tr>
                            <tr>
                                <td>Tyre Thread</td>
                                <td>{{$tyres_report->tyre_thread}}</td>
                            </tr>
                            <tr>
                                <td>Thread Pattern Matches</td>
                                <td>{{$tyres_report->thread_pattern_matches}}</td>
                            </tr>
                            <tr>
                                <td>Same Tyre Brands</td>
                                <td>{{$tyres_report->same_tyre_brands}}</td>
                            </tr>
                            <tr>
                                <td colspan="3" bgcolor="#f9f9f9"><span>Overall Body Condition</span></td>
                            </tr>
                            <tr>
                                <td>Bumpers</td>
                                <td>{{$overall_body_condition_report->bumpers}}</td>
                            </tr>
                            <tr>
                                <td>Free of Scratches</td>
                                <td>{{$overall_body_condition_report->free_scratches}}</td>
                            </tr>
                            <tr>
                                <td>Free of Visible Dents</td>
                                <td>{{$overall_body_condition_report->free_of_visible_dents}}</td>
                            </tr>
                            <tr>
                                <td>No Windshield or Window Cracks</td>
                                <td>{{$overall_body_condition_report->no_windshield_or_window_cracks}}</td>
                            </tr>
                            <tr>
                                <td>Windshield Wipers Working</td>
                                <td>{{$overall_body_condition_report->windshield_wipers_working}}</td>
                            </tr>
                            <tr>
                                <td>No External Mirror Cracks</td>
                                <td>{{$overall_body_condition_report->no_external_mirror_cracks}}</td>
                            </tr>
                            <tr>
                                <td>Body Panel Colors Matches</td>
                                <td>{{$overall_body_condition_report->body_panel_colors_matches}}</td>
                            </tr>
                            <tr>
                                <td>Trunk Cleanliness</td>
                                <td>{{$overall_body_condition_report->trunk_cleanliness}}</td>
                            </tr>
                            <tr>
                                <td>Trunk Opens or Closes Freely</td>
                                <td>{{$overall_body_condition_report->trunk_opens_or_closes_freely}}</td>
                            </tr>
                            <tr>
                                <td>Muffler & Exhaust System </td>
                                <td>{{$overall_body_condition_report->muffler_exhaust_system}}</td>
                            </tr>
                            <tr>
                                <td colspan="3" bgcolor="#f9f9f9"><span>Windows & Locks</span></td>
                            </tr>
                            <tr>
                                <td>Door Locks Operational</td>
                                <td>{{$windows_locks_report->door_locks_operational}}</td>
                            </tr>
                            <tr>
                                <td>Door Handles Operational</td>
                                <td>{{$windows_locks_report->door_handles_operational}}</td>
                            </tr>
                            <tr>
                                <td>Window Control Operational</td>
                                <td>{{$windows_locks_report->window_control_operational}}</td>
                            </tr>
                            <tr>
                                <td colspan="3" bgcolor="#f9f9f9"><span>Inspection Photos</span></td>
                            </tr>
                            <tr>
                                <td>Front Side Photo</td>
                                <td><img src="{{$inspection_photos_report->front}}" height="100" width="100" alt=""></td>
                            </tr>
                            <tr>
                                <td>Rear Side Photo</td>
                                <td><img src="{{$inspection_photos_report->rear}}" height="100" width="100" alt=""></td>
                            </tr>
                            <tr>
                                <td>Driver Side Photo</td>
                                <td><img src="{{$inspection_photos_report->driver}}" height="100" width="100" alt=""></td>
                            </tr>
                            <tr>
                                <td>Passenger Side Photo</td>
                                <td><img src="{{$inspection_photos_report->passenger}}" height="100" width="100" alt=""></td>
                            </tr>
                            <tr>
                                <td>Trunk Photo</td>
                                <td><img src="{{$inspection_photos_report->trunk}}" height="100" width="100" alt=""></td>
                            </tr>
                            <tr>
                                <td>Inside Front Photo</td>
                                <td><img src="{{$inspection_photos_report->inside_front}}" height="100" width="100" alt=""></td>
                            </tr>
                            <tr>
                                <td>Inside Back Photo</td>
                                <td><img src="{{$inspection_photos_report->insode_back}}" height="100" width="100" alt=""></td>
                            </tr>
                            <tr>
                                <td colspan="3" bgcolor="#f9f9f9"><span>Comments</span></td>
                            </tr>
                            <tr>
                                <td>Comments</td>
                                <td>{{$comments_report->comments}}</td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </table>
    </body>
</html>
`

**Comment by angeline155** [comment]
what is the solution for this? We have same issue?

**Comment by AmineKam** [comment]
Please any solution! same issue :(

**Comment by AbdurRehman26** [comment]
Same issue ? Anyone ?

**Comment by AmineKam** [comment]
For me the solution is to do not use <table> in HTML
and using <div class="page-break"></div> for Page breaks

**Comment by AbdurRehman26** [comment]
Thanks. Worked for me

**Comment by bobbychumber** [comment]
working fine with <div>

**Comment by epochbrokers2** [comment]
> For me the solution is to do not use `<table>...</table>` in HTML and using `<div class="page-break"></div>` for Page breaks

If the content is printing in a loop and we can't use the page break, Data is not printing after two pages.
