### ISSUE TITLE
Remove the margin bottom on the page

### ISSUE THREAD

**Issue by murilolivorato** [barryvdh/laravel-dompdf#512]
Hello , how could I remove the margin on the bottom of the page ? I want make the page without margin ( margin: 0px ; ) .

![print_dom_2](https://user-images.githubusercontent.com/19832238/44545346-31ede600-a6eb-11e8-822f-44248aa86aec.jpg)

Thanks

**Comment by santiblanko** [comment]
same here

**Comment by paejan** [comment]
> @page {
> margin-bottom:0px;
> }
> Works!

where to put this code?

**Comment by brada1703** [comment]
> > @page {
> > margin-bottom:0px;
> > }
> > Works!
> 
> where to put this code?

Put this within the style tags.

Example:

```
<style>
    @page { margin:0px; }
</style>
```
