### ISSUE TITLE
Laravel 5.5:Throws an error "This page isn't working" on production server.

### ISSUE THREAD

**Issue by priyakrishnadev** [barryvdh/laravel-dompdf#518]
Well, this package is working fine on local but not on production server. It throws an error say This page isn't working. If any information needed regarding this,please let me know.This question been asked in [stackoverflow ](https://stackoverflow.com/questions/48321361/laravel-barryvdh-dompdf-page-is-not-working-http-500-error)but no luck.So i'm posting issue here.thanks .

here is my controller code
`$pdf = PDF::loadView('pdf',[ 'users' => $users,'keys'=>$key])->save(public_path()."/quotations/data.pdf")->stream('download.pdf');`

**Comment by pankajsanam** [comment]
I don't think it has to do anything with the package itself. Can you please check the logs on the production server and see what exactly went wrong?

**Comment by IH4xx3R** [comment]
try it with :
PDF::setOptions([
            'logOutputFile' => storage_path('logs/log.htm'),
            'tempDir' => storage_path('logs/')
        ])->loadView('pdf',[ 'users' => $users,'keys'=>$key])->save(public_path()."/quotations/data.pdf")->stream('download.pdf');

**Comment by karani-gk** [comment]
You may need to delete the vendor folder, then run composer install
