### ISSUE TITLE
how can i display pdf inside pdf?

### ISSUE THREAD

**Issue by d9it** [barryvdh/laravel-dompdf#524]
Hello,
I am working in 1 portal in which I have 4 different steps, which are combined in last stage. At the last stage all steps data are combining in 1 pdf and I have to generate that pdf, normal data is working fine and also pdf is generating. But there are 2 steps among the 4, in which the user will upload pdf files. So at the last step we have to combine those 2 pdf also in our last pdf as data. Can you please help me ,how I can achieve this ?

**Comment by Gopalkrishna69** [comment]
Hey Hi,
 Can you please let me know how to write API for lumen for downloading PDF and let me know how to test in postman.. Thanks in advance.
