### ISSUE TITLE
Laravel 5.6 - 'ReflectionException: Class config does not exist' after registering provider in bootstrap/app.php

### ISSUE THREAD

**Issue by StrikeAgainst** [barryvdh/laravel-dompdf#525]
I just tried to setup this package in my Laravel (v5.6) project, after reloading the page I got this exception trace put out:

_Fatal error: Uncaught ReflectionException: Class config does not exist in /home/w19232/web/liebherr/vendor/laravel/framework/src/Illuminate/Container/Container.php:767 Stack trace: #0 /home/w19232/web/liebherr/vendor/laravel/framework/src/Illuminate/Container/Container.php(767): ReflectionClass->\_\_construct('config')
#1 /home/w19232/web/liebherr/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\Container\Container->build('config')
#2 /home/w19232/web/liebherr/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\Container\Container->resolve('config', Array)
#3 /home/w19232/web/liebherr/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->make('config', Array)
#4 /home/w19232/web/liebherr/vendor/laravel/framework/src/Illuminate/Container/Container.php(1210): Illuminate\Foundation\Application->make('config')
#5 /home/w19232/web/liebherr/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(57): Illumin in /home/w19232/web/liebherr/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 767_

which is not even represented in Laravel's usual exception UI but put out as plain string. After rolling back the setup step by step I figured out that this exception is caused by adding the line

`$app->register(\Barryvdh\DomPDF\ServiceProvider::class);`

into bootstrap/app.php

**Comment by StrikeAgainst** [comment]
Just realized I don't need this line if I don't use Lumen. My bad!

**Comment by pavanyogi** [comment]
Don't forget to use quotes if any of your environment variables contains space eg.
APP_NAME=_Laravel Learning_ // wrong, it will give an error
APP_NAME=**"Laravel Learning"** // correct, in my case it solved the problem.
