### ISSUE TITLE
Font Path

### ISSUE THREAD

**Issue by homeoftheunits** [barryvdh/laravel-dompdf#527]
Hi,

when i render an html i get the error:
```
fopen(/var/www/vendor/project/dompdf/dompdf/lib/fonts/2d8a5f4f3910ca74e71d55128d64c4fd.ufm): failed to open stream: Permission denied
```

I only use googlefonts, so i don't need this fonts, and i think it makes no sense to change the permission to 777, how can i solve this?

Cheers
Ralf

**Comment by willek** [comment]
I solve this issue by creating `fonts` directory inside `storage` and give it 777 permission,
I think this folder is to store a cache or something related to your fonts

**Comment by isometriq** [comment]
#269

**Comment by smknstd** [comment]
+1

**Comment by marcellopato** [comment]
This solution doesn´t work for me...

**Comment by mdference** [comment]
I'm having the same issue with Symfony any suggestions?
