### ISSUE TITLE
How we can create a PDF with 2 full height columns having BG color

### ISSUE THREAD

**Issue by aneeshsudhakaran** [barryvdh/laravel-dompdf#528]
Is this package support pdf without margins?
![resume template demo](https://user-images.githubusercontent.com/22345127/46907053-654e3380-cf2a-11e8-8dc3-dae17ec00647.png)

I would like to create a pdf like in the attached image. I need to show 2 Columns having background color.

Thanks in advance.

**Comment by daaner** [comment]
Yes!
```
* {
  margin: 0;
  padding: 0;
}
```
and no margins)
