### ISSUE TITLE
thai lang can't show

### ISSUE THREAD

**Issue by dukerspace** [barryvdh/laravel-dompdf#53]
$pdf = App::make('dompdf');
$pdf->loadHTML('<h1>ทดสอบ</h1>');
return $pdf->stream();

but empty in pdf . how to fix?

**Comment by chhumsina** [comment]
Hi @dukerspace ,

I also use @font-face but it still not work,
and has error like that:

**Comment by chhumsina** [comment]
![capture](https://cloud.githubusercontent.com/assets/3894767/9078114/7ba41808-3b61-11e5-8956-695fbc4fb75a.PNG)

Hi @dukerspace ,

I also use @font-face but it still not work,
and has error like above.

my code:

@font-face {
        font-family: Thai;
        src: url('fonts/thai-font/Thai.ttf');
    }

    h1{
        font-family: 'Thai';
    }

**Comment by barryvdh** [comment]
Can you make that directory in the storage dir and make it writable?

**Comment by mkumarjha** [comment]
I am facing the same problem with thai content with english . I am using  
"barryvdh/laravel-dompdf": "^0.8.1"
Laravel 5.3
Does not support thai have any solution please let me know
