### ISSUE TITLE
Breaking Layout - Tables

### ISSUE THREAD

**Issue by sanathdavis** [barryvdh/laravel-dompdf#531]
My HTML contains a big table.
Before the table begins, there are some details.
If my table fits perfectly in the second page, the first page will show only the details and the entire table is skipped to the second page.
This issue happens only when my table fits perfectly in the second table. In other cases the table is split into two.

**Comment by RobertB93** [comment]
Hello,
I have exactly the same problem as described above.

**Comment by Spartaa** [comment]
@linuxjuggler  @jdavidbakr  Anyone help us this from the moderator related to this
