### ISSUE TITLE
Blank pages when using outside of browser

### ISSUE THREAD

**Issue by andresilva-cc** [barryvdh/laravel-dompdf#532]
I'm using DOMPDF to generate reports in my application and I encountered the following problem:

When I hit my route through a browser, it displays the PDF correctly inside the browser, however, if I try to access it via Postman, it returns blank pages only.

Even if I set 'Accept' and 'Content-Type' headers to 'application/pdf', it still doesn't work.

This is my method:

```
    $pdf = \App::make('dompdf.wrapper');

    // PDF Content
    $pdf->loadView('report.entries', [
      'entries' => $this->all()->sortByDesc('control.datetime')
    ]);

    // Set as A4 Landscape
    $pdf->setPaper('a4', 'landscape');

    // Add page count
    $pdf->output();
    $dom_pdf = $pdf->getDomPDF();
    $canvas = $dom_pdf->get_canvas();
    $canvas->page_text($canvas->get_width() - 105, $canvas->get_height() - 35, "Página {PAGE_NUM} de {PAGE_COUNT}", null, 10, array(0, 0, 0));

    return $pdf->stream();
```

My view has nothing special, just a header and a table with the content, without any import of CSS or scripts.

**Comment by thiagoeliasr** [comment]
Well, I don't think this is a problem with dompdf at all, but with Postman. I had the same problem, but then I realised that I was clicking in **[Send]** button instead of clicking the down-arrow in this same button and then selecting "Send and Download". After that, my downloaded PDF file was ok.
