### ISSUE TITLE
save('filename') is hanging

### ISSUE THREAD

**Issue by jpascoe** [barryvdh/laravel-dompdf#535]
/** @var $pdf PDF * */
            $pdf = PDF::loadView('scan.' . $template, ['data' => $data,
                'weight' => $weight,
                'height' => $height,
                'measurement' => $measurement,
                'member' => json_decode($memberscan->apiMember, true)])
                ->setPaper('a4')
                ->save($this->savePath . $this->serverPdf);

When called from browser, this works perfectly, but when called from CLI it hangs with no errors. Any ideas would be greatly appreciated.
The values sent are identical for browser and cli.

Thanks in advance
Jason

**Comment by tarikhagustia** [comment]
same here ..
