### ISSUE TITLE
save the pdf file in storage folder

### ISSUE THREAD

**Issue by almi9** [barryvdh/laravel-dompdf#540]
Hi

how I can pass variables to pdf then generate the file from blade page 
after that Upload the file path in database??

thank you

**Comment by whizsid** [comment]
Hy @almi9  You can [getOriginalContent](https://laravel.com/api/5.7/Illuminate/Http/Response.html#method_getOriginalContent) from http response in laravel to get contents to a variable. Then put contents to your file.

```
$content = $pdf->download()->getOriginalContent();

Storage::put('public/csv/name.pdf',$content) ;
```

**Comment by garhbod** [comment]
Hi another option is to use the `output()` method before returning the `stream()` or `download` method

```
$pdf = PDF::loadView('pdf.invoice', $data);

Storage::put('public/pdf/invoice.pdf', $pdf->output());

return $pdf->download('invoice.pdf');
```

**Comment by garhbod** [comment]
Fonts go a bit weird with my solution so go with @whizsid's

**Comment by Harhukam** [comment]
Using laravel 6   i used this method for download and save pdf 
public function downloadPostPdf($id)
    {
        $post = Post::find($id);
        $pdf = PDF::loadView('post-pdf', compact('post'));

        $path = public_path('pdf/');
        $fileName =  $post['title'] . '.' . 'pdf' ;
        $pdf->save($path . '/' . $fileName);
        return $pdf->download($fileName);
    }

**Comment by Fionajeremychik** [comment]
For window platform, the above is not working but it works in linux/unix envirnoment

I used 
$path = storage_path('pdf/');
    $fileName =  $post['title'] . '.' . 'pdf' ;
    $pdf->save($path . '/' . $fileName);
    return $pdf->download($fileName);

**Comment by Fionajeremychik** [comment]
I tried to use
$pdf->save($path . '\\' . $fileName);
The path is correct but I got the following error
file_put_contents() failed to open stream: no such file or directory

**Comment by impactcolor** [comment]
@whizsid hi in your example is $pdf the file rendered by domPdf?  In example is this how it would look complete:
`      $url = base_path() . '/vendor/dompdf/dompdf/pdfs/email-price-quote.html';
      $pdf = new Dompdf();
      $pdf->load_html_file($url);
      $pdf->render();`

**Comment by latif-developers-studio** [comment]
> Using laravel 6 i used this method for download and save pdf
> 
> use Barryvdh\DomPDF\Facade as PDF;
> 
> public function downloadPostPdf($id) { $post = Post::find($id); $pdf = PDF::loadView('post-pdf', compact('post'));
> 
> ```
>     $path = public_path('pdf/');
>     $fileName =  $post['title'] . '.' . 'pdf' ;
>     $pdf->save($path . '/' . $fileName);
>     return $pdf->download($fileName);
> }
> ```

It's working fine on the local server but not doing save files on the live server. Can you help me please to solve out it.
Thanks

**Comment by Harhukam** [comment]
check your directory permissions on server

**Comment by latif-developers-studio** [comment]
> check your directory permissions on server

I have checked. The directory has www-data permissions.
