### ISSUE TITLE
Can't add custom font in dompdf.

### ISSUE THREAD

**Issue by sayanthkoroth** [barryvdh/laravel-dompdf#541]
```
@font-face {
      font-family: CUSTOM;
      src:url('{{public_path("/themes/fonts/custom.ttf")}}')  format('truetype')
    }
```

Hy @barryvdh  I just tried to add a custom font for generating pdf file. But it always shows an error **_'Undefined index tree'._** Is anyone had the same issue before ?. Please help.

![treeerror](https://user-images.githubusercontent.com/29120488/49782382-1c550880-fd3c-11e8-967d-f0373c3ec1ae.png)

**Comment by jasperf** [comment]
How did you solve your issues @sayanthkoroth ?

**Comment by sicaboy** [comment]
How did you solve your issues @sayanthkoroth ?

**Comment by WahidinAji** [comment]
How did you solve your issues? @sayanthkoroth
