### ISSUE TITLE
Error PHP 7.2: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by edsonrodsilva** [barryvdh/laravel-dompdf#554]
I'm getting this error while updating the PHP version.
Error PHP 7.2: count (): Parameter must be an array or an object that implements Countable
Someone else is also having this error.

**Comment by lalustine7** [comment]
can you show the code where you have used count() function because count() function now only accept array. I think you have passed one object only. You need to pass array of object.

**Comment by kangfq** [comment]
I have the same problem as you. My solution is to modify the file:

`\vendor\phenx\php-svg-lib\src\Svg\Document.php`

Line 259,
```
if (count($this->attributes){
    $tag = new Group($this, $name);
}
```
amend
```
 if (count((Array)$this->attributes)) {
     $tag = new Group($this, $name);
 }
```

> End!
