### ISSUE TITLE
ErrorException: A non well formed numeric value encountered PHP 7.2

### ISSUE THREAD

**Issue by nguyentvnhat** [barryvdh/laravel-dompdf#557]
ErrorException: A non well formed numeric value encountered in /var/app/current/vendor/dompdf/dompdf/include/style.cls.php:491
Stack trace:
#0 /var/app/current/vendor/dompdf/dompdf/include/style.cls.php(491): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'A non well form...', '/var/app/curren...', 491, Array)
#1 /var/app/current/vendor/dompdf/dompdf/include/image_frame_reflower.cls.php(83): Style->length_in_pt(Array)
#2 /var/app/current/vendor/dompdf/dompdf/include/image_frame_reflower.cls.php(34): Image_Frame_Reflower->get_min_max_width()
#3 /var/app/current/vendor/dompdf/dompdf/include/frame_decorator.cls.php(711): Image_Frame_Reflower->reflow(Object(Table_Cell_Frame_Decorator))
#4 /var/app/current/vendor/dompdf/dompdf/include/table_cell_frame_reflower.cls.php(90): Frame_Decorator->reflow(Object(Table_Cell_Frame_Decorator))
#5 /var/app/current/vendor/dompdf/dompdf/include/frame_decorator.cls.php(711): Table_Cell_Frame_Reflower->reflow(NULL)
#6 /var/app/current/vendor/dompdf/dompdf/include/table_row_frame_reflower.cls.php(40): Frame_Decorator->reflow()
#7 /var/app/current/vendor/dompdf/dompdf/include/frame_decorator.cls.php(711): Table_Row_Frame_Reflower->reflow(NULL)
#8 /var/app/current/vendor/dompdf/dompdf/include/table_row_group_frame_reflower.cls.php(37): Frame_Decorator->reflow()
#9 /var/app/current/vendor/dompdf/dompdf/include/frame_decorator.cls.php(711): Table_Row_Group_Frame_Reflower->reflow(NULL)
#10 /var/app/current/vendor/dompdf/dompdf/include/table_frame_reflower.cls.php(480): Frame_Decorator->reflow()
#11 /var/app/current/vendor/dompdf/dompdf/include/frame_decorator.cls.php(711): Table_Frame_Reflower->reflow(Object(Block_Frame_Decorator))
#12 /var/app/current/vendor/dompdf/dompdf/include/block_frame_reflower.cls.php(750): Frame_Decorator->reflow(Object(Block_Frame_Decorator))
#13 /var/app/current/vendor/dompdf/dompdf/include/frame_decorator.cls.php(711): Block_Frame_Reflower->reflow(NULL)
#14 /var/app/current/vendor/dompdf/dompdf/include/page_frame_reflower.cls.php(123): Frame_Decorator->reflow()
#15 /var/app/current/vendor/dompdf/dompdf/include/frame_decorator.cls.php(711): Page_Frame_Reflower->reflow(NULL)
#16 /var/app/current/vendor/dompdf/dompdf/include/dompdf.cls.php(973): Frame_Decorator->reflow()
#17 /var/app/current/vendor/barryvdh/laravel-dompdf/src/PDF.php(208): DOMPDF->render()
#18 /var/app/current/vendor/barryvdh/laravel-dompdf/src/PDF.php(154): Barryvdh\DomPDF\PDF->render()
#19 /var/app/current/vendor/barryvdh/laravel-dompdf/src/PDF.php(191): Barryvdh\DomPDF\PDF->output()

**Comment by meztor** [comment]
$ret += ((float)(mb_substr($l, 0, $i)))  * 72  / $dpi;

**Comment by nguyentvnhat** [comment]
@meztor thank you for responding. it solved after I updated to latest version
