### ISSUE TITLE
View [pdf.invoice] not found.

### ISSUE THREAD

**Issue by dabenedito** [barryvdh/laravel-dompdf#560]
I just install the dompdf on my project, it works quite good when I used 
`$pdf = App::make('dompdf.wrapper');`
`$pdf->loadHTML('<h1>Testing</h1>');`
`return $pdf->stream();`

Now, I'm trying to load a HTML file and it's not working!
It's says "View [welcome.blade.php] not found."

**Comment by hackerunet** [comment]
Do you know where to host the views?

**Comment by mikerodham** [comment]
This is not an issue with this package, this is simply because you're referencing a file with something like `return view('welcome');`

There is not a file @ `resources/views/welcome.blade.php` so go create one.
