### ISSUE TITLE
SSL issues - setHttpContext

### ISSUE THREAD

**Issue by pdiveris** [barryvdh/laravel-dompdf#567]
I ran into some issues on my local environment where Dompdf would not load images over a site running with a self issued SSL certificate. When it comes to using file_get_contents which Dompdf preferes over curl, one could pass a http context to it making it ignore SSL certificate errors.

This could be done like
```      
$arrContextOptions = array(
        "ssl" => array(
          "verify_peer" => false,
          "verify_peer_name" => false,
        ),
      );
```
and 

`$this->dompdf->setHttpContext(stream_context_create($arrContextOptions));`

 in PDF.php for example in a new method setHttpContext.

I have modified my local version of your PDF.php as to include a `setHtthpContext()` which is a wrapper around Dompdf's own `setHttpContext` method. I wonder then if you'd like to have a look at the addition and tell me how I could raise a PR (i.e. which branch etc.)

**Comment by vgoncalves13** [comment]
I was with this problem. Fixed with creation of the method.

**Comment by sunickk** [comment]
https://blog.skunkbad.com/php/dompdf-image-not-found-or-type-unknown

**Comment by rubenlopezgea** [comment]
You can interact with the dompdf object if you don't access it through the Facade:

```
$pdf = PDF::getFacadeRoot();
$dompdf = $pdf->getDomPDF();
$dompdf->setHttpContext(stream_context_create([
    'ssl' => [
        'verify_peer' => FALSE,
        'verify_peer_name' => FALSE,
        'allow_self_signed'=> TRUE
    ],
]));
return $pdf->loadView('____');
```
