### ISSUE TITLE
Lumen 5.7 sample API Need for download PDF 

### ISSUE THREAD

**Issue by Gopalkrishna69** [barryvdh/laravel-dompdf#569]
Hi Guys,
 I need help in writing sample API call for downloading PDF in lumen, Here how to use in postman,

Thanks in advance....

**Comment by hermanwhyd** [comment]
$summary = $this->getUserSummary($request);
        
$pdf = app()->make('dompdf.wrapper');
$pdf->loadView('report.UserSummary', compact('result'))->setPaper('a4', 'portrait');
return $pdf->stream();

// resources/views/report/UserSummary.blade.php
