### ISSUE TITLE
Images not shown in PDF

### ISSUE THREAD

**Issue by MaazAli** [barryvdh/laravel-dompdf#57]
I'm not sure why but when I add in images, the pdf doesn't display it. However, when I see the html on the page, it shows up normally.

This is the error that displays on the pdf

```
Image not readable or empty
/images/logo.png 
```

Not sure what it is, but I can see the images in the HTML that is used to generate the PDF.

**Comment by vadimwe** [comment]
works fine in last version. In old version need to update dompdf package manually

**Comment by RokSiEu** [comment]
Was this problem ever solved? Because it seems that it wasn't. 
When I do 
```php
dd($view->render());
```
everything is OK, image is displayed. 

but when I do 
```php
$html = View::make('emails.upn.pdf-invoice', $data);
$pdfUPN = PDF::loadHTML($html)->stream();
$randomTime = time();
if (!is_dir("upn/")) {
     mkdir("upn/");
}
file_put_contents('./upn/'.$CaseID.'-'.$randomTime.'.pdf',$pdfUPN);
$pdf = './upn/'.$CaseID.'-'.$randomTime.'.pdf';
```

PDF doesn't contain image. 
Here's HTML/CSS code that is used in emails.upn.pdf-invoice

```html
 <html>
<head>
<meta http-equiv="Content-Type" content="charset=utf-8" />
<meta charset="UTF-8">
<title>PDF Upn</title>

<style type="text/css">
 * {
     font-family: "DejaVu Sans";
     font-size: 8px;
    }
.upn{background-image:url("https://sub.domain.com/upn.jpg"); background-repeat:no-repeat; width:700px; height:342px; position:absolute;}
</style>
</head>
<body>
   <div class="upn">test</div>
</body>
```

**Comment by xAockd** [comment]
@RokSiEu 
The same problem.
For temporary fixing, I'm using the relative path to my assets "upn.jpg"
Even path what built by asset helper doesn't help me.

**Comment by bebnev** [comment]
Hi
@xAockd, @RokSiEu can you provide some more information about this problem, because I have just installed fresh laravel app (5.1.8) and laravel-dompdf (0.6.0) I used the code that @RokSiEu had provided, but i get pdf with the image (even when using asset function).
The code:
```php
$html = View::make('emails.upn.pdf-invoice', []);
$pdfUPN = PDF::loadHTML($html)->stream();
$randomTime = time();
if (!is_dir("upn/")) {
  mkdir("upn/");
}
$CaseID = '123';
file_put_contents('./upn/'.$CaseID.'-'.$randomTime.'.pdf',$pdfUPN);
$pdf = './upn/'.$CaseID.'-'.$randomTime.'.pdf';
```
And the emails.upn.pdf-invoice:
```html
<html>
<head>
    <meta http-equiv="Content-Type" content="charset=utf-8" />
    <meta charset="UTF-8">
    <title>PDF Upn</title>

    <style type="text/css">
        * {
            font-family: "DejaVu Sans";
            font-size: 8px;
        }
        .upn {
          background-image:url("{{ asset('images/test.jpg') }}");
          background-repeat:no-repeat;
          width:700px;
          height:342px;
          position:absolute;
       }
    </style>
</head>
<body>
<div class="upn">test</div>
</body>
```
The output pdf
![output-pdf](https://cloud.githubusercontent.com/assets/8371521/9006675/2e763c1a-379b-11e5-95dc-9209fdb8fd0e.png)

**Comment by xAockd** [comment]
Found where is a problem! Just add the site to the hosts file, and all will works!

**Comment by RokSiEu** [comment]
What do you mean with "hosts" file?

**Comment by xAockd** [comment]
/etc/hosts file

**Comment by casank25** [comment]
@xAockd  +1, lost 1 day on this until i saw this.

**Comment by ericgeurts** [comment]
Can't get it to work on localhost:8000 with ``php artisan serve``

**Comment by AMABK** [comment]
This might help someone

This should do the trick.

`image_path = '/images/logo.pdf'
<img src="{{ public_path() . $image_path }}">`

**Comment by NestorAcevedo** [comment]
Hi, I currently have a problem. Images was showing for 3 or 4 generated pdf but now no images are shown. 

I am using the @AMABK code:
```
<?php $image_path = '/images/logo.jpg'; ?>
<img src="{{ public_path() . $image_path }}">

```
It was working as I said for 3 or 4 generated files but now the image is not showed. I save each html on a file and such files the image is showed. Now I am trying with decoded image but is unsuccessful.

I am using the version 0.4 for laravel 4.2

**Comment by hzung** [comment]
This trick works for me! 😃

Convert your Image file to Base64 format with these lines of code, and then include the `$imageData` into `src` attribute of `<img>` tag instead of an image URL.
```
$avatarUrl = 'https://assets-cdn.github.com/images/modules/logos_page/GitHub-Mark.png';
$arrContextOptions=array(
                "ssl"=>array(
                    "verify_peer"=>false,
                    "verify_peer_name"=>false,
                ),
            );
$type = pathinfo($avatarUrl, PATHINFO_EXTENSION);
$avatarData = file_get_contents($avatarUrl, false, stream_context_create($arrContextOptions));
$avatarBase64Data = base64_encode($avatarData);
$imageData = 'data:image/' . $type . ';base64,' . $avatarBase64Data;
```

**Comment by roshimon** [comment]
Thank you @hzung. Took lot of time at last found your solution & it just worked fine :)

**Comment by rdtandel** [comment]
<img src="http://www.example.com/assets/images/image.png">

You just need to change it to,

<img src="assets/images/image.png">

**Comment by nicoHersant** [comment]
@AMABK thanks! it did the trick!

**Comment by acedesigns** [comment]
HI Guys, I am still having this problem. My  setup is as follows. And I am using `Laravel 5.4.36`
The Image is not Showing up on the PDF.
I tried using @hzung example but a bit simpler.

### OS 
```
 System Version: macOS 10.12.6 (16G1036)
```
### PHP Version
```
PHP 7.1.8 (cli) (built: Aug 28 2017 11:09:12) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```
### Composer File
```
"laravel/framework": "5.4.*",
"barryvdh/laravel-dompdf": "^0.8.1"
```

### Controller
```php
public function downloadPDF ($id)
    {
        $user   = UserInfo::find($id);
        $pdf    = PDF::setOptions([
            'images' => true
        ])->loadView('customer.carFact', compact('user'))->setPaper('a4', 'portrait');
        return $pdf->download('carfact_sheet.pdf');
    }
```

### HTML :: customer/carFact.blade.php
```
    <?php
        $path = public_path('/assets/images/company_Logo.jpg');
        $type = pathinfo($path, PATHINFO_EXTENSION);
        $data = file_get_contents($path);
        $base64 = 'data:image/' . $type . ';base64,' . base64_encode($data);
    ?>
    <table class="table table-bordered" style="margin: 0px auto;">
        <tr>
            <td colspan="4" align="center">
                <img src=" {{ $base64 }}" alt=" " class="img-responsive">
            </td>
        </tr>
     ......
   </table>
```
#### The Image is not Showing up on the PDF.

**Comment by andresams** [comment]
@xAockd Thank you very much, your solution worked perfectly.

**Comment by acedesigns** [comment]
@andresams 
Do you mind to share your source code snippet of what/how you did it? **PLEASE !!**

**Comment by DominikStyp** [comment]
I wonder why local links with port doesn't work:
http://mydoiman.test:8000/images/x.jpg - doesn't work in pdf (works in browser)
but every other image from google images for example works.

**Comment by PhillyWebGuy** [comment]
@acedesigns 

Change path:

$path = public_path('/images/company_Logo.jpg');

And I specified size of image:

<img src="{{ $base64 }}" style="width: 100px; height:100px;">

**Comment by SabrineClarck** [comment]
@rdtandel thank you so much, it did the trick :100:

**Comment by CristianGno** [comment]
@hzung I do not know if you will read this, but I thank you, you have taken me out of a big hurry.

**Comment by abbatis** [comment]
> This might help someone
> 
> This should do the trick.
> 
> ```
> <?php $image_path = '/images/logo.pdf'; ?>
> <img src="{{ public_path() . $image_path }}">
> ```

I actually didn't expect this to work, but it does! How's this different from `public_path($image_path)`? 😕

**Comment by andreshg112** [comment]
I don't know why this is happening. It is working on shared hosting, it was working using Xampp on Zorin but It's not working using Docker on Mac.
![imagen](https://user-images.githubusercontent.com/15859884/54498353-55b98900-48d4-11e9-9700-508d09165993.png)

**Comment by emma255** [comment]
Me too i struggled for the same error for 3 days. Also when i tried tricks mentioned above, none of them worked too. But when i changed the image file to **.jpg** file(extension) everything worked well.

Laravel version: 5.8.38
PHP version: 7.3
barryvdh/laravel-dompdf version: 0.8.6

**Comment by emma255** [comment]
Me too i struggled for the same error for 3 days. Also when i tried tricks mentioned above, none of them worked too. But when i changed the image file to **.jpg** file(extension) everything worked well.

> <img src="{{ public_path('img/logo.jpg') }} > 

Laravel version: 5.8.38
PHP version: 7.3
barryvdh/laravel-dompdf version: 0.8.6

> 
> 
> I'm not sure why but when I add in images, the pdf doesn't display it. However, when I see the html on the page, it shows up normally.
> 
> This is the error that displays on the pdf
> 
> ```
> Image not readable or empty
> /images/logo.png 
> ```
> 
> Not sure what it is, but I can see the images in the HTML that is used to generate the PDF.

Me too i struggled for the same error for 3 days. Also when i tried tricks mentioned above, none of them worked too. But when i changed the image file to **.jpg** file(extension) everything worked well.

Laravel version: 5.8.38
PHP version: 7.3
barryvdh/laravel-dompdf version: 0.8.6

**Comment by emma255** [comment]
Me too i struggled for the same error for 3 days. Also when i tried tricks mentioned above, none of them worked too. But when i changed the image file to **.jpg** file(extension) everything worked well.

> <img src="{{ public_path('img/logo.jpg') }} > 

Laravel version: 5.8.38
PHP version: 7.3
barryvdh/laravel-dompdf version: 0.8.6

**Comment by mohsin82** [comment]
in my local, all images are working.

but in live site, some png images are working and some are not working.

i am using laravel dompdf


can some help me on this?

**Comment by maherelgamil** [comment]
You can fix it by adding full path of image not URL 
```php
public_path('images/logo.png ');
```

And it will be worked fine

**Comment by costatavares** [comment]
@andreshg112 
In my case, I added data: image / png; base64
directly in the img tag

<img src = "data: image / png; base64, 333343344343 />

for example

**Comment by Akaaal** [comment]
In my case, i'm using external css and spent time to figured out how to render background images. This works for me:

pdf.php :
```
$dompdf = new Dompdf();	
$content .= '<link type="text/css" media="all" href="https://mydomaine.com/path/to/pdf-css.php" rel="stylesheet" />';	
$dompdf->loadHtml($content);
```
pdf-css.php :
```
<?php
    header("Content-type: text/css; charset: UTF-8");
?>
<?php $image_path = 'https://mydomaine.com/path/to/images/test.jpg';  ?>
html, body { margin:20px;padding:0;width:100%;font-family:Helvetica;}
.testbkg {width:200px;height:200px;background-image:url(' <?php echo $image_path ?>');background-repeat: no-repeat;background-size: cover;background-position:center}
```

**Comment by aurawindsurfing** [comment]
For png files I simply do:

```
<div>
<img src="{{'data:image/png;base64,'.base64_encode(file_get_contents(public_path('images/logo.png')))}}" width="180"/>
</div>
```

for SVG files in this case this is an background image

```
<img class="backdrop" src="{{'data:image/svg+xml;base64,'.base64_encode(file_get_contents(public_path('images/backgroung.svg')))}}"/>
```

**Comment by harshwebdev22** [comment]
Here is the solution
use public_path method
 <img style="height: 100px" src="{{ public_path('admin/assets/img/logo.png') }}" alt="logo">
