### ISSUE TITLE
Trying to get property 'pertanyaan' of non-object 

### ISSUE THREAD

**Issue by L200150019** [barryvdh/laravel-dompdf#571]
i have a view like that and i want make a pdf download . my view **dont have error**

` <div class="box-body">
        
        <div class="col-lg-12 col-xs-12">
            <div class="box">
                <a href="{{ route('pdf',['download'=>'pdf']) }}">Download PDF</a>//function to download
              <div class="box-header">
                <center > <h3 class="box-title">PEMELIHARAAN DAN PERAWATAN ALAT UJI </h3> </center>
                
                <center> Jln. Kabupaten Sragen </center>
  
              
              </div>
              

                 <p> Laporan : {{ $pemeliharaan->status }} </p> 
                 <p> Tanggal : {{ $pemeliharaan->created_at }} </p> 
                 <p> Jenis Alat   : {{ $pemeliharaan->alat->nama_alat }} </p> 
                 <p> User    : {{ $pemeliharaan->user->name }} </p>  
                 
                
                 
                 <div class="box">
                    <div class="box-header">
                      <h3 class="box-title"></h3>
                    </div>
                    
                    <div class="box-body no-padding">
                      <table class="table table-condensed">
                        <tbody><tr>
                          <th style="width: 10px">#</th>
                          <th>Pertanyaan</th>
                          <th>Hasil</th>
                          {{--  <th style="width: 40px">Label</th>  --}}
                        </tr>
                        <tr>
                          <td>1.</td>
                          <td>{{ $pemeliharaan->pertanyaan['question1'] }}</td>
                          <td>
                              {{ $pemeliharaan->pertanyaan['answer1'] }}
                          </td>               
                        </tr>

                        <tr>
                          <td>2.</td>
                          <td>{{ $pemeliharaan->pertanyaan['question2'] }}</td>
                          <td>
                              {{ $pemeliharaan->pertanyaan['answer2'] }}
                          </td>
                        </tr>

                        <tr>
                          <td>3.</td>
                          <td>{{ $pemeliharaan->pertanyaan['question3'] }}</td>
                          <td>
                              {{ $pemeliharaan->pertanyaan['answer3'] }}
                          </td>
                        </tr>

                        <tr>
                          <td>4.</td>
                          <td>{{ $pemeliharaan->pertanyaan['question4'] }}</td>
                          
                            <td>
                              {{ $pemeliharaan->pertanyaan['answer4'] }}
                            </td>
                          
                        </tr>
                      </tbody></table>
                    </div>
                    
                  </div>

              
            </div>
            
          </div>
        
        </div>`

but this link 'download' having error like the tittle on my thread

its my controller 
```
`public function showQuestion(Request $request,$id)
    {
       
         $pemeliharaan = Pemeliharaan::find($id);
         
         $pemeliharaan->pertanyaan = json_decode($pemeliharaan->pertanyaan,true);
       
         if($request->has('download')){
            $pdf = PDF::loadView('users.view_question', $pemeliharaan);
            return $pdf->download('view_question.pdf');
        }
         
         return view('users.view_question',compact('pemeliharaan'));
        
    }`
```

and its my 2 route . to show view ,and 2 get pdf .

```
Route::get('/user/show/question/pdf/{id}','userController@showQuestion')->name('pdf');
Route::get('user/show/question/{id}', 'userController@showQuestion')->name('usershowQuestion');
```

can someone correct my code ? 

> Trying to get property 'pertanyaan' of non-object

**Comment by AyodejiO** [comment]
Hi, 

For your download, at the if structure, you need to convert the object to an array and access it in the blade as an array. Check the modification below:  
`public function showQuestion(Request $request,$id)
    {
       
         $pemeliharaan = Pemeliharaan::find($id);
              
         if($request->has('download')){
            $pdf = PDF::loadView('users.view_question', $pemeliharaan->toArray());
            return $pdf->download('view_question.pdf');
        }
       
         $pemeliharaan->pertanyaan = json_decode($pemeliharaan->pertanyaan,true);
         return view('users.view_question',compact('pemeliharaan'));
        
}`

**Comment by ravikumarchenna** [comment]
hi AyodejiO,

I have couple of objects to render to pdf. just likke this..

$pdf = PDF::loadView('invoice-pdf',['order'=>$order,
                                            'order_items'=>$order_items,
                                            'user'=>$user]);
