### ISSUE TITLE
How to test the download of a PDF

### ISSUE THREAD

**Issue by ErickZH** [barryvdh/laravel-dompdf#574]
Hi,

I want to test the following with PHPUnit

```php
$pdf = PDF::loadView('my_view', compact('data'));

return $pdf->download('my_file.pdf');

```

any ideas?

**Comment by jsamaniegog** [comment]
Why is it closed?... Did you solve it @ErickZH?

I would like to know how to test. I tried with $response->streamedContent() (https://laravel-news.com/testing-streamed-responses-in-laravel), but it doesn't work.

The test says: "The response is not a streamed response."

NOTE: I'm using $pdf->stream() instead $pdf->download()

**Comment by jsamaniegog** [comment]
Well, I've finally done a test like this:

```php
public function testShowPDF()
{
    $response = $this->get(route('test.pdf'));

    $response->assertStatus(200);
    $response->assertSee('[/PDF /Text ]')->assertSee('stream');
}
```

I don't know if it's okay, but hope that it would be useful to someone.

**Comment by ErickZH** [comment]
Hi, @jsamaniegog 
Use a PDF Facade mock.

in my controller

```php
public function download()
{
       /** @var \Barryvdh\DomPDF\PDF $pdf */
       $pdf = PDF::loadView('MY_VIEW.pdf');

       return $pdf->download("FILE_NAME.pdf");
  }
```
in my test
```php

PDF::shouldReceive('loadView')
             ->once()
             ->andReturnSelf()
             ->getMock()
             ->shouldReceive('download')
             ->once()
             ->with('FILE.NAME.pdf')
             ->andReturn('THE_PDF_BINARY_DATA');

**Comment by jsamaniegog** [comment]
Thank you very much @ErickZH
