### ISSUE TITLE
Khmer Unicode doesn't display correctly

### ISSUE THREAD

**Issue by vannakpanha** [barryvdh/laravel-dompdf#576]
![test](https://user-images.githubusercontent.com/9713986/57113256-edccde00-6d6d-11e9-89ae-289d49c15149.png)
Hi I have a problem with loadView to PDF and Khmer font seems not show correctly. Anyone have any idea?

**Comment by kirykr** [comment]
@vannakpanha can you send me your setup?

**Comment by VannochGIGB** [comment]
I also have this problem too...Pls kindly help me.

**Comment by Bornpagna** [comment]
> @vannakpanha can you provide more details about your code setup for the pdf?

i have this problem too . please have me.
![2019-10-02_17-28-29](https://user-images.githubusercontent.com/10671786/66037652-52b57b80-e53a-11e9-8741-b31413caa404.png)

and here is my code
![2019-10-02_17-32-26](https://user-images.githubusercontent.com/10671786/66037823-afb13180-e53a-11e9-9642-4254167aff49.png)

**Comment by kirykr** [comment]
I answer the problem her please take a look.
