### ISSUE TITLE
Default Page Border/Margin/Padding  - Remove or are these print margins?

### ISSUE THREAD

**Issue by MPJHorner** [barryvdh/laravel-dompdf#577]
Hey all,

Please see example below.
<img width="816" alt="ticket layout" src="https://user-images.githubusercontent.com/4990716/57285089-5daed180-70aa-11e9-95dd-4b2e74b678dd.png">

(The black line around the edge shows the edge of the paper/page)

1) I have made custom page which doesn't exist, essentially 1/3 of A4 = `DL` paper size, however I overrode this,

See the example, I have used 100% width/height and also done these using pixels.

However the page padding/margin (whatever you want to call it) or maybe it is even print margins are huge? I can't see any method to override these? How can I go to the edge or closer too?

Many thanks in advance.

**Comment by devuniverse** [comment]
It is helps anyone, 

add this to your head  
```
<style>
@page { margin:0px; }
</style>
```
