### ISSUE TITLE
Undefined index: VERY_HOT_GAY

### ISSUE THREAD

**Issue by Graf03d** [barryvdh/laravel-dompdf#578]
Good day. An unexpected error occurred:

Notice: Undefined index: VERY_HOT_GAY in /bhome/part3/03/vh46885/vakipaki.ru/www/new/post_pdf_all.php on line 6

Fatal error: Uncaught exception 'DOMPDF_Exception' with message 'No block-level parent found. Not good. ' in /bhome/part3/03/vh46885/vakipaki.ru/www/new/dompdf/include/inline_positioner.cls.php:38 Stack trace: # 0 /bhome/part3/03/vh46885/vakipaki.ru/www/new /dompdf/include/frame_decorator.cls.php(546): Inline_Positioner-> position () # 1 /bhome/part3/03/vh46885/vakipaki.ru/www/new/dompdf/include/text_frame_reflower.cls.php(331 ): Frame_Decorator-> position () # 2 /bhome/part3/03/vh46885/vakipaki.ru/www/new/dompdf/include/frame_decorator.cls.php(556): Text_Frame_Reflower-> reflow (NULL) # 3 / bhome / part3 / 03 / vh46885 / vakipaki.ru / www / new / dompdf / include / page_frame_reflower.cls.php (138): Frame_Decorator-> reflow () # 4 /bhome/part3/03/vh46885/vakipaki.ru/ www / new / dompdf / include / frame_decorator.cls.php (556): Page_Frame_Reflower-> reflow (NULL) # 5 /bhome/part3/03/vh46885/vakipaki.ru/www/new/dompdf/include/dompdf.cls .php (817): Frame_Decorator-> reflow () # 6 /bhome/part3/03/vh46885/vakipaki.ru/www/new/post_pdf_all.php(266): DOMPDF-> render () # 7 {main} in /bhome/part3/03/vh46885/vakipaki.ru/www/new/dompdf/include/inline_p ositioner.cls.php on line 38

What to do? Help me please.

**Comment by nicholaszuccarelli** [comment]
It looks like you're missing a VERY_HOT_GAY somewhere.
