### ISSUE TITLE
This file extension is forbidden

### ISSUE THREAD

**Issue by LuukPrins** [barryvdh/laravel-dompdf#580]
I'm trying to display PDF files in an iframe, but I get the "This file extension is forbidden" error when navigating to the page containing the iframe.

    public function paycheck($id)
    {
        $payments = Payment::findOrFail($id);
        $filename = $payments->file_name;
        $foldername = storage_path('app/public/loonstrookjes');
        $pathToFile= '/'. $foldername . '/' . $payments->filename;
        $pdf = PDF::loadFile($pathToFile)->stream($filename . '.pdf');
        dd($pdf);

        return view('paychecks.details', compact('payments', 'pdf'));
    }

Above is the function I'm trying to use to get the file and stream itself.

If someone has a function that works I'd love to hear it!

**Comment by craftcastle** [comment]
Hi there,

any luck with this issue? I'm going through the same thing and I've tried the following to no luck:

- change chroot
- modify file/folder permissions
- storage:link
