### ISSUE TITLE
Laravel + DomPDF how to count pages?

### ISSUE THREAD

**Issue by Cleitonesc** [barryvdh/laravel-dompdf#584]
I would like to bill the pages like this ... 1/30, 2/30
I saw several examples on the internet but I can not make it work. I'll leave the code below to see if anyone can help me.

`````
        $tipoAte = $request->input('tipoAtendimento');
        $resp = $request->input('colaborador');
        $inicio = $request->input('inicio')== "" ?  '1900-01-01' : $request->input('inicio');
        $fim = $request->input('fim')== "" ?  '9999-01-01' : $request->input('fim');

        $Registros = event::join('psicologos','psicologos.psi_codigo','=','events.psi_codigo')
        ->join('pacientes','pacientes.pac_codigo','=','events.pac_codigo')
        ->join('tipo_atendimentos','tipo_atendimentos.ate_codigo','=','events.ate_codigo')
        ->select('pacientes.pac_prontuario','pacientes.pac_nome_paciente','psicologos.psi_nome','tipo_atendimentos.ate_descricao',DB::raw("DATE_FORMAT(event_start_date,'%d/%m/%Y') as dtAtendimento")) 
        ->where('pacientes.emp_codigo', '=', session('empresa_id'))
        ->when($tipoAte, function ($query) use ($tipoAte) { 

        return $query->where('tipo_atendimentos.ate_codigo', $tipoAte);
                })
        ->when($resp, function ($query) use ($resp) { 

        return $query->where('psicologos.psi_codigo', $resp);
                })
        ->whereBetween('event_start_date', [$inicio, $fim])
        //->where('tipo_atendimentos.ate_codigo','=', $request->input('tipoAtendimento'))
        //->where('psicologos.psi_codigo','=', $request->input('colaborador'))
        ->orderBy('psicologos.psi_nome')
        ->get();
        
        
        return \PDF::loadView('RelatorioPSIConsultas', compact('Registros','Empresa'))
                ->setPaper('A4', 'landscape')
                //->stream('relatorio_alunos.pdf');
                ->download('Rel_Consultas_Psicologos.pdf');




`````
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Relatório de Consultas dos Psicólogos</title>
    <link href="{{asset('css/StyleRelatorios.css')}}" rel="stylesheet"> 
  </head>

  <body>
    <main>

    <h1  class="clearfix">
        @foreach ($Empresa as $cab)
        <small><span><img id="foto"  src="{{ $cab->emp_logo }}">

        </span>

        </small>
       {{ $cab->emp_rezao_social }}

        <div id="project">
          <div class="arrow"><div class="inner-arrow">Tel: {{ $cab->emp_tel }}</div></div>
          <div class="arrow"><div class="inner-arrow">E-mail: {{ $cab->emp_email }}</div></div>
          <div class="arrow"><div class="inner-arrow">Impresso em: {{ $cab->impresso }}</div></div>
        </div>
        <br>

        <span id="endereco">
        {{$cab->endereco}}
        </span>
        @endforeach
    </h1>
      <table class="tabela">
        <thead>
          <tr id="DescrColunas">
            <td>Prontuário</td>
            <td>Paciente</td>
            <td>Tipo de Atendimento</td>
            <td>Resp. Atendimento</td>
            <td>Atendimento</td>
          </tr>
        </thead>
        <tbody>
            @foreach ($Registros as $dados)
                <tr>
                    <td class="Menorcolumn">{{ $dados->pac_prontuario }}</td>
                    <td>{{ $dados->pac_nome_paciente }}</td>
                    <td>{{ $dados->ate_descricao }}</td>
                    <td>{{ $dados->psi_nome }}</td>
                    <td class="Menorcolumn">{{ $dados->dtAtendimento }}</td>
 
                </tr>
            @endforeach
        </tbody>
      </table>

    </main>
    <footer>

    </footer>
  </body>
</html>

**Comment by Atnaize** [comment]
Just use something like this:

```
return \PDF::loadView('RelatorioPSIConsultas', compact('Registros','Empresa'))
                ->setPaper('A4', 'landscape')
                ->setOption('footer-right','Page [page]/[topage]');
                ->download('Rel_Consultas_Psicologos.pdf');
```

And to actually add a page-break, in your view you need to put

```
<div style="page-break-after:always"></div>
```
