### ISSUE TITLE
UTF-8 issue

### ISSUE THREAD

**Issue by essteffan** [barryvdh/laravel-dompdf#585]
Hi. I've tried everything but it seems that nothing works.

So my diacritics are not shown correctly.

Here is my html page (part of it)
`<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

	<title>Invoice Nr {{ $invoice->id }}</title>

	<style>
		*{font-family: DejaVu Sans, serif}

		table{
			font-size: x-small;
		}
		td{
			padding: 3px;
		}
		tfoot tr td{
			font-weight: bold;
			font-size: x-small;
		}
		.fact{
			font-size: 16px;
		}
		footer {
			position: fixed;
			bottom: 170px;
			left: 0px;
			right: 0px;
		}
	</style>

</head>`

The view html works fine but the pdf generated doesn't show the diacritics.

i'm using  "barryvdh/laravel-dompdf": "dev-master",

any thoughts? 
thanks

**Comment by essteffan** [comment]
This is how it looks when i use FF
<img width="1107" alt="Screenshot 2019-06-03 at 21 10 14" src="https://user-images.githubusercontent.com/423842/58824118-01f14d00-8644-11e9-83a0-adbe0e6c619e.png">

In Chrome seems to work fine.

doesn't anyone knows why?

**Comment by essteffan** [comment]
@barryvdh Hi Can you help me out? Thanks!

**Comment by kakerdev** [comment]
@essteffan I was tired of this problem 6h, and now i found the solutins,
the problem consisted of retrieving the document, instead of using the command from "barryvdh / laravel-dompdf": 

> return $pdf->download('path to file');

I used the default download from laravel:

> return response()->download(path to file);

and it works, I do not know where the problem lies but I managed to get around it
My html: 


```
> <!DOCTYPE html>
>  <html>
>  
>  <head>
>      <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
>      <meta charset="utf-8">
>      <style>
>         body {
>              font-family: "dejavu sans", serif;
>              font-size: 12px;
>              color: #000;
>          }
>      </style>
>  </head>
>  
>  <body>
>   Test characters: <strong>" ąóśłćń"</strong>
>  </body>
>  
>  </html>
```

Function to generate
```
public function generate_pdf() {
       $path = public_path().'/pdf';
        $pdf = PDF::loadView('load_my_html_path');
        $pdf->save($path.'/my_pdf_name.pdf', 'UTF-8');
        return response()->download($path.'/my_pdf_name.pdf');
    }
```

**Comment by essteffan** [comment]
You are right @kakerdev 

It's working as expected!

Thank you so much!

**Comment by ShanurHUdayberenow** [comment]
as
