### ISSUE TITLE
How to loadview two or more times dompdf

### ISSUE THREAD

**Issue by Oussama-AMMYDRISS** [barryvdh/laravel-dompdf#588]
I want to load same view using function loadview more times to call array with another data 
 this is my code in controller:

`
public function store(Request $request)
   {

       error_log('Some message here.');
       if ( !empty ( $nbrrowsol ) ) {   
$pdf1=PDF::loadview('gestion_commandes.myPDF',['commandesol'=>$commandesol,'nbrrowsol'=>$nbrrowsol])->setPaper('a4', 'landscape');
        }

  if( !empty ( $nbrroweau ) ) {      
        $pdf2=PDF::loadview('gestion_commandes.myPDF',['commandeeau'=>$commandeeau,'nbrroweau'=>$nbrroweau])->setPaper('a4', 'landscape');
}

        $pdf=PDF::loadview('gestion_commandes.myPDF',['clients'=>$clients,'commercial'=>$commercial,'datereception'=>$datereception,'dateprelevement'=>$dateprelevement])->setPaper('a4', 'landscape');
       return $pdf->stream('hdtuto.pdf');//redirect('gestion_commandes/create'); 
  
   }
`

so, i want to add first $pdf1 to second $pdf2 
like this ===>    $pdf=$pdf1+$pdf2 
to pass all data of $pdf1 and $pdf2 to $pdf  for sending to view

i write this just to explain my probleme
is there a way to do that? i need help

**Comment by ekntrtmz** [comment]
All you need to do is to unset the variable, like this:

    $pdf = PDF::loadview('path/to/view', compact('data'));
    // stream, download or whatever
    unset($pdf);

    $pdf = PDF::loadview('path/to/another-view', compact('data'));
    // ...
