### ISSUE TITLE
Cannot load image to pdf 

### ISSUE THREAD

**Issue by sanjayacloud** [barryvdh/laravel-dompdf#590]
Hi everyone, 

I am trying to generate pdf attached to my logo. but it does not work. I got the below error. But If i trying to generate pdf without image its generate properly.  Also, bootstrap 4 grid does not work properly

**Comment by cristianmarint** [comment]
Have you try this? https://github.com/barryvdh/laravel-dompdf/issues/303#issuecomment-282502546

**Comment by safiullahsarhandi** [comment]
use base64 image

**Comment by smockermaster** [comment]
After a lot of documents and post, I finally fix this issue. As you use File Storage system in Laravel, you use
`php artisan storage:link`
to access to a readable/writable path. In my case:
`storage -> /var/www/mysite.com/storage/app/public`
So I use 
`<img src="{{ public_path().'/storage/logo-1.png' }}">`
This implies that my logo is located in /var/www/mysite.com/storage/app/public/logo-1.png
 I hope this help you!
