### ISSUE TITLE
"unlink(.png): No such file or directory" when trying to generate file with image

### ISSUE THREAD

**Issue by ScholtzC** [barryvdh/laravel-dompdf#591]
I am trying to generate a pdf with a image in it using dompdf in laravel. 

I am getting the following error.
![error](https://user-images.githubusercontent.com/19747529/60878372-e3cccd00-a23f-11e9-92e2-f257336a4252.jpg)

My link to the image is correct.

In my blade file.
$image_path = public_path() .'/storage/signatures/'.$independent->signature; 

In my controller:
$pdf = PDF::loadView('pdf.otp', compact('data'));

I have also tried editing the temp file directory in my dompdf/options.php file to :
$this->setTempDir("C:/Temp");

**Comment by abedputra** [comment]
Have you solve this problem?
