### ISSUE TITLE
PDF not working in Laravel 5.8

### ISSUE THREAD

**Issue by golam-sorwar** [barryvdh/laravel-dompdf#592]
Failed to load PDF document. Show always .How to solve this?

<img width="1440" alt="Screen Shot 2019-07-09 at 4 17 46 PM" src="https://user-images.githubusercontent.com/31072206/60880300-3a98cd80-a265-11e9-9229-70116ba16e09.png">

**Comment by cristianmarint** [comment]
Can u pls show some code? It will help to understand the problem better!

**Comment by golam-sorwar** [comment]
<img width="1018" alt="Screen Shot 2019-07-18 at 8 14 01 AM" src="https://user-images.githubusercontent.com/31072206/61424098-22dfda00-a934-11e9-942c-9aeb399cb5af.png">

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title>Mid Result</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <style>
  .colform{
    background-color: #f8f9f9;
    padding: 3rem;
    border: 1px solid #ecf7f9;
    border-radius: 8px;
  }
  .hiddencard{
    background-color: #fff0;
    border: 0px solid rgba(0, 0, 0, 0);
  }
  </style>
</head>
<body>
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-md-16 colform">
        <img class="rounded mx-auto d-block" src="{{ asset('BNCDA.png')}}" style="height: 80px;">
        <div class="card hiddencard">
          <div class="card-body text-center">
            @foreach ($mid_result as $value)
              <h4 class="border font-weight-bolder text-uppercase" style="padding:5px;color:black;width: 65%;margin:auto;">Mid Term Examination - {{ $value->year }} &nbsp {{ ' Group : '.$value->group }}</h4>
              @break
            @endforeach
          </div>
        </div>
        <div class="card hiddencard">
          <div class="card-body text-center">
            @foreach ($mid_result as $info)
              Name: <strong>{{ $info->studentinfo->name_student }}</strong> &nbsp &nbsp
              ID: <strong>{{ $info->id_num }}</strong> &nbsp &nbsp
              Class: <strong>{{ $info->class }}</strong> &nbsp &nbsp
              Section: <strong>{{ $info->section }}</strong> &nbsp &nbsp
              Roll: <strong>{{ $info->stuofficeform->roll_stu_office }}</strong>
              @break
            @endforeach
          </div>
        </div>
        <div class="card hiddencard">
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered table-hover text-center">
                <thead class="">
                  <tr class="text-uppercase">
                    <th scope="col">Subject</th>
                    <th scope="col">QZ-1 CQ</th>
                    <th scope="col">QZ-1 MCQ</th>
                    <th scope="col">QZ-2 CQ</th>
                    <th scope="col">QZ-2 MCQ</th>
                    <th scope="col">CQ</th>
                    <th scope="col">MCQ</th>
                    <th scope="col">CQ Total</th>
                    <th scope="col">MCQ Total</th>
                    <th scope="col">CQ CONV</th>
                    <th scope="col">MCQ CONV</th>
                    <th scope="col">Total</th>
                    <th scope="col">Lg</th>
                    <th scope="col">gp</th>
                    {{-- <th colspan="1">GPA</th> --}}
                  </tr>
                </thead>
                <tbody>
                  @php
                    $total=0;
                    $gp=0;
                  @endphp
                  @foreach ($mid_result as $values)
                    <tr>
                      <td >{{ $values->teacherassign->teacher_assign_subj_name }}</td>
                      <td >{{ $values->quiz_1_cq }}</td>
                      <td >{{ $values->quiz_1_mcq }}</td>
                      <td >{{ $values->quiz_2_cq }}</td>
                      <td >{{ $values->quiz_2_mcq }}</td>
                      <td >{{ $values->cq }}</td>
                      <td >{{ $values->mcq }}</td>
                      <td >{{ $values->cq_total }}</td>
                      <td >{{ $values->mcq_total }}</td>
                      <td >{{ $values->cq_conv }}</td>
                      <td >{{ $values->mcq_conv }}</td>
                      <td >{{ $values->total }}</td>
                      <td >{{ $values->mid_lg }}</td>
                      <td >{{ $values->mid_gp }}</td>
                    </tr>
                    @php
                      $total+=$values->total;
                      $gp+=$values->mid_gp;
                    @endphp
                  @endforeach
                  <tr>
                    <th colspan="11">Grand Total</th>
                    <td>{{ $total }}</td>
                    <td></td>
                    <td>{{ $gp/$mid_result->count() }}</td>
                    {{-- <td rowspan="8"></td> --}}
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div><br>
        <div class="table-responsive">
          <table class="table table-bordered text-center">
            <thead class="">
              <tr>
                <th colspan="3">Grading System</th>
                <th colspan="3">Signature</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Range</td>
                <td>Grade</td>
                <td>GPA</td>
                <td rowspan="7"></td>
                <td rowspan="7"></td>
                <td rowspan="7"></td>
              </tr>
              <tr>
                <td>80-100%</td>
                <td>A+</td>
                <td>5.00</td>
              </tr>
              <tr>
                <td>70-79%</td>
                <td>A</td>
                <td>4.00</td>
              </tr>
              <tr>
                <td>60-69%</td>
                <td>A-</td>
                <td>3.50</td>
              </tr>
              <tr>
                <td>50-59%</td>
                <td>B</td>
                <td>3.00</td>
              </tr>
              <tr>
                <td>40-49%</td>
                <td>C</td>
                <td>2.00</td>
              </tr>
              <tr>
                <td>33-39%</td>
                <td>D</td>
                <td>1.00</td>
              </tr>
              <tr>
                <td>0-32%</td>
                <td>F</td>
                <td>0.00</td>
                <td>Guarian</td>
                <td>Guide Teacher</td>
                <td>Principal</td>
              </tr>
            </tbody>
          </table>
          GP=Grade Point LG=Letter Grade GPA=Grade Point Average
        </div><br>
        <div class="text-right">
          <a href="#" onclick="print()" class="btn btn-md btn-outline-dark">Save</a>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
    print(){
      Window.print();
    }
  </script>
</body>
</html>
