### ISSUE TITLE
error in persian and arabic language

### ISSUE THREAD

**Issue by erfanhemmati** [barryvdh/laravel-dompdf#594]
hi friends
this package dose not support persian or arabic language
for why ?!

**Comment by mRamadan0101** [comment]
im working with laravel 5.7 & barryvdh/laravel-dompdf 0.8.4 fixed arabic letters as below:-

1- download the ar-php library for khaled.alshamaa from the following link
http://www.ar-php.org/ (its free arabic Library with LGPL license)

2 - extract and upload I18N folder inside dompdf folder

3- open Glyphs.php file in this path

vendor\dompdf\I18N\Arabic

search

          public function utf8Glyphs($str, $max_chars = 50

replace to

         public function utf8Glyphs($str, $max_chars = 150

4-in text_renderer.cls.php file
vendor/dompdf/dompdf/src/Render/Text.php

before class name class Text extends AbstractRenderer
add this

include DOMPDF_DIR . "/I18N/Arabic/Glyphs.php";
use I18N_Arabic_Glyphs;

before this line

$this->_canvas->text($x, $y, $text

add this code

 if ( ! class_exists( 'I18N_Arabic' ) ){
$Arabic = new I18N_Arabic_Glyphs('Glyphs');
$text = $Arabic->utf8Glyphs($text);

    }

in ur pdf file add this style

    body{
      font-family: DejaVu Sans, sans-serif;
    }

**Comment by Ammar09** [comment]
include(C:\laragon\www\tamaiuz\vendor\dompdf\dompdf/I18N/Arabic/Glyphs.php): failed to open stream: No such file or directory

this error appeared after i follow the instructions

**Comment by hannanstd** [comment]
use below package:
https://github.com/mccarlosen/laravel-mpdf

i tested and works with persian well.

**Comment by heshanmax** [comment]
> use below package: https://github.com/mccarlosen/laravel-mpdf
> 
> i tested and works with persian well.

@hannanstd when I use this all the pages come blank

**Comment by mounir4019** [comment]
juste use <body onload=" window.print();">
easy and perfect solution,
without domPdf

**Comment by mounir4019** [comment]
juste use <body onload=" window.print();">
easy and perfect solution,
without domPdf
