### ISSUE TITLE
Error Failed to load PDF document

### ISSUE THREAD

**Issue by devsan1** [barryvdh/laravel-dompdf#596]
$pdf = PDF::loadView('flight.PdfPage.booking.pdfPage',
                     compact('solutionSet', 'journey_type'));

$pdf->setPaper('A4', 'portrait');
         return $pdf->stream('san.pdf')->header('Content-Type','application/pdf');
![Screenshot from 2019-08-16 15-53-05](https://user-images.githubusercontent.com/54181470/63176523-fc4db580-c03d-11e9-82b3-74819643ebbc.png)

I am using laravel 5.5 with php 7.2

**Comment by jjoek** [comment]
Facing the exact same issue,  Was there a solution to this?
