### ISSUE TITLE
Remove HTTP Response header from generated PDF

### ISSUE THREAD

**Issue by alfgago** [barryvdh/laravel-dompdf#598]
Whenever I generate a PDF and download it, the file has a hidden header saying:

```
HTTP/1.0 200 OK
Cache-Control: no-cache, private
Content-Disposition: attachment; filename="Invoice.pdf"
Content-Length: 305525
Content-Type: application/pdf
```

Is there a way to remove this from the downloaded file? I do use this, so I get why it downloads with it, but is there any other way to force download without it? While keeping the custom filename

```
$headers = [
            'Content-Type' => 'application/pdf', 
            'Content-Description' => 'File Transfer',
            'Content-Disposition' => "attachment; filename={$filename}",
            'filename'=> $filename
        ];
        return response($file);
```

**Comment by barryvdh** [comment]
I think you can call output() directly and return your own response, or modify the existing response.
