### ISSUE TITLE
Please add "illuminate/support": 6.0.x

### ISSUE THREAD

**Issue by fylzero** [barryvdh/laravel-dompdf#599]
I am doing early testing with Laravel 6.0 and can't install because of the requirement set. Please bump this to support 6.0. Thanks!

**Comment by fylzero** [comment]
I am doing early testing with Laravel 6.0 and can't install because of the requirement set.  Please bump this to support 6.0.  Thanks!

**Comment by fylzero** [comment]
Even better set this to 5.x and up so it doesn't arbitrarily break with future updates.

**Comment by barryvdh** [comment]
Fixed https://github.com/barryvdh/laravel-dompdf/commit/a86e2d4c2e81760b6b605bb44a09e93a1b874331
