### ISSUE TITLE
i install  package   via composer on mac its not working its provide error Class dompdf does not exist

### ISSUE THREAD

**Issue by ajeet85** [barryvdh/laravel-dompdf#60]
i have install it on my window system its working fine but when i install on mac system its show error Class dompdf does not exist

**Comment by adiesdiaz** [comment]
hi, i have an issue .  i followed the steps to get the barruvdh but idk what else to do and i have the following error. So, can u give me a hand to solve this problem? thanks

PHP Fatal error:  Class 'Barryvdh\DomPDF\ServiceProvider' not found in /var/www/sgi/trunk/SGI/vendor/compiled.php on line 6466
                                                       
  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'Barryvdh\DomPDF\ServiceProvider' not found

**Comment by adiesdiaz** [comment]
where part of my project should i put the folders src and config ??
