### ISSUE TITLE
For Laravel 6, need to add laravel/helpers as a dependency

### ISSUE THREAD

**Issue by fylzero** [barryvdh/laravel-dompdf#600]
In Laravel 6, they have moved string helpers out to the laravel/helpers package.  I just needed to bring this in to work since you are using str_contains function in the ServiceProvider.php:69.

I would suggest to add laravel/helpers as a dependency package or rewrite this spot using strpos or something.

Thanks again!

**Comment by barryvdh** [comment]
Fixed by https://github.com/barryvdh/laravel-dompdf/pull/601 ?

**Comment by fylzero** [comment]
Yes!  Thanks!
