### ISSUE TITLE
Call to undefined method Dompdf\Dompdf::loadView()

### ISSUE THREAD

**Issue by David91vlc** [barryvdh/laravel-dompdf#610]
Hello,

In version 0.5.* (with php 5.5) I used the method loadView to load a view in resources/views with array data to create PDF

I updated to php 7.2 and dompdf to versión 0.8.* and now shows error:

Call to undefined method Dompdf\Dompdf::loadView()

Any idea to repair this? This function is deprecated?

Thanks

**Comment by barryvdh** [comment]
Don't call dompdf directly, but call this package class.

**Comment by David91vlc** [comment]
I don't understand you, I calling App::make('dompdf') 

My code (works in 0.5 version) is:

```
$pdf = App::make('dompdf');
				$pdf->loadView('view', $array);
				$pdf->render();
				return $pdf->stream();

```

**Comment by David91vlc** [comment]
I solved calling this:

$pdf = App::make('dompdf.wrapper');
