### ISSUE TITLE
Dompdf Laravel is not displaying background image using css

### ISSUE THREAD

**Issue by wajid8703** [barryvdh/laravel-dompdf#626]
I am trying to set background image but laravel dompdf is not displaying it 
`style="background:url(http://abc.com/images/img.png)"`

any solution for this problem?

**Comment by ericpereira** [comment]
same problem with "background-image", any suggestions to solve it?

**Comment by gustavo9810** [comment]
Same problem here... actually none of the css changes are working

**Comment by whoisthisstud** [comment]
Same here

**Comment by truelet** [comment]
I have used it like below:
`background: url("{{ URL::asset('admin_css') }}/images/back-img1.jpg");
    background-size: 1024px 722px;
    background-repeat: no-repeat;`

and it is working.

**Comment by sayhicoelho** [comment]
try `background: url({{ public_path('path/to/image.jpg') }})`

**Comment by mRamadan0101** [comment]
url images will not loaded 
use public_path to load any images
try background: {{ public_path('path/to/image.jpg') }}

**Comment by alihamza509** [comment]
<img src="{{'data:image/png;base64,'.base64_encode(file_get_contents(public_path('images/logo.png')))}}" width="180"/> 
use this syntax for png

**Comment by pkaskers** [comment]
#

> use: src="{{'data:image/png;base64,'.base64_encode(file_get_contents(public_path('images/logo.png')))}}" width="180"

it works on me with this, perhaps there's security measure on the website default mechanism
also i use div while placing my background image

<div style="background-image: url('{{'data:image/png;base64,'.base64_encode(file_get_contents(public_path('img/balai-tp.png')))}}'); background-attachment:fixed; background-size:cover; background-repeat: no-repeat;" class="bg-image">

<body>
content
</body>

</div>

**Comment by pkaskers** [comment]
> > use: src="{{'data:image/png;base64,'.base64_encode(file_get_contents(public_path('images/logo.png')))}}" width="180"
> 
> it works on me with this, perhaps there's security measure on the website default mechanism also i use div while placing my background image

<wdiv style="background-image: url('{{'data:image/png;base64,'.base64_encode(file_get_contents(public_path('img/balai-tp.png')))}}'); background-attachment:fixed; background-size:cover; background-repeat: no-repeat;" class="bg-image">

<wbody>
content
<w/body>
<w/div>

im using w there because if there's no letter w in this comment, the code wont pop-up

**Comment by pkaskers** [comment]
![image](https://github.com/barryvdh/laravel-dompdf/assets/107665076/a2085c33-448c-4da9-8f13-a5a50ff072ae)

**Comment by Hammad-Naseer** [comment]
<img src="data:image/png;base64,{{ base64_encode(file_get_contents('
[https://devoneclick.secureism.com:8001/public/images/AmirReportShapeLines.png'))](https://devoneclick.secureism.com:8001/public/images/AmirReportShapeLines.png%27)))
}}" style="position:absolute;width:100%"> try this with-out using background link simple this add run that query

**Comment by Hammad-Naseer** [comment]
<img src="data:image/png;base64,{{ base64_encode(file_get_contents('
[https://devoneclick.secureism.com:8001/public/images/AmirReportShapeLines.png'))](https://devoneclick.secureism.com:8001/public/images/AmirReportShapeLines.png%27)))
}}" style="position:absolute;width:100%">

**Comment by Hammad-Naseer** [comment]
> I am trying to set background image but laravel dompdf is not displaying it `style="background:url(http://abc.com/images/img.png)"`
> 
> any solution for this problem?

<img src="data:image/png;base64,{{ base64_encode(file_get_contents('
[https://devoneclick.secureism.com:8001/public/images/AmirReportShapeLines.png'))](https://devoneclick.secureism.com:8001/public/images/AmirReportShapeLines.png%27)))
}}" style="z-index:0;position:absolute;width:100%">

**Comment by Aptana-assumption** [comment]
@Hammad-Naseer https://bdd-lukewarm.github.io/3gGegcANXxtaBwFF8Wb0oZhp9A2yQZosxmsm/
