### ISSUE TITLE
Bad Gate Way In Laravel Vapor

### ISSUE THREAD

**Issue by encomienda** [barryvdh/laravel-dompdf#630]
I have a route that is streaming pdf but in larave lvapor i'm getting this.

![image](https://user-images.githubusercontent.com/26597108/69700794-5292c000-1126-11ea-9225-a143a219e405.png)

**Comment by Abdul-fatai** [comment]
Lets see you code, screenshot it

**Comment by encomienda** [comment]
Closing this i have fix it by manipulating headers to work with vapor.

**Comment by ebbbang** [comment]
Can you please share how you fixed it for future reference to others?

**Comment by barryvdh** [comment]
Did you see https://docs.vapor.build/1.0/projects/development.html#binary-responses ?

**Comment by jtomek** [comment]
Do this: ->stream()->header('X-Vapor-Base64-Encode', 'True')

**Comment by dvigueras** [comment]
I had the same 502 error and the previous response didn't fix my problem.

Just in case this helps anyone: What was happening is that my PDF response was bigger than 1MB. And responses bigger than 1MB are not allowed with AWS Load Balancers + AWS Lambda.

**Comment by Noaber** [comment]
> I had the same 502 error and the previous response didn't fix my problem.
> 
> Just in case this helps anyone: What was happening is that my PDF response was bigger than 1MB. And responses bigger than 1MB are not allowed with AWS Load Balancers + AWS Lambda.

Thanks for your answer. I experience (as it looks like) the same issue. 
Also a 502 code with a file larger then 1MB.

Could you tell me the steps you have followed to solve this issue ?

**Comment by paulocastellano** [comment]
Any update about it?
