### ISSUE TITLE
Deprecated since Symfony 4.4

### ISSUE THREAD

**Issue by diegoba73** [barryvdh/laravel-dompdf#633]
Hi, I put my Laravel project on an Ubuntu server with PHP 7.3.1, Apache and MySQL. When I run "barryvdh / laravel-dompdf" I get the following error:
"Symfony \ Component \ Debug \ Exception \ FatalThrowableError" class is deprecated since Symfony 4.4. 16384
My "composer.json" is as follows:
"require": {
         "php": "> = 7",
         "barryvdh / laravel-dompdf": "^ 0.8.5",
         "fideloper / proxy": "^ 4.0",
         "illuminate / support": "^ 5.5 | ^ 6",
         "kylekatarnls / laravel-carbon-2": "^ 1.0.0",
         "laravel-frontend-presets / argon": "^ 1.0",
         "laravel / framework": "5.8. *",
         "laravel / tinker": "^ 1.0",
         "laravelcollective / html": "^ 5.8",
         "nesbot / carbon": "^ 2.22",
         "spatie / laravel-backup": "^ 6.3"
     },
What could be the mistake? Thank you very much

**Comment by Fischman132** [comment]
As I am guessing, its a bad implementation of the Symfony exception thrower.
For me, it was really caused by the server not having all php extensions installed.
So installing them did fix it for me:
sudo apt install php7.4-bcmath php7.4-ctype php7.4-json php7.4-pdo php7.4-tokenizer php7.4-xml

**Comment by PonthepYJ** [comment]
> As I am guessing, its a bad implementation of the Symfony exception thrower.
> For me, it was really caused by the server not having all php extensions installed.
> So installing them did fix it for me:
> sudo apt install php7.4-bcmath php7.4-ctype php7.4-json php7.4-pdo php7.4-tokenizer php7.4-xml

Thanks a lot, you save my life.
