### ISSUE TITLE
Fatal error memory on a composer update

### ISSUE THREAD

**Issue by Malkom** [barryvdh/laravel-dompdf#634]
Hi,

I have a project with an old laravel version : 5.2.45.

I wanted to install your version 0.5 with a composer update, but I have an memory error : 

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 20480 bytes) in phar://C:/composer/composer.phar/src/Composer/Repository/ComposerRepository.php on line 340

Any idea ?

**Comment by neoteknic** [comment]
OoM with no info, nobdy can help... upgrade your composer to lastest version or your laravel to 6.x maybe (can take few hours)? php version ? 7.2? 7.3 ? 7.4?

**Comment by Malkom** [comment]
I don't have time and skills to upgrade Laravel (about 3h/version) for this project. 
PHP version is 7.3.5.

Any way, I changed my mind and took mpdf.
