### ISSUE TITLE
Page not full in macbook and windows

### ISSUE THREAD

**Issue by yuliantosb** [barryvdh/laravel-dompdf#637]
Hello, I created pdf using html, but the page seems like not full, something like footer collapsed the content, it's only happend in macbook and windows, but looks well on linux, i have no idea what is going on, can you help me please

On Linux
![linux](https://user-images.githubusercontent.com/16331964/70879035-84e16000-1ff6-11ea-8308-115ca9db7c47.png)

On Mac
![mac and windows](https://user-images.githubusercontent.com/16331964/70879039-86128d00-1ff6-11ea-95d6-94079a1a2895.png)

On bottom it's looks like have a margin or padding, but I already set the margin 0px and also the margin 0px

both on mac and linux has a same code

full code here https://pastebin.com/iz0aVQZa

**Comment by DanJamesMills** [comment]
Did you find a fix to this?
