### ISSUE TITLE
Error with <sub> and <sup> tags

### ISSUE THREAD

**Issue by Robyklett** [barryvdh/laravel-dompdf#638]
Hi, when I render a pdf,  tags `<sub>` and `<sup>` are not rendered. I don't know why.
On the blade view everything is ok, but not when I open the pdf
I use laravel 6.2 and the master branch of the laravel-dompdf
Can you help me?
Thanks

**Comment by eddielee394** [comment]
Old post, but just in case someone else runs into this issue.  Most likely it's a css conflict.  So you'll have to reset the css properties for the `sup` tag.  

```
sup {
	font-size: 50%;
    vertical-align: top;
}
```

**Comment by catwhocode** [comment]
> Hi, when I render a pdf, tags `<sub>` and `<sup>` are not rendered. I don't know why. On the blade view everything is ok, but not when I open the pdf I use laravel 6.2 and the master branch of the laravel-dompdf Can you help me? Thanks

In my case, I unescape the variable in Blade, like this
`{!! $variable !!}`
