### ISSUE TITLE
Footer on every page,  only visible on 1st page

### ISSUE THREAD

**Issue by PH-F** [barryvdh/laravel-dompdf#643]
I want to show a footer message on each page but it only shows on the 1st one #356 
What must I do do add it to every page?

html something like this
```
<style>
footer {
    position: fixed; 
    bottom: 0cm; 
    left: 0cm; 
    right: 0cm;
    height: 2cm;
}
</style>
<footer>footer footer</footer>
<main>
	lorem ipsum ... and much more html
</main>
```

using: "barryvdh/laravel-dompdf": "0.8.3",

```
$pdf = App::make('dompdf.wrapper');
$pdf->setPaper('A4', 'portrait');
$pdf->loadView('document.pdf', ['document' => $document]);
return $pdf->stream();
```

**Comment by PatrissolJuns** [comment]
Consult [dompdf/header-footer](https://github.com/dompdf/dompdf/issues/1190) it may help

**Comment by antonioreyna** [comment]
i have the same problem my header and footer only appears on first
