### ISSUE TITLE
HTML is not rendered correctly

### ISSUE THREAD

**Issue by aoamusat** [barryvdh/laravel-dompdf#645]
I wrote a plain html and internal css for generating customer receipt. It display correctly in browser but rendered poorly by dompdf. Is there any solution to this or am I missing something or getting it wrong.

**Comment by RVP04** [comment]
Yes for me also. I am using adminlte bootstrap and i crated one view. It is display properly in browser but not in pdf. Kindly help me.

**Comment by PhishTail** [comment]
I am also having rendering issues. See 
https://stackoverflow.com/questions/60051956/laravel-6-barryvdh-laravel-dompdf-rendering-issues

**Comment by ZeroThe2nd** [comment]
Note that the underlying DomPDF library cannot render all CSS3 and HTML5 items. It's best to assume CSS2.1 and HTML 4.
This is also stated on the [DomPDF readme.md](https://github.com/dompdf/dompdf/blob/master/README.md)

**Comment by RVP04** [comment]
Any idea when it will be rectified ??

**Comment by ZeroThe2nd** [comment]
@RVP04 I'm not associated with DomPDF, so I couldn't give you a valid answer. Best is to make an issue over at their [issue tracker](https://github.com/dompdf/dompdf/issues) if you really want to know, but for now it's the best to stick with HTML5 and CSS 2.1. There's not a lot of really important things you're missing to format a PDF document there.

Optionally you can use [puppeteer](https://github.com/puppeteer/puppeteer/) with NodeJS and have Chrome render and store the PDF file for you, though that's got nothing to do with PHP and this package anymore.

**Comment by Ayzekberk** [comment]
HTML not rendered correctly.... PDFCrowd perfectly render but DomPDF is failing when rendering
