### ISSUE TITLE
How to set my paper to 100x200 instead of A3,A4,...?

### ISSUE THREAD

**Issue by TechNov** [barryvdh/laravel-dompdf#646]
Hi All,
I have and PDF with size 100x200 generated with html2pdf.
After migrate the app to Laraveln  now I have to reproduce the same but using dompdf that a found very simple.
setPaper('100x200',...) is ignored. and take A4 by default. 
someone can help me?

**Comment by nikolaimodified** [comment]
Hi, try this:
setPaper([0,0,100,200]);
In my test it seems to add some extra margins, but this is at least how you're supposed to do it.

**Comment by TechNov** [comment]
thanks
