### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by SergioWiesner** [barryvdh/laravel-dompdf#647]
I have php 7.4.1 and laravel 6 and i try show a pdf with the option **$pdf->stream();** but out this error:

**Trying to access array offset on value of type null**

Illuminate\Foundation\Bootstrap\HandleExceptions::handleError:1427
vendor/dompdf/dompdf/src/Css/Style.php:1427

    protected function _get_border($side)
    {
        $color = $this->__get("border_" . $side . "_color");
        return $this->__get("border_" . $side . "_width") . " " .
        **

> $this->__get("border_" . $side . "_style") . " " . $color["hex"];

**
    }

**Comment by EvgeniyHablak** [comment]
Having the same issue but trying to download a pdf file

**Comment by bop10** [comment]
Take a look at:
https://github.com/dompdf/dompdf/issues/2063

https://github.com/PhenX/php-font-lib/pull/76

Waiting till php-font-lib publishes a new release with the fix.

**Comment by albertpratomo** [comment]
Any update about this issue?

**Comment by vstyler96** [comment]
What about today? :(

**Comment by akashict** [comment]
any updates?

**Comment by MENtechmedia** [comment]
We still have this problem...

**Comment by OAnouman** [comment]
Still no solution?

**Comment by OAnouman** [comment]
I managed to solve it by only including bootstrap 4 CSS CDN. No js.

**Comment by tipudanny** [comment]
Still i am fetching this problem at this time, any update for this issue, please let me know. Thanks

**Comment by MohammedGhareeb** [comment]
any update for this issue

**Comment by lebnani** [comment]
any updates?

**Comment by ecblanco** [comment]
any updates?

**Comment by matteoerrera** [comment]
Updates?

**Comment by Varfendell** [comment]
having the same problem

**Comment by Varfendell** [comment]
Work for me if editing vendors Cpdf.php line 3787:

`if (null !== $this->currentLineTransparency &&
            $mode === $this->currentLineTransparency["mode"] &&
            $opacity == $this->currentLineTransparency["opacity"]
        ) {
            return;
        }`
and line 3887
`if (null !== $this->currentFillTransparency &&
            $mode === $this->currentFillTransparency["mode"] &&
            $opacity == $this->currentFillTransparency["opacity"]
        ) {
            return;
        }`

Adding a null check in if statement. I will try to open pull request

**Comment by securious-mayank** [comment]
Issue is still exist with latest version 0.9.0

**Path:** vendor\dompdf\dompdf\lib\Cpdf.php

**Line:** 3787

As I can see lots of people submitted same requests multiple times in different Git pull request, it still not resolved. I can't believe this. You guys even not looked into it even single time. So sad.

**Comment by Rabia78665** [comment]
I removed color:inherit; from CSS and it fixed the issue

**Comment by benittobeny34** [comment]
hope this will help.
Try the following. 
1. remove images and SVG from the HTML. 
2. try to change the adapter type from CPDF to GD.

**Comment by OsvaldoMelchor54** [comment]
I was using external files with an svg extension on my blade view, I changed the files to jpg or png and it no longer caused problems

**Comment by saurabhbcadev** [comment]
**if you are facing this issue in mpdf then**

1. go to Mpdf.php
2. search for this line: $e = $this->otl->applyOTL($e, $this->CurrentFont['useOTL']);
3. replace it with : $e = preg_replace("/[\xe2\x80\x8c\xe2\x80\x8d\xe2\x80\x8e\xe2\x80\x8f]/u", '', $e); $e = preg_replace("/[\xef\xbb\xbf]/u", '', $e);
