### ISSUE TITLE
Not able to print English and Chinese language together

### ISSUE THREAD

**Issue by prateek756** [barryvdh/laravel-dompdf#650]
From last few days I am trying to print **English** and **Chinese** together by **DOMPDF** but didn't get success. I have used many different font files like **DroidSansFallbackFull**, **FireFly** etc but nothing works.
In some font family English is showing and In some Chinese but not showing both together. Please help me, I got stuck on this and it is the main feature of my application.

**Example:** 
I am using DroidSansFallbackFull  font and Output should be **深圳限公司 Hello 123** but getting like this:

![chinesepdf](https://user-images.githubusercontent.com/33754856/72779756-086c1d80-3c43-11ea-985b-ab6f178622e3.PNG)

**Comment by newfylox** [comment]
Don't know if it's related to dompdf/dompdf#2064 but I fixed some issues reverting **dompdf/dompdf** to 0.8.3
