### ISSUE TITLE
Bootstrap 4 styles not working

### ISSUE THREAD

**Issue by navaneeth-raman-bhaskar** [barryvdh/laravel-dompdf#653]
some of the bootstrap 4 styles are not working.

**Comment by TutoDS** [comment]
I have same problem.
Or timeout because not load css of bootstrap or columns overlap

**Comment by vadimwe** [comment]
CSS3 support is still experemental.

**Comment by RVP04** [comment]
Yes i am using adminlte theme and it is not showing properly.

**Comment by navaneeth-raman-bhaskar** [comment]
Still not fixed?

**Comment by allaghi** [comment]
any news ?

**Comment by ejaz-ul-haq** [comment]
Bootstrap v3.3.6 is supported, kindly check. Thanks

**Comment by itsahmadawais** [comment]
> Bootstrap v3.3.6 is supported, kindly check. Thanks

Right. Thanks for letting us know about the correct answer. It worked for me!
JazakAllah Khair

**Comment by e-hop** [comment]
+1

**Comment by fsasvari** [comment]
+1
