### ISSUE TITLE
Google fonts?

### ISSUE THREAD

**Issue by schmidfelix** [barryvdh/laravel-dompdf#655]
Hey,

in my theme css I import a font from google fonts

```scss
@import url('https://fonts.googleapis.com/css?family=Nunito:300,400,700&display=swap');
```

and i get following error:

`fopen(/var/www/felix-schmid/dashboard/storage/fonts//nunito-normal_176125b1b6dc4704cbf0390040859779.ufm): failed to open stream: No such file or directory`

Isn't it possible via google fonts?

Best regards

**Comment by serj42** [comment]
up
can't import google fonts 
 <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">
    
not works

**Comment by jrbecart** [comment]
Import the font like this (HTML only):
```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link href="http://fonts.googleapis.com/css2?family=Noto+Sans&display=swap" rel="stylesheet">
<link href="http://fonts.googleapis.com/css2?family=Amiri&display=swap" rel="stylesheet">
</head>
<body>
<h2>Noto Sans</h2>
<p style="font-family: 'Noto Sans', sans-serif;">Гордей Беляев</p>
<h2>Amiri</h2>
<p style="font-family: 'Amiri', serif;">عنوان</p> 
</body>
</html>
```

**Comment by jaacu** [comment]
The HTML import worked for me!
