### ISSUE TITLE
Issue in Creating PDF from html

### ISSUE THREAD

**Issue by shubhambdexbytes** [barryvdh/laravel-dompdf#657]
I am trying to create pdf using html in laravel 5.6. Can you please help me in this.

message: 
"fopen(vendor/dompdf/dompdf/lib/fonts/a5a5970acc26f679ed9ad7632d8572df.ufm): failed to open stream: Permission denied"
exception: "ErrorException"
file: "vendor/phenx/php-font-lib/src/FontLib/AdobeFontMetrics.php"
line: 45

**Comment by devfaysal** [comment]
You are using custom fonts in your HTML. So you need to set the correct fonts directory.
Publish the config file and locate your fonts folder.
https://github.com/barryvdh/laravel-dompdf#configuration
