### ISSUE TITLE
Not formatting PDF output properly on live server

### ISSUE THREAD

**Issue by w3designweb** [barryvdh/laravel-dompdf#658]
I have developed and test my $html render locally and than, on the production server, Dompdf generates a pdf with the wrong formatting. Many CSS styles are present, others are not. The header of the sheets is present, but then the body does not and the page-breaks generate 5/6 blank pages.

Could this be a version issue of some PHP library? Or, could it be that some PHP library is missing on the production server?

Thanks a lot

**Comment by astalpaert** [comment]
Is your css placed in <style> tags? Or external css file?
