### ISSUE TITLE
new dompdf 0.8.4 and tables

### ISSUE THREAD

**Issue by subdesign** [barryvdh/laravel-dompdf#660]
with the latest update the new dompdf 0.8.4 distorted my tables (price tables with lot of columns). the right columns were off from the page. before the update with 0.8.3 my tables looked good.

the solution was:
```html
table {
    table-layout:fixed;
    width: 100%
}
```
FYI

**Comment by RobertB93** [comment]
This one did also the trick for me - had the same issue.
Your workaround fixed it, thank you.
