### ISSUE TITLE
used font not embedded into PDF

### ISSUE THREAD

**Issue by kopitar** [barryvdh/laravel-dompdf#663]
Font used does not get embedded into PDF document. If I open the generated HTML, the correct font is used (Open Sans).
If I inspect the page, font used is Open Sans, but when I check the PDF document properties in Adobe Acrobat Reader the fonts used are:

> Helvetica
> Type: Type 1
> Encoding: Ansi
> Actual Font: ArialMT
> Actual Font Type: TrueType
> 
> Helvetica-Bold
> Type: Type 1
> Encoding: Ansi
> Actual Font: Arial-BoldMT
> Actual Font Type: TrueType

HTML used (rendered Blade template):
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1.0">
        
        <title>Salus CEX</title>
        
        <style>
            @font-face {
                font-family: 'OpenSans';
                src: url('./../../fonts/OpenSans-Regular.ttf');
            }

            @page {
                margin-top: 0;
            }

            body {
                font-family: 'OpenSans', 'sans-serif';
                padding: 0 5mm;
                margin: 0;
                box-sizing: border-box;
            }

            #header,
            #content,
            #signature {
                padding: 0;
                margin: 0 auto;
                border: none;
                outline: none;
                width: 100%;
            }

            #header .table-header tr {
                width: 100vw;
            }

            #header .table-header td {
                border-right: 1px solid #52B848;
                padding: 8px 0;
                min-width: 25vw;
                max-width: 25vw;
            }

            #header .table-header td:last-of-type {
                border: none;
            }

            #header .table-header td strong,
            p {
                margin: 5px 0 5px 30px;
                font-size: 9px;
            }

            #header .table-header td p.colored {
                color: #52B848;
            }

            #info,
            #signature {
                margin: 0 2%;
            }

            #info p {
                font-size: 12px;
                font-weight: normal;
                margin: 5px 0;
            }

            #info strong {
                font-size: 12px;
                font-weight: 700;
                margin: 5px 0;
            }

            #content th {
                text-align: left;
                font-size: 10px;
                border: 1px solid #000;
                padding: 1mm 4mm;
            }

            #content tbody tr>td {
                padding: 7px 0;
                font-size: 10px;
            }

            #signature {}
        </style>
    </head>

    <body>
        <table id="header" cellpadding="0" cellspacing="0">
            <tbody>
                
                <tr class="table-header">
                    <td align="center" style="width: 24%">
                        <img src="C:\xampp\htdocs\salus-cex-api\public\images/salus.png">
                    </td>
                    <td style="width: 24%">
                        <strong>XXXX, Veletrgovina d.o.o.</strong>
                        <p>Litostrojska cesta 99A</p>
                        <p>1000 Ljubljana</p>
                    </td>
                    <td style="width: 24%">
                        <p class="colored">Tel.<p>
                                <p>+386 1 589 91 00</p>
                                <p class="colored">Fax<p>
                                        <p>+386 1 xxx 10 xx</p>
                    </td>
                    <td style="width: 24%">
                        <p class="colored">E-pošta<p>
                                <p>info@xxxx.xx</p>
                                <p class="colored">Splet<p>
                                        <p>www.xxxx.si</p>
                    </td>
                </tr>
            </tbody>
        </table>

        <div id="info">
            <div style="width: 100%; padding: 10mm 0;">
                <p style="text-align: left; width: 50%; float: left">SA PRD20191127</p>
                <p style="font-size: 1em; font-weight: 700; text-align: left;">Potrdilo o dostavi št.: DL-19/00396</h3>
            </div>

            <div style="clear: both;">
                <div style="float: left; width: 50%;">
                    <strong>Prejemnik:</strong><br>
                    <strong>LEKARNA xxxxx</strong>
                    <p>ŠUTNA x</p>
                    <p>xxxx Kamnik</p>
                    <p>Tel.: </p>
                </div>
                <div style="float: left;">
                    <br>
                    <p style="padding-bottom: 5mm;"><strong>Predvideni datum dobave:</strong>&nbsp;&nbsp;&nbsp;28.02.2020
                    </p>
                    <p style="padding-bottom: 5mm;"><strong>Špediter:</strong>&nbsp;&nbsp;&nbsp;xxxxx</p>
                    <p><strong>Proga:</strong>&nbsp;&nbsp;&nbsp;KAMNIK 1</p>
                </div>
            </div>

            <div style="width: 100%; display: block; padding: 10mm 0; clear: both;">
                <strong>Dobavnica</strong>
                <p>DOB/19-12345, DOB/19-12347</p>
            </div>
        </div>

        <table id="content" cellpadding="0" cellspacing="0" style="border-bottom: 1px solid #000; padding: 5px 2%;">
            <thead>
                <tr>
                    <th>Tip transportne enote</th>
                    <th>Sobna temperatura</th>
                    <th>Hladilnik 2-8°C</th>
                    <th>globoko zamrznjeno</th>
                    <th>Narkotik</th>
                    <th>Skupno št.</th>
                </tr>
            </thead>
            <tbody>

                <tr>
                    <td>TERMO</td>
                    <td>3</td>
                    <td>2</td>
                    <td>3</td>
                    <td></td>
                    <td>8</td>
                </tr>

                <tr>
                    <td>ZABOJ</td>
                    <td>1</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>1</td>
                </tr>
            </tbody>
        </table>

        <br>
        <strong style="padding: 0 2%;">Število TE skupaj: 9</strong>
        <br>
        <br>

        <div id="signature">
            <div style="float: left; margin-right:40%;">
                <div style="width: 80mm; margin: 7mm 0;">
                    <p
                        style="border-bottom: 1px solid #000; padding-bottom: 5px; padding-right: 10px; margin-left: 0; font-size: 12px;">
                        08.02.2020 07:00:00</p>
                    <p style="margin: 5px 0;">Datum in ura prejema blaga</p>
                </div>
                <div style="width: 80mm; margin: 7mm 0;">
                    <p
                        style="border-bottom: 1px solid #000; padding-bottom: 5px; padding-right: 10px; margin-left: 0; font-size: 12px;">
                        Ga. xxxx ORxxEM, mag. farm.</p>
                    <p style="margin: 5px 0;">Ime in priimek prejemnika blaga</p>
                </div>
                <div style="width: 80mm; margin: 7mm 0;">
                    <p
                        style="border-bottom: 1px solid #000; padding-bottom: 5px; padding-right: 10px; margin-left: 0; font-size: 12px;">
                        <img src="data:image/png;base64,iVBO4tvSsXPJzTiRAAiQQGwIUMLFZimQOpGt4+lwYvNxRPJggg==" alt="podpis"
                            style="max-width: 50mm;" />
                        <p style="margin: 0 0 5px 0;">Podpis prejemnika blaga</p>
                </div>
            </div>
            <div style="float: left">
                <div style="width: 80mm; margin: 7mm 0;">
                    <p
                        style="border-bottom: 1px solid #000; padding-bottom: 5px; padding-right: 10px; margin-left: 0; font-size: 12px;">
                        Peter xxxx š ž đ ć č </p>
                    <p style="margin: 5px 0;">Ime in priimek voznika</p>
                </div>
            </div>
        </div>

        <div style="clear: both; padding: 15mm 2% 0 2%">
            <p style="width: 100%; border-bottom: 1px solid #000; margin: 7mm 0;">Opomba:</p>
            <p style="width: 100%; border-bottom: 1px solid #000; margin: 7mm 0;">&nbsp;</p>
        </div>

    </body>

    </html>

**Comment by kopitar** [comment]
Solved:
```
   @font-face {
        font-family: 'OpenSans';
        src: url({{storage_path().'/fonts/OpenSans-Regular.ttf'}}) format("truetype");
   }
```

**Comment by ysq352358871** [comment]
God. The issues I encountered were the same as yours. I still couldn’t fix my issues with your solution. I’m going to crash！
