### ISSUE TITLE
Unable to render canvas element in PDF.

### ISSUE THREAD

**Issue by veed76** [barryvdh/laravel-dompdf#666]
Hi @barryvdh 
I have a canvas element in the html page.
here is my dom pdf code
```
        $pdf = \App::make('dompdf.wrapper');
        $view = view("pdf/test-report",compact('query', 'test_checks'));
        $pdf->loadHTML($view);
        $name = "example.pdf";
        return $pdf->download($name);
```
The canvas element is inside in test-report.blade.php file.
This code is not rendering the canvas element.

Can you help me with this, Thank you.

**Comment by phildkevin** [comment]
i got the same problem. I even converted the canvas to base64 image. but i didn't solve the problem.

**Comment by veed76** [comment]
Hi @phildkevin 
Try this https://github.com/barryvdh/laravel-snappy I'm not sure but maybe that can help you.
