### ISSUE TITLE
Laravel 6

### ISSUE THREAD

**Issue by Nayeb-karimi** [barryvdh/laravel-dompdf#669]
It is not working on Laravel 6

**Comment by SuperDJ** [comment]
For me it also doesn't work on Laravel 6. It returns the following: 
>%PDF-1.3 1 0 obj << /Type /Catalog /Outlines 2 0 R /Pages 3 0 R >> endobj 2 0 obj << /Type /Outlines /Count 0 >> endobj 3 0 obj << /Type /Pages /Kids [6 0 R ] /Count 1 /Resources << /ProcSet 4 0 R /Font << /F1 8 0 R /F2 9 0 R >> >> /MediaBox [0.000 0.000 595.280 841.890] >> endobj 4 0 obj [/PDF /Text ] endobj 5 0 obj << /Producer (��dompdf <�6782abfc> + CPDF) /CreationDate (D:20200323150420+01'00') /ModDate (D:20200323150420+01'00') /Title (��Contract export) >> endobj 6 0 obj << /Type /Page /MediaBox [0.000 0.000 595.280 841.890] /Parent 3 0 R /Contents 7 0 R >> endobj 7 0 obj << /Filter /FlateDecode /Length 158 >> stream x�}�1�0ཿ�Fz�\Kj-:��MJ[cAMiN��k)���<��>^BHD�OV2�l6G�\jà �`?;��K���� (m�]*�FUWM�H���w??���ڍ*� ��W�Z�`�6�:e~U��~����� 5�q7=|���'=8 endstream endobj 8 0 obj << /Type /Font /Subtype /Type1 /Name /F1 /BaseFont /Times-Roman /Encoding /WinAnsiEncoding >> endobj 9 0 obj << /Type /Font /Subtype /Type1 /Name /F2 /BaseFont /Times-Bold /Encoding /WinAnsiEncoding >> endobj xref 0 10 0000000000 65535 f 0000000009 00000 n 0000000074 00000 n 0000000120 00000 n 0000000284 00000 n 0000000313 00000 n 0000000514 00000 n 0000000617 00000 n 0000000847 00000 n 0000000956 00000 n trailer << /Size 10 /Root 1 0 R /Info 5 0 R /ID[] >> startxref 1064 %%EOF

This seems to match an issues created much earlier https://github.com/barryvdh/laravel-dompdf/issues/183

**Comment by chellem** [comment]
I've put a quick fix to this issue in #183
