### ISSUE TITLE
Font Family Century Gothic not works in PDF.

### ISSUE THREAD

**Issue by veed76** [barryvdh/laravel-dompdf#670]
HI @barryvdh 
I have installed this package and its working fine with normal font family.
Now, I want to use "Century Gothic" font family, this font family working fine in HTML page but not working in PDF I converted that same HTML to PDF and it throws this error: https://prnt.sc/rpjkow

Can you please help me with this?

Thank you.

**Comment by wdebusschere** [comment]
Try to set the warnings in the config/dompdf.php to true :)

**Comment by praditha-hidayat** [comment]
Hello, I've got the same issue here.
I'm trying to use the Segoe UI font which is installed by default on the Windows, but it didn't work on the PDF.
It's working fine on the HTML page.

I have tried to add the fonts at storage/fonts/segoui.ttf and it still doesn't work.

Any clue about this issue?

Thanks
