### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by pavan-cs** [barryvdh/laravel-dompdf#672]
php 7.4
laravel 5.8

```
$pdf = \PDF::loadView( 'pdf-layout', compact('data') );
return $pdf->download("abc.pdf");
```
in php 7.3 it was working fine, i changed my php version and it trigger error!!

**Comment by danielcharrua** [comment]
Same error here, any ideas or fixes?

I'm using PHP 7.3.15
barryvdh/laravel-dompdf: ^0.8.5
laravel/framework: ^6.0
