### ISSUE TITLE
Cache files are not created in the cache folder.

### ISSUE THREAD

**Issue by YuK1Game** [barryvdh/laravel-dompdf#673]
Hi.

I want to keep the font directory and cache directory separate.

I wrote the configuration file like this.

```dompdf.php
"font_dir" => storage_path('fonts/'),
"font_cache" => storage_path('fonts/cache/'),
```

However, the following directory-generated

![WS000000](https://user-images.githubusercontent.com/20548753/78103000-b146ae00-7426-11ea-9b68-0c3936179efc.jpg)

How do I create these three files in the cache directory?
- fonts/dompdf_font_family_cache.php
- fonts/ipag-normal_cbd1503bb7af9be0a4c4cb7cb70ba6d1.ttf
- fonts/ipag-normal_cbd1503bb7af9be0a4c4cb7cb70ba6d1.ufm

Best regards.

**Comment by dinacuatro** [comment]
I have the same problem.

With exactly the same configuration as @YuK1Game , this is my initial files state:
![image](https://user-images.githubusercontent.com/51204470/80366059-e9f07080-8888-11ea-9140-03fd71018e08.png)

and after executing dompdf:
![image](https://user-images.githubusercontent.com/51204470/80366109-fd034080-8888-11ea-8532-4d6535973909.png)

**Comment by dinacuatro** [comment]
I have no idea whether this is the normal behavior, but I found a solution that works for me.

I created two directories in `storage` directory  - `fonts` and `fontsCache`:

- `fonts` directory contains the `ttf` font files
- `fontsCache` directory is empty, writable (chmod 777) and excluded from my repository (.gitignore)

The `config/dompdf.php` file contains the following configuration:
```
"font_dir" => storage_path('fontsCache/'),
"font_cache" => storage_path('fontsCache/')
```
On the other hand, the `blade` file contains the following code:
```
    <style>
        @font-face {
            font-family: 'Jaldi';
            src: url({{storage_path('fonts/Jaldi/Jaldi-Regular.ttf')}}) format("truetype");
        }
        @font-face {
            font-family: 'Jaldi';
            src: url({{storage_path('fonts/Jaldi/Jaldi-Bold.ttf')}}) format("truetype");
            font-weight: bold;
        }
```

In this way I keep a separation between the files which are controlled by my repository, and the files which are generated on-the-fly by dompdf.

**Comment by jamesbhatta** [comment]
Facing the same issue. I think this needs to be reopened.

**Comment by matthiasPOE** [comment]
> Facing the same issue. I think this needs to be reopened.

Agreed this seems like a bug. Its autogenerating files into the `font_dir` directory when it should be placing them in the `font_cache` dir
