### ISSUE TITLE
"A non-numeric value encountered" with the v0.8.5,laravel 5.6 and php 7.2

### ISSUE THREAD

**Issue by naimbob95** [barryvdh/laravel-dompdf#678]
![Screenshot_1](https://user-images.githubusercontent.com/13710927/79632336-26d5ac80-8191-11ea-9048-88a4e515727f.png)

The problem arises when I am publishing the code in the server using ubuntu 18.04. When I am using on my local environment using laragon I did not encounter these issues. Hope somebody can help me.

**Comment by Rogue85** [comment]
The same problem
Laravel 6, php 7.4

**Comment by naimbob95** [comment]
i have solve it, if you run it on server(linux) the variable $w is detected the value as null/empty/string. try to put (float) in the $w variable. 

for example:
$x = (float) $w +$height +$width

**Comment by naimbob95** [comment]
i have solve it, if you run it on server(linux) the variable $w is detected the value as null/empty/string. try to put (float) in the $w variable. 

for example:
$x = (float) $w +$height +$width 

> i have solve it, if you run it on server(linux) the variable $w is detected the value as null/empty/string. try to put (float) in the $w variable.
> 
> for example:
> $x = (float) $w +$height +$width

**Comment by Rogue85** [comment]
Where should I do this? I get this error when I generate pdf from html + inline css

**Comment by naimbob95** [comment]
i got an error in Positioner/Absolute.php

can can you show the error of the code?

**Comment by Rogue85** [comment]
I got an error here
dompdf/src/Css/AttributeTranslator.php:472

**Comment by naimbob95** [comment]
do you have a screenshot?

try add (float) at the variable

**Comment by barryvdh** [comment]
This is probably a dompdf issue
