### ISSUE TITLE
Load font problem, required file Font.php missing 

### ISSUE THREAD

**Issue by wimklerkx** [barryvdh/laravel-dompdf#68]
Including DomPdf in a Laravel based API went smooth, to this point;

When trying to load a custom font, by running font_load.php from the command line, the DomPDF package misses a required file
##### Font.php

Full  error:

```
PHP Fatal error:  require_once(): Failed opening required '********/vendor/barryvdh/laravel-dompdf/vendor/dompdf/dompdf/lib/php-font-lib/classes/Font.php' (include_path='.:/Applications/MAMP/bin/php/php5.4.26/lib/php') in**********vendor/barryvdh/laravel-dompdf/vendor/dompdf/dompdf/dompdf_config.inc.php on line 332
```

Also after composer-updates, the whole php-font-lib/classes folder remains absent.

Tried copying the /classes folder from another DomPDF non-laravel install, but then this error:

```
PHP Fatal error:  Class 'Font' not found in********/vendor/barryvdh/laravel-dompdf/vendor/dompdf/dompdf/load_font.php on line 139
```

Not sure, but this might be a namespace problem. Which will probably be the problem for everything in the copied classes folder then.

**Comment by hassankhan** [comment]
Can you fix this? Not much point if I can't get it to work without a workaround, no?
