### ISSUE TITLE
Dompdf Show Blank

### ISSUE THREAD

**Issue by saadabdurrazaq** [barryvdh/laravel-dompdf#680]
When I use this query:
`$admin` = \App\Admin::all();`
It works. 

But when I use this query:
`$admin = \App\Admin::where('status', "ACTIVE");`
Its shows blank! Even though when I use this query to show data at blade file, it's works!

Why?

**Comment by jelledijkstra97** [comment]
Looks like you forgot to call get() on your query. Try \App\Admin::where('status', "ACTIVE")->get();.
