### ISSUE TITLE
Error on php7.4

### ISSUE THREAD

**Issue by rushxs7** [barryvdh/laravel-dompdf#681]
I have php7.4 installed and I cannot downgrade. Apparently this library has issues working with version 7.4 and higher. I simply cannot generate pdfs on 7.4.

**Comment by wdebusschere** [comment]
It works perfect on PHP 7.4, try to set the warnings in the config/dompdf.php to true :)

**Comment by KevinWaterson** [comment]
Works fine here with 7.4
