### ISSUE TITLE
Quality image Issue

### ISSUE THREAD

**Issue by jpofmars** [barryvdh/laravel-dompdf#682]
Hello,

I have some troubles when generating pdf with image.
With PNG I get a image where color are white and transparent are colored (transparent purple for example).
With JPG, the background of the image are light gray whereas the background of the image is white.
Before all worked fine but I think problem started when I install Imagick and php extension.
I try to update dompdf package too.
But I need it for an other package.
Do you have an idee how to solve the problem.
Thank you very much

**Comment by KevinWaterson** [comment]
"I have some troubles" is not an error description. Show your code.

**Comment by dikaaw** [comment]
same problem..

**Comment by barryvdh** [comment]
This is an issue with Dompdf itself. Please create an issue at https://github.com/dompdf/dompdf
