### ISSUE TITLE
Image not found or type unknown

### ISSUE THREAD

**Issue by thaonguyen90** [barryvdh/laravel-dompdf#686]
![image](https://user-images.githubusercontent.com/15682278/83627700-8fea7580-a5c1-11ea-8700-6201eb3a67d0.png)

do not understand why this error arises, whoever encountered it and asked for a solution

**Comment by thaonguyen90** [comment]
Help me

**Comment by jothikannan** [comment]
I am also getting the same issue with 
DOMPDF: 0.8.5
PHP: 7.2.5
Which is working fine in my localhost, but when i try the same code in my server. I am getting this error

```
$this->pdf->set_option('isHtml5ParserEnabled', true);
$this->pdf->set_option('isRemoteEnabled', true);
$this->pdf->loadHtml($html_content);
$this->pdf->render();
$output = $this->pdf->output();
```

**Comment by alexSelah** [comment]
Hi, I have found a by-pass solution. It is adding the source image as a Base64 image in the blade.

For example:
<img src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUA
    AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
        9TXL0Y4OHwAAAABJRU5ErkJggg=="/>

**Comment by sayhicoelho** [comment]
Try this: https://github.com/barryvdh/laravel-dompdf/issues/303#issuecomment-470950309
