### ISSUE TITLE
Error... How to configure the font cache on Vapor / Serverless?

### ISSUE THREAD

**Issue by sandervanhooft** [barryvdh/laravel-dompdf#687]
Hi @barryvdh ,

Have you by any chance managed to get DomPDF working on Laravel Vapor / a serverless setup?

I'm running into this error with a Google Font (works fine on a "normal" EC2 server)

```
fopen(/var/task/vendor/dompdf/dompdf/lib/fonts/source-sans-pro-200_0f1d90ee1e41fa500b5bdd010be93c25.ufm): failed to open stream: Read-only file system
/var/task/vendor/phenx/php-font-lib/src/FontLib/AdobeFontMetrics.php:45
```

I guess it's about the font caching directory. Is there any way around this?

**Comment by barryvdh** [comment]
Can you change it to /tmp?

**Comment by marijnbent** [comment]
Hey Sander! Did you end up getting `laravel-dompdf` working on a serverless setup?

**Comment by sandervanhooft** [comment]
Yes, Barry's suggestion worked!

**Comment by jtomek** [comment]
This is my config on Laravel Vapor that works.

I store my fonts and other blade assets I'm loading on EFS in a folder "app/dompdf".

```php
// Verbose version
return FacadePDF::loadView($template, compact('footer_text', 'document', 'allowed_mime_types'))
      ->setOptions([
          'chroot' => '/mnt/local/app/dompdf/',
          'fontDir' => '/mnt/local/app/dompdf/fonts/',
          'fontCache' => '/mnt/local/app/dompdf/fonts/',
          'isRemoteEnabled' => true,
          'isFontSubsettingEnabled' => true
      ]);
```

**Comment by psizer10** [comment]
@sandervanhooft Did you do anything other than setting font_cache to "/tmp"?

**Comment by sandervanhooft** [comment]
I think so. This is what I did:

https://github.com/sandervanhooft/vaporize-spark-mollie/blob/master/src/Http/Controllers/UserInvoiceController.php

**Comment by psizer10** [comment]
Ahh brilliant, thanks! I hadn't done anything with the temp_dir and that sorted it
