### ISSUE TITLE
Error on PHP 7.0!!!

### ISSUE THREAD

**Issue by UdyW** [barryvdh/laravel-dompdf#688]
This package does not work on PHP 7.0 any more.
Package https://packagist.org/packages/dompdf/dompdf#v0.8.5 only supports php 7.1 or higher. So it has stopped working. 

I get the following error when I run a artisan command

```
In Container.php line 811:
                                      
  Class Dompdf\Dompdf does not exist  
                                      

In Dompdf.php line 356:
                                
  syntax error, unexpected '='  

```

Will you be able to look in to this ASAP please?

Thank you

**Comment by niektenhoopen** [comment]
PHP 7.0 is end of life since Jan 1st 2019. I honestly would not expect package maintainers to spend their time for free on something that outdated.

**Comment by barryvdh** [comment]
Composer should prevent installing incompatible versions, but otherwise this is an dompdf issue.
