### ISSUE TITLE
Too many space between lines

### ISSUE THREAD

**Issue by spnagar** [barryvdh/laravel-dompdf#689]
I have issue in pdf generating through blade view and getting pdf with too many white space between lines. Please help me to fix this issue. 
![test](https://user-images.githubusercontent.com/16163608/84348279-3215e900-abd2-11ea-9a1e-1f02c3fa9758.png)

Thanks in advance

**Comment by guiwestrup** [comment]
show the entire blade, to see the css implemented

**Comment by allaghi** [comment]
I have a same issue , and I am using bootstrap 4. is there any issues with that ?

**Comment by guiwestrup** [comment]
bootstrap dont work, you need to work with absolute display and use top / left.
For example:

```
<head>
<style>
div.absolute {
            position: absolute;
            padding: 0.5em;
            text-align: center;
            vertical-align: middle;
        }

</style>
</head>
<div class="absolute" style="top: 240px; left: 800px; font-size: 16px;">`
 Element
</div>
```
I don't know if it's the best practice, but it worked for me
