### ISSUE TITLE
How to add a new page?

### ISSUE THREAD

**Issue by LC2712** [barryvdh/laravel-dompdf#69]
Hello,
is it possible to add a new page?
This is my code:

$protTestcase = ProtTestcase::with("feed", "meat")->find($testcase_id);
$pdf = PDF::loadView('protTestcases::pdf.testcase.pdf', array("protTestcase" => $protTestcase));

I NEED to add a page here, but I can't do PDF::loadView again because it overwrites the previous page

return $pdf->download($protTestcase->name.'.pdf');

Is there a way?
Thanks a lot.

**Comment by wajrcs-dk** [comment]
Simple Way: Add a Page Break Before a Section

In your Blade file:

`<div class="page-break"></div>`

```
<style>
    .page-break {
        page-break-before: always;
    }
</style>
```
