### ISSUE TITLE
Can't change font-weight when use variable font 

### ISSUE THREAD

**Issue by ollyth3d1gger** [barryvdh/laravel-dompdf#694]
I'm generating my certificates with laravel-dompdf with custom "bahnschrift" font that  developed as a variable font.When i render certificate normally from view, i can see the changes (i.e bold,italic etc.) but when i generate PDF from this view,it's only displaying PDF with "normal" weight.I can not make any changes when generating PDF,it's displaying only normal weight font.Are there any solutions or work for this?

**Comment by barryvdh** [comment]
This is an issue with Dompdf itself. Please create an issue at https://github.com/dompdf/dompdf
