### ISSUE TITLE
Return Stream API

### ISSUE THREAD

**Issue by akhmadrizki** [barryvdh/laravel-dompdf#697]
Hiii, I want to ask
how to return stream in API, why if I use function stream always download the file, not preview in browser.
Thanks

**Comment by subhanassiddik** [comment]
same issues

**Comment by guiwestrup** [comment]
`$pdfview = PDF::loadView('vendor.pdf', compact('variable_with_data'));`
`return $pdfview->stream();`

**Comment by akhmadrizki** [comment]
I don't know, I think stream not open in a browser because I use IDM and then automatically downloaded
