### ISSUE TITLE
Bootstrap Grids

### ISSUE THREAD

**Issue by mitajunior** [barryvdh/laravel-dompdf#70]
Am trying to BS3 its working fine expect the grid system is not working.. what could be the issue?

**Comment by vadimwe** [comment]
Bootstrap does not works for me...

**Comment by EnricoVilloteBarandon** [comment]
Having the same issues now with the bootstrap grid system. Other classes like btn-suces and jumbotron works fine. Do you guys have the solution now?

**Comment by ajcastro** [comment]
Solve the issue: https://github.com/barryvdh/laravel-snappy/issues/42#issuecomment-75898224

**Comment by jpdesignerrio** [comment]
Bootstrap 4.3 don't have ```col-xs-*```, it's was replaced by ```col-*``` and not working for me.

**Comment by Ghostff** [comment]
Any update on this issue?

**Comment by faiq-ahmad** [comment]
still same issue. Grid system is not working properly. Tried with bootstrap 5, 4 and 3 but no luck in exported file.
