### ISSUE TITLE
Symfony\Component\ErrorHandler\Error\FatalError Allowed memory size of 134217728 bytes exhausted (tried to allocate 54493924 bytes)

### ISSUE THREAD

**Issue by Dilshan97** [barryvdh/laravel-dompdf#700]
I have an issue using this package. I use 

- windows 10
- laravel 7.0
- php 7.3.2

this is the error I got

`Symfony\Component\ErrorHandler\Error\FatalError Allowed memory size of 134217728 bytes exhausted (tried to allocate 54493924 bytes)`

how can I resolve this problem?

**Comment by PHPGuus** [comment]
Hi @Dilshan97 

primarily by allowing PHP to allocate a larger chunk of memory by setting the memory_limit in php.ini appropriately. Alternatively by reducing the size of the HTML that is to be converted to PDF.

Please note that this is not an issue with this Laravel DOMPDF wrapper.

Best regards,
Guus

@barryvdh This issue can be closed.

**Comment by Dilshan97** [comment]
okey thank you

**Comment by InputOutputZ** [comment]
@PHPGuus @barryvdh what if another bigger file exceeds the memory limit? I thought the solution in this case it's to be able to catch the fatal error and I couldn't find way to do so? did any one find a way to catch this fatal error?

**Comment by PHPGuus** [comment]
Depends on your PHP version. If PHP7 and newer, you can always `try { ... } catch(Throwable $t) { ... }`. For earlier versions of PHP, you'd have to use `set_exception_handler()`, `set_error_handler()` and potentially `register_shutdown_function()`.
