### ISSUE TITLE
background-size:cover not Work

### ISSUE THREAD

**Issue by akhmadrizki** [barryvdh/laravel-dompdf#702]
Hii, I have a problem with the background-size.
Background-size is not working. I think background-size already support since less CSS 3.

thanks

**Comment by PHPGuus** [comment]
Hi @akhmadrizki 
This is very likely an issue with the wrapped DOMPDF Library. Please raise an issue in the DOMPDF Library: https://github.com/dompdf/dompdf/issues.
Thank you,
Guus

@barryvdh This issue can be closed.
