### ISSUE TITLE
Can't get css in PDF

### ISSUE THREAD

**Issue by robertnicjoo** [barryvdh/laravel-dompdf#703]
If I load my view in browser it looks like this

![001](https://user-images.githubusercontent.com/8672823/88510948-3412fa80-d00e-11ea-9b36-ccb85fe3166c.png)

But when I add `pdf` function to it, it will look like this

![002](https://user-images.githubusercontent.com/8672823/88511061-645a9900-d00e-11ea-8cf1-5860500b00d5.png)

# Code

```php
public function exportTemplate(Request $request, $id) {
    $templateContent = .......;
    
    // return view('backend.template.pdf', compact('templateContent')); // screenshot #1
    
    $view = View('backend.template.pdf', ['templateContent' => $templateContent]);
    $pdf = \App::make('dompdf.wrapper');
    $pdf->loadHTML($view->render());
    return $pdf->stream(); // screenshot #2
  }
```
`view`

```html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    </head>
    <body>
        {!! $templateContent !!}
    </body>
</html>
```

> Note: My data (including html and css) all are inside `templateContent` variable.

**Any idea?**

**Comment by Rairomero** [comment]
Are you using inline-styles?

**Comment by PHPGuus** [comment]
Hi @robertnicjoo 
This is very likely an issue with the wrapped DOMPDF Library. If Rairomero's comment did not help, please raise an issue in the DOMPDF Library: https://github.com/dompdf/dompdf/issues.
Thank you,
Guus

@barryvdh This issue can be closed.

**Comment by robertnicjoo** [comment]
@Rairomero no is not inline css

**Comment by Dartui** [comment]
@robertnicjoo are you using `asset` or `mix` to apply your styles? Try load it directly from your server (not via URL) by `public_path` function like this:

```diff
- <link href="{{ asset('css/pdf.css') }}" rel="stylesheet">
+ <link href="{{ public_path('css/pdf.css') }}" rel="stylesheet">
```

**Comment by fahmiegerton** [comment]
got the same problem and no fix in the moment :(

**Comment by mahadSajeel** [comment]
Has anybody figured the issue yet, i am unable to use `background-color` css even it's inline

**Comment by Haris-DStudio** [comment]
For CSS you can use bootstrap or inline css. 
I have used the bootstrap classes in DOMPDF, and they work.
But some CSS properties like linear-gradient etc. don't work in pdf.
I think using another library will be the solution.

**Comment by gemanzo** [comment]
Still the same issue for me...

**Comment by obalaweb** [comment]
using the `public_path` works for me
