### ISSUE TITLE
[Laravel 7] PNG doesn't get printed, neither base64 PNG

### ISSUE THREAD

**Issue by franzudev** [barryvdh/laravel-dompdf#707]
I've tried many solutions found on the net(stackoverflow, tutorials, README.md.....): using asset(), public_path(), putting the absolute path in the src attribute of the image tag, base64 inside image tag, but I can't print a .png in my pdf.
What I've found is that if you voluntarily write a wrong path a warning in the file appear like "image not found", but if you put the right path the warning disappear, so I assume that the file get found, but for some reason is not visible.

I solved my problem converting the .png image to .jpeg, is not the best solution if you need an alpha layer.

**Comment by aimalamiri** [comment]
I have the same problem, did you found any solution?

**Comment by franzudev** [comment]
I've converted the png to jpeg, because I don't need transparency.

**Comment by aimalamiri** [comment]
It's better to make it optional cause some people need to add their logs on it, and most of the logos are in png format.

**Comment by aimalamiri** [comment]
I did the same.

But I think this package should make it optional cause so many people are using logos on it, and logos are png most of the times.

**Comment by nckg** [comment]
I had the same problem. I am running ImageMagick 7.0.10-23 and a transparent PNG (converted to base64) would not render. After some investigation I found out it is related to this issue: https://github.com/dompdf/dompdf/issues/2132

It was fixed after pointing the dompdf dependency to the develop branch. It should also be fixed when dompdf 0.8.6 releases.

**Comment by fernando78098** [comment]
Same problem here, someone found the solution?

**Comment by sirking1991** [comment]
has anyone found a solution for this? having the same issue.

**Comment by aimalamiri** [comment]
@sirking1991 Nope, the only solution is to convert your image to jpeg.
