### ISSUE TITLE
Frame not Found in Cellmap When Using Rowspan in Table

### ISSUE THREAD

**Issue by andy1992** [barryvdh/laravel-dompdf#71]
Hai Barry,

Thanks for creating such a wonderful DOMPDF wrapper for laravel. It helped me so much. I just wondering the issue when i was applying rowspan to my table, then has page break between pages, then I got the exception "Frame not found in cellmap".

Although for temporary solutions, I have changed the table structure and it worked great, I was curious about this issue.

Thanks.

Best regards.

**Comment by archambaultalex** [comment]
> Not sure, perhaps the html is not valid. You can also try settings html5 parser to true in the settings, maybe that helps. Otherwise look at https://github.com/barryvdh/laravel-snappy for better html support.

Had  the same problem and setting html5 parser to true worked. Also, rowspan=0 was causing me problems when generating the pdf so i just changed the rowspan to the number of rows it needed to cover.
