### ISSUE TITLE
Invalid characters passed for attempted conversion, these have been ignored

### ISSUE THREAD

**Issue by briopakistan** [barryvdh/laravel-dompdf#714]
**Describe the bug**
Invalid characters passed for attempted conversion, these have been ignored

**Expected behavior**
I am going to create pdf by parsing whole view in laravel

**Comment by alessandrobelli** [comment]
For me this was solved here:
https://github.com/barryvdh/laravel-dompdf/issues/636

> For me, I had to remove my dompdf dependency in my composer file, and then I removed this package and reinstalled, that bumped this package to .9, and then it upgraded dompdf and everything is working again.

Yes I had same issue...updating the package didn't work but when I ran `composer remove barryvdh/laravel-dompdf` then `composer require barryvdh/laravel-dompdf` it seemed to update whatever it needed to update with the fresh install and all working now

_Originally posted by @deanzod in https://github.com/barryvdh/laravel-dompdf/issues/636#issuecomment-778077640_
