### ISSUE TITLE
Laravel DOMPDF failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by blpraveen** [barryvdh/laravel-dompdf#718]
I am getting this error when saving the pdf.

 `$pdf = PDF::loadView('invoice::pdf_generate', $data)->setOptions(['dpi' => 115, 'defaultMediaType' 
    => 'media', 'defaultFont' => 'sans-serif', 'isRemoteEnabled' => true])
     ->save('core/storage/app/pdf/pdffile'.$invoice->id.'.pdf');`

This error occurs while task scheduling with a command `php artisan recurring:invoice`

**Comment by owaiskiani65** [comment]
I got the same error. Any one here to provide some knowledge?

**Comment by greimers** [comment]
I've had the same problem and realized it is because you must not provide a plain string path to the save function. Instead you need to pass in an absolute path genered by `storage_path()`:

    $pdf = PDF::loadView('my-view', $data);
    $fileName = 'myFile.pdf';
    $pdf->save(storage_path('export/'.$fileName));`

**Comment by simonorups** [comment]
Has anyone tried to run `php artisan vendor:publish` got it from [so](https://stackoverflow.com/questions/53369380/laravel-pdf-issue-failed-to-open-stream-no-such-file-or-directory-by-using-bar)

**Comment by Desto1998** [comment]
With laravel 10, you should fisrt create all the directories manualy, before pasing the path to pdf save method, ex:
`$now = now();
       
$now = now();
        $stringNow = "$now";
        $stringNow = str_replace(' ', '_', $stringNow);
        $stringNow = str_replace(':', '_', $stringNow);
        $stringNow = str_replace('-', '_', $stringNow);
        $name = 'file_'.$stringNow.'.pdf';

        $pdf = PDF::loadView('devis.print', compact('data', 'mois','categories', 'pocedes', 'complements','sections'))->setPaper('a4', 'portrait')->setWarnings(false)->save("pdf/".$name);`

Make sure :###  core/storage/app/pdf/pdffile exist in public folder

_NB:_ **Avoid using spaces and special characters in the file name or the path.**

Thanks!
