### ISSUE TITLE
How to add Thai fonts ?

### ISSUE THREAD

**Issue by Codingjames** [barryvdh/laravel-dompdf#719]
This is my Pdf file pdf.blade.php
![image](https://user-images.githubusercontent.com/17596934/94113685-77a0ae00-fe71-11ea-896b-26d6b914e095.png)

my pdf stream
![image](https://user-images.githubusercontent.com/17596934/94117674-bdac4080-fe76-11ea-9abb-ee2571fa5cc9.png)

**Comment by amitchandrakar** [comment]
Follow Link  [https://github.com/barryvdh/laravel-dompdf/issues/712](https://github.com/barryvdh/laravel-dompdf/issues/712)
