### ISSUE TITLE
How to upload to Cloudinary?

### ISSUE THREAD

**Issue by refojunior** [barryvdh/laravel-dompdf#725]
I have a problem when I try to upload the PDF file to cloud storage (Cloudinary). I know most people here using AWS, in my case I using [Cloudinary](https://cloudinary.com/) and [Cloudder](https://github.com/jrm2k6/cloudder) as a wrapper.
The upload process requires the file path. 
The question is, can I get the file path and store it to the server? If that not possible can someone tell me how the best way to do it?

I already try 
```
$pdf = App::make('dompdf.wrapper');
$pdf->loadView('portfolio.pdf', $data);
$content = $pdf->download()->getOriginalContent();               
Cloudder::upload($content, 'portfolio_1');
```
and
```
$pdf = App::make('dompdf.wrapper');
$pdf->loadView('portfolio.pdf', $data);
Cloudder::upload($pdf->output(), 'portfolio_1');
```

Please, kindly help me. 
Thank you very much!

**Comment by refojunior** [comment]
Solved by store it on a public path, then from public path send to Cloudinary

**Comment by JorgeOrtiz121** [comment]
como lo resolvistes, como fue eso de almacenarlo en una ruta publica, igualmente estoy usando cloudinary y quiero enviar mi pdf a la nube de cloudinary con la url para poder visualizarlo. Gracias
