### ISSUE TITLE
Render a pdf is too slow

### ISSUE THREAD

**Issue by aguilerajl** [barryvdh/laravel-dompdf#726]
Hello, 

In UsuarioController.php, i have this 2 methods: printPDF() is very slow (about 1 min), and printToWindow is so fast (about 1sec)

Help apreciated

Thaks!!

`<?php

namespace App\Http\Controllers;

use App\Models\Usuario;
use Barryvdh\DomPDF\PDF;
...
class UsuarioController extends Controller
{

    public function printPDF()
    {
        $usuarios = Usuario::all();
        $pdf = \PDF::loadView('usuarios.print', compact('usuarios'));
        $pdf->setPaper('a4', 'landscape');   //horizontal
        return  $pdf->stream('lista_usuarios.pdf');
    }

    public function printToWindow()
    {
        $usuarios = Usuario::all();
        $html = view('usuarios.print', compact('usuarios'))->render();
        return $html;
    }
}
`

**Comment by aqilfiqran** [comment]
it because u running in `php artisan serve`. please try in hosting or xampp

**Comment by aguilerajl** [comment]
Hello Aquil, 
I'm using a virtual host on Xampp.  I don't use the laravel'server.
Can be the cause the use of bootstrap?
Best regards

**Comment by kgp43** [comment]
Likely because of all the css classes in Bootstrap.
Dompdf rewrite them or something - takes forever.

**Comment by Alisa-Margaryan** [comment]
hello everyone, can you please help me I have Japanese and Chinese pdf load very slow issues on Mac, when I try to open pdf on Mac in Files part, it open about 12-18 sec, I am using this version of package, can it be the cause?
![image](https://github.com/barryvdh/laravel-dompdf/assets/77612455/b3f7c17a-87c9-4fa3-b9c0-5580915b7c6b)
