### ISSUE TITLE
ErrorException: Trying to get property 'y' of non-object

### ISSUE THREAD

**Issue by shahpankaj981** [barryvdh/laravel-dompdf#727]
**Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
vendor/dompdf/dompdf/src/Renderer/ListBullet.php:233**

I am trying to convert the content from ckeditor into pdf. Everything works fine until one enters bullets and numbering in ckeditor.
It leads to the error mentioned above.

It is because of the line 233: list($x, $y) = [$frame->get_position("x"), $line->y]; of src/Renderer/ListBullet.php

Is this a bug?

**Comment by alejandropages** [comment]
Same issue here. Same line throwing the exception and can't seem to find anything wrong with my css. It renders fine as a view in the browser. Any solutions? @shahpankaj981

**Comment by zakariasantoso** [comment]
Same issue here, anyone has a solution to fix this bug?

**Comment by petriuslima** [comment]
@zakariasantoso This repository is just a Laravel wrapper for Dompdf. The bug you found is coming from Dompdf. Try to find an opened issue or create a new one on https://github.com/dompdf/dompdf
