### ISSUE TITLE
Digital Signature Feature Not available

### ISSUE THREAD

**Issue by sanmitpawar** [barryvdh/laravel-dompdf#730]
Hello, I Have a laravel project where I have integrated this package for generating PDF. here I want to integrate digital signature using this package but there is no feature available in the same also no documentation available for the same. please look into the same

**Comment by sanmitpawar** [comment]
@barryvdh please look into it i have completely developed one pdf based project on laravel using DOMPDF and if i am not getting this feature i have to move to tcpdf which is completely redo of development work , its  a pain job for me please add this enhancement into this library

**Comment by blwsh** [comment]
@sanmitpawar I would also like to see this feature but you really shouldn't guilt trip the maintainer to doing your job and instead do research prior to starting the project like the rest of us.

**Comment by sanmitpawar** [comment]
> @sanmitpawar I would also like to see this feature but you really shouldn't guilt trip the maintainer in to doing your job and instead do research prior to starting the project like the rest of us.

I got the point, but I just requested to add an enhancement feature to this package, if it will be there then its good for most of the developers who use laravel and dompdf
