### ISSUE TITLE
DOMDocument::loadHTML(): Tag header invalid in Entity,

### ISSUE THREAD

**Issue by duanekurt** [barryvdh/laravel-dompdf#731]
i dont have problems in exporting before but recently i got this upon updating to latest version i removed external CSS and JS 
i am using the PDF::loadView() facade

here is the full error stack 
DOMDocument::loadHTML(): Tag header invalid in Entity, line: 157 DOMDocument::loadHTML(): Tag main invalid in Entity, line: 174

**Comment by mslabba** [comment]
I am getting error message like this 
DOMDocument::loadHTML(): htmlParseEntityRef: no name in Entity, line: 246 
DOMDocument::loadHTML(): Tag footer invalid in Entity, line: 466
