### ISSUE TITLE
Class 'DOMDocument' not found in Laravel 6.18.40

### ISSUE THREAD

**Issue by xflavio-dev** [barryvdh/laravel-dompdf#733]
Hello everyone...

I have the following problem, my laravel is not but printing the PDFs, just gave me this message, the interesting thing is that I did not change any settings.
I will be grateful for someone to help me.

Symfony\Component\Debug\Exception\FatalThrowableError
Class 'DOMDocument' not found

Dompdf\Dompdf::loadHtml
vendor/dompdf/dompdf/src/Dompdf.php:510

"require": {
        "php": "^7.3",
        "barryvdh/laravel-debugbar": "^3.2",
        "barryvdh/laravel-dompdf": "^0.8.7",
        "doctrine/dbal": "^2.10",
        "dompdf/dompdf": "^0.8.3",
        "fideloper/proxy": "^4.0",
        "intervention/image": "^2.5",
        "laravel/framework": "^6.0",
        "laravel/tinker": "^1.0",
        "laravelcollective/html": "^6.1",
        "lavela/phpjasper": "^3.0",
        "spatie/db-dumper": "^2.15"

Tanks.

**Comment by barryvdh** [comment]
You need to install the php-dom extension.
