### ISSUE TITLE
Arabic charachers is reversed

### ISSUE THREAD

**Issue by sagadsalem** [barryvdh/laravel-dompdf#734]
hi
Arabic characters are in reversed its show like:

```
ابحرم
```

should show like:

```
مرحبا
```

i have default configration but in my template i use:

```
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        body {
            font-family: "DejaVu Sans", sans-serif !important;
        }
    </style>
</head>
<body>
<h1>مرحبا</h1>
</body>
</html>
```

**Comment by ammarsaleem-dev** [comment]
any solution for this ?

**Comment by devNajjary** [comment]
I have the same problem, after generate PDF  showed ????? character in page.
![image](https://user-images.githubusercontent.com/17889773/99903117-91c30500-2cd7-11eb-8892-d54678e09601.png)

**Comment by mRamadan0101** [comment]
install this https://github.com/mRamadan0101/dompdf

**Comment by mukesh17mj** [comment]
Facing the same issue. 

Creating the PDF, all the other fonts like English, Hindi etc looks fine but the Arabic font is reversed when creating the pdf.

الإغتيالات والسموم الكيميائية is change to ةيئايميكلا مومسلاو تالايتغإلا

**Comment by AhmedMarcom** [comment]
i face issue when i use arabic font is reversed any solution for that 
thanks ...???

**Comment by ICodingStack** [comment]
**finally i got the solution** 
This setup is designed to help you integrate custom fonts with mPDF in a Laravel project, specifically using fonts for Arabic text rendering.

1. Download the Required Fonts: Navigate to [Google Fonts]( [https://fonts.google.com/selection/embed] and download the font files you need.
2. Install the Necessary Package:  Run the following command to install the mpdf/mpdf package:
`composer require mpdf/mpdf`
3. Add Fonts to the Public Folder: Place the downloaded font files into the public directory of your Laravel project. For example:
`/public/fonts/Amiri-Regular.ttf
/public/fonts/Amiri-Bold.ttf
`
4. Update the Layout Page to Include Font-Face:
Modify your layout page to include the custom fonts using CSS. Here's an example of how to define the @font-face for your fonts:
`@font-face {
    font-family: "Amiri";
    src: url('{{ asset('/fonts/Amiri-Regular.ttf') }}') format('truetype');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: "Amiri";
    src: url('{{ asset('/fonts/Amiri-Bold.ttf') }}') format('truetype');
    font-weight: bold;
    font-style: normal;
}

body {
    font-family: 'Amiri';
    margin: 0;
    padding: 0;
    background-color: #f4f7f6;
    color: #333;
    direction: rtl; /* RTL direction for Arabic */
}
`
5. Implement the PDF Generation Function:  Create a function in your Laravel controller to generate PDFs using mPDF, configuring it to use the custom fonts:
`public function generatePDFAR(Quote $quote)
{
    $companyProfile = CompanyProfile::first(); // Fetching the first company profile entry

    // Setup custom font directory and font data configuration
    $fontDirs = [public_path('fonts')];
    $fontData = [
        'amiri' => [
            'R' => 'Amiri-Regular.ttf',
            'B' => 'Amiri-Bold.ttf'
        ]
    ];

    $defaultConfig = (new \Mpdf\Config\ConfigVariables())->getDefaults();
    $defaultFontDirs = $defaultConfig['fontDir'];

    $defaultFontConfig = (new \Mpdf\Config\FontVariables())->getDefaults();
    $defaultFontData = $defaultFontConfig['fontdata'];

    $mpdf = new \Mpdf\Mpdf([
        'mode' => 'utf-8',
        'format' => 'A4',
        'orientation' => 'P',
        'autoScriptToLang' => true,
        'autoLangToFont' => true,
        'fontDir' => array_merge($defaultFontDirs, $fontDirs), // Merge default font directory with your custom directory
        'fontdata' => $fontData + $defaultFontData, // Merge default font data with your custom font data
        'default_font' => 'amiri' // Set default font to Amiri
    ]);

    $view = view('quotes.quotes-ar', compact('quote', 'companyProfile'))->render(); // Render view to HTML string
    $mpdf->WriteHTML($view);
    return $mpdf->Output('quotes_ar.pdf', 'I'); // Output PDF to browser
}
`
   **Feel Free to Ask Any Questions**  good luck :)
