### ISSUE TITLE
Invalid characters passed for attempted conversion, these have been ignored

### ISSUE THREAD

**Issue by vjain1994** [barryvdh/laravel-dompdf#739]
First of all, Thanks for the package. I got on error in \vendor\dompdf\dompdf\src\Css\Color.php:213. Please help.
 $alpha = round(hexdec(mb_substr($color, 7, 2))/255, 2);
The above line throws an error

`
   

        if ($length == 4 && $color[0] === "#") {

            return $cache[$color] = self::getArray($color[1] . $color[1] . $color[2] . $color[2] . $color[3] . $color[3]);

        } // #rgba format

        else if ($length == 5 && $color[0] === "#") {

            $alpha = round(hexdec($color[4] . $color[4])/255, 2);

            return $cache[$color] = self::getArray($color[1] . $color[1] . $color[2] . $color[2] . $color[3] . $color[3], $alpha);

        } // #rrggbb format

        else if ($length == 7 && $color[0] === "#") {

            return $cache[$color] = self::getArray(mb_substr($color, 1, 6));

        } // #rrggbbaa format

        else if ($length == 9 && $color[0] === "#") {

            $alpha = round(hexdec(mb_substr($color, 7, 2))/255, 2);

            return $cache[$color] = self::getArray(mb_substr($color, 1, 6), $alpha);

        } // rgb( r,g,b ) / rgba( r,g,b,α ) format

        else if (mb_strpos($color, "rgb") !== false) {

            $i = mb_strpos($color, "(");

            $j = mb_strpos($color, ")");

 

            // Bad color value

            if ($i === false || $j === false) {

                return null;

            }
`

**Comment by DiegoFSFlor** [comment]
hello, equal for me

**Comment by DiegoFSFlor** [comment]
my version php is 7.4.13
is there any difference in this version for dompdf?

**Comment by zulhelmi** [comment]
Have a same error. i'm using php 7.4.3

**Comment by alessandrobelli** [comment]
For me this was solved here:
https://github.com/barryvdh/laravel-dompdf/issues/636

> For me, I had to remove my dompdf dependency in my composer file, and then I removed this package and reinstalled, that bumped this package to .9, and then it upgraded dompdf and everything is working again.

Yes I had same issue...updating the package didn't work but when I ran `composer remove barryvdh/laravel-dompdf` then `composer require barryvdh/laravel-dompdf` it seemed to update whatever it needed to update with the fresh install and all working now

_Originally posted by @deanzod in https://github.com/barryvdh/laravel-dompdf/issues/636#issuecomment-778077640_
