### ISSUE TITLE
stream not working in livewire

### ISSUE THREAD

**Issue by santhika29** [barryvdh/laravel-dompdf#740]
how to make pdf preview on livewire...
i'm using :
`
return $pdf->stream('invoice-pasien-pdf');
` 
but nothing happen in my browser

**Comment by nicoja** [comment]
Hi @santhika29 

here the solution :

```
return response()->streamDownload(function () {
            $pdf = App::make('dompdf.wrapper');
            $pdf->loadHTML('<h1>Test</h1>');
            echo $pdf->stream();
        }, 'test.pdf');
```

**Comment by 0l1v3r5** [comment]
```
$pdfContent = PDF::loadView('view', $viewData)->output();
return response()->streamDownload(
     fn () => print($pdfContent),
     "filename.pdf"
);
```

**Comment by DavidNogara** [comment]
> Hi @santhika29
> 
> here the solution :
> 
> ```
> return response()->streamDownload(function () {
>             $pdf = App::make('dompdf.wrapper');
>             $pdf->loadHTML('<h1>Test</h1>');
>             echo $pdf->stream();
>         }, 'test.pdf');
> ```

Thanks! that works, I was struggling with this error.

**Comment by djgraphics28** [comment]
return response()->streamDownload(function () {
            $pdf = App::make('dompdf.wrapper');
            $pdf->loadHTML('<h1>Test</h1>');
            echo $pdf->stream();
        }, 'test.pdf');
        
        this code ikeeps on download, how about print preview?

**Comment by djgraphics28** [comment]
return response()->streamDownload(function () {
            $pdf = App::make('dompdf.wrapper');
            $pdf->loadHTML('<h1>Test</h1>');
            echo $pdf->stream();
        }, 'test.pdf');

**Comment by masoud-codes** [comment]
$pdf::writeHTML($html_content, true, false, true, false, '');

$pdf::Output('tb_patient_list_'.time().'.pdf', 'D');

I use TCPDF how can i print?
help

**Comment by juliusestebar** [comment]
how to add Encryption?
