### ISSUE TITLE
Laravel-dompdf not working with bootstrap-3.3.6 in Laravel-5.8

### ISSUE THREAD

**Issue by noblemfd** [barryvdh/laravel-dompdf#741]
I am working on a project using Laravel-5.8. I tried to download pdf using laravel-dompdf (barryvdh/laravel-dompdf": "^0.8.5) 

I have something like  this in my controller:

` $pdf = PDF::loadView('appraisal-default-pdf',['goals' => $goals])->setPaper('a4', 'landscape');
     return $pdf->download('PDF-report.pdf'); `

I use bootstrap-3.3.6 but laravel-dompdf is not detecting it.

How do I resolve this?

**Comment by ttomdewit** [comment]
@noblemfd When you use `file_get_contents` within `<style>...</style>` tags in your `<head>`, does that work?
