### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by hmawla** [barryvdh/laravel-dompdf#745]
Is PHP 8 support coming any time soon?

**Comment by marcoalesan** [comment]
Take a look at **Php8-compat** branch

**Comment by dariocarbone** [comment]
I tried to install php8-compat branch but barryvdh/laravel-dompdf  requires dompdf/dompdf ^0.8.6 and fails...

**Comment by hmawla** [comment]
The same happened to me as @dariocarbone 
I am now using "barryvdh/laravel-dompdf": "^v0.8.7" and it is working well so far with PHP8

**Comment by dariocarbone** [comment]
for a temporary solution I'm using [[https://github.com/dompdf/dompdf/pull/2313#issuecomment-743763802](url)

**Comment by omaisali** [comment]
> Take a look at **Php8-compat** branch

Where is this branch?

**Comment by omaisali** [comment]
Any help? I was using it with php 7.4. and now need for php8

**Comment by qahtansaid** [comment]
Yea i get this error too, need update for php 8

**Comment by blissgrn** [comment]
@barryvdh : FYI, the last version of dompdf/dompdf 1.0.2 (released on 2021, Jan 8) adds support for PHP 8.0. 
For testing purpose, I forced the version in your package and it seems to work fine (at least on the project I'm working on). 
Hope this helps.

**Comment by LZong-tw** [comment]
Needed +1
