### ISSUE TITLE
pdf export whole site data

### ISSUE THREAD

**Issue by nishanmazumder** [barryvdh/laravel-dompdf#746]
I have pointed to the pdf view file & use the code properly on the controller. but it exports the whole site data. not specific data what I want
![1](https://user-images.githubusercontent.com/10381035/102049542-40f08900-3e0b-11eb-8916-f9d97aa168cf.png)
![2](https://user-images.githubusercontent.com/10381035/102049544-4221b600-3e0b-11eb-9772-a052816f60a7.png)

**Comment by dehboris** [comment]
Hi,
Try to use this code

```php
protected function orderView($id)
{
       $pdf = PDF::loadView('admin.pages.order-details', [
           'order' => Order::find($id)
       ]);

       return $pdf->stream();
}
```

**Comment by nishanmazumder** [comment]
thanks, dehboris. I got a solution like this:

`return PDF::setOptions(['isHtml5ParserEnabled' => true, 'isRemoteEnabled' => true])
        ->loadView('invoice.invoice', compact('order'))->stream();`
