### ISSUE TITLE
Required parameter $dompdf follows optional parameter $paper

### ISSUE THREAD

**Issue by WaiThawOo** [barryvdh/laravel-dompdf#747]
Required parameter $dompdf follows optional parameter $paper
Please check this issue. Is it issue or My error?? Please guide me.
![f](https://user-images.githubusercontent.com/42320296/102128983-0de6dd80-3e7d-11eb-882f-77a3a8049bbe.PNG)

**Comment by dariocarbone** [comment]
If you have installed php8 it seems related to [this issue](https://github.com/barryvdh/laravel-dompdf/issues/745)

**Comment by husnainahmed61** [comment]
i am also facing the same issue.

**Comment by badrshs** [comment]
i have same problem :/

**Comment by Nandi1234** [comment]
have the same problem when using php 8.0

**Comment by amitkumarbiswas2001** [comment]
I also have the same problem when using PHP 8.0

**Comment by xoco70** [comment]
Same here with PHP8.0.2

**Comment by Sadikgamstone** [comment]
Same Error in laravel8 with PHP^7.3|^8.0 - only update "barryvdh/laravel-dompdf": "^0.9.0", and command composer update

**Comment by joao-pedro-alves** [comment]
> Same here with PHP8.0.2 - I fixed it using "barryvdh/laravel-dompdf": "^0.9.0"

Worked for me!

**Comment by L0MAX** [comment]
@ # #

> Same here with PHP8.0.2 - I fixed it using "barryvdh/laravel-dompdf": "^0.9.0"

worked for me too

**Comment by danieluac** [comment]
> Same here with PHP8.0.2 - I fixed it using "barryvdh/laravel-dompdf": "^0.9.0"

It worked for me too

**Comment by korirdennis** [comment]
I ensured that the package had "barryvdh/laravel-dompdf": "^0.9.0" and  did a composer update and I was able to get it working
