### ISSUE TITLE
How to combine text-indent and text-align: justify;

### ISSUE THREAD

**Issue by azisn11s** [barryvdh/laravel-dompdf#748]
I have something like this in head html for CSS :
`.content-paragraph{
            text-indent: 10%; 
            text-align: justify; 
            text-justify: inter-word;
            line-height: 1.5;
            margin-left: 76px;
            margin-right: 76px;
}`

What Iayout that I want is like 
![image](https://user-images.githubusercontent.com/11908698/102325338-9bc5e400-3fb5-11eb-8a40-b6e2cd8a16e6.png)

But, the result is here 
![image](https://user-images.githubusercontent.com/11908698/102325456-bd26d000-3fb5-11eb-86dc-3bf870e21d94.png)

**Comment by azisn11s** [comment]
As alternative I wrapped using span tag.

**Comment by pocrone** [comment]
@azisn11s  Bang boleh liat source code solusinya nya ndak ? gua nemu masalah yg sama
