### ISSUE TITLE
Image orientation error 

### ISSUE THREAD

**Issue by sonnyyugra** [barryvdh/laravel-dompdf#749]
Hello, i have some images(portrait) and i want to show on my PDF files but when i print the PDF the images show rotated like a landscape. I watch the resolution and its 3000x4000 (portrait). This just happen with some random images. I use to show this snippet on the view.

<img src="{{ public_path(Storage::url($answer->question->image))}}" width="250" style="padding-top: 35px;">      

When i execute the script

`@php
    list($width, $height) = getimagesize(public_path(Storage::url($answer->answer)));
    if ($width > $height) {
        // landscape
        $orientation = "landscape";
    } else {
        // portrait
        $orientation = "portrait";
    }
@endphp        `                          

Its landscape but in real its portrait.

**Comment by acgtwentyone** [comment]
i'm facing this issue too.

**Comment by lordrah** [comment]
@acgtwentyone I am having the same issue. I found out the image I was using had an orientation property that rotates it upright. Browsers and photo apps use this orientation property to make it display upright but dompdf does not process the property. You can use this site (https://www.metadata2go.com) to check the image's meta data.

To solve this issue, you can rotate the image using php image and exif functions. Please see this article: https://medium.com/thetiltblog/fixing-rotated-mobile-image-uploads-in-php-803bb96a852c

Hope it helps

**Comment by edrick27** [comment]
@lordrah, thanks! This solution worked for me.
