### ISSUE TITLE
Compatibility with Dompdf 1.0.0

### ISSUE THREAD

**Issue by dvdchn** [barryvdh/laravel-dompdf#751]
Cannot use with Dompdf 1.0.0

**Comment by vladislavtkachenko** [comment]
@barryvdh 
![image](https://user-images.githubusercontent.com/21283123/103139621-2497fa80-46ef-11eb-97b1-de8e9f82e858.png)

**Comment by peterthomson** [comment]
The dompdf repo now seems to only support PHP 8.0 with their 1.0.0 release. That means the 0.8.7 release of laravel-dompdf does not support PHP 8.0 because it loads 0.8.6.

**Comment by barryvdh** [comment]
Please try v0.9.0 now.

**Comment by vladislavtkachenko** [comment]
@barryvdh thank you
