### ISSUE TITLE
Arabic Language Showing (?)Question Mark

### ISSUE THREAD

**Issue by blpraveen** [barryvdh/laravel-dompdf#756]
I am using arabic language translation. it is showing question marks . I tried following 
          `<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>`

         <style>body { font-family: DejaVu Sans, sans-serif; }</style>

it is throwing an error
Invalid characters passed for attempted conversion, these have been ignored

                              if ($c >= 0) {
                                // Set values in CID to GID map
                                if ($c >= 0 && $c < 0xFFFF && $glyph) {
                                    $cidtogid[$c * 2] = chr($glyph >> 8);
                                    $cidtogid[$c * 2 + 1] = chr($glyph & 0xFF);
                                }
 
                          --- if ($c != hexdec($n)) {--- at this line error is occuring
                                    $data['codeToName'][$c] = $n;
                                }
                                $data['C'][$c] = $width;
                            } else {
                                $data['C'][$n] = $width;
                            }

**Comment by AO-IO** [comment]
it is pain in the ass for Arabic/Persian in this package.. use this instead https://github.com/niklasravnsborg/laravel-pdf

**Comment by HamoBoker** [comment]
try change the font family to 'Lateef' or any arabic font that DOMPDF support .
arabic fonts will not work with some fonts
