### ISSUE TITLE
render/save is very slow

### ISSUE THREAD

**Issue by hanzalaafzal** [barryvdh/laravel-dompdf#758]
Hi !
I found no solution to this issue, DomPDF is rendering too slow when using LoadView().
I'm using  laravel 7.30.1 on xampp server and laravel-dompdf version 0.9.0.

**Comment by Bulmer** [comment]
I am using Laravel 8 and version 0.9.0 laravel-dompdf and finding exactly the same thing. Compared to the version i used with laravel 5.7, it takes 4-5 times as long to render.

**Comment by jamiepage** [comment]
Hi, I've noticed that it's especially slow when you have images in your our html, I have 5 images and it takes 90seconds to generate a pdf file.  loads quick on reports where there are no images.
