### ISSUE TITLE
Images are not visible on dompdf

### ISSUE THREAD

**Issue by pratikmmt** [barryvdh/laravel-dompdf#759]
I have tried very thing from {{asset('.....')}} to {{base_path()}} and {{public_path()}} but still images are not visible while generating pdf

**Comment by iamaz007** [comment]
I tried this `<img alt="logo" width="300px" src="img/logo.png">` and it is working in PDF

**Comment by HerlyOlivares** [comment]
Hi, @pratikmmt ,
I had the same problem a while ago, I solved it using relative paths in development and absolute paths in production, I explain:

on the local server use public_path () and for development I had to change to url (), for the image paths, I hope it works for you.

**Comment by lesleyxyz** [comment]
For me, I had height="auto" which hid the image.

Also try this:
`<img src="data:image/png;base64,{{ base64_encode(file_get_contents(public_path('YourPublicImageHere''))) }}">`

Obviously change "YourPublicImageHere"
