### ISSUE TITLE
Image not found or type unknown

### ISSUE THREAD

**Issue by jecfarolan360** [barryvdh/laravel-dompdf#761]
Hello. I need your help. I am sending a pdf file through email with a background image. It would occur that ```image not found or type unknown```. It just occur recently and the issue is not yet resolved.

pdf.blade.php 
``` <img class="mx-auto" src="{{ asset('/images/bgimage.jpg') }}">```

controller
```$pdf = PDF::setOptions(['isHtml5ParserEnabled' => true, 'isRemoteEnabled' => true])
                   ->loadView('pdf', compact('customer'));
            Storage::put('public/pdf/receipt.pdf', $pdf->output());```

mail
```return $this->markdown('receipt-markdown')->attach(Storage::disk('public')->path('pdf/receipt.pdf'));```

It just happen recently and I try to change the path. It would solve for a while but the error would occur again.

**Comment by HerlyOlivares** [comment]
Hi, jecfarolan360, 
I had the same problem a while ago, I solved it using relative paths in development and absolute paths in production, I explain:

on the local server use public_path () and for development I had to change to url (), for the image paths, I hope it works for you.

**Comment by Wawingi** [comment]
> Hi, jecfarolan360,
> I had the same problem a while ago, I solved it using relative paths in development and absolute paths in production, I explain:
> 
> on the local server use public_path () and for development I had to change to url (), for the image paths, I hope it works for you.

can u guive example, please?

**Comment by KatiaSishost** [comment]
> > Hi, jecfarolan360,
> > I had the same problem a while ago, I solved it using relative paths in development and absolute paths in production, I explain:
> > on the local server use public_path () and for development I had to change to url (), for the image paths, I hope it works for you.
> 
> can u guive example, please?

`<img src="data:image/png;base64,{{ base64_encode(file_get_contents(public_path('YourPublicImageHere''))) }}">`

**Comment by kavunap** [comment]
> > > Hi, jecfarolan360,
> > > I had the same problem a while ago, I solved it using relative paths in development and absolute paths in production, I explain:
> > > on the local server use public_path () and for development I had to change to url (), for the image paths, I hope it works for you.
> > 
> > 
> > can u guive example, please?
> 
> `<img src="data:image/png;base64,{{ base64_encode(file_get_contents(public_path('YourPublicImageHere''))) }}">`

I tried all other options but only this of using base64 worked for me

**Comment by wassim20** [comment]
i am having the ssame problem 

> > > > Hi, jecfarolan360,
> > > > I had the same problem a while ago, I solved it using relative paths in development and absolute paths in production, I explain:
> > > > on the local server use public_path () and for development I had to change to url (), for the image paths, I hope it works for you.
> > > 
> > > 
> > > can u guive example, please?
> > 
> > 
> > `<img src="data:image/png;base64,{{ base64_encode(file_get_contents(public_path('YourPublicImageHere''))) }}">`
> 
> I tried all other options but only this of using base64 worked for me but the remaining problem is what if you want to use url from the database? like i want to get the image i normally get with src="/image/profiles/{{$comment->user->profile}}"

im having this issue does anyone have a solution ?

**Comment by mndeto** [comment]
I added **$pdf->setPaper('A4', 'portrait');** and the problem was resolved.

**Example:**
$pdf = PDF::loadView("view_name", compact('param1', 'param2', 'etc');
            // (Optional) Setup the paper size and orientation
            $pdf->setPaper('A4', 'portrait');
            return $pdf->download("My PDF downloaded at " . date("Y-m-d h:iA").".pdf");

**Comment by dea96** [comment]
> data:image/png;base64,{{ base64_encode(file_get_contents(public_path('YourPublicImageHere''))) }}

wow work like charm, thanks bro

**Comment by HarishSTOnline** [comment]
Setting chroot works for me in Ubuntu 20.04.
Reference from: https://github.com/barryvdh/laravel-dompdf/issues/797#issuecomment-880601006

**Comment by TerminalTurtle** [comment]
> > > Hi, jecfarolan360,
> > > I had the same problem a while ago, I solved it using relative paths in development and absolute paths in production, I explain:
> > > on the local server use public_path () and for development I had to change to url (), for the image paths, I hope it works for you.
> > 
> > 
> > can u guive example, please?
> 
> `<img src="data:image/png;base64,{{ base64_encode(file_get_contents(public_path('YourPublicImageHere''))) }}">`

For anyone having this issue. This answer fixed it more.
