### ISSUE TITLE
CSS styles not rendered when using setOptions

### ISSUE THREAD

**Issue by amaurycid** [barryvdh/laravel-dompdf#762]
My PDF renders fine when using:
<pre>

        $pdf = PDF::loadView('reports.employee', compact('employees'))->setPaper('letter', 'landscape');

        return response()->streamDownload(fn () => print($pdf->output()), 'Employess.pdf');
</pre>
But, if I set and option, it renders without css styling:
<pre>

        $pdf = PDF::loadView('reports.employee', compact('employees'))
            ->setOptions(['enable_php' => true])
            ->setPaper('letter', 'landscape');

        return response()->streamDownload(fn () => print($pdf->output()), 'Employess.pdf');
</pre>
The php script I'm running doesn't seems to be the problem, as if I comment it out, it doesn't render css the same.
<pre>
<script type="text/php">
    if ( isset($pdf) ) {
            $pdf->page_script('
            $font = $fontMetrics->get_font("Arial, Helvetica, sans-serif", "normal");
            $pdf->text(700, 30, "Page $PAGE_NUM of $PAGE_COUNT", $font, 9);
        ');
    }
</script>
</pre>

**Comment by masterix21** [comment]
Same issue, solved like so:
```php
$pdf->getDomPdf()->getOptions()->set('enable_php', true);
```

Using `setOptions` from the package, it resets options like a factory state.
