### ISSUE TITLE
Dompdf not working with Livewire Component in Laravel 8

### ISSUE THREAD

**Issue by hanifbd7** [barryvdh/laravel-dompdf#765]
Getting the below error message while using in livewire component in Laravel 8.

"render" method on [App\Http\Livewire\ComponentName] must return instance of [Illuminate\View\View]

My Code

public function render()
{
if ($this->download){
$data = array();
$pdf = PDF::loadView('livewire.money-receipt', compact('data'));
return $pdf->download('eTrust_money_receipt.pdf');
}else{
return view('livewire.money-receipt');
}

Is there any solution ?

**Comment by mazedlx** [comment]
That's not a problem with this package nor with Livewire. You just cannot do anything else in Livewire's `render()`method but return a view.

I'd recommend creating a method in your component e.g. `public function downloadPdf()` and consulting the Livewire docs on how to deliver files as downloads: https://laravel-livewire.com/docs/2.x/input-validation
