### ISSUE TITLE
Laravel-dompdf aborts on long PDF documents

### ISSUE THREAD

**Issue by chrispeeters** [barryvdh/laravel-dompdf#767]
I have successfully implemented this package to render price lists in a categorised table layout using page breaks.

All works fine if the output is no more than 4 to 5 pages. I can get by with this but I'd also like to do price lists of about 25 pages, whichever way I try this, dompdf aborts after 5 or 6 pages without reporting errors.

I'm using Laravel 6 and in my first version I was using the blade file to do the formatting, I got to max 4 pages then. Afterwards, I generated the HTML in the controller, stripping al unnecessary spaces and avoiding fancy HTML; now I can reliably generate my on average 3 to 4 page long lists. Attached is a typical example of my lists.
[Price_Checklist_UK_Yamaha_20210218-1151.pdf](https://github.com/barryvdh/laravel-dompdf/files/6002544/Price_Checklist_UK_Yamaha_20210218-1151.pdf)

Is there a limit to the bulk of the output or am I overlooking something?

**Comment by ArinzeJeffrey-droid** [comment]
Also having the same problem.
