### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by Varfendell** [barryvdh/laravel-dompdf#769]
Reopen isssue #647 https://github.com/barryvdh/laravel-dompdf/issues/647

if (null !== $this->currentLineTransparency && $mode === $this->currentLineTransparency["mode"] && $opacity == $this->currentLineTransparency["opacity"] ) { return; }
and line 3887
if (null !== $this->currentFillTransparency && $mode === $this->currentFillTransparency["mode"] && $opacity == $this->currentFillTransparency["opacity"] ) { return; }

Adding a null check in if statement. I will try to open pull request

**Comment by Filip-Konkowski** [comment]
I agree with the comment from 11 Mar. The issue is still happening at least in version 0.8.6
