### ISSUE TITLE
 PHP Fatal error:  Allowed memory size of  ... exhausted

### ISSUE THREAD

**Issue by antonioreyna** [barryvdh/laravel-dompdf#77]
hello,

I am getting this and I just have like 4 styles at the moment

 PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted

**Comment by bosz** [comment]
thanks @barryvdh , snappy does the task for me.

**Comment by sukhdeepsingh5** [comment]
You can try https://github.com/barryvdh/laravel-snappy for larger documents.
