### ISSUE TITLE
PDFs are randomly 'corrupted'

### ISSUE THREAD

**Issue by fonz-lu** [barryvdh/laravel-dompdf#770]
Hi,

I am sometimes getting corrupted PDFs when I am embedding custom fonts. This happens randomly, around 2 to 3 PDFs of 15. When I open these corrupted PDFs, I do not see any text and the custom fonts are not embedded. The text shows when I open the PDFs with chrome.

- I did try with fonts in the storage directory, google fonts and the Dejavu font that comes with dompdf.
- I "numbered" the fonts in css, so dompdf would create a cached font per PDF, but same problem.
- I tried to convert the same file with just dompdf and everything works fine.

This does not work sometimes: 
` $pdf = PDF::loadView('pdf.minimal');
$pdf->save($temporaryDirectory->path() . '/' . $number . '_' . $filename . '.pdf');`

This works every time:
`$fileContent = file_get_contents( resource_path('views/pdf/minimal.blade.php') ) ;
$pdf = new Dompdf();
$pdf->load_html($fileContent);
$output = $pdf->output();
file_put_contents($temporaryDirectory->path(). '/' . $number . '_' . $filename . '.pdf', $output);`

And this is the 'pdf.minimal' view:
`<!DOCTYPE doctype html>`
`<html>`
   ` <head>`
       ` <meta charset="utf-8">`
           ` <meta content="width=device-width, initial-scale=1" name="viewport">`
                `<title>`
                `</title>`
                `<style type="text/css">`
                    `body {
                      font-family:'Dejavu Sans', font-size: 11pt;
                    }
                </style>`
            `</meta>`
        `</meta>`
  `  </head>`
   ` <body>`
`        <h1>`
            `Hello`
       ` </h1>`
   ` </body>`
`</html>`

Thanks

**Comment by qoszira15** [comment]
This happen to me too. Once in a while the pdf generated is corrupted.
Showing error:
<img width="440" alt="Screenshot 2021-12-29 124136" src="https://user-images.githubusercontent.com/59812971/147627977-eab568ba-8efd-4be7-aa67-48fbbf59fb25.png">

Open in browser: Losing text here and there
<img width="622" alt="Screenshot 2021-12-29 124350" src="https://user-images.githubusercontent.com/59812971/147628096-26cf730c-cf5a-4342-a768-6eaff1f0c917.png">

This happened randomly and I don't have an idea why.
Using Dompdf version 1.0.0

**Comment by qoszira15** [comment]
> Hi,
> 
> I am sometimes getting corrupted PDFs when I am embedding custom fonts. This happens randomly, around 2 to 3 PDFs of 15. When I open these corrupted PDFs, I do not see any text and the custom fonts are not embedded. The text shows when I open the PDFs with chrome.
> 
> * I did try with fonts in the storage directory, google fonts and the Dejavu font that comes with dompdf.
> * I "numbered" the fonts in css, so dompdf would create a cached font per PDF, but same problem.
> * I tried to convert the same file with just dompdf and everything works fine.
> 
> This does not work sometimes: ` $pdf = PDF::loadView('pdf.minimal'); $pdf->save($temporaryDirectory->path() . '/' . $number . '_' . $filename . '.pdf');`
> 
> This works every time: `$fileContent = file_get_contents( resource_path('views/pdf/minimal.blade.php') ) ; $pdf = new Dompdf(); $pdf->load_html($fileContent); $output = $pdf->output(); file_put_contents($temporaryDirectory->path(). '/' . $number . '_' . $filename . '.pdf', $output);`
> 
> And this is the 'pdf.minimal' view: `<!DOCTYPE doctype html>` `<html>` ` <head>` ` <meta charset="utf-8">` ` <meta content="width=device-width, initial-scale=1" name="viewport">` `<title>` `</title>` `<style type="text/css">` `body { font-family:'Dejavu Sans', font-size: 11pt; } </style>` `</meta>` `</meta>` ` </head>` ` <body>` ` <h1>` `Hello` ` </h1>` ` </body>` `</html>`
> 
> Thanks

Hi @fonz-lu,

I'm currently facing same issue as you. Did you managed to fix it?

Thank you.

**Comment by fonz-lu** [comment]
> Hi @fonz-lu,
> 
> I'm currently facing same issue as you. Did you managed to fix it?
> 
> Thank you.

Hi @qoszira15,

No I did not manage to fix it. But I am now using https://github.com/barryvdh/laravel-snappy and https://github.com/mikehaertl/php-pdftk if I need to set passwords and permissions.

Fonz
