### ISSUE TITLE
ErrorException: A non-numeric value encountered in vendor\dompdf\dompdf\src\Renderer\Text.php:158

### ISSUE THREAD

**Issue by kashifmit** [barryvdh/laravel-dompdf#772]
Hello,
        I am getting issue while generating pdf ```ErrorException: A non-numeric value encountered in vendor\dompdf\dompdf\src\Renderer\Text.php:158```. Can you please let me know how to fix it? my php version is 7.3 and i am using ```"barryvdh/laravel-dompdf": "^0.9.0"```
        
        thanks in advance.

**Comment by Sacrlet339** [comment]
I'm having the same problem but php version is 7.4

**Comment by kashifmit** [comment]
@Sacrlet339 on my side i went to the folder and replace the following on line#158
```$x2 = $x + (float)$width + $dx + self::DECO_EXTENSION;```
and it start working on my side. It may help you.

**Comment by srexi** [comment]
Experiencing the same warning as Kashifmit ^^
