### ISSUE TITLE
Long content moves outside the pa

### ISSUE THREAD

**Issue by imran300** [barryvdh/laravel-dompdf#774]
Hello,
My content moves outside the border area of pdf. Kindly help
![Capture](https://user-images.githubusercontent.com/7050400/113291639-be81cb80-930c-11eb-8eb8-326cdabbf127.PNG)

**Comment by itundret** [comment]
I got the same issue.

**Comment by imran300** [comment]
I di included jquery as well sweetalert but still not working...
FIles are included in app.blade.php
