### ISSUE TITLE
Image not found or type unknown

### ISSUE THREAD

**Issue by KatiaSishost** [barryvdh/laravel-dompdf#778]
Hello, im using Laravel.. and php 7.4.11

in windows it work ok..
blade: `<img src="{{asset('img/logo.png')}}" alt="" width="322" height="88"/>`

controller:
```
$pdf = PDF::loadView('pdf.remito',["service"=>$service,"detalles"=>$detalles]);
        return $pdf->stream();
```

but... in my production server with CentOS 7 and CWP Panel... it work but the logo can't show

**Comment by KatiaSishost** [comment]
i change to <img src="data:image/png;base64,{{ base64_encode(file_get_contents(public_path('/img/logo.png''))) }}">

**Comment by royaldream704** [comment]
same problem here image does not show

**Comment by royaldream704** [comment]
I have solve this use publick path
<img src="{{public_path('img/logo.png')}}" alt="" width="322" height="88"/>

**Comment by alaminstore** [comment]
Thanks KatiaSishost , it's worked for me

**Comment by manfield** [comment]
@KatiaSishost solution works on PHP 7.4.x

**Comment by pierrepavlov** [comment]
I've had this problem in the past where one solution worked on the production environment and one on my local environment. Now we've updated everything (Laravel 8, PHP 8) and I can't get it work on either one except for using base64 which is not that performant.
I see there's multiple issues regarding this and what works for some does not work for others (public_path(), asset() and such).

Does anyone have more information regarding this?

**Comment by TechNov** [comment]
> i change to `<img src="data:image/png;base64,{{ base64_encode(file_get_contents(public_path('/img/logo.png''))) }}">`

you save my day . Thanks @KatiaSishost

**Comment by HarishSTOnline** [comment]
Setting chroot works for me in Ubuntu 20.04.
Reference from: https://github.com/barryvdh/laravel-dompdf/issues/797#issuecomment-880601006

**Comment by Malek-fadel** [comment]
Good Note my dear
