### ISSUE TITLE
Problem about Dompdf Chinese display

### ISSUE THREAD

**Issue by sir3453715** [barryvdh/laravel-dompdf#779]
My dompdf cant show any chinese

I use msyh.ttf in my code

`
@font-face {
            font-family: 'msyh';
            font-style: normal;
            font-weight: normal;
            src: url({{ storage_path('fonts/msyh.ttf') }}) format('truetype');
        }
        body {
            font-family: msyh, DejaVu Sans,sans-serif;
        }
`

but still cant show chinese
How can I do?

**Comment by panadol007** [comment]
How you solve it?
