### ISSUE TITLE
Flex property

### ISSUE THREAD

**Issue by teamFinanssoreal** [barryvdh/laravel-dompdf#784]
I try use flex like
`.component{
     display: flex;
     flex-direction: column;
}`

But all tags with "component" class are not displayed in the pdf

How can i solve this ?

**Comment by Angel-Ponce** [comment]
Same problem

**Comment by whoisthisstud** [comment]
same

**Comment by taras-budzyn** [comment]
@teamFinanssoreal @Angel-Ponce @whoisthisstud 
I had the same issue. But after a few min of digging found that it's not supported in the library yet.
[Check this out](https://github.com/dompdf/dompdf/issues/971)

I assume Issue can be closed.
