### ISSUE TITLE
Cannot install composer require barryvdh/laravel-dompdf

### ISSUE THREAD

**Issue by gkarthikkumar** [barryvdh/laravel-dompdf#785]
root@host:/var/www/vhosts/minttos.com/httpdocs# composer require barryvdh/laravel-dompdf
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^0.9.0 for barryvdh/laravel-dompdf
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
/usr/local/bin/composer: line 8: 10943 Killed                  "$COMPOSER_BIN" "$@"

**Comment by kevinpallado** [comment]
what composer version you using?
