### ISSUE TITLE
Facing Problem when using with tailwind css 

### ISSUE THREAD

**Issue by saeed-sikandar** [barryvdh/laravel-dompdf#787]
Hey There I am using this library with laravel 8 and latest DOMPDF lib it work pretty fine without tailwindcss but the moment I add css link it load and load and at the end give an  error "**Maximum execution time of 60 seconds exceeded**"

**Comment by thatleeguy** [comment]
Are you using a minimized version of the CSS? You might be trying to load a massive file otherwise.

**Comment by fershopls** [comment]
I got the same problem, when I remove the link pointing to tailwind everything works smooth

**Comment by shekenz** [comment]
Same problem. Just tried linking a very small CSS and it does the same. Seems like the lib don't support `<link>` tags.

**Comment by saeed-sikandar** [comment]
I figured out reason not working is not tailwind issue thats was my apache exec  limit was

**Comment by saeed-sikandar** [comment]
Thanks to all of you for supporting me to fix this problem and your suggestion

**Comment by arv07** [comment]
For this time I can't use tailwind, styles not working in the pdf report, but it works in a view blade. does somebody has the same problem? I'm using tailwind 3.2.7 and Laravel 9

**Comment by gharabaghi** [comment]
I have problem with some tailwind classes like 'w-1/2', they don't work in dompdf output while html input is correct. other classes are being applied.

**Comment by mikebronner** [comment]
We have this issue as well, we have been forced to rewrite everything we render out to PDF using traditional CSS in style tags, as we have not been able to figure out a workaround yet.

**Comment by einar-hansen** [comment]
I have the same issue. I managed to get tailwind up and running by using Steve Baumans new project curlwind:
```
<link rel="stylesheet" href="https://cdn.curlwind.com">
```
 https://curlwind.com/
