### ISSUE TITLE
Footer is not showing in only first page of pdf when i have multiple page pdf

### ISSUE THREAD

**Issue by mrmmbhesaniya** [barryvdh/laravel-dompdf#788]
When i have mupltiple pages PDF in other pages footer is showing but on first page footer is not showing.

I had used below css and html

     footer {
                position: fixed; 
                bottom: 36px;
                left: 0cm;
                right: 0cm;
                /** Extra personal styles **/
                z-index: 10;
                padding: 0 20px;
                padding-bottom: 10px;
            }
            
            

    <footer>
        <table style="width: 100%; border: 0px;border-spacing: 0;" class="">
            <tr>
                <td style="color: #777; font-size: 12px;">
                    Copyright by 2020 | MT-ELECTRIC OY
                </td>
            </tr>
        </table>
    </footer>

**Comment by furthurr** [comment]
I have the same issue ....

**Comment by furthurr** [comment]
I have the solution:
```
<html>
  <head>
   <style>
     @page { margin: 180px 50px; }
     #header { position: fixed; left: 0px; top: -180px; right: 0px; height: 150px; background-color: orange; text-align: center; }
     #footer { position: fixed; left: 0px; bottom: -180px; right: 0px; height: 150px; background-color: lightblue; }
     #footer .page:after { content: counter(page, upper-roman); }
   </style>
  <body>
   <div id="header">
     <h1>Widgets Express</h1>
   </div>
   <div id="footer">
     <p class="page">Page <?php $PAGE_NUM ?></p>
   </div>
   <div id="content">
     <p>the first page</p>
     <p style="page-break-before: always;">the second page</p>
   </div>
 </body>
 </html>
```

Set the header and footer before the content xD

**Comment by muhfirdaus19** [comment]
this works , thnks bro

**Comment by strarsis** [comment]
Please note that the element that should be positioned fixed must be a direct child element of the body/page.
I encountered an issue where the fixed positioned element was not rendered, the reason was the element being nested.
