### ISSUE TITLE
Wrong image orientation html to php on laravel

### ISSUE THREAD

**Issue by Umbus44** [barryvdh/laravel-dompdf#789]
In some images (I noticed at least the size 4032x3024), when they change from html to pdf, they change their orientation (some are sideways and others are upside down).

I am using Laravel, what can I do to fix this?

On html all images are ok

Thanks

**Comment by Naghal** [comment]
You can try to look at the exif data, specifically for the orientation/rotation property. Based on that, apply required image transformation to rotate it in the desired orientation.
This may help you:
https://stackoverflow.com/questions/7489742/php-read-exif-data-and-adjust-orientation
