### ISSUE TITLE
Encoding error for displaying of chinese characters

### ISSUE THREAD

**Issue by bczm8703** [barryvdh/laravel-dompdf#79]
hi. 
Firstly thanks for the awesome package, saved me alot of time for rendering html into pdf.

when i use the package to render pdf everything is working perfectly.. the only issue i have is that the chinese characters are being replaced with white spaces. need help on this.

i have already added the utf-8 meta tag in my template file already but it is still not working

**Comment by raykwok** [comment]
I had the same error, and not fixed.

**Comment by anandselvarasu** [comment]
I have question mark instead of Chinese language. Please help me any one.

**Comment by chaiwei** [comment]
I have manage to get Chinese font to work with Laravel dompdf. 
Reference: https://github.com/dompdf/dompdf/wiki/UnicodeHowTo

laravel version: 5.3

1. Look for your preference [fonts ](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=download+chinese+font)
2. Download the [load_font.php](https://github.com/dompdf/utils) 
3. Upload the load_font.php and the ChineseFontName.ttf to laravel folder (I uploaded to my laravel root directory) 
4. Create a folder in laravel/storage/fonts
5. Edit load_font.php 
(point the require_once to your laravel vendor autoload.php and set the font directory, for my case it is as below)
```
<?php
// 1. [Required] Point to the composer or dompdf autoloader
- require_once "autoload.inc.php";
+ require_once "vendor/autoload.php";

// 2. [Optional] Set the path to your font directory
//    By default dopmdf loads fonts to dompdf/lib/fonts
//    If you have modified your font directory set this
//    variable appropriately.
//$fontDir = "lib/fonts";
+ $fontDir = "storage/fonts";
```
Go to terminal/putty and navigate to the directory where you upload the load_font.php earlier. 
Type below command

`php load_font.php "Font Name" ChineseFontName.ttf`

example below output
```
cw@ubuntu:/var/www/laravel# php load_font.php "Font Name" ChineseFontName.ttf
Unable to find bold face file.
Unable to find italic face file.
Unable to find bold_italic face file.
Copying ChineseFontName.ttf to storage/fonts/ChineseFontName.ttf...
Generating Adobe Font Metrics for storage/fonts/ChineseFontName...
```

Also I checked on my storage/fonts directory and found 3 files has been created. 

```
dompdf_font_family_cache.php -> contains all the font name and the font location path
ChineseFontName.ttf
ChineseFontName.ufm
```
6. Edit my html code and directly set 
```
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<style>body { font-family:  'chinese font name'; } </style>
```
The chinese font is now display properly in my pdf..

7. Delete the load_font.php and the font.ttf that I uploaded to my laravel root directory earlier.

**Comment by ltrtuan** [comment]
Unfortunately, i practice step by step as @chaiwei but it is not worked. I downloaded Roboto ttf format and run load_font.php, the code append
`'roboto' => array(
    'normal' => $fontDir . '/Roboto-Medium',
    'bold' => $fontDir . '/Roboto-Medium',
    'italic' => $fontDir . '/Roboto-Medium',
    'bold_italic' => $fontDir . '/Roboto-Medium',
  ),`
but when i include the font into view blade file
`body {
			    font-family: 'roboto', sans-serif;			  
			}`
And view pdf file, text is not shown

**Comment by nagihiko93** [comment]
Tried @chaiwei suggestion but still ain't working. @ltrtuan how did it went for you?

**Comment by RichardTianke** [comment]
@chaiwei Thanks guy, I fixed Chinese characters problem.

**Comment by liaobaocheng** [comment]
thanks @chaiwei,it work for me on laravel5.6. 
I use simhei.ttf 
```
1. from https://github.com/dompdf/utils download load_font.php; 
2.copy simhei.ttf and load_font.php to laravel project root folder;
3.create a foloder name `fonts` in storage/fonts;
4.add code to line 10 `$fontDir = 'storage/fonts';
5.in terminal,run: php load_font.php "simhei" simhei.ttf 
6.now it works.
```

**Comment by bernierayxu** [comment]
I had the same problem and followed the above instructions.

Please note that you might need an .afm version of the font. Go convert ttf to afm online and download and extract. Copy the file into storage/fonts. Everything should work.

AND NOTICE THAT:

YOUR PDF MAY NEED 10 SECONDS TO SHOW ITS CONTENT.

If it's blank at first glance, just wait. Should you follow the above instructions, wait until you see characters.

BTW, I work on mac. Not sure if the waiting issue happens on other computers or systems.

**Comment by nicole929chan** [comment]
Thank you, @chaiwei , it works well on Windows.
But on Linux, It seems to need more.
`$dompdf = new Dompdf;`
`
$dompdf->set_option('fontDir', storage_path('fonts')); // let dompdft know where the wt001.ttf is 
`

blade file also needs to know the path of wt001.ttf
`
@font-face {
    font-family: 'wt001';
    font-style: normal;
    src: url({{ storage_path('fonts/wt001.ttf') }}) format('truetype');
}
`

**Comment by Maquilaweb** [comment]
@ nicole929chan hello !, I have the same problems of the characters and I have it in windows, can you help me? telling me if you just uploaded the font wt001.ttf and adding storage_path ('fonts') in the file you're going to print? for example I am in the root, and there I have the folder dompdf and in another I have the PDF file that is going to print, but I get an error with $dompdf->set_option

**Comment by goforwork** [comment]
> Encounter similar issue as above: Chinese Character display as white space/white color font/square bracket,
> 
> After few hours trying, I have manage to get Chinese font to work with Laravel dompdf.
> Reference: https://github.com/dompdf/dompdf/wiki/UnicodeHowTo
> 
> laravel version: 5.3
> 
> 1. Look for your preference [fonts ](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=download+chinese+font)
> 2. Download the [load_font.php](https://github.com/dompdf/utils)
> 3. Upload the load_font.php and the ChineseFontName.ttf to laravel folder (I uploaded to my laravel root directory)
> 4. Create a folder in laravel/storage/fonts
> 5. Edit load_font.php
>    (point the require_once to your laravel vendor autoload.php and set the font directory, for my case it is as below)
> 
> ```
> <?php
> // 1. [Required] Point to the composer or dompdf autoloader
> - require_once "autoload.inc.php";
> + require_once "vendor/autoload.php";
> 
> // 2. [Optional] Set the path to your font directory
> //    By default dopmdf loads fonts to dompdf/lib/fonts
> //    If you have modified your font directory set this
> //    variable appropriately.
> //$fontDir = "lib/fonts";
> + $fontDir = "storage/fonts";
> ```
> 
> Go to terminal/putty and navigate to the directory where you upload the load_font.php earlier.
> Type below command
> 
> `php load_font.php "Font Name" ChineseFontName.ttf`
> 
> example below output
> 
> ```
> cw@ubuntu:/var/www/laravel# php load_font.php "Font Name" ChineseFontName.ttf
> Unable to find bold face file.
> Unable to find italic face file.
> Unable to find bold_italic face file.
> Copying ChineseFontName.ttf to storage/fonts/ChineseFontName.ttf...
> Generating Adobe Font Metrics for storage/fonts/ChineseFontName...
> ```
> 
> Also I checked on my storage/fonts directory and found 3 files has been created.
> 
> ```
> dompdf_font_family_cache.php -> contains all the font name and the font location path
> ChineseFontName.ttf
> ChineseFontName.ufm
> ```
> 
> 6 Edit my html code and directly set
> 
> ```
> <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
> <style>body { font-family:  'chinese font name'; } </style>
> ```
> 
> The chinese font is now display properly in my pdf..
> 
> 7 Delete the load_font.php and the font.ttf that I uploaded to my laravel root directory earlier.

thanks a lot
