### ISSUE TITLE
Image not found or type unknown

### ISSUE THREAD

**Issue by Fredericld** [barryvdh/laravel-dompdf#797]
Images are not being displayed in PDF file. I get a square with a cross...
I have tried dynamic URLs and also static URLs that I know are correct as the view display fine when rendered normally in the browser. But when passed to the PDF module everything fails

I am running the site using 
php artisan serve --host=www.mysite.com

The www.mysite.com is is my host file.

- Laravel 8
- PHP 7.4
- barryvdh/laravel-dompdf 0.9.0

```
$pdf = PDF::setOptions(['show_warnings' => false, 'isHtml5ParserEnabled' => true, 'isRemoteEnabled' => false])
                ->loadView('frontend.pages.article.pdf.show', compact('article'));
return $pdf->download($article->slug.'.pdf');
```
The images I try to display are on my local machine but I also tried to display images that are online. The same error occurs

I tried to set the "isRemoteEnabled" option to True but the script times out if I do so. The "show_warning" option does not show any information related to this error.

Not sure what else to do.... Any help would be appreciated

**Comment by Fredericld** [comment]
Found my solution
The chroot variable needed to be set

For me
```
$pdf = PDF::setOptions(['isHtml5ParserEnabled' => true, 'isRemoteEnabled' => false, 'chroot' => [ realpath(base_path()).'/public/images', realpath(base_path()).'/public/media'] ])->loadView('my.view.path');
```
The chroot array contains authorized paths to files

See vendor\dompdf\dompdf\src\Image\Cache.php line 128-142

**Comment by alexandru-gaidei** [comment]
> Found my solution The chroot variable needed to be set
> 
> For me
> 
> ```
> $pdf = PDF::setOptions(['isHtml5ParserEnabled' => true, 'isRemoteEnabled' => false, 'chroot' => [ realpath(base_path()).'/public/images', realpath(base_path()).'/public/media'] ])->loadView('my.view.path');
> ```
> 
> The chroot array contains authorized paths to files
> 
> See vendor\dompdf\dompdf\src\Image\Cache.php line 128-142

worked for me after set chroot

**Comment by pascualdas** [comment]
Hi, i was finding a solition for a long time; i share my way:

FOR STYLES:

 $pdf = PDF::setOptions(['isHtml5ParserEnabled' => true, 'isRemoteEnabled' => true, 'chroot' => [ realpath(base_path()).'/public/css']]);

<link href="'.realpath(base_path()).'/public/css/bootstrap.min.css'.'" rel="stylesheet" type="text/css">
<link href="'.realpath(base_path()).'/public/css/misEstilos.css'.'" rel="stylesheet" type="text/css">

FOR IMAGES:

$imgPDF = public_path('storage/'.$examenData[0]->logo_clinica);
$imgPDF = 'data:image/png;base64,'.base64_encode(file_get_contents($imgPDF));

<img src="'.$imgPDF.'" class="rounded" height="80px" width="100%">

I hope it help us.
