### ISSUE TITLE
Microsoft is flagging the generated PDF as Trojan:PDF/Phish.FI

### ISSUE THREAD

**Issue by Tanmay53** [barryvdh/laravel-dompdf#798]
**Describe the bug**
Windows sees the generated PDF as Threat and deletes it after few seconds of creating it.

**To Reproduce**
- PHP - 7.3, Laravel - 8.0, DomPDF - 0.9.0
- Input Blade View for the PDF generation
[payment_invoice.blade.php.txt](https://github.com/barryvdh/laravel-dompdf/files/6776625/payment_invoice.blade.php.txt)

- array_passed to the view for Testing
`['invoice_no' => 'ada', 'created_at' => 'abc', 'paid_on' => 'abc', 'name' => 'abc', 'address' => 'abc', 'email' => 'abc', 'mobile_no' => 'abc', 'subscription_detail' => 'abc', 'amount' => 500, 'isEmail' => false]
`
Script Running to generate the PDF
```
$pdf = PDF::loadView('emails.payment_invoice', [
        'invoice_no' => 'abc',
        'created_at' => 'abc',
        'paid_on' => 'abc',
        'name' => 'abc',
        'address' => 'abc',
        'email' => 'abc',
        'mobile_no' => 3322389379,
        'subscription_detail' => 'abc',
        'amount' => 500,
        'isEmail' => false,
]);
$content = $pdf->download()->getOriginalContent();
Storage::put(("invoices/" . 23423 . ".pdf"), $content);
```

**Expected behavior**
The PDF should open when Click
But, windows flags the PDF as Trojan and deletes it.

If any Windows system is not nearby. You can test the PDF on the following website also
[https://www.virustotal.com](https://www.virustotal.com)

**ScreenShots**
![Screenshot(104)](https://user-images.githubusercontent.com/52573153/124747239-5bbd5300-df3f-11eb-8b75-615268879359.png)
![windows-file-error](https://user-images.githubusercontent.com/52573153/124747982-2d8c4300-df40-11eb-870e-f019158aa8cf.PNG)

**Sample PDF which is flagged by Windows as Trojan**
[SE000706.pdf](https://github.com/barryvdh/laravel-dompdf/files/6776525/SE000706.pdf)

**Comment by Tanmay53** [comment]
Removing the Style Tag from the View(payment_invoice.blade.php), fixes the error.
I think there might be style property which might be responsible for the error.

**Comment by andreich1980** [comment]
ff
