### ISSUE TITLE
how to export dynamic blade view to pdf using a button?

### ISSUE THREAD

**Issue by K1-Aria** [barryvdh/laravel-dompdf#800]
imagine we have a table which we can add rows and columns to it using javascript, and after some customization, we want to export the page to pdf

is this possible? and how

**Comment by barryvdh** [comment]
Store the result and render it as html, then create and PDF.

**Comment by K1-Aria** [comment]
hi bro
where should i store it?
i cant understand

**Comment by nikonachev** [comment]
I want to use JavaScript in my Blade template to add or change dynamically the HTML but I don't know how to enable it in dompdf.
I have a simple Blade:
```blade
<!DOCTYPE html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <style>
    .page-break {
        page-break-after: always;
    }
    *{ font-family: DejaVu Sans !important;}
    </style>
    <title>Hi</title>
</head>
<body>
  <h1 id="demo">Test PDF</h1>
  <script type="text/javascript">
    function insertHtml() {
      document.getElementById("demo").innerHTML = "I have changed!";
    }
    insertHtml()
</script>
</body>
``` 
I use Laravel Filament actions to generate the PDF.
```php
Tables\Actions\Action::make('pdf') 
                    ->label('PDF')
                    ->color('success')
                    ->icon('heroicon-s-download')
                    ->action(function (Model $record) {
                        return response()->streamDownload(function () use ($record) {
                            echo Pdf::loadHTML(
					Blade::render('pdf', ['record' => $record]), 'UTF-8'
                            )->stream();
                        }, 'Test-' . $record->number . '.pdf');
                    }), 
``` 
When I click on the action button the PDF is generated but the JavaScript is not take into account and the outputted text in the PDF is still "Test PDF" instead "Test PDF".
Can you help me to solve this problem?

Thank you in advance.
