### ISSUE TITLE
Images And Font Files Are Not Being Loaded

### ISSUE THREAD

**Issue by hanisirfan** [barryvdh/laravel-dompdf#813]
**Describe the bug**
Can't load images or files from the public route of the app using `asset()` helper. I'm creating the PDF with the `loadView()` method. The view itself renders perfectly (see screenshot 1) but the images and font files not being able to be embedded into the PDF (see screenshot 2). The images is a background image of a `div` element being loaded with `asset()` helper for example `{{ asset('storage' . $eventData->logo_first) }}`  (the file is located in the `/storage` route). Here is the example of the output from the `asset()` helper: `background: url(https://seajelldev.local/storage/img/logo/1630132239-SeaJell-Logo.png)`.

Because of this, fonts also aren't being able to be loaded for the `@font-face` rule that I've set in CSS. I've also referenced all the `.ttf` file to a public route specifically `/fonts` route. I've also tried to access the image and font route and it works fine.

**To Reproduce**
- Laravel and package version
- Input HTML/CSS
- Options / code

**Expected behavior**
Images and fonts to load properly and being used in the PDF.

**Screenshots**
- 1
![image](https://user-images.githubusercontent.com/66242389/131591675-e6ed1c62-5c77-4bf1-90a1-3d6fbd291179.png)
- 2
![image](https://user-images.githubusercontent.com/66242389/131591728-0ab0a05d-2c4a-46bb-8dd7-9e1903a81aea.png)

I hope anyone could help me with this problem. Thanks.

**Comment by rodrigoross** [comment]
@hanisirfan Did you managed to fix of find a solution?

**Comment by hanisirfan** [comment]
Yes I do. I'm hosting the app on my local server with self-signed certificate. So I have to enable it using `setHttpContext()` to fix it.
