### ISSUE TITLE
Korean characters are not converted

### ISSUE THREAD

**Issue by kimjingo** [barryvdh/laravel-dompdf#814]
**This is just a Dompdf wrapper!**
I understand that this package is just a Laravel wrapper for https://github.com/dompdf/dompdf
Any issues with PDF rendering, CSS that is not applied correctly, aligning/fonts/characters etc that are not directly related to this package, should be reported there. When having doubts, please try to reproduce the issue with just dompdf. If it's also present there, do not open an issue here please.

**Describe the bug**

**To Reproduce**
please refer below
https://github.com/kimjingo/laravel-dompdf-korean

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/32721831/134092821-6fc7d32e-4615-4719-8854-13a39ec358f3.png)

**Additional context**

**Comment by Ilxomjon123** [comment]
I had similar issue when downloaded Korean chars
