### ISSUE TITLE
Maximum execution time of 60 seconds exceeded

### ISSUE THREAD

**Issue by edwaroa10** [barryvdh/laravel-dompdf#815]
Hey, i have an error 
![image](https://user-images.githubusercontent.com/73045064/134421511-dfdb5c24-43ab-49e5-a2cb-be31df105c1e.png)
Doesn´t work.

Maximum execution time of 60 seconds exceeded. 
This is my error, but when i do ...
![image](https://user-images.githubusercontent.com/73045064/134421687-f7b72e14-a031-4bfd-ad9f-cfe20f7aa2e9.png)
It works

**Comment by JoaoPedroMDP** [comment]
I am having a similar issue here but the file is generated.
When i use `PDF::loadView()`, it takes a huge amount of time to generate the PDF, about one minute.

**Comment by bnjunge** [comment]
Same case here

**Comment by kapilsapkota** [comment]
any solution to this problem

**Comment by etherealtaste** [comment]
There is an issue with "php artisan serve" and external file: you must use only local file.
You can't even use the "asset" helper because it generates a full url (eg. "http://localhost:8000/css/app.ccs") that will hang your app.

**Comment by kapilsapkota** [comment]
Thank you for your response.

**Comment by tamedevelopers** [comment]
Good day team.

This error occurred when isRemoteEnabled is set to true on laravel.

$options = new Options();
$options->set('isRemoteEnabled', true); 

$dompdf = new Dompdf($options);

**Comment by NasserFaris** [comment]
Hi there! In my case, it seems to be the images... it need an absolute path instead of using "asset()".

Hope it helps.

**Comment by mshamaseen** [comment]
a quick solution to that is to use a queue system for the PDF, make sure to put QUEUE_DRIVER=database in the .env and run PHP artisan queue:listen to run.
