### ISSUE TITLE
Custom Font

### ISSUE THREAD

**Issue by espositodaniele** [barryvdh/laravel-dompdf#816]
**This is just a Dompdf wrapper!**
I understand that this package is just a Laravel wrapper for https://github.com/dompdf/dompdf
Any issues with PDF rendering, CSS that is not applied correctly, aligning/fonts/characters etc that are not directly related to this package, should be reported there. When having doubts, please try to reproduce the issue with just dompdf. If it's also present there, do not open an issue here please.

**Describe the bug**
I've tried all the replies on the issue tracking to find a solution without success. I'm trying to add a custom font on my pdf that is generated from an action but I'm not able to get it working. 

I've created a folder under the storage path as suggested.
Download the font in that folder. 
Added the css on my pdf view in a million of way by following the replies on the issue tracking, but all of them are not working. 

**To Reproduce**

```
@font-face {
font-family: 'rockwell';
    src: url('fonts/RockwellBold.ttf') format('truetype');
    font-weight: bold;
    font-style: bold;
}

h2 {
   font-family: 'rockwell', sans-serif;
}

```

Please, just give an explanation of how we can add custom fonts using this package.

**Comment by happyDemon** [comment]
I had the best results converting the original font file to a format dompdf understands without needing to defined the font family as a font face myself.

I created a PR #820 that adds an artisan command to do this for you.
