### ISSUE TITLE
Problem generating pdf in multi tenant applications

### ISSUE THREAD

**Issue by cavajr** [barryvdh/laravel-dompdf#817]
Hi. I use the barryvdh/laravel-dompdf package with livewire often and I have no problems. When using it with livewire and any package, for example gecche/laravel-multidomain, that works with tenancy is not generating the pdf. Any incompatibilities when working with tenancy regarding file system or cache?

**Comment by viktoras25** [comment]
This might be something similar to what I have encountered. You can check this out #838
