### ISSUE TITLE
Invalid request (Unexpected EOF)

### ISSUE THREAD

**Issue by arbetts** [barryvdh/laravel-dompdf#82]
I am trying to generate a pdf of one of my views using the following code and whenever I try to actually perform any action on the pdf It generates an invalid request message in my console and the browser never resolves

```
public function generatePDF($slug) {

    $article = Article::where('slug', '=', $slug)->firstOrFail();

    $pdf = PDF::loadView('articles.show', array('article'=>$article));

    return $pdf->stream();
}
```

I know that the article exists and that the route is correct. If I don't call anything on the pdf object then the browser is responsive, but if i try to save, download, output or stream, i get the error.

i hope you can help.
Thanks!

**Comment by rujaun** [comment]
+1

**Comment by chintanvadi** [comment]
invalid request (unexpected eof) ?
