### ISSUE TITLE
Images are getting squeezed

### ISSUE THREAD

**Issue by abhishekunic** [barryvdh/laravel-dompdf#823]
![image](https://user-images.githubusercontent.com/44509453/137680045-dc292704-65c1-43c9-b0b8-26d896bcae31.png)
as you can check in image, on first page Images are getting squeezed, but not on second page

**Comment by loekwetzels** [comment]
@abhishekunic have you ever solved this? Running into the same issue

**Comment by loekwetzels** [comment]
Found the solution!

This happens when images are inside tables. Solved using:
```css
td img {
  max-width: auto;
}
```

Reference:
https://github.com/dompdf/dompdf/issues/1448#issuecomment-337337244
