### ISSUE TITLE
useOTL, useKashida dont support in DomPDF

### ISSUE THREAD

**Issue by junayedmahmud** [barryvdh/laravel-dompdf#826]
I am behalf from A Software Company. We are running a big project in Bangladesh. Recently we needed to add bangla font in PDF. 
we tried with load_font.php and with

`@font-face {
        font-family: 'font_family';
        font-style: normal;
        font-weight: normal;
        src: url(fonts/Kalpurush.ttf) format('truetype');
}
body {
        font-family: Arial, sans-serif, 'font_family';
}`
    
I also tried with changing config/DomPDF.php file. UseOTL ,use Kashida dont work there. So generated word is looking like this:

![image](https://user-images.githubusercontent.com/16017682/139164466-6aa4d8c6-6a0c-471f-902e-5622347bec03.png)

    
    
![image](https://user-images.githubusercontent.com/16017682/139164093-54223489-2f99-4d1a-bfff-04c05eb99f17.png)
 
 These words are broken. That is generated with load_font.php
 
 Have any way to fix ?

**Comment by bishwajitcadhikary** [comment]
@junayedmahmud 
Did you find the solution?
![image](https://user-images.githubusercontent.com/55208330/154027501-f383237c-45e6-4334-aecc-cb5afce2ddf3.png)
