### ISSUE TITLE
Custom paper

### ISSUE THREAD

**Issue by mrdaano** [barryvdh/laravel-dompdf#83]
Hello,

Can i do paper with points instead of A4 or A5?

Its now:
```PHP
return $pdf->setPaper('a6')->setOrientation('landscape')->stream();
```

What i mean example:
```PHP
return $pdf->setPaper(500,500)->setOrientation('landscape')->stream();
```

**Comment by barryvdh** [comment]
Hey, I don't think so.
You can use these sizes: https://github.com/dompdf/dompdf/blob/master/include/cpdf_adapter.cls.php#L37

**Comment by barryvdh** [comment]
Or you could try passing an array: `array(0,0,1683.78,2383.94)` Not sure how that works though..

**Comment by mrdaano** [comment]
Thanks, I try it

**Comment by mrdaano** [comment]
You can pass an array. Thanks :+1:

**Comment by tendiarifin** [comment]
> Or you could try passing an array: `array(0,0,1683.78,2383.94)` Not sure how that works though..

can i set heigh paper auto by contents?
i think we need it for thermal printer

**Comment by tendiarifin** [comment]
> Or you could try passing an array: `array(0,0,1683.78,2383.94)` Not sure how that works though..

can i set heigh paper auto by contents?
i think we need it for thermal printer
