### ISSUE TITLE
iconv error on Lambda using Vapor

### ISSUE THREAD

**Issue by luismabenitez** [barryvdh/laravel-dompdf#830]
Getting the next error on with DomPDF using Lambda (Vapor)
**iconv(): Wrong charset, conversion from `utf-8' to `us-ascii//TRANSLIT' is not allowed**

It does work perfectly on local, but can't find any doc related about this error.

I'm using docker with Laravel Vapor and PHP 7.4 on **->stream()**

**Comment by dembal1990** [comment]
+1

**Comment by dibakalaantari** [comment]
+1
