### ISSUE TITLE
Illegal string offset 'hex'

### ISSUE THREAD

**Issue by Devendra1419** [barryvdh/laravel-dompdf#832]
@barryvdh 
When I am creating PDF file from Html file it shows me above error. I am using Php 7.4
![Screenshot 2021-11-17 at 5 20 34 PM](https://user-images.githubusercontent.com/79687038/142195446-d6bc2934-4be9-4d6c-905f-0c0f246ede5f.png)

**Comment by hugomatheus** [comment]
Does anyone have a possible solution to this problem?
