### ISSUE TITLE
Unsupported operand types: string + float

### ISSUE THREAD

**Issue by RaheesIocod** [barryvdh/laravel-dompdf#833]
Laravel Framework 8.72.0
PHP 8.0.12

**Comment by yangeruzi** [comment]
same issue here.. Unsupported operand types: string + float while using laravel dompdf

<img width="1226" alt="Screenshot 2021-11-20 at 4 06 10 PM" src="https://user-images.githubusercontent.com/12079913/142723210-60760d0d-34a1-4204-af40-bb1fa4feee64.png">

**Comment by lunalabs-srl** [comment]
same issue on PHP8 + Laravel8 : i think could be easily solved by updating composer.json with latest DOMPDF version (1.1.0)

![dompdf](https://user-images.githubusercontent.com/66718913/142780504-b70a9873-57bf-4c16-8827-d96fa3070f35.png)

**Comment by NettSite** [comment]
I did the update and it didn't solve my problem, which was on line 198 of /vendor/dompdf/dompdf/src/frameReflower.php. I did the following workaround:

`$rm = (float) $rm + (float) $diff;`

Seems to work.

**Comment by yangeruzi** [comment]
Hi,

Thanks for the update.. will surely try it out.

Yanger Longkumer
