### ISSUE TITLE
Unable to reuse PDF object to generate different documents

### ISSUE THREAD

**Issue by viktoras25** [barryvdh/laravel-dompdf#838]
Hello Barry and maintainers,

I've encountered an issue trying to generate multiple documents using this library. While this DOES stem from Dompdf Library I believe there is a place for a workaround in the wrapper.

The issue can be easily reproduced with this test:
```
    public function testReloadViewProducesAnException(): void
    {
        $html = '<div/>';

        $domPdf = Facade::getFacadeRoot();

        $domPdf->loadHTML($html);
        $domPdf->render();

        $domPdf->loadHTML($html);
        $domPdf->render();

        $this->assertTrue(true, 'Did not throw an exception');
    }
```

> 1) Barryvdh\DomPDF\Tests\PdfTest::testReloadViewProducesAnException
> Dompdf\Exception: No block-level parent found.  Not good.

dompdf/dompdf is of v1.1.1
wrapper version is master (`4e805f5df2`, 2 commits behind of v1.0.0-beta1)

My suggested solution is to re-create Dompdf object before every render. This would imply, multiple setters would have to save e.g. papre size etc, which would have to be reapplied after each reset.

Preview PR available: #837
If you find it appropriate I can finish the idea and present the complete solution.

**Comment by parallels999** [comment]
Don't use `getFacadeRoot` with this package

the correct way would be:
```php
public function testReloadViewProducesAnException(): void
{
    $html = '<div/>';

    $domPdf = Facade::loadHTML($html);
    $domPdf->render();

    $domPdf = Facade::loadHTML($html);
    $domPdf->render();

    $this->assertTrue(true, 'Did not throw an exception');
}
```
