### ISSUE TITLE
Config file not found when used from workbench package

### ISSUE THREAD

**Issue by appcia** [barryvdh/laravel-dompdf#84]
because of these lines in ServiceProvider:

```
  $config_file = $this->app['config']->get(
            'laravel-dompdf::config_file'
        ) ?: $this->app['path.base'] . '/vendor/dompdf/dompdf/dompdf_config.inc.php';
```

Default value for config file should include that your package could be located under workbench/[vendor]/[package]/vendor/barryvdh/laravel-dompdf (I recommend that you use relative path -> maybe use __DIR__ constant ?

Where should I specify its custom location to get it work / what does it mean - `'laravel-dompdf::config_file'` ?

**Comment by barryvdh** [comment]
In the config file.

**Comment by appcia** [comment]
In my published config I see: /app/config/packages/barryvdh/laravel-dompdf/config.php instead of 'config_file.php' ... I can't get it working.

**Comment by appcia** [comment]
OK, now I understand. I put:
```
'config_file' => 'workbench/hydra/core/vendor/dompdf/dompdf/dompdf_config.inc.php',
```

in the app/config/packages/barryvdh/laravel-dompdf/config.php

However, could you change "$this->app['path.base'] . '/vendor/dompdf/dompdf/dompdf_config.inc.php'"

to "\_\_DIR\_\_ . '/../../../dompdf/dompdf/dompdf_config.inc.php'"

It will works also as workbench's composer.json dependency :>

**Comment by barryvdh** [comment]
Can't you just require this package in your root composer file, probably easier ;)

**Comment by appcia** [comment]
No, because I'm building a system which uses workbench as plugin system. Each plugin might have its own dependencies...

**Comment by appcia** [comment]
Solution proposed by me should not break anything ;)

**Comment by gambledor** [comment]
I had this same issue. @appcia thank you for your solution
