### ISSUE TITLE
arabic support

### ISSUE THREAD

**Issue by OmarMakled** [barryvdh/laravel-dompdf#85]
it doesn't support arabic characters even if set charset utf-8

```
$data = ['title' => 'عنوان','body' => 'body'];
    $pdf = PDF::loadView('tests.pdf', $data);
    return $pdf->download('test.pdf');
```

```
<!DOCTYPE html>
<html lang="ar">
<head>
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<body dir="rtl">
    <h1>{{$title}}</h1>
    <p>{{$body}}</p>
</body>
</html>
```

any arabic letters doesn't show

**Comment by ahm3dMansour** [comment]
+1

**Comment by adriandmitroca** [comment]
Try to set `font-family: 'dejavu sans', sans-serif;` in your CSS for the body or set a constant `def("DOMPDF_DEFAULT_FONT", "dejavu sans");` in `dompdf_config.inc.php` file

**Comment by OmarMakled** [comment]
I used tcpdf-clone/tcpdf thank you

**Comment by mansouralex** [comment]
Anything new with the Arabic letters support?

I have tried as you mentioning in your above comment and I got the text in the PDF document but it's not correct (not encoded correctly).

Let me know if you have solution for this problem.

Thanks

**Comment by MajidHws** [comment]
i'm facing the same problem , but what is tcpdf?

**Comment by OmarMakled** [comment]
try https://github.com/wkhtmltopdf/wkhtmltopdf

**Comment by amitmeetu12** [comment]
I am able to fix the issue by using mpdf library. 
1. Use the mpdf library. In laravel use package https://github.com/niklasravnsborg/laravel-pdf
2. Use the font-family: "XB Riyaz".

http://www.solutionsbased.in/laravel-arabic-content-display-issue-in-the-pdf/

**Comment by OAmor** [comment]
> Try to set `font-family: 'dejavu sans', sans-serif;` in your CSS for the body or set a constant `def("DOMPDF_DEFAULT_FONT", "dejavu sans");` in `dompdf_config.inc.php` file

i tried it but the characters will be unordered

**Comment by mukesh17mj** [comment]
Facing the same issue, Arabic letters does not support, is there a way to fix it, or need to use some other library. ?

**Comment by mukesh17mj** [comment]
@adriandmitroca Does not work with this solution.

**Comment by jrbecart** [comment]
I found a very easy solution (Nothing to configure):
```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link href="http://fonts.googleapis.com/css2?family=Noto+Sans&display=swap" rel="stylesheet">
<link href="http://fonts.googleapis.com/css2?family=Amiri&display=swap" rel="stylesheet">
</head>
<body>
<h2>Noto Sans</h2>
<p style="font-family: 'Noto Sans', sans-serif;">Гордей Беляев</p>
<h2>Amiri</h2>
<p style="font-family: 'Amiri', serif;">عنوان</p> 
</body>
</html>
```
I have used "Noto Sans" because this font support 582 languages in 237 regions.
"Amiri" font is for arabic.
Choose the one that work the best for you here: https://fonts.google.com/

Enjoy!

**Comment by Aloha276** [comment]
This solution helped me a lot!
https://github.com/dompdf/dompdf/issues/712#issuecomment-650592099

With this solution you don't have to change anything in domPDF or Ar-PHP.

**Comment by moamahfouz** [comment]
> I am able to fix the issue by using mpdf library.
> 
> 1. Use the mpdf library. In laravel use package https://github.com/niklasravnsborg/laravel-pdf
> 2. Use the font-family: "XB Riyaz".
> 
> http://www.solutionsbased.in/laravel-arabic-content-display-issue-in-the-pdf/

Thank you. I spend many hours trying to fix it.
