### ISSUE TITLE
Issue with php unit

### ISSUE THREAD

**Issue by lucabecchetti** [barryvdh/laravel-dompdf#851]
The method to generate pdf works correctly, but testing by phpunit i obtain:

`Call to a member function stream() on string`

**Comment by barryvdh** [comment]
Which unit test?

**Comment by lucabecchetti** [comment]
10);
 
        // Mock PDF generator
        PDF::shouldReceive('loadView')
            ->once()
            ->andReturnSelf()
            ->getMock()
            ->shouldReceive('loadHTML')
            ->andReturn('THE_PDF_BINARY_DATA');

**Comment by barryvdh** [comment]
LoadHtml should return self also: https://github.com/barryvdh/laravel-dompdf/blob/master/src/PDF.php#L99

**Comment by lucabecchetti** [comment]
Can you provide an example how to test it?

**Comment by mukesh17mj** [comment]
@lucabecchetti : How did you solve this. Getting same error. "Call to a member function stream() on string"

**Comment by lucabecchetti** [comment]
`        PDF::shouldReceive('loadHTML')
            ->once()
            ->andReturnSelf()
            ->getMock()
            ->shouldReceive('stream')
            ->andReturn('THE_PDF_BINARY_DATA');`

**Comment by mukesh17mj** [comment]
I am not writing Unit Test. It is to create PDF file. PDF file is created and stored to AWS bucket but it also throws erros. Added sample snippet code used. How to debug this, any help or suggestion on this

```
$html = \View::make('frontend.courses.certificate', [
	'course'     => "This is test course",
])->render();

$pdf = \PDF::setPaper('a4', 'landscape')->loadHtml($html);
\Storage::disk('s3')->put($s3Path, $pdf->stream($fileName)->getContent());
```

Error : "Call to a member function stream() on string".

**Comment by mukesh17mj** [comment]
@lucabecchetti I am not writing Unit Test. It is to create PDF file. PDF file is created and stored to AWS bucket but it also throws erros. Added sample snippet code used. How to debug this, any help or suggestion on this

```
$html = \View::make('frontend.courses.certificate', [
	'course'     => "This is test course",
])->render();

$pdf = \PDF::setPaper('a4', 'landscape')->loadHtml($html);
\Storage::disk('s3')->put($s3Path, $pdf->stream($fileName)->getContent());
```

Error : "Call to a member function stream() on string".
