### ISSUE TITLE
invoice pdf in not show QR code

### ISSUE THREAD

**Issue by vishaldamasiya** [barryvdh/laravel-dompdf#863]
my QR code in pdf file

-------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/99727207/155258928-3a102f0d-e26b-4276-9574-204becddc720.png)
---------------------------------------------------------------------------------------------
and invoice pdf download in not show QR code

controller code

use SimpleSoftwareIO\QrCode\Facades\QrCode;

public function print($id)
{
$invoice = $this->invoiceRepository->findOrFail($id);
$html = view('admin::sales.invoices.pdf', compact('invoice'))->render();

return PDF::loadHTML($this->adjustArabicAndPersianContent($html))
->setPaper('a4')
->download('invoice-' . $invoice->created_at->format('d-m-Y') . '.pdf');
}

private function adjustArabicAndPersianContent($html)
{
$arabic = new \ArPHP\I18N\Arabic();

$p = $arabic->arIdentify($html);

for ($i = count($p) - 1; $i >= 0; $i -= 2) {
$utf8ar = $arabic->utf8Glyphs(substr($html, $p[$i - 1], $p[$i] - $p[$i - 1]));
$html = substr_replace($html, $utf8ar, $p[$i - 1], $p[$i] - $p[$i - 1]);
}
return $html;
}
--------------------------------------------------------------
but download invoice pdf in not Show QRcode

**Comment by salmanhijazi** [comment]
Print QrCode like this:

```
<img src="data:image/svg+xml;base64,{{ base64_encode( QrCode::size(150)->generate($item->id) ) }}"/>
```
