### ISSUE TITLE
Cannot resolve public path

### ISSUE THREAD

**Issue by vaibhavpanchal2218** [barryvdh/laravel-dompdf#868]
I deployed a Laravel app to shared hosting. Then I separated the folders into DOMAIN containing the all the other folders and public_html containing the files in the public directory. 

After downloading PDF file it generate an error called ("Cannot resolve public path").

It looks all right, but when I go to use it, I'm getting the following error (Cannot resolve public path), see :

`$this->app->bind('dompdf', function ($app) {`
           ` $options = $app->make('dompdf.options');`
            `$dompdf = new Dompdf($options);`
            `$path = realpath(base_path('public'));`
            `if ($path === false) {`
                `throw new \RuntimeException('Cannot resolve public path');`
            `}`
            `$dompdf->setBasePath($path);`
            `return $dompdf;`
       ` });`

**Comment by Eixix** [comment]
I have the same issue :(

**Comment by alfiosalanitri** [comment]
> I have the same issue :(

See https://github.com/barryvdh/laravel-dompdf/pull/867

**Comment by Anfi1924** [comment]
You can create public folder 
or 
replace base_path('public') with base_path()

**Comment by Rogierownage** [comment]
@barryvdh Any ETA on when a new version will be released that contains the fix? It's been more than 2 weeks since the PR has been merged.

**Comment by alfiosalanitri** [comment]
@barryvdh news?

**Comment by angeljqv** [comment]
#890

**Comment by stivenmadrid** [comment]
hola la solucion es en la ruta vendor-barryvdh\laravel-dompdf-src-servicesProvider.php  copiar tal cual el codigo que acabo de dejar, saluos
$this->app->bind('dompdf', function ($app) {

            $options = $app->make('dompdf.options');
            $dompdf = new Dompdf($options);
            $path = realpath(base_path(''));
            if ($path === false) {
                throw new \RuntimeException('Cannot resolve public path');
            }
            $dompdf->setBasePath($path);

            return $dompdf;
        });

**Comment by fredsal** [comment]
Ok, in case someone did not realize, the correct solution is setting custom path on config
https://github.com/barryvdh/laravel-dompdf/blob/1d47648c6cef37f715ecb8bcc5f5a656ad372e27/config/dompdf.php#L16
https://github.com/barryvdh/laravel-dompdf/blob/1d47648c6cef37f715ecb8bcc5f5a656ad372e27/src/ServiceProvider.php#L54-L58
Por ciertas personas el shampoo necesita instrucciones
