### ISSUE TITLE
Dompdf Library Issue

### ISSUE THREAD

**Issue by SuperStarDeveloper** [barryvdh/laravel-dompdf#870]
Hello everyone.

as a web developer, I am using dompdf laravel package for invoice pdf. but there is a problem with arabic number. now showing mixed arabic number with english, so please assist me. thank you,

issue:
Order Date :22:25:10 am 09-Feb-20٢2
lNMS164٤4023٢2

best regards,
Jin

**Comment by SuperStarDeveloper** [comment]
Thank you for your reply.
I used the package, there is no problem in arabic character, only have issue with number.

**Comment by erikn69** [comment]
Report the issue on the real package, not here

**Comment by SuperStarDeveloper** [comment]
Okay.
