### ISSUE TITLE
Uninstall Dompdf

### ISSUE THREAD

**Issue by NatxS00** [barryvdh/laravel-dompdf#876]
I have tried to remove the package but when I open a web page I get the following message:
ErrorException (E_WARNING)
include(/var/www/vhosts/grp20221-ct5038.uogs.co.uk/httpdocs/Group1-Assignment2-CT5038/vendor/composer/../barryvdh/laravel-dompdf/src/ServiceProvider.php): failed to open stream: No such file or directory.

I have used composer remove, deleted the provider and alias, and all other mentions so I have no idea where this is coming from. 
Please help!

**Comment by edemots** [comment]
Have you tried to run `composer dump-autoload` ?
