### ISSUE TITLE
Issue with php 8.1.4 and Laravel 9

### ISSUE THREAD

**Issue by abhikm1991** [barryvdh/laravel-dompdf#879]
**Describe the bug**
Just updated Laravel 8.81 to Laravel 9 ( "laravel/framework": "^8.81" TO "laravel/framework": "^9.0",). Previously I had 0.9 ("barryvdh/laravel-dompdf": "^0.9.0"), Now I updated it into v1.0 ("barryvdh/laravel-dompdf": "^1.0"). After update PDF generating is not working. The Facade is renamed from Barryvdh\DomPDF\Facade to Barryvdh\DomPDF\Facade\Pdf. 

"message": "Barryvdh\\DomPDF\\PDF::loadView(): Argument #2 ($data) must be of type array, App\\Models\\Test given, called in D:\\projects\\test\\vendor\\barryvdh\\laravel-dompdf\\src\\Facade\\Pdf.php on line 51",
"exception": "TypeError",
"file": "C:\\projects\\test\\vendor\\barryvdh\\laravel-dompdf\\src\\PDF.php",
"line": 131,

**To Reproduce**
"laravel/framework": "^8.81" TO "laravel/framework": "^9.0",
"barryvdh/laravel-dompdf": "^0.9.0" TO "barryvdh/laravel-dompdf": "^1.0"

**Expected behavior**
PDF should work without any error

**Screenshots**
![image](https://user-images.githubusercontent.com/51713785/163784251-31df0883-660f-44b6-9e17-ce61213d2b94.png)

**Additional context**
please update the plugin which suitable for the updated Laravel

**Comment by egrobler** [comment]
This doesn't sound like a bug to me, but rather how you're using `loadView`. Would you be willing to post some of the relevant code where you're using `loadView` so we can see what's what?

**Comment by abhikm1991** [comment]
use \PDF;

$pdf = PDF::loadView('pdf/detail',$data); 
$pdf->setPaper('A4', 'landscape');
$fileName = 'export-'. date('m-d-Y-His').'.pdf';
Storage::put('public/uploads/datas/downloads/'.$fileName, $pdf->output());
$link =  Storage::disk('datas')->url('downloads/'.$fileName);
return $link;

**Comment by abhikm1991** [comment]
@egrobler please look into code snapshots

**Comment by egrobler** [comment]
@abhikm1991 is $data of type array there?

**Comment by egrobler** [comment]
Haven’t tested this but try this to see if $data will be turned into an array
`$data=Service::find($id)->toArray();`
Or
`$data=Service::find($id)->all();`

**Comment by abhikm1991** [comment]
@egrobler Its also having error

**Comment by egrobler** [comment]
Even after returning $data as type array? Same error?

**Comment by abhikm1991** [comment]
@egrobler yes bro

**Comment by egrobler** [comment]
@abhikm1991 I am struggling to understand. If $data is of type array, how can the error still say: `Argument https://github.com/barryvdh/laravel-dompdf/issues/2 ($data) must be of type array, App\Models\Test given` Are you sure it is still the exact same error, and that you have confirmed that if you do something like `echo dd(gettype($data));` says it is an "array"?

**Comment by abhikm1991** [comment]
@egrobler  So Array only works in laravel 9?

**Comment by egrobler** [comment]
Don't know, but that's what the error is telling me...

**Comment by abhikm1991** [comment]
@egrobler  You are right. Its having Objects + Some Array data. So in the blade file, I am using that for the display. But this code works well in Laravel 8.*. So in Laravel 9, only the array will be working? We can't use objects directly?

**Comment by egrobler** [comment]
Probably, but if changing the return value to an array works, then stick with that. I am no expert on Laravel or dompdf, but if the error says it wants an array, give it an array :)

**Comment by abhikm1991** [comment]
@egrobler it's a burden for me to change everywhere! @jdavidbakr @zaherg @luke83  Please check with the issue

**Comment by abhikm1991** [comment]
@barryvdh Please check with the issue

**Comment by egrobler** [comment]
Why reopen this issue, as I feel it is clearly not an issue with the library? Even in Laravel 9 the 2nd parameter of the `view()` function has to be an array.

https://github.com/barryvdh/laravel-dompdf/blob/e49e1747d71f26454d3138d36247e9f8adc724e7/src/PDF.php

Lines 125-135
```
/**
     * Load a View and convert to HTML
     * @param array<string, mixed> $data
     * @param array<string, mixed> $mergeData
     * @param string|null $encoding Not used yet
     */
    public function loadView(string $view, array $data = [], array $mergeData = [], ?string $encoding = null): self
    {
        $html = $this->view->make($view, $data, $mergeData)->render();
        return $this->loadHTML($html, $encoding);
    }
```

**Comment by jdavidbakr** [comment]
Not sure why you pinged me into this conversation - but as far as I know, sending an object as the argument to a view has never been officially supported.  It probably worked in the past because it wasn't strongly typed and so the object was converted to an array, but it looks like it's now strongly typed.
