### ISSUE TITLE
v1.0.1 public_path usage breaks Lumen

### ISSUE THREAD

**Issue by thewebdevelopers** [barryvdh/laravel-dompdf#883]
**Describe the bug**
The change from `$path = realpath(base_path('public'));` to `$path = realpath(public_path());` in v1.0.1 introduces a breaking change to Lumen, which has no `public_path` method.

Instead of generating a PDF, the following error occurs:

`Call to undefined function Barryvdh\\DomPDF\\public_path() at /home/vagrant/src/document-generation-service/vendor/barryvdh/laravel-dompdf/src/ServiceProvider.php:54`

**To Reproduce**
- Install v1.0.1 in Lumen, attempt to produce a PDF using `Pdf::loadHtml($html)->output();`

**Expected behavior**
A PDF is generated from the HTML.

**Comment by barryvdh** [comment]
Reverted

**Comment by ddr5292** [comment]
I am wondering why the code was reverted. The project I inherited does not have a "public" path - not sure why but it was renamed. Anyway, if the general purpose, public_path() works, why would you want to only allow the hard-coded version, base_path('public')?
