### ISSUE TITLE
Save file in server

### ISSUE THREAD

**Issue by BrunoQuaresma** [barryvdh/laravel-dompdf#89]
How i do to save a pdf file in my server... on the public folder?

**Comment by tonetlds** [comment]
```php
$pdf = PDF::loadView( 'some.view', compact('somevar'))->save( 'path/pdfname.pdf' ); 
```

**Comment by vadimwe** [comment]
@BrunoQuaresma woks fine PDF::loadView( 'some.view', compact('somevar'))->save( 'path/pdfname.pdf' ); as @tonetlds said

**Comment by langocthach** [comment]
Can I save file to another folder? Not the Public folder?
Because I'm afraid another users can access those file they don't have permission.
Thanks

**Comment by zhuqiwen** [comment]
@langocthach I guess this is out the scope of dompdf. You can set up your own save path as you want, as long as you correctly set up laravel's filesystem

**Comment by barryvdh** [comment]
You can save it anywhere you like.

**Comment by Siphiwo** [comment]
I am trying to save a pdf to my public/pdf folder on the server. I am using laravel 5.x . The error I am receiving is : 

"Unable to open file for reading [/usr/home/ftp-username/laravel_voogle/public/xxxx.pdf]"

How can I set this to save the file here: [ /usr/home/ftp-user/public_html/pdf/xxx.pdf ]
