### ISSUE TITLE
DOMPDF_ENABLE_REMOTE is set to FALSE

### ISSUE THREAD

**Issue by bajramemini** [barryvdh/laravel-dompdf#90]
Hello barryvdh,

I am somehow stuck and don't know what to do! I installed your package, published the config, created my pdf:

```
$pdf = \PDF->loadView('pdfs.test', $data);
$pdf->stream();
```

The image has of course its img path. But I get the following error:
DOMPDF_ENABLE_REMOTE is set to FALSE
http://test.app:8000/img/logo.png

I am using "barryvdh/laravel-dompdf": "dev-master", but tried 0.4.\* before. Still getting the same error.

Of course, the DOMPDF_ENABLE_REMOTE is set to true in your config file. What am I doing wrong?

Thanks in advance.

Kind regards
from Switzerland

**Comment by marcorivm** [comment]
Same issue here, any suggestions?
