### ISSUE TITLE
Bring the package up to date with CSS3!

### ISSUE THREAD

**Issue by cedricfortuin** [barryvdh/laravel-dompdf#905]
**Describe the bug**
There is no support for CSS3 features, like border-box, flexbox, grid, etc. This is very annoying, since CSS3 is the most used version of CSS.

**To Reproduce**
- Laravel 9.22, package version 2
- No alternations to options.

**Comment by hebbet** [comment]
that package here is just a wrapper for dompdf to make usage in Laravel easier.

there are a few issues in their repositories for differrent CSS 3 features:
https://github.com/dompdf/dompdf/issues

**Comment by Soban3** [comment]
Give [laravel-snappy](https://github.com/barryvdh/laravel-snappy) a shot. It supports flexboxes.
