### ISSUE TITLE
Undefined variable: data in blade template

### ISSUE THREAD

**Issue by chhumsina** [barryvdh/laravel-dompdf#91]
controller
```
public function index()
	{
		$data = array("Test1", "Test2", "Test3");
		$pdf = PDF::loadView('pdf', $data);
		return $pdf->stream();
	}
```

blade template
```
@foreach ($data as $key => $test)
			{{ $test[0] }}
			{{ $test[1] }}
		@endforeach
```

Error message
![whoops there was an error 2015-02-04 11-18-33](https://cloud.githubusercontent.com/assets/3894767/6035114/94dba9ee-ac5f-11e4-9fec-148cf5af5a89.png)

Thanks you for helping.

**Comment by barryvdh** [comment]
Use an array as second argument for the view.
array('data' => $data)

**Comment by WikiGaga** [comment]
use it
$pdf = PDF::loadView('pdf', compact('data'));
