### ISSUE TITLE
Error adding css Font Face

### ISSUE THREAD

**Issue by chhumsina** [barryvdh/laravel-dompdf#92]
```
@font-face {
			font-family: StardosStencil;
			src: url("{{ asset('font/StardosStencil-Bold.ttf') }}");
		}
```

![whoops there was an error 2015-02-04 15-55-29](https://cloud.githubusercontent.com/assets/3894767/6037468/73c1811c-ac86-11e4-86a9-8b2fda00069f.png)

Thanks you.

**Comment by barryvdh** [comment]
Perhaps create storage/fonts folder.

**Comment by chhumsina** [comment]
But why it generated the key number .ttf  instead of font name ?

**Comment by barryvdh** [comment]
Not sure, that is done by dompdf.

**Comment by eventengineering** [comment]
This is due to the /storage/fonts/ folder missing from Laravel. simply add the folder and everything will work just fine.

Cheers

Oli
