### ISSUE TITLE
ParseError: syntax error, unexpected identifier "am"

### ISSUE THREAD

**Issue by anatolistoev** [barryvdh/laravel-dompdf#924]
After upgrading dompdf from 1.0 to 2.0 in connection with php 8.0.22 and php 8.0.24 we see the following permanent error in application logs:

ParseError: syntax error, unexpected identifier "am" in /home/www/dbdn-l9/vendor/dompdf/dompdf/src/PhpEvaluator.php(52) : eval()'d code:1
syntax error, unexpected identifier "am" {"userId":6, "exception":"[object] (ParseError(code: 0): syntax error, unexpected identifier \"am\" at /home/www/app-name/vendor/dompdf/dompdf/src/PhpEvaluator.php(52) : eval()'d code:1)

No PDF files are generated and the function fails every time.

Is this anomaly known and has it already been reported by others? How should we proceed here?
Your recommendation would be greatly appreciated in this matter.

**Comment by atontchev** [comment]
We are experiencing the same thing and are wondering what the problem could be ... We have been using laravel-dompdf for over seven years and boldly recommend it with only positive feedback.

**Comment by PaolaRuby** [comment]
>How should we proceed here? 

This is only a laravel wrapper, the issues about pdfs must be on the original DOMPDF package

**Comment by anatolistoev** [comment]
Thank you for your comment. I‘ll address our issue to dompdf directly and post it there for further assistance.
:)

**Comment by parallels999** [comment]
https://github.com/dompdf/dompdf/issues/3027#issuecomment-1277738596
Answered, must close this
