### ISSUE TITLE
Installation instructions for registering service provider are incorrect

### ISSUE THREAD

**Issue by mlambley** [barryvdh/laravel-dompdf#932]
**Describe the bug**
Installation instructions are incorrect. Service providers are not registered in `bootstrap/app.php`

**To Reproduce**
- Clean install of Laravel 9
- Load this package
- Place `$app->register(\Barryvdh\DomPDF\ServiceProvider::class);` inside `bootstrap/app.php` as described in the README
- Run any command in the CLI
- See error:
```
Illuminate\Contracts\Container\BindingResolutionException: Target class [config] does not exist. in /webroot/vendor/laravel/framework/src/Illuminate/Container/Container.php:877
Stack trace:
#0 /webroot/vendor/laravel/framework/src/Illuminate/Container/Container.php(756): Illuminate\Container\Container->build()
#1 /webroot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(860): Illuminate\Container\Container->resolve()
#2 /webroot/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\Foundation\Application->resolve()
#3 /webroot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(845): Illuminate\Container\Container->make()
#4 /webroot/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(135): Illuminate\Foundation\Application->make()
#5 /webroot/vendor/barryvdh/laravel-dompdf/src/ServiceProvider.php(28): Illuminate\Support\ServiceProvider->mergeConfigFrom()
#6 /webroot/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(689): Barryvdh\DomPDF\ServiceProvider->register()
#7 /webroot/bootstrap/app.php(44): Illuminate\Foundation\Application->register()
```

**Expected behavior**
Error to not appear

**Additional context**
Service providers should be wired up via `config/app.php` in the `Package Service Providers...` section, or alternatively in the `AppServiceProvider` register function. By loading them in `bootstrap/app.php`, the config object has not been loaded into the application yet.
```
/*
 * Package Service Providers...
 */
Barryvdh\DomPDF\ServiceProvider::class,
```

**Comment by erikn69** [comment]
This is not a bug

You are reading Lumen instructions, not Laravel instructions 😄😄
https://github.com/barryvdh/laravel-dompdf/blob/7516caab940796d31267da9b30b548a56bef50cb/readme.md?plain=1#L18-L25

**Comment by mlambley** [comment]
Notwithstanding the unnecessary smart-alec side commentary from this other fellow here, perhaps including full instructions in the Laravel section might help?

**Comment by erikn69** [comment]
> Laravel did not autodiscover this for me

Seems like a problem with your implementation, did you try ?
```batch
php artisan config:clear
composer update
```

**Comment by systemsolutionweb** [comment]
It's not a bug or an issue

**Comment by mlambley** [comment]
Would have appreciated the situation to be handled without the meme or the laugh emotes, but if you insist that no one else could possibly make that same mistake I'll not say another word on the topic.

**Comment by emalsa** [comment]
I fell into the same trap. Out of habit from other instruction, I only found the configuration steps for Laravel after looking up this issue. These are after the `Using` chapter.

Just my 49 cents.
