### ISSUE TITLE
Unable to render Object

### ISSUE THREAD

**Issue by chhumsina** [barryvdh/laravel-dompdf#94]
controller

```
$notes = Notes::all();
$pdf = PDF::loadView('pdf', $notes)->setPaper('a4')->setOrientation('landscape');
return $pdf->stream();
```
template.blade
```
{{$notes}}
```
Error message: Undefined variable: notes

Thanks you :)

**Comment by barryvdh** [comment]
Array('notes'=>$notes)
Same as regular views..

**Comment by marwan2** [comment]
I had the same issue and your solution solved it, please update it in the documentation
