### ISSUE TITLE
unpack(): Type n: not enough input, need 2, have 0

### ISSUE THREAD

**Issue by naseemkhan7021** [barryvdh/laravel-dompdf#942]
Hello there,
  My name is Naseem khan from Mumbai India.

### Issue:
 When I try to create PDF with my custom google font-family `<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">`  this gives me an error `unpack(): Type n: not enough input, need 2, have 0`. I am using default dompdf.config file.
I tried every single possibility which is found on google. I try to run it on Windows 10 and Ubuntu v16.04

I need help.

**Comment by parallels999** [comment]
https://github.com/barryvdh/laravel-dompdf/issues/937#issuecomment-1342777118

**Comment by naseemkhan7021** [comment]
ok

**Comment by erlangparasu** [comment]
https://github.com/dompdf/php-font-lib/issues/47

**Comment by nehemiaobati** [comment]
'ERROR - 2025-11-07 18:25:42 --> [Dompdf Fallback Failed] unpack(): Type n: not enough input values, need 2 values but only 0 were provided'

adding $options->set('isFontSubsettingEnabled', false);, you instruct DomPDF to embed the entire font file without trying to parse it and pull out individual characters.  larger file sizes but did it for me
