### ISSUE TITLE
Support for Flexbox in LaravelPDF DOM

### ISSUE THREAD

**Issue by bhupesh7shakya** [barryvdh/laravel-dompdf#947]
Currently, the LaravelPDF DOM does not support the use of flexbox layout. This can be a significant limitation for developers who rely on flexbox to create responsive and dynamic layouts in their PDFs.

Flexbox is a powerful layout tool that allows developers to create flexible, responsive, and dynamic layouts. It is widely used in web development and is becoming increasingly popular for PDF development as well.

However, without support for flexbox in the LaravelPDF DOM, developers are forced to rely on other layout tools or to manually code their layouts, which can be time-consuming and error-prone.

We would like to request that the LaravelPDF DOM be updated to support flexbox, so that developers can take advantage of this powerful layout tool when creating PDFs.

Impact:

The lack of support for flexbox in the LaravelPDF DOM makes it difficult for developers to create responsive and dynamic layouts in their PDFs. This can lead to frustration and lost productivity, as well as errors in the final product.

Recommended Action:

We recommend that the LaravelPDF DOM be updated to support flexbox, so that developers can take advantage of this powerful layout tool when creating PDFs. This could be done by adding support for flexbox to the existing layout tools or by creating a new layout tool specifically for flexbox.

We would be happy to work with the LaravelPDF team to help implement this feature and to test it to ensure that it is working correctly.

Thank you for considering this request. We look forward to hearing from you.

**Comment by hedgelot** [comment]
flex/grid aren't supported by dompdf, laravel-dompdf is only a wrapper of dompdf. 
See following issue: https://github.com/dompdf/dompdf/issues/971 :)

**Comment by bhupesh7shakya** [comment]
ok thank you for the response
