### ISSUE TITLE
Configuration to use desired font

### ISSUE THREAD

**Issue by atulrpandey** [barryvdh/laravel-dompdf#95]
Nice work :)

Thanks in advance.

How can I configure this library to use desired font during installation?

**Comment by barryvdh** [comment]
You should be able to publish the config file and change the font path:
https://github.com/barryvdh/laravel-dompdf/blob/master/config/dompdf.php#L41

Not sure how it works exactly, that's just dompdf itself.

**Comment by atulrpandey** [comment]
Thanks! :)
