### ISSUE TITLE
Fonts are not responding 

### ISSUE THREAD

**Issue by a-akashsoni** [barryvdh/laravel-dompdf#957]
I am using "Old English Text MT" fonts in shopify using dompdf library, but it does not give response anything. 
Cdn link and font face of "Old English Text MT" fonts are following. 

cdn link:-
<link href="//db.onlinewebfonts.com/c/f3258385782c4c96aa24fe8b5d5f9782?family=Old+English+Text+MT" rel="stylesheet" type="text/css"/>

font face:-
@font-face {font-family: "Old English Text MT"; src: url("//db.onlinewebfonts.com/t/f3258385782c4c96aa24fe8b5d5f9782.eot"); src: url("//db.onlinewebfonts.com/t/f3258385782c4c96aa24fe8b5d5f9782.eot?#iefix") format("embedded-opentype"), url("//db.onlinewebfonts.com/t/f3258385782c4c96aa24fe8b5d5f9782.woff2") format("woff2"), url("//db.onlinewebfonts.com/t/f3258385782c4c96aa24fe8b5d5f9782.woff") format("woff"), url("//db.onlinewebfonts.com/t/f3258385782c4c96aa24fe8b5d5f9782.ttf") format("truetype"), url("//db.onlinewebfonts.com/t/f3258385782c4c96aa24fe8b5d5f9782.svg#Old English Text MT") format("svg"); }

But if I am using "Old English Five" fonts in shopify, these fonts are working properly.
Cdn link and font family of "Old English Five" fonts are following. 

cdn link:-
<link href="https://fonts.cdnfonts.com/css/old-english-five" rel="stylesheet">

font-family: 'Old English Five', sans-serif;

Kindly give your reference as soon as possible.

Thanks.

**Comment by parallels999** [comment]
**This is just a Dompdf wrapper!**
I understand that this package is just a Laravel wrapper for https://github.com/dompdf/dompdf
Any issues with PDF rendering, CSS that is not applied correctly, aligning/fonts/characters etc that are not directly related to this package, should be reported there. When having doubts, please try to reproduce the issue with just dompdf. If it's also present there, do not open an issue here please.

**Comment by a-akashsoni** [comment]
@parallels999 Kindly tell what should I do right now?
Thanks

**Comment by parallels999** [comment]
> This is just a Dompdf wrapper! .... Any issues with ... aligning/fonts/characters etc that are not directly related to this package, should be reported there

@a-akashsoni first close this issue, and open an issue on the real package
>this package is just a Laravel wrapper for https://github.com/dompdf/dompdf
