### ISSUE TITLE
Image not showing tried everything

### ISSUE THREAD

**Issue by umairge66** [barryvdh/laravel-dompdf#959]
I am using this library there are many issues but the most frustrating issue is the image is not showing in pdf

**Comment by parallels999** [comment]
**This is just a Dompdf wrapper!**
I understand that this package is just a Laravel wrapper for https://github.com/dompdf/dompdf
Any issues with PDF rendering, CSS that is not applied correctly, aligning/fonts/characters etc that are not directly related to this package, should be reported there. When having doubts, please try to reproduce the issue with just dompdf. If it's also present there, do not open an issue here please.

**Comment by Mike-Carolan** [comment]
I had this issue as well - solved by using the built-in base64_encode function.
    $image = file_get_contents('path_to_png_image');
    $img_data = base64_encode($image);
    
    Then render in html:
    <img alt="" src="data:image/png;base64, ' . $img_data . '">

**Comment by umairge66** [comment]
thanks @Mike-Carolan solved my problem
