### ISSUE TITLE
DOMNode::cloneNode(): ID biggerbox already defined

### ISSUE THREAD

**Issue by thededdy** [barryvdh/laravel-dompdf#96]
i don't know if you're still working on this version, but can you help me with this error? it used to run and generate pdf just fine then this error pops out of nowhere today.

**Comment by thededdy** [comment]
nvm, fixed it just now..

**Comment by barryvdh** [comment]
How?

**Comment by thededdy** [comment]
i just change the ID 'biggerbox' into class, and it's working again. not too sure why tho because it used to work just fine. might be some error on my css or something.

**Comment by undermink** [comment]
is there any other option to solve this?! i'm having the same cloneNode errors but i'd like to keep my ids:)

**Comment by barryvdh** [comment]
Sorry, this is an upstream dompdf issue

**Comment by ThomasLandauer** [comment]
The reason for this seems to be that dompdf clones the required HTML elements when the content exceeds one page. However, elements with an `id` can't be cloned. See https://github.com/dompdf/dompdf/issues/1027
