### ISSUE TITLE
Incorrect output of font

### ISSUE THREAD

**Issue by dnznk** [barryvdh/laravel-dompdf#960]
**Describe the bug**
First of all, I know this is only a wrapper, but it seems to me that dompdf is working.
Sometimes the content of the generated PDF is Japanese. Just like for many others before me the PDF shows either only question marks or boxes, hence can't display the special characters.

**To Reproduce**
- `"laravel/framework": "^7.0"`, `"barryvdh/laravel-dompdf": "^2.0",`
- `return Pdf::loadView('pdfs.explo', $data)->stream($pdfName . '.pdf');`
- Characters that won't display: スペア パーツ [example]
- Already tried to use DejaVu Sans (shows boxes) and also NotoSans (donwloaded and added to storage, aswell as implemented with @font-face)
- `'convert_entities' => true,` set to false
- If I change the output not to show a rendered PDF but a html page, everything is displayed correctly.

**Expected behavior**
The Japanese characters (same problem for Greek) should be displayed in the rendered PDF.

**Screenshots**
![Bildschirm_foto 2023-03-17 um 10 05 18](https://user-images.githubusercontent.com/107815714/225867411-49b17bde-2b5b-4eaf-a60b-37e5c29e465e.png)

**Additional context**

**Comment by parallels999** [comment]
https://github.com/barryvdh/laravel-dompdf/blob/424a223ce80e7afc8bfb6e84449679efe272fbb5/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L10-L12
>**This is just a Dompdf wrapper!**
I understand that this package is just a Laravel wrapper for https://github.com/dompdf/dompdf
Any issues with PDF rendering, CSS that is not applied correctly, aligning/**fonts**/characters etc that are not directly related to this package, should be reported there. When having doubts, please try to reproduce the issue with just dompdf. If it's also present there, do not open an issue here please.
