### ISSUE TITLE
Method not defined when chaining methods

### ISSUE THREAD

**Issue by yh-ankit** [barryvdh/laravel-dompdf#971]
**Describe the bug**
IDE and static analysis complains that the method is not defined when chaining methods 

**To Reproduce**
- Laravel 10,
- laravel-dompdf v2.0.1

Create a controller and add the following code. Run static analysis on it like phpstan. Alternatively, inspect the return type of the chained methods in your IDE or try to go to the definition of the chained methods in the IDE. The best way to replicate is to use a static analysis tool like phpstan
```php
$pdf = Pdf::loadView('any.random.view')->setPaper('a4', 'portrait'); // setPaper() not defined
return $pdf->download(); // static analysis complains downlaod() is not defined. Also "go to definition" in IDE doesn't work"
// OR
$pdf->save(...); // static analysis complains save() is not defined. Also "go to definition" in IDE doesn't work"
```

**Expected behavior**
The methods should be defined according to the docs

**Comment by parallels999** [comment]
Did you try [barryvdh/laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper)?
Feel free to make a PR for better static analysis

**Comment by erikn69** [comment]
Hi try #972 and let your review
