### ISSUE TITLE
Generate pdf gets too slow with foreach items

### ISSUE THREAD

**Issue by chhumsina** [barryvdh/laravel-dompdf#98]
Hi,
I have generate pdf pages more than 30 with image item it's gets too slow.

How can I make faster speed for that. 

Thanks you :)

**Comment by nic** [comment]
+1

**Comment by wilcho-vnz** [comment]
Hi, 

Could you solve this?

**Comment by barryvdh** [comment]
Nope. This is just a wrapper. Ask on the dompdf repo or use https://github.com/barryvdh/laravel-snappy

**Comment by sudeshkumar147** [comment]
yes i have also this problem help anyone i can.

**Comment by harshadvala** [comment]
I have also this proble, can help anyone

**Comment by danfox** [comment]
I have the same problem, when generating the pdf all the system slows down

**Comment by rahman5147** [comment]
+1

**Comment by paulocastellano** [comment]
+1

**Comment by luanrodrigues** [comment]
+1

**Comment by guiimarques18** [comment]
+1

**Comment by c5st4wr6ch** [comment]
+1

**Comment by programmermarvin** [comment]
+1

**Comment by mshifo** [comment]
+1

**Comment by elephantux** [comment]
+1

**Comment by vinidotruan** [comment]
+1

**Comment by Guilherme-Valle** [comment]
+1

**Comment by erredius** [comment]
+1

**Comment by jemkob** [comment]
> +1
Use https://github.com/barryvdh/laravel-snappy its faster and very stable.

**Comment by brianyudanto** [comment]
compress the image can help to rendering PDF more fast

**Comment by adil62** [comment]
+1
