### ISSUE TITLE
Project abandoned 

### ISSUE THREAD

**Issue by carlos-dubon** [barryvdh/laravel-dompdf#997]
The project is abandoned. The CSS flex property doesn't work. This is an issue that has been open long enough now!! This should be top priority. But developer doesn't care

**Comment by lenvanessen** [comment]
I don't believe the developer doesn't care. @barryvdh manages a lot of open source projects and has put a good amount of his time towards the community. Perhaps he's busy, has things going on in his personal life. Whatever the reason might be, don't be to quick to judge.
