### ISSUE TITLE
The PAGE_NUM and PAGE_COUNT only display at page 1 but not other pages

### ISSUE THREAD

**Issue by Lukimer** [barryvdh/laravel-dompdf#999]
Im using Laravel 10, The PAGE_NUM and PAGE_COUNT only showing in page 1, and not displaying to other pages.
And this is no problem for my other Laravel 8 project.

**To Reproduce**
- Laravel 10.3.3
<script type="text/php">

    if (isset($pdf)) {

      $text = "Page {PAGE_NUM} of {PAGE_COUNT}";

      $x = $pdf->get_width() - 80;

      $y = $pdf->get_height() - 35;

      $pdf->page_text($x, $y, $text, null, 8, array(0,0,0), 0.0, 0.0, 0.0);

  }

</script>

**Comment by parallels999** [comment]
https://github.com/barryvdh/laravel-dompdf/blob/424a223ce80e7afc8bfb6e84449679efe272fbb5/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L10-L12
>**This is just a Dompdf wrapper!**
I understand that this package is just a Laravel wrapper for https://github.com/dompdf/dompdf
Any issues with PDF rendering, CSS that is not applied correctly, aligning/fonts/characters/html/css etc that are not directly related to this package, should be reported there. When having doubts, please try to reproduce the issue with just dompdf. If it's also present there, do not open an issue here please.

**Comment by Lukimer** [comment]
Hi, parallels999

Well noted with thanks. And I solved the problem. 

Best

**Comment by AaEzha** [comment]
> Hi, parallels999
> 
> Well noted with thanks. And I solved the problem.
> 
> Best

what is the solution?

**Comment by PetiSallai** [comment]
> > Hi, parallels999
> > Well noted with thanks. And I solved the problem.
> > Best
> 
> what is the solution?

Just move the script to the bottom of the document. It works for me.

I spend hours to find the solution. :)

**Comment by maximesahagian** [comment]
Did you find any solution @Lukimer ?

**Comment by Lukimer** [comment]
Sorry all for late reply,

And the Solution is:

- I just copy the whole old directory of dompdf from laravel 8 and directly overwrite to the same place of laravel 10.

Then the page number issue solved.

Best

**Comment by Lukimer** [comment]
Close issue
